### ISSUE TITLE
Kurátor - řazení požadavků

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#101]
Dobrý den,

šlo by vytvořit do kurátorských účtů různé návrhy řazení? V současné době si jednotlivé návrhy/požadavky dají pouze filtrovat a jsou řazeny od nejstaršího návrhu. 

Nyní už se tam návrhů dost nahromadilo a bylo by dobré, aby se daly tyto návrhy různě řadit, například:

- od nejnovějšího návrhu (datum zadání), 
- od nejstaršího návrhu (datum zadání), 
- podle uživatelů, 
- podle institucí, 
- od nejstaršího (datum vyřízení), 
- od nejnovějšího (datum vyřízení). 

Po stránce kurátorské práce by se s tím lépe pracovalo.

![řazení požadavků - kurátor](https://user-images.githubusercontent.com/86351100/137309054-c40c95e4-4a11-4ea5-8331-c4e0999fb1f7.jpg)
DC

**Comment by Cypzirschova** [comment]
Zatím není možnost filtrovat žádosti podle uživatelů.

**Comment by Cypzirschova** [comment]
Dobrý den,
chtěla jsem se zeptat, zda se bude možnost filtrovat žádosti i podle uživatelů? 
D. Cypzirschová

**Comment by CIZKOVAL** [comment]
Dobrý den,
filtrování **dle uživatelů** je docela zásadní. 
Naopak filtrování **dle Priority**, které tam nyní je by tam ani být nemuselo. Priorita má totiž význam pouze u žádostí, které čekají na posouzení kurátorem. Do výsledku řazení jsou ale zamíchané i další stavy, které nemají už význam.  Pokud si vybere pouze požadavky, které čekají na posouzení, tak jsou zde i požadavky bez priority (na konci nebo na začátku, podle toho zda řadí vzestupně/sestupně) a uživatel se musí nejdříve vnořit dovnitř, aby zjistil, které požadavky ještě mají nějakou prioritu a které ne.

![razeni_dle_prio](https://user-images.githubusercontent.com/92719629/151157089-8bf23478-37ab-4146-907a-b28766b6db9c.png)

_Kurátor si nejlépe zobrazí prioritní požadavky tak, že si dá do filtru požadavky, které čekají na posouzení a dále vybere **ve filtru** konkrétní prioritu._

**Comment by CIZKOVAL** [comment]
@Cypzirschova - prosím o posouzení, zda řazení dle Priority vyhodit.

Řazení dle Uživatelů požadujeme.

**Comment by Cypzirschova** [comment]
@CIZKOVAL 
Řazení podle uživatelů rozhodně uvítám.
Seřadit podle priorit být nemusí, ale určitě bych zachovala filtr na priority vlevo, viz obr. oranžová barva.
![priority](https://user-images.githubusercontent.com/86351100/151159039-7d2aa33c-8658-4425-9a21-18f041c90d00.png)

**Comment by CIZKOVAL** [comment]
@Cypzirschova ano, filtr pro Prioritu určitě musí být zachován, řazení dle prio ne.

**Comment by CIZKOVAL** [comment]
@pavel-stastny bude mít kurátor možnost **řadit dle uživatele**? Požadavek je zde od 14.10. 2021, děkuji

**Comment by pavel-stastny** [comment]
@CIZKOVAL Uvidíme, jak to vyjde časove.  Založte na to, prosím, nové issue (ne bug prosím).

**Comment by CIZKOVAL** [comment]
@pavel-stastny nedává mi smysl zakládat nové issue, když v počátku i historii tohoto issue voláme po **řazení dle uživatele.** Zároveň nám přijde zbytečné řadit dle priority, kterou lze vyfiltrovat.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Dobrá. Ale jak jsem se již zmínil.  Bude se řešit dle času.

**Comment by Cypzirschova** [comment]
Souhlasím s paní @CIZKOVAL.

**Comment by Cypzirschova** [comment]
Dle dnešní schůzky stačí řazení podle uživatelů, nikoliv filtr.

**Comment by Cypzirschova** [comment]
Uzavírám, vyřešeno filtrováním v issue #325.
