### ISSUE TITLE
Licence nad repo

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#102]
Prosim o pridelani licence nad repo v gitu, dekuji

**Comment by JanMeritus** [comment]
@pavel-stastny je konecne mozne uz zde pridat tu licenci?

**Comment by pavel-stastny** [comment]
@JanMeritus Co je tim mysleno ?  Licenci v gitu vidim ( [LICENSE](https://github.com/NLCR/SeznamDNNT/blob/main/LICENSE) )

**Comment by pavel-stastny** [comment]
To myslim, ze muzu zavrit.
