### ISSUE TITLE
Bublina s licenci - Funkcni zmena

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#103]
- pokud ma dilo _**aktivni**_ licenci pridat do zobrazeni jednotlivych zaznamu defilujicich v selekci licenci ("Online", "Terminál")

**Comment by JanMeritus** [comment]
navaznost na #91

**Comment by CIZKOVAL** [comment]
Dobrý den,
retest OK. Díla, která jsou ve stavech PA nebo A mají licenci DNNTT nebo DNNTO.

**Comment by JanMeritus** [comment]
@CIZKOVAL za mne ok, prosim sem screenshot a uzavrit

**Comment by CIZKOVAL** [comment]
![licence_zobrazeni](https://user-images.githubusercontent.com/92719629/150758825-2c6bd145-4bb8-442c-afbc-6990251b4ba9.png)
