### ISSUE TITLE
Duplicity - ISBN, ISSN, ISMN...

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#105]
Dobrý den,

v aplikaci jsou opět duplicity. Týká se to čísla ISBN, které je uvedeno i u jiného záznamu (hudebnina), u kterého je stejné číslo uvedeno v poli 024, konkrétně **0242 podpole z = chybné ISMN.** (Raději zasílám odkaz na přehled polí pro speciální mono. zdroje: http://text.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/katalogizacni-politika/minimalni-zaznam-rda-marc-21-pro-specialni-monograficke-zdroje)

Díky tomu, že aplikace (zřejmě zatím) neřeší pole **020, 022, 024 podpole z**, které se vůbec nemá brát v potaz, se nám do aplikace dostávají duplicitní záznamy ze SKC. Je potřeba toto nějak vyřešit, to jsem už psala/říkala dříve. Pokud se bude pracovat se SKC, je nutné vyřešit, jak se bude dál pracovat s duplicitami. V přechozí verzi tyto duplicity nebyly, tuším, že předchozí verze pracovala pouze z aleph. bází DNT01, proto tam duplicity nebyly.

V SDNNT je aktuálně zařazen tento titul:
https://aleph.nkp.cz/F/?func=direct&doc_number=000154298&local_base=DNT
https://aleph.nkp.cz/F/?func=direct&doc_number=001873418&local_base=SKC - stejný záznam v SKC

Chybný záznam, který je zařazen v aplikaci:
https://aleph.nkp.cz/F/?func=direct&doc_number=007578276&local_base=SKC 

![duplicita - isbn (020 z)](https://user-images.githubusercontent.com/86351100/137468652-2670ea0f-c235-4f8d-922d-98a526e6b6aa.jpg)
![duplicita - isbn (020 z) SKC](https://user-images.githubusercontent.com/86351100/137468688-f6ebcd4f-e0c7-4605-86d7-529928ba2524.jpg)
![duplicita - isbn (020 z) záznam](https://user-images.githubusercontent.com/86351100/137468699-e0ab5877-25e0-4131-84ee-68fdb7314a64.jpg)
DC
@Lichtenbergova

**Comment by pavel-stastny** [comment]
@Cypzirschova Po konzultaci s @albertoh se nam zda, ze je neporadek v datech na Testu. Spustili jsme indexaci na devu a zkontrolujeme stav.

**Comment by Cypzirschova** [comment]
Na devu je to už v pořádku, na testu nikoliv.

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova data jsem na sdnnt-test reindexoval

**Comment by Cypzirschova** [comment]
@pavel-stastny Na testu stále stejné.

**Comment by pavel-stastny** [comment]
@Cypzirschova @smallcubes  Pokud se test a dev liší, musí se jednat o data na testu.   

@smallcubes Došlo před indexaci k promazání starých dat ?

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova k promazaní nedošlo, ohledně tohoto jsem @pavel-stastny zaslal upřesňující e-mail

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova děkuji za na směrování, dle [wiki](https://github.com/NLCR/SeznamDNNT/wiki/Instalace-aplikace) jsem spustil příkaz a zadal reindexaci

**Comment by Cypzirschova** [comment]
Dobrý den,
narazila jsem na titul, který je zařazen v aplikaci (test) a v SDNNT ho vůbec nemáme. Titul ani nemá ISBN, tak netuším, jak se do aplikace dostal. Je pouze shodný název a nakladatel. Zrovna tento titul má i formát MU.
![hudebnina - není v sdnnt](https://user-images.githubusercontent.com/86351100/140494373-7ab01b02-739f-47dd-aed8-2c260e9392e5.jpg)
Cypzirschová

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova smazání a reindexace na serveru proběhla

**Comment by Cypzirschova** [comment]
Děkuji za informaci. Na testu stále stejné.

**Comment by pavel-stastny** [comment]
@smallcubes Prosím o promazání dat na testu a poté nasazení novější verze a následný harvest

**Comment by Cypzirschova** [comment]
Po kontrole na testu to vypadá, že je to OK.

**Comment by Cypzirschova** [comment]
Vyřešeno, zavírám.
