### ISSUE TITLE
Navzajom sa vylucujuci stav licencie

### ISSUE THREAD

**Issue by Romx98** [NLCR/SeznamDNNT#106]
Dobry den,

dnes som si vytahoval documenty pomocou endpointu /catalog. Mojou ulohou bolo skontrolovat rocniky z daneho vystupu, avsak narazil som na stav, ktory sa navzajom vylucuje. Pre korenove uuid je nastavena license na dnnto, avsak to iste uuid je v sekcii granularity ale nastaveny status na N. 
Prikladam screen:
![obrázok](https://user-images.githubusercontent.com/47435706/137480487-7314de9d-7cd7-4da4-8b99-8413f62dee79.png)

**Comment by JanMeritus** [comment]
@smallcubes prosim o overeni stavu

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Již by se nemělo vyskytovat.  V případě potřeby, prosím, otevřete nové issue
