### ISSUE TITLE
Notifikace

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#107]
Dobrý den,

posílám Vám seznam issues, na které jsme narazili. (Odzkoušeno na účtu _"nakladatel"_, prostředí _"sdnnt-test"_, webový prohlížeč _Firefox_)

- [x] pokud zakliknu v rozhraní pro poslání žádosti tlačítko pro notifikaci (zvonek se stane červený), tak se po určité době vrátí zpět do výchozího stavu tzn. zvonek je černý  
- [x] změním-li nastavení intervalu např. na _"měsíc"_, tak se změna neuchová (rozhraní pro nastavení uživatelských údajů)
- [x] neexistuje nějaké rozhraní, kde bych viděl svoje aktivní notifikace (musím vždy vyhledat dílo, abych zjistil, zdali je notifikace aktivní (DEV i TEST))

**Comment by CIZKOVAL** [comment]
Dobrý den,
retest OK. Přepínací checkbox, kde jsou vidět díla, u kterých je nastavena notifikace také funguje.
