### ISSUE TITLE
Požadavky na změnu UI

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#108]
Dobrý den,
zasílám návrh na změny UI, které se týkají těchto funkčností:
- [x] 1: v hlavním menu položka **Uživatel** - udělat rozklikávací menu s následujícími položkami:
- změnit osobní údaje
- změnit heslo
- odhlásit
- [x] 2: v hlavním menu položka **Moje konto** - přejmenovat na **Moje požadavky** 
- [x] 3: do hlavního menu přidat tlačítko **Procházet dokumenty** nebo přejmenovat text ve vyhledávací liště (nyní je "Zadejte dotaz...")
- [x] 4: Menu **Moje konto**, u zobrazených záznamů pole **Návrh na stav** - zobrazit tooltip s vysvětlením zkratek (NZN, VVS...)
- [x] 5: Menu **Moje konto**, u zobrazených záznamů, které jsou ve stavu **Neodesláno** je možnost "Poslat". Měl by být použit button "Poslat žádost"
- [x]  6: Menu **Moje konto** - **detail** zobrazeného záznamu - tlačítko "Odkaz na digitální dokument" - měl by být zobrazen jen zkrácený název URL, např. krameriusndk.nkp.cz nebo krameriusndk.mzk.cz
- [x]  7: Menu **Moje konto**, u zobrazených záznamů pole **Požadavek** - popisek pole by měl být konkrétnější (nejspíše "odůvodnění") a pole by mělo být povinné vyplnit
- [x]  8: Menu **Moje konto** u zobrazených záznamů by se mělo zobrazit číslo žádosti
- [x] 9: Vyhledání záznamů - checkbox "Zobrazit i záznamy mimo seznamu" přejmenovat na "Zobrazit dokumenty, které nejsou zařazeny na seznamu"

**Comment by CIZKOVAL** [comment]
Dobrý den,
retesty dopadly následovně:
1 - OK
2 - OK
3 - OK
4 - OK
5 - OK
9 - OK

**Comment by CIZKOVAL** [comment]
6 -  Moje konto - detail zobrazeného záznamu - tlačítko "Odkaz na digitální dokument" - měl by být zobrazen jen zkrácený název URL, např. krameriusndk.nkp.cz nebo krameriusndk.mzk.cz. 
**RETEST** - nyní zde není tlačítko "Odkaz na digitální dokument", ale tlačítko se zkrácenou URL adresou. Tlačítko "Odkaz na digitální dokument" by mělo být zachováno a pouze zkrácená URL adresa v tooltipu. Možná se projeví po reindexaci, poprosím o to @smallcubes 

![#108_retest_bod_6](https://user-images.githubusercontent.com/92719629/139663393-2afc5efc-eaea-4d7a-a442-fde6c7198a40.png)

**Comment by CIZKOVAL** [comment]
7 - Moje konto, u zobrazených záznamů pole Požadavek - popisek pole by měl být konkrétnější (nejspíše "odůvodnění") a pole by mělo být povinné vyplnit.
**RETEST** - pole "Požadavek" bylo v přehledu žádostí správně přejmenováno na "Odůvodnění", ale NENÍ povinné. 
Při odesílání žádosti se ale pole jmenuje "Požadavek" - toto by asi bylo vhodné sjednotit a nazvat ho také "Odůvodnění.

![#108_retest_bod_7](https://user-images.githubusercontent.com/92719629/139664751-e2c11220-71b0-4e34-938d-4595fa8c5a9d.png)

![#108_bod7_pozadavek](https://user-images.githubusercontent.com/92719629/139664778-e2516801-115a-4bcf-abe8-b042572ca97d.png)

**Comment by CIZKOVAL** [comment]
8 - Moje konto u zobrazených záznamů by se mělo zobrazit číslo žádosti.

Číslo žádosti zde není, je třeba  v tomto issue dořešit, jak se má zobrazovat.

**Comment by pavel-stastny** [comment]
@CIZKOVAL 
Ad 6 Z důvodu #66 došlo/dochází k redisignu a tlačítka se přestěhují jinam.  Asi nemá smysl to teď řešit.
Ad 7 Ok 
Ad 8 @Cypzirschova @CIZKOVAL @pkudela  Pokud je to tak jak píše @JanMeritus, tedy identifikátor je z důvodu snadné identifikace žádosti,  tak by možná stačilo mít v tabulce zobrazeny jenom poslední číslice žádosti (plný identifikátor by se mohl objevit v tom tooltipu) .  

Něco na způsob commitů v githubu :  Následuící zkrácený hash e080c451541d8a540aa0a99e6542ca4a681456aa identifikuje tento komit `e080c451541d8a540aa0a99e6542ca4a681456aa`

@CIZKOVAL Z bodu 7 a 8 udělám nové issue.  Toto je již zapracované ve verzi 0.85.

**Comment by pkudela** [comment]
zmena labelu "pozadavek" na "oduvodneni" v dialogu pro odeslani zadosti - HOTOVO

**Comment by CIZKOVAL** [comment]
Dobrý den,
retest OK

6 - zkraceny odkaz na digitalni dokument je skryt pod tlacitkem "Více"
7 - pole Oduvodneni je konzistentni
8 - id zadosti - zobrazuje se konec id, pri rozkliknuti zadosti je videt id cele
