### ISSUE TITLE
V přehledu žádostí se zobrazuje záznam, u kterého byly všechny žádosti smazány

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#109]
Dobrý den,
pokud vymažu dokumenty z žádosti - žádost zůstane v mém kontu s počtem položek 0 - měla by se smazat. Je tedy možné odeslat prázdnou žádost - což je špatně...
![odstraněné záznamy](https://user-images.githubusercontent.com/92719629/137901443-0c0a283e-15a6-4bf1-b4a7-d14b5c0ea7f9.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, chyba přetrvává. Pokud smažu všechny neodeslané žádosti, tak zůstává řádek s 0 záznamy.

![#109_retest_NOK](https://user-images.githubusercontent.com/92719629/139657493-237421a4-34ac-41c6-a4e0-8993cf9ad497.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova Aplikace nyní standardně otevírá pouze jednu žádost daného typu. Pokud jsou z minula otevřené dvě (nebo víc) pošlete nejdříve tu jednu, pak se začne plnit druhá atd...   Až pošlete všechny, vytvoří se nová

**Comment by pavel-stastny** [comment]
@Cypzirschova Případně je můžu smazat z db ale chování by mělo být takové, jaké jsem popsal.

**Comment by Cypzirschova** [comment]
Takže v kontu budou zůstávat prázdné žádosti z předchozích dnů, které uživatel nevyužije k odeslání požadavků a odstraní z nich všechna díla?

**Comment by pavel-stastny** [comment]
@Cypzirschova Jo, resp. ta logika je vlastně stejná jako byla. Tedy žádost zůstává otevřená dokud ji dotyčný neodešle.  Chyba na straně UI byla, že se množily otevřené žádosti a fungovalo tlačítko prázdnou žádost.

**Comment by pavel-stastny** [comment]
Uživatel má u otevřených žádostí tlačítko delete.

**Comment by CIZKOVAL** [comment]
Retest Ok. Prázdná žádost nelze odeslat (tlačítko je neaktivní) a u žádostí je tlačítko pro smazání.
