### ISSUE TITLE
U žádostí se nezapisuje do Historie změn

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#110]
Dobrý den,
v detailu žádostí se nezapisují záznamy do Historie změn.

Moje konto - detail vybrané žádosti - historie změn
![Historie zmen](https://user-images.githubusercontent.com/92719629/137902554-1424035c-7f04-471f-a89d-27f3341a05e7.png)

**Comment by CIZKOVAL** [comment]
Dobrý den,
ověřovala jsem prozatím historii stavu a změny se sem již zapisují.

Jsou zde ale následující chyby:

- název díla není kompletní
- sloupec Licence je prázdný
- sloupec Typ se plní v případě, kdy kurátor mění stav. Při změně stavu ale kurátor vyplňuje pole "Poznámka", které se poté projeví v poli "Typ" - toto by se mělo sjednotit

![historie_stavu](https://user-images.githubusercontent.com/92719629/139828176-4e8b5ae3-a116-4a9d-a2fc-b4c428efaffb.png)


![historie_zmena_stavu_poznamka](https://user-images.githubusercontent.com/92719629/139826747-1b8615ab-4203-4126-bd77-bdadc1254a83.png)


Ještě poznámka: v historii se lze překlikávat mezi Historií stavu a Historií bibliografického záznamu. Na první pohled ale není patrné, že jde o různé náhledy, vypadá to spíše jako nadpis tabulky.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Opět, dám to do nového issue. Netýká se původního problému.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Zkopíroval jsem do Issue #129

**Comment by CIZKOVAL** [comment]
Dobře, toto issue zavírám.
