### ISSUE TITLE
Změny stavů po zpracování žádostí - nezařazená díla

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#111]
Dobrý den,
vybrala jsem tituly, které nejsou vůbec zařazené v SDNNT a ani nemají žádný stav v aplikaci. Po zpracování žádosti, se u titulů nezobrazí žádný stav i přesto, že jsem titul schválila, aby byl zařazen jako návrh do SDNNT.
Cypzirschová

![změna stavů](https://user-images.githubusercontent.com/86351100/137907391-fc5dbebf-e3af-4c99-aee5-348152b80a1d.jpg)

**Comment by Cypzirschova** [comment]
Zatím stále stejné.
![návrhy - chyba](https://user-images.githubusercontent.com/86351100/139629559-aeb2d636-f060-47c8-9074-acd7ae225bce.jpg)

**Comment by pavel-stastny** [comment]
@Cypzirschova Máte pravdu.  Odebírám ToTests.

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova data jsem na sdnnt-test reindexoval

**Comment by Cypzirschova** [comment]
@pavel-stastny dev i test stále stejné

**Comment by pavel-stastny** [comment]
@Cypzirschova Ano, tady jsem odebral i label ToTests. Viz komentář výše.  Je to chyba ve workflow.

**Comment by Cypzirschova** [comment]
Toto issue uzavírám, dále se řeší problematika v issue #158
