### ISSUE TITLE
Admin rozhraní: správa uživatelů

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#112]
Dobrý den,

bylo by možné trochu předělat rozhraní pro správu uživatelů? V současné době se zobrazují registrovaní uživatelé v seznamu, při nižším počtu uživatelů to je v pořádku, ale naroste-li počet např. na 100 uživatelů, tak už se rozhraní stává nepřehledné. 

Navrhnuté úpravy
- [x] změna rozhraní pro správu uživatelů
- [x] možnost vyhledat konkrétního uživatele 

![obrazek](https://user-images.githubusercontent.com/78028909/137940162-1371807a-13ee-4723-a65d-20d8c8c5d39b.png)

**Comment by smallcubes** [comment]
@pavel-stastny filtrováno funguje, bylo by možné přidat i vyhledávání podle e-mailových adres?

**Comment by pavel-stastny** [comment]
@smallcubes  pro vyhledávání dle email adres, prosím založit nove issue
