### ISSUE TITLE
Při registraci nemusím souhlasit s podmínkami aplikace

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#113]
Dobrý den,

při registraci jsem narazil na tento problém. 
Uživateli se úspěšně vytvoří účet, ačkoliv nedal souhlas s ani jednou podmínkou.

**Comment by CIZKOVAL** [comment]
Retest OK. Uživatel je registrován pouze pokud souhlasí se všemi podmínkami, jinak chybová hláška.
