### ISSUE TITLE
Formulář: kontaktní údaje

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#114]
Dobrý den,

při testovaní jsme narazili na tyto problémy: Testováno na uživateli: _habetpet_, webový prohlížeč: _Chrome_, prostřední: _sdnnt-test_

Rozhraní _Kontaktní údaje_:
- [x] 1. při aktualizaci políčka _Telefon_ jdou zadat nesmyslné údaje např. string _knihovna_ a políčko _IČO_ se nevaliduje
- [x] 2. bylo by dobré rozpadnout políčko _Adresa_ na podpole jako např. město, ulice, PSČ, číslo popisné
- [x] 3. pole _Poznámka_, _Telefon_, _IČO_, _Role v systému_ se sice úspěšně uloží, ale po opětovném přihlášení jsou opět pole prázdná
- [x] 4. uživatel by si neměl být schopen libovolně měnit instituci a roli po registraci
- [x] 5. v poli _interval notifikace_ není diakritika (mesic, tyden)

**Comment by CIZKOVAL** [comment]
Dobrý den, 
retest proběhl následovně:

Rozhraní Kontaktní údaje:

 1. OKpole telefon a IČO se validuje (IČO - 8 čísel, Telefon 9 čísel s předvolbou nebo bez, s mezerami po 3 číslicích)
 2. Ok, adresa se rozdělila na několik polí
 3. OK
 **4. NOK** uživatel by si neměl být schopen libovolně měnit instituci a roli po registraci
 - uživatel si nemůže měnit instituci, ale **může si i nadále měnit role v systému**
 5. OK
 6. **Nový problém** - neprobíhá validace na povinná pole. Uživatel může všechno smazat (zůstává pouze "Přihlašovací jméno") a změny lze uložit.
 
Poznámka: možná by byl vhodnější název formuláře "Osobní údaje" místo "Registrační formulář"

**Comment by CIZKOVAL** [comment]
Poznámka k bodu 4 - uživatel si nakonec Roli v systému nezmění, ale je matoucí, že při změně údajů se tak aplikace tváří.

Toto issue zavírám, body 1-5 OK.

Založím 2 nové issue (bod 6 a souvislost s bodem 4).

**Comment by CIZKOVAL** [comment]
Založeny 2 nové issues:
#138 
#139
