### ISSUE TITLE
Registrační formulář

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#115]
Dobrý den,

při testovaní jsme narazili na tyto problémy: Testováno na uživateli: _habetpet_, webový prohlížeč: _Chrome_, prostřední: _sdnnt-test_

Registrační formulář:
- [x] 1. přejmenovat název formuláře z _Kontaktní údaje_ na _Registrační formulář_
- [x] 2. políčko _Uložit_ změnit na _Registrovat se_
- [x] 3. vyplněná pole _Telefon_, _IČO_, _Poznámka_ se sice úspěšně uloží tzn. v admin prostředí je u daného uživatele vidím, ale v kontu uživatele již nikoliv
- [x] 4. políčko _Role v systému_ se neuloží po registraci (admin i konto)
- [x] 5. poté se vyskytují problémy jako u issue #114: při vyplnění políčka _Telefon_ jdou zadat nesmyslné údaje např. string knihovna a políčko _IČO_ se nevaliduje + by bylo dobré rozpadnout políčko _Adresa_ na podpole jako např. město, ulice, PSČ, číslo popisné + v poli interval notifikace není diakritika (mesic, tyden)

**Comment by CIZKOVAL** [comment]
Provedla jsem retest:
 1. OK
 2. OK
 3. OK
 4. OK
 5. pole se validují, ale v některých případech špatně, založím nové issue
Pole Adresa obsahuje jmenovaná podpole OK
Interval notifikace - diakritika OK

**Comment by CIZKOVAL** [comment]
založeno nové issue k bodu 5 validaci 
<body link="#0563C1" vlink="#954F72">

#134 
--




</body>

</html>
