### ISSUE TITLE
Obsah zasílaných e-mailů

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#116]
Dobrý den,

při testovaní jsme narazili na tyto problémy: Testováno na uživateli: _habetpet_, webový prohlížeč: _Chrome_, prostřední: _sdnnt-test_

- [x] 1. v e-mailu _Registrace uživatele_ změnit pan**i** na pan**í**
- [x] 2. pokud jako admin někomu resetuji heslo, tak se pošle e-mail, ve kterém je překlep **Vvám**
- [x] 3. v e-mailu _Žádost o resetování hesla_ nefunguje odkaz a zároveň není proklikávací

**Comment by pavel-stastny** [comment]
To je záležitost nastavení resp. šablony.  Obsahy mailů jsou v adresáři `~/.sdnnt/texts`.  Mail pro reset hesla je v souboru mail_reset_link.   Ohledně proklikávacího obsahu, pokud je v konfiguraci nastaveno html mail (viz https://github.com/NLCR/SeznamDNNT/blob/main/installation/config.json#L27-L30)  je možné používat html značky.

**Comment by smallcubes** [comment]
@pavel-stastny funguje, děkuji Vám za radu. Uzavírám.
