### ISSUE TITLE
Nakladatel - zobrazení 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#119]
Dobrý den,
v aplikaci se zobrazují někteří nakladatelé 2x. První jsou bez čárky za nakladatelem a druhý nakladatel s čárkou. Toto se zobrazuje, jak po přihlášení v aplikaci, tak i bez přihlášení.
Cypzirschová
![Nakladatel - duplicitní info](https://user-images.githubusercontent.com/86351100/138059211-342dd04c-1a17-4c27-9323-fcdfb75b6168.png)

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova data jsem na sdnnt-test reindexoval

**Comment by Cypzirschova** [comment]
@pavel-stastny chyba stále přetrvává na testu

**Comment by pavel-stastny** [comment]
Z důvodu nasezní nové verze se musí promazat data na testu, po přemazání se již nebude vyskytovat.

**Comment by pavel-stastny** [comment]
Již se nevyskytuje ani ani na testu.
