### ISSUE TITLE
Dokud není žádost odeslaná, pak by měl mít možnost akce nad dokumentem i jiný uživatel 

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#120]
Dobrý den,
pokud uživatel 1 (např. Knihovna) zadá návrh na vyřazení, ale neodešle jej, pak další uživatel 2 (např. Nakladatel) nemůže podat návrh na vyřazení (u dokumentu je příznak "Záznam má návrh: VVS").

![Knihovna_neodeslane_zadosti](https://user-images.githubusercontent.com/92719629/138065122-e18d60fd-a45d-4e10-a006-f05bab14d915.png)

![Nakladatel_nema_moznost_vyradit](https://user-images.githubusercontent.com/92719629/138065138-04b236b1-a083-42f6-acbc-0de2cddf68e0.png)

**Comment by CIZKOVAL** [comment]
Dobrý den,
doplňuji jak by to mělo fungovat a poprosím o potvrzení paní @Cypzirschova, zda souhlasí s popisem očekávaného chování:

žádost na změnu 1
uživatel A
uživatel B

**Očekávané chování:** 

uživatel A - původní stav 0 - zadá žádost na změnu 1 --> **okamžitě se změní stav 1**
**dokud není žádost schválená kurátorem, pak:**
uživatel B - **vidí původní stav 0** - může zažádat o změnu 1 -- změní se stav 1

**Nyní se aplikace chová následovně:**

uživatel A - původní stav 0 - zadá žádost na změnu 1 --> **zůstává původní stav** - ten se změní buď po refresh stránky nebo po odeslání žádosti 
uživatel B - **vidí stav 1** - nemůže zažádat o změnu

**Comment by Cypzirschova** [comment]
Jen mi není jasný pojem  "zadá žádost na změnu 1 --> **okamžitě se změní stav** 1" - stav by se měl měnit až po rozhodnutí kurátora.

Jinak to je, tak jak píše paní Čížková. Díla nesmí být blokovaná pro jiné uživatele, jak je to v současné době nastavené v aplikaci.

**Comment by Cypzirschova** [comment]
Tak takhle je to správně, jak je výše uvedeno.

**Comment by CIZKOVAL** [comment]
Upravuji tedy takto:

interní stav 0 = akce 
stav 0
uživatel A
uživatel B

**Očekávané chování:**

uživatel A - původní stav 0 - interní stav 0 - podání návrhu --> stav 0, **interní stav 1**
dokud není žádost schválená kurátorem, pak:
uživatel B - původní stav 0 - **interní stav 0** - může podat návrh --> stav 0, interní stav 1

_Pozn. poté, co kurátor schválí návrh, tak se změní i stav z 0 -->1_

**Nyní se aplikace chová následovně:**

uživatel A - původní stav 0 - interní stav 0 - podání návrhu --> stav 0, **interní stav 0** (ten se změní buď po refresh stránky nebo po odeslání žádosti)
uživatel B - původní stav 0 - **interní stav 1** - nemůže zažádat o změnu

**Comment by pavel-stastny** [comment]
Změněno v novém layoutu

**Comment by CIZKOVAL** [comment]
Dobrý den,
proces funguje správně v tomto ohledu: 
Pokud uživatel A zadá žádost (návrh, tj. interní stav) na díle 1, pak se pro něj možnost další akce nad tímto dílem zablokuje.
Uživatel B může až do okamžiku zpracování žádosti kurátorem zadávat žádosti na díle 1.

**Poznámka:**

uživatel A (Knihovna) zadal návrh VN a poté se pro něj akce zablokuje, ale **není zde zobrazen interní stav** (konkrétně VN) - to by asi mělo být, to je ta změna interního stavu na 1

uživatel B (např. Lucie Čížková) může provádět akci nad dílem až do okamžiku zpracování žádosti. Tento uživatel interní stav nevidí, tj. OK

uživatel C (Kurátor) vidí interní stav (konkrétně VN) a může změnit stav na N-vyřazeno, toto je podle mě OK.

Poprosim pani @Cypzirschova o potvrzeni vyse uvedeneho.

![knihovna_akce](https://user-images.githubusercontent.com/92719629/144032270-b6614003-b61c-4ffb-bae4-40302fa3e065.png)

![CIZKOVAL_VN](https://user-images.githubusercontent.com/92719629/144032010-6826a16b-c848-49a8-951e-186a74278097.png)

![kurator_VN](https://user-images.githubusercontent.com/92719629/144032026-149c1bcc-53dc-4bc1-ae7f-8b8c6bc36764.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Jenom poznamka.  NZN, VN, VNL a VNZ nejsou reprezentovany v aplikaci jako interni stavy ale vazby dokumentu na zadost.  Stav nebo interni stav je vzdy exkluzivni.  Tedy kdyz je A jiz nemuze byt PA, N, X atd...  u vazeb tomu tak neni.    Dokument muze mit vice vazeb na ruzne zadosti.  (Jeden dokument muze byt v zadosti VN, VNZ i VNL a pokud je ve stavu PA tak i NZN)

**Comment by CIZKOVAL** [comment]
Dobrý den, tomu rozumím, že u 1ho dokumentu může být několik žádostí a mohou se lišit. Jde mi o to, že když já jako uživatel podám např. návrh VN, tak se pro mě už další akce nad tímto dílem zablokuje - šlo mi o to, jestli nezobrazit ten interní stav i pro tohoto uzivatele (ktery uz nemuze provest zmenu)

**Comment by Cypzirschova** [comment]
Souhlasím, že by sám navrhovatel o vyřazení/zařazení měl vidět, proč už dál nemůže s dílem pracovat, když se jen jemu konkrétní dílo zablokuje. Viz komentář níže (úplně dole pracovní stavy).
https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-919140167

**Comment by pavel-stastny** [comment]
@Cypzirschova Ok, můžu přidat informaci o žádosti i pro uživatele.

**Comment by Cypzirschova** [comment]
Jestli by to šlo, tak bych to dala jenom toho konkrétnímu uživateli (po přihlášení), který žádost podal.

**Comment by CIZKOVAL** [comment]
Retest OK

![VN_zadost](https://user-images.githubusercontent.com/92719629/156748340-aee4528c-651c-49d6-b72e-ddc742a3504a.png)
