### ISSUE TITLE
U dokumentu ve stavu X (volné) se v přehledu žádostí nezmění jeho stav 

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#126]
Dobrý den,
v roli "Knihovna" jsem vybrala dokument, který byl ve stavu X (Volný). 
Odeslala jsem žádost NZN - návrh na zařazení a v roli "Kurátora" jsem žádost schválila a zpracovala.

Očekávám, že se v přehledu žádostí "Moje konto" změní stav u daného dokumentu na PA (Dílo publikováno jako návrh). Daný stav se ale nezměnil a zůstává X.

![zmena_stavu_X](https://user-images.githubusercontent.com/92719629/139053122-78e8f7a3-fa3c-426f-b665-db243f3afdad.png)

**Comment by Cypzirschova** [comment]
Nebylo by jednodušší, kdyby se volná díla, co jsou už v aplikaci, nedaly vůbec navrhovat do SDNNT?

**Comment by pavel-stastny** [comment]
@Cypzirschova To je záležitost ošetření na straně UI ale myslím, že to má teď smysl řešit až s issue #66 .  (Bude tam hodně změn i na UI)

**Comment by pavel-stastny** [comment]
X by  již nemělo jít zařadit.

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK. Volná díla X nelze zařadit na seznam (není možnost akce NZN).
