### ISSUE TITLE
Historie změn- připomínky

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#129]
Kopírováno z issue #110 

Dobrý den,
ověřovala jsem prozatím historii stavu a změny se sem již zapisují.

Jsou zde ale následující chyby:

název díla není kompletní
sloupec Licence je prázdný
sloupec Typ se plní v případě, kdy kurátor mění stav. Při změně stavu ale kurátor vyplňuje pole "Poznámka", které se poté projeví v poli "Typ" - toto by se mělo sjednotit

![image](https://user-images.githubusercontent.com/675753/139829937-afeb2126-1f5b-4730-8211-0fbca0a48f1e.png)
![139826747-1b8615ab-4203-4126-bd77-bdadc1254a83](https://user-images.githubusercontent.com/675753/139830011-0b2d1000-378b-4c20-ae27-1f5c20236736.png)

**Comment by CIZKOVAL** [comment]
Dobrý den,

- název díla stále není kompletní
- sloupec Licence se plní, ale je zde chyba #199 
- kurátorovi se zobrazuje i ID žádosti, ale popis sloupce je desc.zadost - týká se to **Historie stavu** i **Historie kurátorského stavu**

_Poznámka: je v pořádku, že běžný uživatel (user) nevidí ID žádosti v historii?_

![historie_stavu_retest](https://user-images.githubusercontent.com/92719629/145840528-9ed3e723-8198-42a4-b972-5e9f93d47747.png)

![historie_kur_stavu](https://user-images.githubusercontent.com/92719629/145840552-fec91c57-87f3-44a3-ad4e-0e862977799c.png)

![user_historie](https://user-images.githubusercontent.com/92719629/145840564-0a2bf389-3856-463e-a72c-dd32f9353e12.png)

**Comment by pavel-stastny** [comment]
Doplněn název. Ohledně id žádosti, je to z toho důvodu, že se jedná o informaci pouze pro kurátora.

**Comment by CIZKOVAL** [comment]
Retest OK. Kurátor vidí navíc historii kurátorského stavu a číslo žádosti.

![kurator_historie](https://user-images.githubusercontent.com/92719629/153384247-50f95d04-a69a-478a-b418-57c1e88ce1ce.png)
