### ISSUE TITLE
Připravit statické texty

### ISSUE THREAD

**Issue by pavelkocourek** [NLCR/SeznamDNNT#13]
Statické texty v html  (převezmou se jak jsou nebo proběhne revize?)
Aktuality, O DNNT, Čtenářům, Autorům, Nakladatelům, Knihovnám,
+ Popis API připraví AH

**Comment by JanMeritus** [comment]
@Cypzirschova prosim o pripravu prozatimni textace k seznamu DNNT pro aplikaci

**Comment by Cypzirschova** [comment]
@JanMeritus Stačí úprava textů převzatých z dnnt.nkp.cz? Bude stačit poslat pak zase mailem? Jednotlivé záložky budou, jak je nyní v app (o DNNT, aktuality, čtenářů,, autorům, nakladatelům, knihovnám)?

**Comment by JanMeritus** [comment]
@Cypzirschova urcite ano. Zalozky muzu byt takto, ale muze ich byt i mene, to je na Vas. V zasade by se to malo tykat hlavne informaci k seznamu pro jednotlive skupiny.

**Comment by pavel-stastny** [comment]
Položka nakladatele je sloučena s autory.  Zavírám v případě potřeby je možno otevřít nové issue s chybějícím textem, popiskem.
