### ISSUE TITLE
Layout refactoring / zmena layoutu

### ISSUE THREAD

**Issue by pkudela** [NLCR/SeznamDNNT#130]
Behem vyvoje SDNNT a postupneho rozsirovani aplikace  bylo nutne komplentne zmenit layout reusult-item komponenty (karty vysledku). Aby to davalo smysl a prineslo to zlepseni prehlednosti uzivatelum, snazil jsem se to svazat s facetem "stav dokumentu" a "licence". Zkratku stavu jsem pouzil jako barevne oznaceni stavu, podle ktereho lze snadno identifikovat jenotlive karty vysledku. Kazde takove oznaceni je v karte vysledku osazeno tooltipem, kde je zobrazen plny nazev stavu / licence. Pozice stavu / oznaceni dokumentu je ted nove v leve casti karty. Nove jsem take predelal tlacitka, ktera se v soucasnem zobrazeni casto michaly se stavem, ktery nemel tak vyraznou barevnou identifikaci a zaroven uzivatel jasne nevedel, jestli se jedna o stav / oznaceni, nebo o tlacitko, ktere dela nejakou akci. Tlacitka jsem nyni sjednotil do skupiny a jsou umisteny vpravo, takze pro uzivatele je nyni jasne, ze vlevo jsou jakesi identifikatory a vpravo jsou tlacitka, ktere neco delaji / zobrazuji. S ohledem na nedostatek mista v puvodnim zobrazeni, kde se layout karty v nekterych situacich rozpadal a na budouci vyvoj aplikace jsem vetsinu akci schoval pod dropdown tlacitko "vice". Cili pokud se rozhodneme v budoucnosti pridat nejaky dalsi identifikator, nebo nejake tlacitko, ktere bude delat najakou akci, tak pak by s mistem nemel byt problem. Pro predstavu prikladam par screenshotu + odkazy na soucasnou a novou verzi:

Soucasna verze -> https://sdnnt-dev.nkp.cz/sdnnt/search?page=0
Nova verze -> https://sdnnt-dev.nkp.cz/sdnnt-0.85_nl/search?page=0

![image](https://user-images.githubusercontent.com/16591052/139848367-27495bc8-e0fd-442c-8767-186a429dc5f4.png)

![image](https://user-images.githubusercontent.com/16591052/139846972-5902f059-a193-46ed-841e-f1670898ec97.png)

![image](https://user-images.githubusercontent.com/16591052/139847074-60e69924-319f-411f-aaab-d9151c203724.png)

Doslo tam i jinym vylepsenim mensiho vyznamu. Nize porovnejte stavajici zobrazeni s novym:

![image](https://user-images.githubusercontent.com/16591052/139848707-2ff928e2-f163-44a7-a968-c097b13248f4.png)

![image](https://user-images.githubusercontent.com/16591052/139848777-6744859b-17c2-42e5-ba7a-df7dfa39b927.png)

Prosim podivejte se na to a pokud byste meli nejake podnety, muzeme dat k tomuto issue kratky meeting pred tim, nez udelame merge teto verze se soucasnou.

Take jsme s Pavlem premysleli o zpropagovani nekterych stavu formou barevne designovanych karet ne home page, ktere by odkazovaly na filtrovane vysledky. Podobnym zpusobem jsem to resil v digiarchivu viz. priklad -> https://digiarchiv.aiscr.cz/
Tim bychom mohli designove osvezit titulni stranku a zaroven vice provazat home page s vysledky. Titulni stranka by si zaslouzila vice uprav, mam nejakou predstavu, ale tu bych s vami potreboval probrat.

@JanMeritus , @CIZKOVAL , @Cypzirschova prosim o komentare.

**Comment by pavel-stastny** [comment]
@JanMeritus Ad odkaz na digiarchiv.  Tímto způsobem by byly řešeno issue ohledně statistik pro uživatele. Viz issue #78

**Comment by Cypzirschova** [comment]
Vypadá to dobře. Akorát by bylo potřeba, aby po přejetí kurzorem myši, bylo vidět, co ty zkratky (stavy) znamenají. Když uživatel sjede níže např. konec stránky, tak nebude vědět, co jednotlivé stavy znamenají.
@Lichtenbergova

**Comment by pkudela** [comment]
@Cypzirschova to by takto melo fungovat viz. screenshot nize a jestli se nekde plny nazev neobjevuje, tak se jedna o chybu, pak prosim o seznam stavu, kde se tak nedeje.

![image](https://user-images.githubusercontent.com/16591052/139856104-1e830480-e834-4288-9533-69c7cdb494b4.png)

**Comment by Cypzirschova** [comment]
Mě to bohužel funguje pouze u licence.

**Comment by pkudela** [comment]
@Cypzirschova uz jsem to upravil, jakmile zmergujeme tyto zmeny layputu a dame na server, tak toto issue dam k testovani.

**Comment by JanMeritus** [comment]
@pkudela @pavel-stastny  kedy mozme ocakavat testovaci verzi pro nasazeni na server? FYI @CIZKOVAL @smallcubes @Cypzirschova

**Comment by pavel-stastny** [comment]
@JanMeritus Ted jsme ve fazi predelavani worflow.  Az bude hotove dame to na dev server.  Test muze nasledovat hned potom.

**Comment by Cypzirschova** [comment]
Dobrý den,
už se ví přibližný termín, kdy bude nasazená nová verze? Jestli to máme dát k testování nakladatelům, tak musíme mít dostatek času, abychom to mohli nejprve otestovat i my.
Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Dobrý den, na dev dneska večer.  Měla by pokrývat nový layout plus řešené workflow z issue 66 . Dále ještě připravíme instalační balíček ale to popíšu separátně v mailu.  Zatím se ještě řeší věci na  UI.

**Comment by pkudela** [comment]
@Cypzirschova dobry den, prosim, zavrete toto issue, tykalo se to zmeny layoutu komponent v karte + souvisejicich prvku a to uz je davno hotove. Dekuji

**Comment by Cypzirschova** [comment]
Dobrý den, issue musíte uzavřít Vy. @pkudela

**Comment by pkudela** [comment]
OK, diky za zpetnou vazbu.
