### ISSUE TITLE
Změny nutné z důvodu dvou bází DNT a SKC

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#131]
Bylo domluveno následující: 

- Jsou harvestované dvě báze: SNK a DNT  
- Obě jsou harvestované tak jak jsou - tedy nedochází  ke ztotožnení děl z SKC a DNT 
   Viz komentáře:  
      - https://github.com/NLCR/SeznamDNNT/issues/98#issuecomment-948364826
      - https://github.com/NLCR/SeznamDNNT/issues/98#issuecomment-948438676
      - https://github.com/NLCR/SeznamDNNT/issues/55#issuecomment-905314150

- Běžný uživatel vyhledává a pracuje pouze nad seznamem. Knihovna, kurátor a admin má možnost prohledávat celý SKC 

Možné problémy: 

Duplicitní dílo -  Knihovna může pracovat s dílem, které je zároveň v SKC a přitom existuje jeho dvojče v DNT:  Poznámka: U běžných uživtelů by k tomu docházet nemělo, pracují jenom se seznamem 

Odkazy do katalogu  do báze DNT nebudou existovat (Báze dnt se vypne) -   Souvisí s prvním bodem.  Správný odkaz do katalogu obsahuje obraz z báze SKC naproti tomu v DNT jsou informace o granularite, stavech, licencích atd.. 

Prosím o komentáře: 

@Cypzirschova @JanMeritus @Lichtenbergova

**Comment by Lichtenbergova** [comment]
Duplicitní dílo - nevím jestli rozumím dobře - v SKC jsou pro jedno dílo dva záznamy. Z toho jeden je již v SDNNT, se stavem např. A. Pokud pošle knihovna nyní (tedy prostřednictvím excelu) požadavek na zařazení druhého záznamu (nebo i téhož, pokud jeho přítomnost v seznamu přehlédne), návrhy procházejí kontrolními programy, které nastavoval R. Zahořík. 
Pokud se duplicitní záznamy výrazně liší, máme smůlu, program duplicitu neodhalí, duplicita bude i v aplikaci. 

Alephovská báze DNT se po zahájení provozu aplikace vypne, aplikace ji nahradí.

**Comment by pavel-stastny** [comment]
@Cypzirschova @Lichtenbergova @JanMeritus 

Jak jsme probírali na schůzce.  Porovnání dvou záznamů (DNT a SKC) 

https://sdnnt-dev.nkp.cz/sdnnt/search?q=cnb000413550&fullCatalog=true&page=0  (musíte být přihlášený pod účetem knihovna)

Odkaz do katalogu (báze DNT - přestane existovat)  https://aleph.nkp.cz/F/?func=direct&local_base=DNT&doc_number=000183867

Odkaz do katalogu (báze SKC ) 

https://aleph.nkp.cz/F/?func=direct&doc_number=000424724&local_base=SKC

**Comment by JanMeritus** [comment]
@pavel-stastny ako je to technicky teda nakonec vyreseno? na schuzce sme probirali vicero reseni, tento problem nebyl jednoduchy - core proto ze jeden zaznam v DNT obsahuje ve skutecnosti aktualne vic zaznamu z SKC, prosim jeste o vyjadreni p. Lichtenbergovu

- v ramci pilotniho testovaciho provozu si bude nutne overit co se ze zaznamy deje pokud dojde k jejich zmene/slouceni/rozpadu zaniku v SKC 

FYA @CIZKOVAL @smallcubes  - zasadni funkcionalita

**Comment by pavel-stastny** [comment]
@JanMeritus Nejdřív se to musí vyřešit/rozhodnout metodicky.

**Comment by JanMeritus** [comment]
@pavel-stastny aby se mohlo metodicky rozhodnou boli sme dohodnuti ze dodate informaci kolik je toho propojeno a kolik se toho meni, bez toho pri zavedeni aplikace do produkce se riskuje nestabilita prenosu prav

**Comment by pavel-stastny** [comment]
@JanMeritus  ??   -  To prece neni pravda.

**Comment by JanMeritus** [comment]
muzme si k tomu zavolat. Dve schuzky dozadu se resilo ze potrebujeme ziskat vice informaci k tomu jak je to propojeno a jak je to udrzitelne provozovat do budoucna. prosim prip. p. @Lichtenbergova o upresneni

**Comment by pavel-stastny** [comment]
@JanMeritus Asi jo, pamatuju si tu schůzku ale mám uplně jiné závěry z ní.

**Comment by JanMeritus** [comment]
@Lichtenbergova slo o to, kolik tato aplikace ma aktualne propojenych zaznamu s SKC a jakych, pokud ma fungovat vypnuti baze DNT, to muze stanovit jenom dodavatel teto aplikace

**Comment by pavel-stastny** [comment]
@JanMeritus Žádný.  Viz komentáře  v úvodu tohoto issue.

**Comment by smallcubes** [comment]
@pavel-stastny měl bych ještě dotaz. Tlumočím dle @JanMeritus, pokud jsem to špatně pochopil, poprosil bych o opravu. 

Co se stane, pokud zmizí dílo ze SKC, ale zároveň už má dílo nějaký stav v seznamu v SDNNT?

**Comment by pavel-stastny** [comment]
@Cypzirschova Od další verze se již nebudou zobrazovat odkazy do báze DNT (bude vypnutá).  Kurátor má možnost zobrazit / vyhledat záznam v alephu dle ččnb.  (Je napsán proces, který umožní obohvatit DNT zánam o link)

**Comment by Cypzirschova** [comment]
Takže z aplikace zmizí úplně odkaz na záznam?

**Comment by pavel-stastny** [comment]
Ano

**Comment by Cypzirschova** [comment]
Nebudou tam vůbec odkazy do SKC na jednotlivé záznamy?

**Comment by pavel-stastny** [comment]
Ty které pochází z SKC tak tam budou, u těch, které pochází z báze DNT bude mít kurátor položku pro zobrazení odpovídajícího záznamu v katalogu dle ČČNB .

**Comment by JanMeritus** [comment]
@smallcubes prosim o kontrolu nastaveni dle @pavel-stastny

**Comment by smallcubes** [comment]
@pavel-stastny jestli si dobře vzpomínám, tak na schůzce v 4/4/2022 padlo, že by se mělo něco nastavit. Poprosil bych Vás o popsání postupu.

**Comment by smallcubes** [comment]
@pavel-stastny poprosil bych o popis nastavení 
@JanMeritus

**Comment by CIZKOVAL** [comment]
@smallcubes, @pavel-stastny je možné toto issue uzavřít? Popis popsán v issue #387.
