### ISSUE TITLE
Reset hesla: Odeslání požadavku trvá příliš dlouho

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#132]
Dobrý den,

pokud jako uživatel odešlu požadavek (_"Zapomněli jste heslo"_) pro reset hesla, tak jeho odeslání trvá příliš dlouho cca. 13 sekund. 

https://user-images.githubusercontent.com/78028909/140030205-ee2d7ded-c00f-477a-a1af-9ca0a2995793.mp4

![obrazek](https://user-images.githubusercontent.com/78028909/140032024-da3b4175-f4ba-4a11-b720-e507375935df.png)

**Comment by pavel-stastny** [comment]
@smallcubes Tipl bych, že to je ten stejný problém co byl s DEVEm .

**Comment by pavel-stastny** [comment]
Viz #122
