### ISSUE TITLE
Reset hesla

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#133]
Dobrý den,
nemohl by se přejmenovat název Poslat resetovací token na např. Obnovit heslo, Poslat nové heslo nebo něco podobného?
![reset](https://user-images.githubusercontent.com/86351100/140036003-544f5d6f-8264-4c8e-8ed7-ce3feae71528.jpg)

Cypzirschová

**Comment by pkudela** [comment]
@Cypzirschova ano, muzeme prejmenovat, jakmile se k tomu dostanu a bude to nasazene, dam vedet.

**Comment by Cypzirschova** [comment]
Super, děkuji.

**Comment by pkudela** [comment]
@pavel-stastny prosim oznac pro testovani, az bude nasazeno, je to jiz hotove

**Comment by Cypzirschova** [comment]
Děkuji za zpracování.
