### ISSUE TITLE
Správa uživatelů - při editaci polí neprobíhají žádné validace

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#135]
Dobrý den,
pokud se do SDNNT přihlásím jako ADMIN a chci editovat pole v sekci "Správa uživatelů", pak zde neprobíhají žádné validace. Kromě zašedlého pole "Přihlašovací jméno" můžu ostatní pole vyplnit jakkoliv nebo nevyplnit vůbec.

![ADMIN_správa_uživatelů](https://user-images.githubusercontent.com/92719629/140040963-e8c1cbf1-50dc-4a84-a629-4d0db8732a54.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, problém stále trvá. Kdy bude prosím opraveno?

**Comment by pavel-stastny** [comment]
Hotovo. Nasazeno na devu

**Comment by CIZKOVAL** [comment]
Retest OK

Validace probíhají u těchto polí:

FO - jméno, příjmení, email
PO - jméno, příjmení, email, kontaktní osoba jméno, kontaktní osoba příjmení.

Uživatelské jméno je v obou případech povinné a editovat nelze.

Všechna povinná pole jsou označena hvězdičkou a musí být vyplněna.
