### ISSUE TITLE
Vytváření žádosti na vyřazení děl a více prázdnych žádostí

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#136]
Dobrý den,

v kontu nakladatel jsem měla více prázdných žádostí (2), které neobsahovaly žádná díla. Tyto žádosti jsem tam měla z předchozích dní. Dnes jsem chtěla vytvořit novou žádost, ale díla se mi rozhodila do těch 2 žádostí, které tam byly z předchozích dnů. Nemělo by se to přidávat do 1 žádosti? 
Bylo by asi dobré, kdyby si nakladatel/knihovna mohla prázdné žádosti smazat nebo byly automaticky po určitém časovém úseku smazány, kdyby byly prázdné.
![přidání záznamů1](https://user-images.githubusercontent.com/86351100/140268930-03b52e2c-d38e-4201-9515-e43ced5c056f.jpg)
![přidání záznamů2](https://user-images.githubusercontent.com/86351100/140268943-3e208973-f8b0-4b2e-b43b-ba497907e6e8.jpg)

Cypzirschová
@pavel-stastny

**Comment by pavel-stastny** [comment]
@Cypzirschova V rámci nového layoutu jsme zavedli tlačítko smazat žádost.

**Comment by Cypzirschova** [comment]
Za mě OK, zavírám.
