### ISSUE TITLE
Změna osobních údajů - povinná pole

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#138]
Dobrý den,
při změně osobních údajů neprobíhá validace povinných polí.

Uživatel může všechno smazat (zůstává pouze "Přihlašovací jméno") a změny lze uložit.
Pole "Příjmení" by mělo být označeno hvězdičkou a být také povinné.

Poznámka: možná by byl vhodnější název formuláře "Osobní údaje" místo "Registrační formulář"

![Změna_osobnich_udaju](https://user-images.githubusercontent.com/92719629/140305049-33a50ccd-99e9-4a9b-81d0-43c816d8843d.png)

**Comment by CIZKOVAL** [comment]
Předpokládám, že souvisí s #134

**Comment by CIZKOVAL** [comment]
Dobrý den, problém stále trvá, kdy bude prosím opraveno?

**Comment by pavel-stastny** [comment]
Hotovo. Nasazeno na devu

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK

**Comment by CIZKOVAL** [comment]
Validace probíhají u těchto polí:

FO - jméno, příjmení, email
PO - jméno, příjmení, email, kontaktní osoba jméno, kontaktní osoba příjmení.

Uživatelské jméno je v obou případech povinné a editovat nelze.

Všechna povinná pole jsou označena hvězdičkou a musí být vyplněna.
