### ISSUE TITLE
Přehled požadavků - některé filtry nelze po prohlížení žádostí zrušit

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#140]
Dobrý den,
jsem přihlášená v roli "Kurátor" --> Moje požadavky --> filtr Instituce=NKP -->jsou zobrazeny všechny záznamy odpovídající filtru.

Pokud chci zpracovat konkrétní žádost nebo pokud si chci prohlédnout žádosti a poté se vrátím k přehledu, pak už nevidím možnost zrušit filtr. Filtr lze zrušit pouze tak, že vyberu další podmínku filtru a poté se objeví možnost "Zrušit filtry".

**Toto se děje u následujících filtrů:**
_Instituce
Priorita
Delegovaný kurátor_

Filtry _Stav žádosti_ a _Typ návrhu_ jsou OK.

![zrušení_filtru](https://user-images.githubusercontent.com/92719629/140486719-c44e85e7-7b77-4f1e-a3a8-2996101cf2ba.png)

![po_akci_zrušení filtru](https://user-images.githubusercontent.com/92719629/140487298-07723e64-49ef-46a3-ba47-acd63fbec675.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Děje se to i na devu ?

**Comment by CIZKOVAL** [comment]
ano

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK, zavírám.
