### ISSUE TITLE
Špatně fungující filtr pro díla mimo seznam

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#141]
Dobrý den,
filtr "Zobrazit dokumenty, které nejsou zařazeny na seznamu" nefunguje správně. Měl by vracet pouze díla, která jsou mimo seznam. **Nyní vrací díla mimo seznam + díla na seznamu.**

Příklad: filtruji dílo "Farma zvířat" - zobrazí se 4 díla --> zaškrtnu volbu "zobrazit dokumenty, které nejsou zařazeny na seznamu" - zobrazí se 8 děl.

Mezi těmito díly jsem podle dalších identifikátorů našla 4 díla, která jsou na seznamu.

![farma_zvirat](https://user-images.githubusercontent.com/92719629/140711504-bf9ec100-4167-47de-b654-471b6734fae4.png)

![farma_zvirat_mimo_seznam](https://user-images.githubusercontent.com/92719629/140712341-84719cac-eadf-41b4-96dc-01bd36d40ccc.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Souvisí s daty na testu.

**Comment by CIZKOVAL** [comment]
Na DEV je situace stejná

![DEV_farma_zvirat](https://user-images.githubusercontent.com/92719629/140738041-1165f2b6-d4fd-4b59-96be-b7c4a859511e.png)

![DEV_farma_zvirat_mimo_seznam](https://user-images.githubusercontent.com/92719629/140738059-72f49aa4-be11-4499-8100-50cc0f141134.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Aha, tak to jsme nerozuměli resp. Já jsem neporozuměl.  Ta funkcionalita je jak jste pospsala na začátku, 

Se zaškrtnutým checkboxem se vyhledává v seznamu + v katalogu a měla by to být možnost pro knihovny přidávat do seznamu i díla z katalogu.

**Comment by JanMeritus** [comment]
@Cypzirschova prosim o upresneni jak by to dle vas melo byt uzivatelsky najlepe

@CIZKOVAL tak jako tak. UI musi o tom jednoznacne vypovidat aby to uzivatele nematlo

**Comment by Cypzirschova** [comment]
@JanMeritus  Lepší by bylo pokud se zaškrtne Zobrazit dokumenty, které nejsou na seznamu, aby byly vidět jenom dokumenty, které nejsou na seznamu. Uživatele to může mást, když to bude sloučené i s díly, které jsou na seznamu.

**Comment by Cypzirschova** [comment]
@JanMeritus Možná by se do toho dala přidat díla, která jsou vyřazená. Ty se mohou znovu zařadit např., když je dílo nedostupné na trhu (před tím bylo vyřazeno např. na základě dostupnosti).

**Comment by pavel-stastny** [comment]
@Cypzirschova @JanMeritus  Ale já myslím, že to vychází z toho jaká byla domluva s @albertoh s paní @Lichtenbergova.  Uživatelé mají právo procházet/prohledávat jenom to co je nebo bylo na seznamu sdnnt .   Knihovny a kurátoři mají právo prohledávat celý všechno  -  tedy seznam + katalog.   Tento checkbox odpovídá právě té volbě dostupné pro knihovny.  Při zapnutém checkboxu mohou hledat ve všem.

@JanMeritus TJde o název UI prvku. On byl nešikovně pojmenován a toto se řešilo v  Issue #109  bod 9

**Comment by CIZKOVAL** [comment]
@Cypzirschova @Lichtenbergova @JanMeritus Poprosím o potvrzení výše uvedeného, tzn., že filtr má knihovnám a kurátorům zobrazit všechno. Pokud ano, tak by se asi měl lépe nazvat filtr "Zobrazit dokumenty, které nejsou zařazeny na seznamu", např. "Zobrazit **i** dokumenty, které nejsou zařazeny na seznamu" nebo "Zobrazit včetně dokumentů mimo seznam", apod.

**Comment by Lichtenbergova** [comment]
Souhlasím, formulace "Zobrazit i dokumenty, které nejsou na seznamu" je výstižnější.

**Comment by JanMeritus** [comment]
@CIZKOVAL zde jde o rozhodnuti spravcu s ohledem na stanoveny biznis model, za mne ok

**Comment by pavel-stastny** [comment]
Text změněn

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK, popisek upraven

**Comment by CIZKOVAL** [comment]
Jeste poprosim o vyjadreni p. @Cypzirschovou, ze je to takto OK, tedy ze mezi díly i mimo seznam je všechno (díla ze seznamu + díla mimo seznam)....pro uživatele je to trochu zmatené, pokud nehledá konkrétní dílo. Díla mimo seznam nemají stav a nedají se jednoduše filtrovat. Možná kdyby tam bylo něco jako Stav=null tak by se zobrazily pouze díla mimo seznam...

**Comment by Lichtenbergova** [comment]
Pro testování bych nechala takto, knihovny by to měly používat pro vyhledávání. Pokud by to nevyhovovalo, můžeme nastavení změnit. Nefunguje filtr - jsou tam i zahraniční díla.

**Comment by Cypzirschova** [comment]
Otestováno a funguje. Zatím tedy necháme takto a případně by se změnilo, pokud by to knihovnám nevyhovovalo.
Do SDNNT mohou být navrhována pouze díla vydaná na území ČR. Dá se omezit polem 008 - Místo vydání (15-17): xr.

**Comment by CIZKOVAL** [comment]
Dobrý den, děkuji. Založím novou chybu na ty zahraniční díla.

**Comment by CIZKOVAL** [comment]
Zalozeno https://github.com/NLCR/SeznamDNNT/issues/164
