### ISSUE TITLE
Zapnout / vypnout hromadne sledovani na zaklade filtru

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#142]
ze #40 

moznost v UI zapnout/vypnout sledovani **hromadne**, napr. nad dilami napr z celeho nakladatelstvi / jinou vyfiltrovanou mnozinou. Notifikace by chodila hromadne v jedny sprave.

**Comment by pavel-stastny** [comment]
@JanMeritus Dle domluvy, nyní se dělat nebude.

**Comment by JanMeritus** [comment]
Dle domluvy - nemuselo se to delat v teto verzi ale v dalsi ano, jde o
pozadavek nakladatelu snad od sameho zacatku - jeho moznou implementaci
jsem navrhoval

Dňa pi 26. 11. 2021, 13:45 Pavel Šťastný ***@***.***>
napísal(a):

**Comment by CIZKOVAL** [comment]
@pavel-stastny ráda bych se zeptala, zda se počítá s hromadnými notifikacemi - nakladatelé tuto funkcionalitu velmi ocení. Požadavek byl, že není nutné aby byla v aktuální verzi (listopad 2021), ale v některé budoucí ano.

**Comment by pavel-stastny** [comment]
@CIZKOVAL V těch dvou verzích, které se připravují se s funkcionalitou nepočítá.  Můžeme probrat na schůzce.

**Comment by JanMeritus** [comment]
@pavel-stastny potvrzuje ze se tim budou zabyvat s @pkudela

**Comment by CIZKOVAL** [comment]
Hromadné notifikace jsou uz na DEV, ceka se na nasazeni na TESTu

**Comment by JanMeritus** [comment]
@CIZKOVAL @smallcubes je to otestovano?

**Comment by CIZKOVAL** [comment]
@JanMeritus ano, je to v poradku viz issue #339, ktere uz je OK
