### ISSUE TITLE
Nefungují notifikace

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#144]
Dobrý den,
u uživatele CIZKOVAL (Lucie Čížková) mám nastavené notifikace na denní bázi u následujících titulů:

Ondrova sázka, aneb, Dobrodružství s kobylkou Šimlou / Liběna Skálová ; [ilustrace] Vlasta Švejdová
Teologie Agapé : dogmatika. Josef Zvěřina Svazek II. /
Šmírák / Jan Pelc

Na všech dílech jsem 16.11. dělala nějaké změny (je vidět i v historii změn). Žádný email jsem neobdržela (adresa lucie.cizkova@nkp.cz je platná). Např. Teologie Agapé: 

![notifikace](https://user-images.githubusercontent.com/92719629/142833651-a328c00b-ff28-4f79-8e20-8ab582c283ca.png)

**Comment by pavel-stastny** [comment]
@smallcubes  Vypada to, ze neni definovana sablona pro notifikace na testu. (`~/.sdnnt/texts/mail_notification`)

**Comment by smallcubes** [comment]
@pavel-stastny ano máte pravdu, přidal jsem zmíněné 
poprosil bych @CIZKOVAL o vyzkoušení

**Comment by CIZKOVAL** [comment]
Provedla jsem nějaké změny u notifikovaných, výsledek zkontroluji zítra

**Comment by CIZKOVAL** [comment]
Notifikace už chodí, zavírám

**Comment by Cypzirschova** [comment]
@CIZKOVAL Fungovali Vám odkazy v mailu? Mě to nefungovalo.

**Comment by CIZKOVAL** [comment]
@Cypzirschova odkazy v mailu nefungovaly, právě jsem řešila s kolegou. Zadám na to separátní issue, je třeba změnit odkaz.

**Comment by Cypzirschova** [comment]
@CIZKOVAL Dobře, děkuji za zprávu.

**Comment by CIZKOVAL** [comment]
založeno nové issue: https://github.com/NLCR/SeznamDNNT/issues/149
