### ISSUE TITLE
Prosím o přejmenování záložek v SDNNT

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#145]
Dobrý den,
na základě požadavku od p. @Cypzirschova prosím o přejmenování záložky v SDNNT následovně:

O DNNT --> O SDNNT

Děkuji

**Comment by JanMeritus** [comment]
@pkudela @pavel-stastny skor by ma zaujimalo ci zalozky su konfigurovatelne nekde (nebo zasahem do DB)

**Comment by CIZKOVAL** [comment]
Dále ještě poprosím na základě požadavku od p. @Cypzirschova o sloučení záložek **"Nakladatelům"**, **"Autorům"** pod jednu záložku **"Nositelům práv"**.

Děkuji

**Comment by pavel-stastny** [comment]
Záložka přejmenována, sloučení záložek uděláme v následující verzi

**Comment by CIZKOVAL** [comment]
Záložka O SDNNT ok, ještě počkám na sloučení záložek

**Comment by CIZKOVAL** [comment]
Retest OK, zmeny provedeny. Dekuji.

![popisky](https://user-images.githubusercontent.com/92719629/144866159-e0a112ad-1d11-4e69-85af-d6ba8713e54d.png)
