### ISSUE TITLE
Změna priority žádosti

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#147]
Dobrý den,
v žádostech se dají měnit priority i po vyřízení těchto žádostí. Priorita by se měla měnit do chvíle než je žádost vyřízená, poté už by se neměla měnit.
Cypzirschová
![priority](https://user-images.githubusercontent.com/86351100/142989538-fdb8226d-aed1-4b58-8372-f53bde66e717.jpg)
![Priority1](https://user-images.githubusercontent.com/86351100/142989543-938690fb-41a2-4b63-8ed6-d2e5a926433b.jpg)
@pavel-stastny @JanMeritus

**Comment by pavel-stastny** [comment]
Nyní lze měnit prioritu a kurátora pouze, pokud je žádost ve stavu `waiting`

**Comment by Cypzirschova** [comment]
Funguje, zavírám.
