### ISSUE TITLE
Změna stavu děl 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#148]
Dobrý den,
při ruční změně stavu na PA - návrh na zařazení, se u díla zobrazí stav Zařazeno, ale v popisku je, že dílo je evidováno jako návrh, což popisek neodpovídá.
Cypzirschová
![změna stavu na pa](https://user-images.githubusercontent.com/86351100/143218340-6c02dd53-946e-473d-a42f-bd1d81e405a5.jpg)
![změna stavu na pa1](https://user-images.githubusercontent.com/86351100/143218351-790a7826-d0dd-4841-8126-4642a0e58189.jpg)
![změna stavu na pa2](https://user-images.githubusercontent.com/86351100/143218360-50351de6-3f82-425a-9893-05fdb97c1c32.jpg)

**Comment by Cypzirschova** [comment]
Po aktualizování stránky se zobrazí už správně Stav: dílo publikováno jako návrh. To by se mělo objevit ihned po změně.

**Comment by CIZKOVAL** [comment]
Totéž se mi stalo u následujících přechodů:
NZ --> VS
VN --> NZ

Děje se tak v roli Kurátora při **ručním** zásahu.
![state S](https://user-images.githubusercontent.com/92719629/143225226-50e7504d-1c64-4c6f-8e70-e2eeaa74ebe8.png)

![state_Z](https://user-images.githubusercontent.com/92719629/143225239-f1cdfe9a-4ebe-4f7c-a681-7a90980e3fb0.png)

**Comment by pavel-stastny** [comment]
Již by se mělo aktuolizovat hned po změně

**Comment by Cypzirschova** [comment]
Už to funguje, zavírám.
