### ISSUE TITLE
Úprava diakritiky a odkazu v notifikacích

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#149]
Ahoj Jirko,

- [ ] prosím o úpravu v notifikacích, aby byla zohledněna diakritika, viz níže:

Dobrý den pane/**pani**  

Seznam **zmenenych dokumentu**

- [ ] zároveň prosím o úpravu odkazu u dokumentů, ten současný nefunguje

https://server/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-000547304 ---na--> https://sdnnt-test.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-000547304

**Comment by smallcubes** [comment]
@CIZKOVAL došlo k nápravě, prosím o ověření i případné uzavření

**Comment by CIZKOVAL** [comment]
Retest NOK, stále stejné.

**Comment by CIZKOVAL** [comment]
Retest OK, diakritika i odkazy v pořádku.
