### ISSUE TITLE
Vyresit registraci korporaci a jejich delegovanych osob

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#15]
UC: Nakladatele a jejich delegovane kontaktni osoby pro podani do SDNNT

**Comment by pavel-stastny** [comment]
NAkladatel bude mit na sebe navazany osoby.  Nyni vystupuje nakladatel pouze jako role.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o status update

**Comment by pavel-stastny** [comment]
@JanMeritus Toto se nejdříve musí řešit na úrovni UI s @albertoh.

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Po domluvě s @albertoh je nutno specifikovat usecase. Nejlepší bude mít separátní call. Dříve nelze implementovat.

**Comment by JanMeritus** [comment]
Uzivatel zastupuje korporaci (nakladatele). Pozadavky jdou menem nakladatele, realizuje je ale fyzicka osoba.

Call pripadne upresnete moznosti @pavel-stastny

**Comment by JanMeritus** [comment]
muzu byt ve skupine jineho uzivatele @pavel-stastny prosim o rozepsani dle dohody, udeluje ho ke korporaci admin

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Provedeny nasledujici zmeny: 

- Na serveru je konfigurovatelny seznam instituci/korporaci
- Uzivatel si pri registraci muze nekterou z nich zvolit.
- Administrator muze zmenit v admin prostredi
- Kazda zadost a vyzva je opatrena instituci, pokud uzivatel v nektere je
- Kurator muze ted filtrovat podle instituci.

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za implementaci. 
Dle požadavku od @JanMeritus by měl *admin* schvalovat příslušnost uživatele k nějaké instituci. Možná by to měl dělat spíše hlavní kurátor @JanMeritus?

Další poznatky:
- pokud se uživatel registruje pod nějakou institucí *Instituce a*, tak ji může následně, po úspěšné registraci, změnit na jinou např. na *instituci b*
- bylo by možné do rolovací nabídky dát políčko *žádné* nebo případně nějak upozornit, že políčko není povinné?

**Comment by CIZKOVAL** [comment]
Kontaktní formulář se řeší zde: #114 
Výše zmíněné poznatky jsou OK, po dohodě se @smallcubes zavírám.
