### ISSUE TITLE
Notifikace přišla 2x za sebou

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#150]
Dobrý den, 
na uživateli cizkoval (jmeno lucciz) mám nastavené notifikace u následujících děl na denní bázi:

Nazev: Latina nejen pro teology / Milena Přecechtělová
Identifikator: oai:aleph-nkp.cz:DNT01-000130089
Stav: NZ

Nazev: Cvičebnice latiny pro střední školy, především pro gymnázia / Vlasta Seinerová
Identifikator: oai:aleph-nkp.cz:DNT01-000099945
Stav: N

24.11. 2021 jsem u nich prováděla žádosti a dostaly se do těchto stavů --> 25.11.2021 0:00 mi přišla notifikace, tj. OK

**Stejná notifikace mi ale přišla i následující den**, tj. 26.11.2021 0:00

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim o nasimulovani a potvrzeni ze problem se stale objevuje

**Comment by Cypzirschova** [comment]
Notifikace přišla 15.4. a 16.4., stavy a licence jsou stejné v obou e-mailech. 
Obě díla jsou zařazená v hromadné notifikaci.
![notifikace](https://user-images.githubusercontent.com/86351100/163957793-212221f8-f0cd-4e50-8ac1-b18ba9d3c15a.png)

**Comment by CIZKOVAL** [comment]
Mě přišla stejná notifikace např. v pátek 8.4. 2022 a v sobotu 9.4. 2022

![notif](https://user-images.githubusercontent.com/92719629/163986507-d02bbc39-e19e-4785-9f33-6a9a82fe9525.png)

**Comment by Cypzirschova** [comment]
Nevím, zda došlo k nějaké změně, ale dnes mi notifikace přišla 3x. 
![notifikace](https://user-images.githubusercontent.com/86351100/164416662-2aa6afc7-6891-4afc-880f-56409ce4f818.png)

**Comment by CIZKOVAL** [comment]
@Cypzirschova - Jirka to tam od vcerejska prenastavuje ty casy notifikaci, nefunguje totiz notifikace pro uzivatele pres Shibboleth, tak jsme delaly pokusy, toho si nevsimejte...

**Comment by JanMeritus** [comment]
- @smallcubes nastavi idealni cas rozesilani
- @CIZKOVAL otestuje v novy verzi (zejmena Shib uziky)

**Comment by smallcubes** [comment]
nové nastavení notifikací: 
- denní: každý den ve 03:00
- tydenní: každé pondělí ve 04:00
- měsíční: každý první den v měsíci v 05:00

**Comment by CIZKOVAL** [comment]
Retest OK, notifikace už chodí pouze 1x a neduplikují se.
