### ISSUE TITLE
Filtr Rok vydání se chová podivně

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#151]
Dobrý den,
když chci filtrovat podle roku vydání a zadám např. údaje od 2018 do 2018, tak to žádné záznamy nenajde, což je OK. Ale poté chci pokračovat a filtr pro zadání roku vydání je přednastaven na roky 1-23. Poté filtr zruším a rok vydání je přednastaven od r. 200 do r. 20032.

![2018](https://user-images.githubusercontent.com/92719629/143860667-ddd7cee3-682f-4f79-b84b-96c596085838.png)

![2018_zruseni filtru](https://user-images.githubusercontent.com/92719629/143860699-8e28af1b-7342-4b4d-88e2-94ed255dad5b.png)

**Comment by CIZKOVAL** [comment]
Všimla jsem si, že toto se děje pouze v případě, kdy je zaškrtnutá volba: "Zobrazit i dokumenty, které nejsou zařazeny na seznamu"

**Comment by pkudela** [comment]
@pavel-stastny to je spise na tebe, neco v ts

**Comment by pavel-stastny** [comment]
Opraveno

**Comment by CIZKOVAL** [comment]
Dobrý den, chyba trvá. Špatné zobrazení datumu je v případě, kdy je zaškrtnuta volba "zobrazit i dokumenty mimo seznam".

Defaultní rozpětí je 200-20032.

![retest_151](https://user-images.githubusercontent.com/92719629/144992672-beeab479-d3ca-4db7-8b50-cc2dea864eaf.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Nedaři se mi to reprodukovat na DEVU a na TESTu nemám knihovního uživatele.  Můžete, prosím, vyzkoušet na DEVu a případne popsat kroky? (Pokud se liší od těch již zmíněných nahoře)

**Comment by CIZKOVAL** [comment]
@pavel-stastny na DEV stejné, jsem přihlášená jako admin. Děje se to pokud je zaškrtnutý filtr, níže:

![mimo_seznam](https://user-images.githubusercontent.com/92719629/145563197-b7ebbf67-af07-4f59-ad83-8b255ce4f3ab.png)

![dev](https://user-images.githubusercontent.com/92719629/145563226-b2016076-031e-4bc7-9727-bb78f8c5d216.png)

**Comment by pavel-stastny** [comment]
Ano máte pravdu, je to pravděpodobně zpracovávaným datumem.  Vyřešíme s @albertoh

**Comment by CIZKOVAL** [comment]
Retest OK
