### ISSUE TITLE
Žádosti VNZ se zobrazují jako VNL

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#153]
Dobrý den,
pokud díla ve stavu A s licencí online omezím na terminál, tak se pak obejví jako žádosti VNL. Měly by být jako žádosti VNZ. 

Poznámka: výzvu VNL může provádět pouze jiný nakladatel nebo kurátor a asi by to mělo být nazvané jinak než omezení na terminál.

![VNL](https://user-images.githubusercontent.com/92719629/144033687-242f0471-f6d4-4798-b216-278963d9ef9a.png)

**Comment by CIZKOVAL** [comment]
Jeste jsem si vsimla preklikavaci nabidky, viz níže. K čemu má sloužit? Nyní se všechna díla překliknou buď na jedno nebo druhé...

![preklikavani_VNZ](https://user-images.githubusercontent.com/92719629/144034688-6a75deaa-77bd-4040-93e7-b51500bdbda4.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL 

> Jeste jsem si vsimla preklikavaci nabidky, viz níže. K čemu má sloužit? Nyní se všechna díla překliknou buď na jedno nebo druhé...

Ono to bylo realizováno dle [tohoto ](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-963019211)komentáře

**Comment by CIZKOVAL** [comment]
Dobrý den,
aha, děkuji. Nemělo by být tedy defaultně VNZ a po případném zaškrtnutí změna na VNL? Teď je to obráceně...

**Comment by pavel-stastny** [comment]
Může být, necháme rozhodnout paní @Cypzirschova

**Comment by pavel-stastny** [comment]
@CIZKOVAL Dal jsem implicitni volbu VNZ

**Comment by CIZKOVAL** [comment]
Ještě otázka asi na p. @Cypzirschova  - nyní se celá žádost dá překliknout na VNL nebo VNZ, což je tedy v pořádku dle návrhu v #66. 
Při podání žádosti ale uživatel u různých děl vybírá možnost "Omezit na terminál" (kdy něco chce dejme tomu jako VNZ a něco jako VNL) --> vše je sloučeno pod 1 žádost, takže pak je vše buď VNL nebo VNZ.
Mě by přišlo praktičtější, kdyby šly poté jednotlivá díla v žádosti rozlišit jako VNL nebo VNZ, ale nevím zda to lze. 

V praxi to bude asi fungovat tak, že uživatel bude vybírat najednou díla jen pro VNL nebo jen pro VNZ a nebude tedy nutné toto řešit?

**Comment by Cypzirschova** [comment]
> Dal jsem implicitni volbu VNZ

S tím souhlasím. Primárně by mělo být VNZ.

> Při podání žádosti ale uživatel u různých děl vybírá možnost "Omezit na terminál" (kdy něco chce dejme tomu jako VNZ a něco jako VNL) --> vše je sloučeno pod 1 žádost, takže pak je vše buď VNL nebo VNZ. Mě by přišlo praktičtější, kdyby šly poté jednotlivá díla v žádosti rozlišit jako VNL nebo VNZ, ale nevím zda to lze.
> 
> V praxi to bude asi fungovat tak, že uživatel bude vybírat najednou díla jen pro VNL nebo jen pro VNZ a nebude tedy nutné toto řešit?

Odlišené to být musí, protože VNL a VNZ je trochu něco jiného. VNL je omezené jen na 18 měsíců a pak by měla proběhnout kontrola. VNZ se omezí napořád, pokud nebude podána další žádost, nebo se nezvedne hranice let do kdy, jsou díla zpřístupňována pouze na terminálu.

To co navrhujete, by asi také šlo, ale spíše se k tomu přistupuje, že si nakladatelé budou vytvářet ty hromadné žádosti, které asi zatím nebyly úplně vyřešené? Jak jsem byla několik dní mimo, tak nevím, jak se pokročilo. @pavel-stastny @JanMeritus

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK. Defaultně jsou žádosti **omezení ne terminál** zobrazeny jako VNZ a lze překliknout na VNL.

Omezila jsem na terminál 3 díla - zatímco ve verzi 0.85 se vše dávalo pod 1 žádost, nyní má každé dílo svoji žádost. 
Souvisí úprava s mojí otázkou [zde](https://github.com/NLCR/SeznamDNNT/issues/153#issuecomment-984726638)?

_Poznámka: např. u žádostí NZN jsou i nadále žádosti slučovány pod 1 žádost._

![retest_153](https://user-images.githubusercontent.com/92719629/144996527-e4b790c5-d754-4241-bf78-ae619f744ac0.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Tak to je chyba.  Poprosim o nove issue

**Comment by CIZKOVAL** [comment]
Založeno issue #195 na to, 6e se neseskupují žádosti

**Comment by pavel-stastny** [comment]
@CIZKOVAL Toto issue prosim uzavrit.
