### ISSUE TITLE
Zpracováné žádosti kurátorem mají status v EN

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#154]
Dobrý den,
pokud kurátor schválí nebo zamítne žádost, tak je tento status zobrazen v angličtině. 

![potvrzeni_kuratorem_en](https://user-images.githubusercontent.com/92719629/144035379-b934d874-9c95-4ac5-b920-baf35653bbe8.png)

**Comment by pkudela** [comment]
@CIZKOVAL ano, to opravim.

**Comment by pkudela** [comment]
hotovo, @pavel-stastny prosim pridej k testovani az bude nasazeno

**Comment by CIZKOVAL** [comment]
Retest OK, zaviram.

![154_retest](https://user-images.githubusercontent.com/92719629/144871404-8d4473cf-4aaa-4c00-a697-fe102f9e0610.png)
