### ISSUE TITLE
Špatné zobrazení u zpracovaných žádostí

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#155]
Dobrý den,
provedla jsem 5 návrhů na zařazení (NZN) u vyřazených děl (N) - žádosti se sloučily do 1ho balíčku.

Kurátor 3 tyto žádosti schválil a **2 žádosti zamítl**.

Mezi žádostmi to ale vypadá tak, že všem žádostem běží nyní lhůta 0 a je zobrazeno, že budoucí stav je PA.

![zamitnute zadosti](https://user-images.githubusercontent.com/92719629/144036471-b26824d0-a8cf-44e7-a141-6cf6b37caeb7.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ne do stavu se prepnou pouze ty dokumenty, ktere byly schvalene.  (Maji stav NPA).   Ten sloupec je vicemene informativni a slouzi jako informace k tomu aby se vedelo ve ktere casti workflow se prave nachazi.   (Je to stejne, jako kdyz prijde zadost na posouzeni a cilovy stav je NPA a pritom to neznamena, ze se vsechny dokumenty schvali a skonci stavem NPA)

**Comment by CIZKOVAL** [comment]
Dobře, děkuji, už jsem se zorientovala. Návrhy (VN, VNZ, VNL, NZN vzdy zustavaji a meni se budouci stav. Ten je zavisly na tom, zda zadost ceka na zpracovani kuratorem nebo jestli se ceka na automaticke zpracovani (podle toho potom NPA nebo PA, NL nebo NLX). Zaviram.
