### ISSUE TITLE
Popisek u žádostí v tooltipu

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#156]
Dobrý den,
popisek u žádostí v tooltipu by měl být patrně stejný jako je vlevo u stavu žádosti.

![popisek](https://user-images.githubusercontent.com/92719629/144040714-93169f4d-872e-4358-bd95-b2b25f3b3946.png)

**Comment by pkudela** [comment]
Dobry den, opravim.

**Comment by pkudela** [comment]
hotovo, @pavel-stastny prosim dej k testovani az zmena bude nasazena

**Comment by CIZKOVAL** [comment]
Retest OK, dekuji, zaviram.

![retest_tooltip](https://user-images.githubusercontent.com/92719629/144991542-084abef8-359a-4a4e-8924-ca2ba72da30b.png)
