### ISSUE TITLE
Chybová hláška pokud je stejné dílo ve více žádostech

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#157]
Dobrý den,
dílo A je předmětem žádosti 1 (spolu s dalšími díly)
a zároveň dílo A je předmětem žádosti 2 (spolu s dalšími díly) 

--> kurátor schválí žádost 1 u díla A, vyhodnotí ostatní díla a zpracuje
--> kurátor chce schválit žádost 2 u díla A --> chybová hláška "Chyba při schválení návrhu. Není možné schválit stav", kurátor vyhodnotí ostatní díla v žádosti a označí žádost jako zpracovanou --> chybová hláška "Chyba při označení jako zpracované. Ne všechny žádosti jsou zpracované"

Systém se chová správně, ale budou kurátoři vědět, v čem je problém? **Tedy, že musí při schvalování 2. žádosti u díla A návrh zamítnout?**

![nelze_schvalit podruhe](https://user-images.githubusercontent.com/92719629/144206077-5e8739de-34fb-41ea-a928-25f8691c62e4.png)

![zpracovani_zadosti podruhe](https://user-images.githubusercontent.com/92719629/144206102-98bc45d1-bd0d-4b8c-92a1-3685db76f0df.png)

**Comment by pavel-stastny** [comment]
> Systém se chová správně, ale budou kurátoři vědět, v čem je problém? Tedy, že musí při schvalování 2. žádosti u díla A návrh zamítnout?

No, tady od začátku implementace bylo při posuzování kurátorem nutné projít celou žádost (přijmout nebo odmítnout) a děje se to i v případě, že některý dokument již nejde přijmout  (z důvodu změny stavu) a musí se odmítnout.  Já to chápal za správné chování.  Nicméně to je otázka na paní  @Cypzirschova

**Comment by Cypzirschova** [comment]
Ideální by bylo, když kurátor zpracuje žádost 1 i dílo A, tak by se to do žádosti 2 promítlo u díla A tak, že by tam byla informace, že už to bylo zpracované v žádosti 1. + změněný stav. Kurátor si pak může ověřit, v jaké žádosti a jak bylo rozhodnuto. 

Teoreticky by se mohlo stát, že navrhnout 2 knihovny stejné dílo. Tady je to OK, když bude vše v pořádku, tak se schválí a obě knihovny chtějí to samé tzn., chtějí zařadit dílo. Pokud jde o stejný záměr - chci, aby dílo mělo PA, tak už by se v žádosti 2 nemělo schvalovat, ale ta informace by tam měla být.

Také by se mohlo stát, že budou 2 žádosti a 2 různí uživatelé a budou chtít 2 různé akce - vyřadit úplně, omezit na terminál.

Podle mě by se mělo dát pracovat se stejný dílem ve více žádostech a změněné stavy by se měly promítnout do všech žádostí, kde dílo figuruje.

**Comment by pavel-stastny** [comment]
> Ideální by bylo, když kurátor zpracuje žádost 1 i dílo A, tak by se to do žádosti 2 promítlo u díla A tak, že by tam byla informace, že už to bylo zpracované v žádosti 1. + změněný stav. Kurátor si pak může ověřit, v jaké žádosti a jak bylo rozhodnuto.

Tak to teď je. Můžete rozhdnout pouze v jedné žádosti a v té druhé Vám nezbude nic jiného, než dílo A odmítnout. (Protože je dílo již v požadovaném stavu.)  V tom příspěvku od paní @CIZKOVAL slo právě o to explicitní odmítnutí.  Žádost neuzavřete, protože všechny položky nejsou zpracovány a položku A musíte odmítnout. (Schválit nejde) .  V historii stavů je uvedena žádost 1 a kurátor, který schvaloval dílo v žádosti 1.

**Comment by Cypzirschova** [comment]
No pokud tedy jde o to, že to nejde schválit z důvodu, že už dílo ten stav má, který byl předmětem žádosti, tak bych to asi nechala zatím takto. Kurátor se může podívat do historie díla a podle žádosti bude vědět, proč to nelze přijmout. Zítra to ještě otestuji a případně napíšu ještě nějaký komentář.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Pokud s tím takto souhlasíte, poprosil bych zavřít issue.

**Comment by Cypzirschova** [comment]
Zkoušela jsem si to otestovat. Prozatím bych takto nechala. V historii je uvedený i identifikátor žádosti, ve které proběhla změna stavu. Pokud by to dělalo v budoucnu kurátorům potíže, tak by se případně vymyslelo jiné řešení.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Prosim tedy uzavrit.
