### ISSUE TITLE
NZN u děl mimo seznam

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#158]
Dobrý den,
provedla jsem u následujícího díla, které bylo mimo seznam (stav null) žádost NZN.
Kurátor žádost schválil a nyní je dílo v interním stavu NPA (běží lhůta 0). Tento stav vidí jenom kurátor a je to zaznamenáno i v historii kurátorského stavu --> OK

**Zároveň toto dílo přešlo do stavu N a je to zaznamenáno i v historii stavu**. Je to takto v pořádku, že se ze stavu null dostal do stavu N? Ve workflow to tak zaznamenané není. 

Dílo: oai:aleph-nkp.cz:SKC01-003263541 (The war of the worlds)

![nezarazene_dilo_NZN](https://user-images.githubusercontent.com/92719629/144212335-6eb669a7-99ca-4a46-949f-1659f4bb73fe.png)

![NZN_kuratorsky stav](https://user-images.githubusercontent.com/92719629/144212353-87eb3417-ca84-4a97-accb-4d89de672e42.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ano, je to tak naimplementovane.  Resp. Neni tam situace, kdy by dilo melo nastaveno kuratorsky stav a nemelo verejny.  Z toho plyne to N.   Prosim o reakce @Cypzirschova

**Comment by Cypzirschova** [comment]
Proč je dílu dáno N (pokud to kurátor nezměnil ručně)? N nemůžou mít díla, která ještě nejsou v seznamu. N jsou díla, která byla na seznamu nebo byla už v návrzích a jsou vyřazena.

**Comment by pavel-stastny** [comment]
@Cypzirschova Tady jsem odpovídal v issue #66  a tento [komentář  ](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-987650175)

**Comment by CIZKOVAL** [comment]
Trochu se nám pomotala issues. Toto issue nechávám pouze pro díla **mimo seznam**, tj. **BEZ STAVU** a následné podání žádosti o zařazení (NZN) - po schválení se dostávají do veřejného **stavu N** (interní stav NPA). Dle paní @Cypzirschova to je špatně [viz tento komentar](https://github.com/NLCR/SeznamDNNT/issues/158#issuecomment-986705453)

Odpoved pana @pavel-stastny z issue #66:

Ok. Pokusím se vysvětlit. Ono to mělo implementační konotace. Ve workflow jsem se snažil mít vždy stav veřejný pouze jako subset stavu pro kurátory. Kurátorský stav je ten, podle kterého se řídí workflow, veřejný pak pouze pro zobrazení. Proto se při přepnutí přiřadil i veřejný stav.

**Comment by Cypzirschova** [comment]
Určitě to N mít nemůže dílo, které ani na seznamu nebylo a teprve bude navrhováno. Žádný veřejný stav tyto díla nemají a to i z důvodu, aby nám nakladatelé nezačali vyřazovat díla, která ještě ani nejsou ve stavu PA - tedy v návrhu na zařazení, kde má nakladatel 6 měsíců na vyjádření.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Nyní dílo dostane veřejný stav až stav PA, do té doby je mimo seznam (bez veřejného stavu)

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK. 

**Bez stavu** --> NZN --> schvaleno --> kuratorsky stav NPA, **běžný stav null** --> Lhůta 0 -->kuratorsky stav PA, běžný stav PA --> Lhůta 1 -->kuratorsky stav A, běžný stav A
