### ISSUE TITLE
Zadost o vyrazeni a zarazeni / zmeny stavu del

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#16]
zohlednit nalezitosti dle

korespondencni formulare

- https://dnnt.nkp.cz/downloads/vyrazeni.xlsx
- https://dnnt.nkp.cz/downloads/zarazeni.xlsx

Aktualni formulare pro vyrazeni a zarazeni 

- viz po registraci https://aleph.nkp.cz/F/?func=file&file_name=find-b&local_base=DNT

Predpokladane nalezitosti se prenesou kuratorovi v ramci podani, uzivatel by mel mit nekde potvrzeni, pripadne na mail by mu melo dojit vyrozumeni o vyrizeni/doplneni informaci

**Comment by JanMeritus** [comment]
@albertoh jaky je stav?

**Comment by albertoh** [comment]
To je duplikat #48, ne?

**Comment by JanMeritus** [comment]
castecne (ps #48 je duplikat teto issue).

**Comment by CIZKOVAL** [comment]
Dobrý den,
@pavel-stastny informace o tom, že byla zpracovaná žádost na zařazení/vyřazení díla na základě csv formuláře nesouvisí s nastavením notifikace. V rámci notifikace se řeší změny stavu u děl, které si uživatel označí jako předmět notifikace. Toto je něco jiného - pokud odešlu např. jako knihovník formulář o zařazení/vyřazení díla, tak po zpracování kurátorem by mi měla přijít notifikace na email, že byl požadavek vyřešený (aniž bych si předem díla, která jsou předětem csv souboru označila pro notifikaci).

**Comment by pavel-stastny** [comment]
@JanMeritus Tykalo se to notifikaci  ?

**Comment by pavel-stastny** [comment]
@CIZKOVAL @JanMeritus Notifikace dle zadosti jsou jiz  v jinem issue.  Formulare ktere postihuji vlastnosti prihlasovanych uzivatelu jsou podchyceny pri registraci.   Issue zaviram.
