### ISSUE TITLE
Stav NL by měl být veřejný

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#160]
Dobrý den,
díla, která jsou ve stavu NL by měla být zobrazená všem. Nyní je vidí pouze kurátor+admin mezi kurátorskými stavy.

Viditelné stavy: PA, A, N, NZ (tj. A dnntt), NL
Interní stavy: PX, X, NPA

_Poznámka: nově vznikl stav NLX, což je návazný stav na NL, který by měl být interní (v tomto stavu zatím žádná díla nejsou)_

![KURATOR](https://user-images.githubusercontent.com/92719629/144397190-44c1b1af-d4f6-4fe5-b0e2-2f5346c91d0a.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Zmenil jsem to na verejny.  Ten popisek ve fasetech nepusobi dobre, je dlouhy.  Viz obrazek 

![image](https://user-images.githubusercontent.com/675753/144409670-79bf865d-2434-40e6-968e-84521954c9d7.png)

Existuje nejaka kratsi varianta ?

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK - stav už je veřejný. Mám k tomu ale následující otázky, poprosím p. @Cypzirschova:
1. Pokud je stav veřejný pak bych očekávala, že bude i na úvodní obrazovce SDNNT 
2. šedá barva u stavu nevypadá dobře (šedé barvy se používají u interních stavů) viz [zde](https://github.com/NLCR/SeznamDNNT/issues/160#issuecomment-984520420)
3. popisek je moc dlouhý viz [zde](https://github.com/NLCR/SeznamDNNT/issues/160#issuecomment-984520420)

![NLpng](https://user-images.githubusercontent.com/92719629/144863711-61138411-7433-45cd-b621-a28c1993e469.png)

**Comment by Cypzirschova** [comment]
1.  Zde bych možná ponechala, jak je. Nejdůležitější jsou stavy A, PA, N. NL vlastně částečně řeší licence.
2. Souhlasím, zvolila bych jinou barvu. Šedou bych nechala jen pro interní stavy.
3. Bude se nejspíše upravovat.

**Comment by Cypzirschova** [comment]
@pavel-stastny  Z jakého důvodu je X veřejný stav? Pokud to takto rozhodla paní Lichtenbergová, tak je to OK. https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-919140167

**Comment by pkudela** [comment]
Dobry den @Cypzirschova, stav u stavu NL jsem nadefinoval v konfiguraci barvu viz. screenshot.

![image](https://user-images.githubusercontent.com/16591052/145025869-fde86b29-1b79-4f59-9054-e3b4a24a9a65.png)

Co se tyce zobrazeni tohoto stavu v karte na home page, tak se mi to jevi znacne problematicke co se tyce designu a mozna i dulezitosti zobrazeni tohoto stavu pro uzivatele. Zobrazeni s delkou textu, jako je ve facetech, to vypada takto:

![image](https://user-images.githubusercontent.com/16591052/145026143-86aa98dd-cf0d-47f7-8c55-96769fbdf211.png)

Pokud by byl text kratsi a jednotlive karty by byly osazeny tooltipem, ktery by po najeti mysi zobrazoval plny popis stavu, tak pak by to mozna slo viz. screenshot nize:

![image](https://user-images.githubusercontent.com/16591052/145026400-8f3b88f8-5e3a-4f69-a286-9e7ca2ab148e.png)

Jeste musime brat v potaz zobrazeni na mobilnich zarizenich, ktere budu pro zobrazeni karet resit az bude odsouhlasen nejaky "finalni" stav.

**Comment by pkudela** [comment]
Dobry den, dekuji za odpoved. Ano, to je i muj nazor. V pripade, ze byste se v budoucnu rozhodli jinak, tato karta je jiz zanesena v konfiguraci, takze pak ji staci jen povolit, ale musela by se tak jako tak vyresit delka textu a pripadne doplnit tooltipy, jak jsem jiz zminil.

**Comment by Cypzirschova** [comment]
Ještě bych vyčkala na názor paní Lichtenbergové.

**Comment by pkudela** [comment]
Ano, to neni problem, proto jsem zminil, ze je to jiz zanesene v konfiguraci.

**Comment by Lichtenbergova** [comment]
OK, za mne souhlas

**Comment by pkudela** [comment]
Ano, tak jsem to myslel.

**Comment by CIZKOVAL** [comment]
Toto issue tedy zaviram a zalozim nove na zmenu barvy a zkraceni popisku.
