### ISSUE TITLE
Debug workflow

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#163]
Pro ucely debugovani  -  Lhůty  v minutových intervalech, konfigurovatelné v konf souboru

**Comment by pavel-stastny** [comment]
Příklad konf soubouru:

Příklad konfigurace: 

```javascript
"server": {
     ....
		"jobs": {
		      "zadost_po_minute": {
				"type": "workflow",
				"cron": "0 * * * * ?"
			},

			"notifikace_den": {
				"type": "notifications",
				"interval": "den",
				"cron": "0 0 0 * * ?"
			},
			"notifikace_tyden": {
				"type": "notifications",
				"interval": "tyden",
				"cron": "0 2 0 ? * MON"
			}
		},
        	  "workflow" :{
			"escalation" :{
			  "VNZ" : {
				"value": 1,
				"unit": "minute"
			  },
			  "VNL" : {
				"value": 1,
				"unit": "minute"
			  },
			  "NZN" : {
				"value": 1,
				"unit": "minute"
			  }
			},
			"periods": {
				"debug": true,
				"debug_nzn_0_5wd" : {
				  "value": 2
				},
				"debug_nzn_1_12_18" : {
				  "value": 20
				},
				"debug_nzn_2_6m" : {
				  "value": 3
				},
				"debug_vn_0_28d" : {
				  "value": 2
				},
				"debug_vnl_0_5wd": {
					"value": 3
				},
				"debug_vnl_2_18m": {
					"value": 7
				}
			}
		  }

```

**Comment by CIZKOVAL** [comment]
Dobrý den, konfigurace lhůt vyzkoušena - funguje to.

**Comment by smallcubes** [comment]
Poprosil bych jenom o posání a zanesení do dokumentace na wiki.
S @CIZKOVAL jsme se to snažili dát zpětně dohromady, ale nemáme to 100%. (hledali jsem i v e-mailech)

**Comment by smallcubes** [comment]
našel jsem [popis](https://github.com/NLCR/SeznamDNNT/wiki/Soupis-konfigura%C4%8Dn%C3%ADch-parametr%C5%AF), poprosil bych potom jenom o potvrzení až bude vše hotové

**Comment by smallcubes** [comment]
lhůta 0 = debug_nzn_1_12_18
lhůta 1 = debug_nzn_2_6m
lhůta 2 = debug_vn_0_28d
lhůta 3 = debug_vnl_0_5wd
lhůta 3 = debug_vnl_0_5wd
lhůta 4 = debug_vnl_2_18m
lhůta 5 = debug_vnl_0_5wd
lhůta 5 = debug_vnl_0_5wd

popis [lhůt](https://github.com/NLCR/SeznamDNNT/wiki/Stavy-a-licence-:-Popis-mapovani)
