### ISSUE TITLE
Mimo seznam jsou obsaženy i díla vydaná v zahraničí

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#164]
Dobrý den,
ve filtru mimo seznam (zobrazit i díla, která jsou mimo seznam) jsou obsažená i díla, která byla vydaná v zahraničí.

Poznámka od p. @Cypzirschova:
Do SDNNT mohou být navrhována pouze díla vydaná na území ČR. Dá se omezit polem 008 - Místo vydání (15-17): xr.

![mimo seznam](https://user-images.githubusercontent.com/92719629/144818330-d665d276-320d-4add-8d2b-e89db3f7fd62.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova Přidal jsem implicitní filtr pro všechny role.   Filtrovaná hodnota je "xr ".

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK.
