### ISSUE TITLE
Při ruční změně stavu na NL nelze změnit licenci

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#165]
Dobrý den,
pokud kurátor ručně změní stav na NL, pak se nezmění licence na terminál - není zde možnost aby to kurátor učinil.
Pokud proběhne kolečko VNL --> NL, tak automaticky dojde ke změně stavu na NL a licenci dnntt.

_Poznámka: ještě upozorňuji na podivný popisek u stavu NL při ruční změně stavu_

![NL_licence](https://user-images.githubusercontent.com/92719629/144861242-883da5eb-b9c7-4d84-a245-54e0fcd425a2.png)

![rucni_zasah_licence](https://user-images.githubusercontent.com/92719629/144861327-ea56503f-bdd7-4275-92ec-58084fa68ebb.png)

**Comment by pavel-stastny** [comment]
Při ruční změně se nyní objeví dialog s předvyplněnou licencí dnntt  a nejde změnit.  Popisek změněn

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK

![retest_NL](https://user-images.githubusercontent.com/92719629/148217463-f1421b88-cdf9-4e61-979f-2d401502e4ea.png)
