### ISSUE TITLE
Žádosti NZN se můžou hromadit

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#166]
Dobrý den,
zakládám nové issue - otázku, kterou jsem původně řešila v #66.

Nezařazené dílo (dříve zařazené, nyní vyřazené, tj. stav **N**) --> **NZN** --> interní stav NPA, veřejný stav stále **N**

Žádost čeká na automatické zpracování, které proběhne dle lhůty 0 (1.2. nebo 1.8.). Do té doby dílo zůstává ve stavu N a tudíž se můžou podávat opakované žádosti NZN. Ty se nakonec nezpracují, protože interní stav už je NPA - to je v pořádku. 

Jen chci upozornit na to, že se můžou třeba i 1/2 roku  **žádosti hromadit u kurátorů** (ve finále je stejně musí zamítnout)

**Comment by Cypzirschova** [comment]
Já jsem asi špatně pochopila naší předchozí diskuzi.

- Dílo se stavem **N** bude předmětem žádosti k zařazení **NZN** - interní stav **NPA**, ale veřejně je stále zatím **N** - je v pořádku.
- Špatně jsem to asi pochopila. Myslela jsem, že se bavíme o dílech, která nemají žádný stav - tedy ani **N**.

**Comment by Cypzirschova** [comment]
Doplňuji výše. Teď jsem si otestovala dílo, které **nemá stav** - po schválení žádosti **NZN** dostane dílo stav **N**. Zde prosím o opravu.

**Comment by Cypzirschova** [comment]
> Jen chci upozornit na to, že se můžou třeba i 1/2 roku **žádosti hromadit u kurátorů** (ve finále je stejně musí zamítnout)

Toto řešení jsme vymyslely s paní Lichtenbergovou z toho důvodu, že v současné době mohou knihovny navrhovat díla pouze v určité době. Je to cca v lednu a cca v červenci. Během celého roku jinak nemohou nic navrhovat. Knihovny čekají až na písemnou výzvu, kterou rozesílá paní Lichtenbergová nebo pan Richter. Chtěly jsme udělat pro knihovny kompromis, aby mohly navrhovat během celého roku a zároveň byly dodrženy datumy 1.2. a 1.8. pro zveřejnění nových návrhů.

**Comment by CIZKOVAL** [comment]
Dobrý den, dobře, děkuji. Toto issue zavírám.

Díla mimo seznam **(bez stavu)** se řeší samostatně v issue #158
