### ISSUE TITLE
Stav funkcionality: hromadná žádost/výzva 

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#168]
Dobrý den, 

je možné vytvářet hromadné žádosti/výzvy za nějakou organizaci. Pokud ano, tak jakým způsobem? (Mělo by to nejspíše jít pomocí API a případně i importů, je možné něco takového udělat i z front-endu?)

Předem Vám děkuji za odpověď.

**Comment by pavel-stastny** [comment]
@smallcubes Z frontendu ne. Důdovdů je hned několik. Probíralo se to na některé schůzce cca 2 týdny dozadu: 

1. Byla to více méně problematická implementace na straně UI, kdy se hromadná žádost musí vztahovat pouze k učitým položkám ve filtru - ne ke všem 
2. Agrument paní @Cypzirschova, která zmínila že je problematické, když bude mít možnost v uživatel dát do žádosti řádově tisíce položek   (bez toho aniž by je sám viděl/kontroloval)
3. Nabízeli jsme možnost vytvořit hromadné žádosti  pouze v úrovni API.  Paní Lichtenbergová zmínila, že API by bylo dostatečné.

**Comment by Cypzirschova** [comment]
Hromadné žádosti se musí ještě dořešit. Během schůzky jsem musela odejít a zatím mám jen informaci, že se to zatím bude dělat pomocí API. Určitě jsem pro hromadné žádosti, ale je potřeba to dobře promyslet, jak se to bude dělat. Viz komentář výše. Nevím, zda je v našich kapacitních možnostech řešit žádosti, které budou mít několik desítek tisíc položek, u kterých musím ručně rozhodovat (u každé položky/díla).

**Comment by Cypzirschova** [comment]
Možná by pomohlo, kdyby i kurátor mohl označit hromadně všechny položky/díla v žádosti a označit - zamítnuto/schváleno. Nevím, jak by se to chovalo, kdyby si kurátor vybral pár děl a ty schválil/zamítl ručně a zbytek by označil hromadně.
 @JanMeritus

**Comment by pavel-stastny** [comment]
@Cypzirschova @JanMeritus  už několikrát během tohoto projektu došlo k tomu, že se funckionalita naimplemetovala a posléze zahodila.   Já bych opravdu důrazně poprosil, aby se případné větší změny buď promyslely tak, že že to ve výsledku bude mít pozitivní efekt nebo aby se šlo po malých krůčcích...  

Zde jsme přemýšlely spíš tím způsobem, že by hromadné žádosti mohly jít podávat pouze z toho, co uživatel vidí... Tedy z aktuální stránky, stejně tak by bylo záhodno, aby počet položek v žádosti byl limitován nějakým rozumným číslem ..  ale to vše by bylo dobré nejdříve podiskutovat.

**Comment by JanMeritus** [comment]
- moznost konfigurovatlne limitace hromadnich pozadavku je jednim z pozadavku zadani
- proces vyrizovani je dulezite dusledne vydefinovat ze strany kuratoru, v zasade by ale melo byt mozno urcite jednotlive casti navrhu spracovavat individualne
- podavani z UI se musi ridit jenom tim co uzivatel vidi, pokud vidi "mixed data" je nutno mu (zde treba rozhodnuti):
   -  zavest validaci - oznamit ze zadost muze vyrizovat jenom v ramci jedneho stavu/licence - musi si selekci rucne opravit, znova skusit a nasledne vybrat jestli chce zmenit stav nebo licenci
   - implementovat logiku ktera mu umozni jednotlive podavat mozne kombinace v ramci subformulare (toto ale muze byt zlozite pro implementaci a mozno aj zbytecne)

**Comment by Cypzirschova** [comment]
Domluvily jsme s paní Lichtenbergovou, že hromadné žádosti budou. Minimálně z důvodů, co jsou v komentáři výše uvedené.

**Comment by Cypzirschova** [comment]
Pro kurátora by bylo ulehčení, kdyby mohl i v žádostech hromadně schvalovat/zamítat díla. Rozhodnutí nechám na @JanMeritus. Ideální by byla kombinace ručního schvalování + hromadného v jedné žádosti.

**Comment by JanMeritus** [comment]
@cypzirschova souhlas, tj jeste moznost schvalit hromadnou zadost en bloc

Dňa št 9. 12. 2021, 13:42 Cypzirschova ***@***.***>
napísal(a):

**Comment by pavel-stastny** [comment]
Přidáno kontextové tlačítko na stránku výsledků vyhledávání.  Je dostupné pouze tehdy, pokud pro stránku existuje alespoň jedna akce. Výsledkem je seznam akcí, které uživatel může provádět. 
 
![image](https://user-images.githubusercontent.com/675753/151974203-149ac88c-d06d-4844-87d8-fd6e2e2451e2.png)
![image](https://user-images.githubusercontent.com/675753/151974254-0e64253f-fced-49d4-81cf-83b97fb9ba95.png)

Vztahuje se pouze k aktuální stránce. 

Na straně kurátora přibyly tlačítka pro hromadné schvalování nebo odmítání návhrhů. 

![image](https://user-images.githubusercontent.com/675753/151974486-cdf30a98-3d85-424f-aa92-f265b63d1258.png)

Zde se to týká celé žádosti.  Postupně prochází položku po položce a schvaluje nebo zamítá.  Pokud danou položku nejde schválit (protože je například již v jiném stavu), musí se odmítnout ručně. 

U žádostí VNL funguje pouze první dotaz na kurátora (Výsledný stav NL).  Ten druhý stav, kdy se ze stavu NL dostane do stavu A musí kurátor roznodnout ručně.

**Comment by Cypzirschova** [comment]
Nejdou mi hromadně schválit díla ani po aktualizování stránky. Zkoušela jsem variantu, jak celou žádost schválit, tak kombinaci ručního odmítnutí a zbytek hromadně schválit.

**Comment by CIZKOVAL** [comment]
@ Cypzirschova já mám dotaz k podání hromadné žádosti - funguje to tak, že se dá do hromadné žádosti vše, co je na aktuální stránce (**tedy max 20 záznamů**). Chápu, že hromadné podání žádosti má smysl tam, kde si uživatel dopředu vyfiltruje díla dle určitých kritérií a ta chce poté hromadně navrhovat do žádostí. 

Nevím ale, zda si bude vědom toho, že se mu do hromadné žádosti dá automaticky vše co je na stránce (bez předchozího omezení filtrem). Já jsem např. očekávala, že budu dále vyklikávat položky ze seznamu.

Po výběru hromadné žádosti je rovnou potvrzovací hláška, že hromadná žádost proběhla.

**Comment by Cypzirschova** [comment]
Zatím jsem to testovala krátce, ale přijde mi to tak, že to je tak, jak píšete. 
Po testování jsem zjistila, že maximální počet děl v žádosti je 60.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Ona ta implementace vycházela z prosincové schůzky,  kde se řeklo, že usecase se bude řídít pouze tím co si uživatel vyfiltruje... Zvažované varianty pak byly:  

- Buď umožnit hromadné akce pouze nad jedním typem dokumentů 
- Nebo uživateli nabídnout možné akce  nad aktuálním výběrem 

Ta druhá varianta nám přišla logičtějsí.  To, že bychom ještě po filtrování nabídli dialogové okno s výběrem, tak nad tím jsme neuvažovali.  Mně by to přišlo úplně stejné jako to co bylo před hromadnými akcemi:  Tedy uživatel si vybírá položku po položce. 

Pokud by byl problém ta situace bez vybraného filtru.  Dají se v tomto případě hromadné akce zakázat. 

Jinak, je to jak píšete. Dává se vše co je na aktuální stránce  (uživatel by měl mít možnost dávat do žádosti pouze to co vidí)  ale velikost stránky se může měnit.  Maximální počet položek v žádosti je konfigurovatelný. Defaultně je 60.

**Comment by Cypzirschova** [comment]
@CIZKOVAL Dnes už vše funkční - hromadné zamítání a schvalování v žádostech. Zkoušela jsem i kombinaci ručního zpracování a hromadného a vše OK. Ještě dnes se tomu budu věnovat.

**Comment by Cypzirschova** [comment]
Po dnešním testování, vše OK až na hromadné návrhy mimo seznam viz issue #261

**Comment by smallcubes** [comment]
@Cypzirschova mohu tedy issue uzavřít?

**Comment by Cypzirschova** [comment]
Nevím, zda to uzavřít, když nefungují ty hromadné návrhy mimo seznam, aby to pak nebylo pochopené, že je to plně funkční, když jedny hromadné návrhy nejsou funkční.

**Comment by smallcubes** [comment]
@Cypzirschova děkuji za reakci, počkáme tedy na dořešení #261

**Comment by smallcubes** [comment]
@CIZKOVAL dobře uzavírám, poprosil bych jen o přidání odkazů na navazující issues

**Comment by CIZKOVAL** [comment]
Hromadné žádosti se řeší zde: #259, #260, #261, #265
