### ISSUE TITLE
Stav funkcionality: Přehledové statistiky přístupnosti a stavů

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#169]
Dobrý den,
dle zadávací dokumentace mají být z databáze poskytovány údaje pro statistiky.
Definovány jsou dva základní okruhy údajů: údaje o změnách stavu děl a procesu žádostí,- údaje o dotazech na vyhledávací systém (běžný uživatel, vyhodnocení chování uživatele). Přehledové statistiky poskytují informace o přístupnosti a stavech, seznamy dle intervalů.

Jsou statistiky někde evidovány? Děkuji

**Comment by CIZKOVAL** [comment]
Poznámka: tento dotaz se netýka FE

**Comment by pavel-stastny** [comment]
@CIZKOVAL Jednotlivé informace jsou logovány. Je možné je zpracovat a vizualizovat přes Logstash + es + kibana.  Ale zde opět poprosil, hodně těch požadvaků vzniklo v době kdy se kumulovaly požadavky typu "nice to have" a neřešilo se reálné použití.  Opravdu bych upřednostnil  reálnou potřebu která vyjde z používání aplikace.

**Comment by CIZKOVAL** [comment]
Toto issue uzaviram, statistiky uz v SDNNT jsou a resi se v issue #257
