### ISSUE TITLE
EUIPO test portal

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#17]
Prosim o kratky pohled na portal EUIPO

https://test.euipo.europa.eu/

**Comment by pavel-stastny** [comment]
@albertoh @pavel-stastny SDNNT bude sklizeno EUIPO

**Comment by smallcubes** [comment]
@pavel-stastny chtěl bych se zeptat, zdali je tato funkcionalita implementována případně bych poprosil o její popis (nastavení)

@JanMeritus

**Comment by smallcubes** [comment]
@pavel-stastny připomínám se s dotazem na funkcionalitu

**Comment by smallcubes** [comment]
@pavelkocourek @pavel-stastny @albertoh opět se připomínám s dotazem
