### ISSUE TITLE
Stav funkcionality: automatické vyřazování

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#174]
Dobrý den,

obracím se na Vás s dotazem na automatické vyřazování záznamů v SDNNT. Exsituje nějaká konfigurovatelná procedura, která by vyřazovala dokumenty na základě námi zvoleného časového stropu? Takováto procedura by měla dodržovat učitá pravidla uvedená v zadávacím dokumentu.

Viz zadávací dokument sekce (C): *„Automatické vyřazování ze SDNT... (strana 5-6)“*

Předem Vám děkuji za odpověď.

**Comment by Cypzirschova** [comment]
Od roku 1910 a dřív, tak jak je to nastaveno v Krameriovi.

**Comment by Cypzirschova** [comment]
Ideální by bylo, kdyby kurátorovi přišla hromadná žádost, aby to mohl případně zkontrolovat.

**Comment by pavel-stastny** [comment]
Přidán proces, který umožňuje změnit stav nebo vytvořit žádost na základě filtrovacích kritérí. Ty mohou být:

- Stavy dokumentů
- Rozsah datumu vydání 
- Formát (BK nebo SE)

**Comment by pavel-stastny** [comment]
Příklad pro změnu stavu u u knih vydaných před rokem 1910:
```json
{
   "type":"date_px_check",
    "cron": "0 12 10 * * ?",
     "iteration":{
          "date_range":"[* TO 1900]",
           "states":["A","PA","NL"],
           "fmt":"BK"
      },
      "results":{
                "state":"PX"
       }
}
```

**Comment by smallcubes** [comment]
@CIZKOVAL @Cypzirschova pokud bych měl nastavit jinak časové rozpětí, formáty nebo stavy, dejte mi prosím vědět

**Comment by smallcubes** [comment]
@pavel-stastny rok uvedený v závorkách `"date_range":"[* TO 1900]"` je včetně?

**Comment by CIZKOVAL** [comment]
@smallcubes pro otestování jsem si připravila data, prosím o spuštění upravené procedury. Děkuji

"automaticke_vyrazovani": {
    "type":"date_px_check",
    "cron": "40 12 14 * * ?",
    "iteration":{
            "date_range":"[* TO 1910]",
            "states":["A","PA","NL"],
            "fmt":"BK"
    },
    "results":{
            "state":"PX"
    }
},

**Comment by smallcubes** [comment]
@CIZKOVAL přenastaveno

**Comment by CIZKOVAL** [comment]
Dobrý den,
spustili jsme proceduru, ale data, která jsem měla k tomu účelu připravená se nepřevedla do stavu PX.

**Comment by pavel-stastny** [comment]
@Cypzirschova Je to ten včerejší běh ? Pokud ano, vidím tam dokumenty přepnuté do PX stavu.    Napište mi dokumenty, které se nepřepnuly.

**Comment by CIZKOVAL** [comment]
@pavel-stastny např. tyto: cnb001263776, cnb000561719

![PA_vyrazeni](https://user-images.githubusercontent.com/92719629/158766843-66645eec-37f8-458a-9ad5-f1a5862a0b40.png)

**Comment by smallcubes** [comment]
Job je nastaven následovně (dle [wiki](https://en.wikipedia.org/wiki/Cron 19:00 každý 14 den v měsící): 
```json
 "automaticke_vyrazovani_dle_data": {
                                "type":"date_px_check",
                                "cron":"00 19 14 * * ?",
                                "iteration":{
                                        "date_range":"[* TO 1910]",
                                        "states":["A","PA","NL"],
                                        "fmt":"BK"
                                },
                                "results":{
                                        "state":"PX"
                                }
                        },
```

Dle logů se spustil hned několikrát (možná to dělá po 60 položkách):
```
18-Mar-2022 14:19:00.002 INFO [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.sched.Job.fire Job automaticke_vyrazovani_dle_data fired
19-Mar-2022 14:19:00.001 INFO [QuartzScheduler_Worker-2] cz.inovatika.sdnnt.sched.Job.fire Job automaticke_vyrazovani_dle_data fired
20-Mar-2022 14:19:00.000 INFO [QuartzScheduler_Worker-10] cz.inovatika.sdnnt.sched.Job.fire Job automaticke_vyrazovani_dle_data fired
```

Změna by měla být např. v `20-Mar-2022 14:19:00.355 INFO [QuartzScheduler_Worker-10] cz.inovatika.sdnnt.services.impl.PXYearServiceImpl.update Updating identifiers :[oai:aleph-nkp.cz:DNT01-000047158, oai:aleph-nkp.cz:DNT01-000047174, oai:aleph-nkp.cz:DNT01-000047233, oai:aleph-nkp.cz:DNT01-000047891, oai:aleph-nkp.cz:DNT01-000048354...]`

**Comment by JanMeritus** [comment]
@CIZKOVAL @smallcubes jaky je zde stav?

**Comment by CIZKOVAL** [comment]
Dobrý den,
na testu jsem měla připravená data - knihy ve stavu A, NL, PA vydané do roku 1910, příklad dat níže.

Očekávané chování - díla mají získat kurátorský stav PX. Po spuštění procedury díla tento stav nemají.

**Důležitá poznámka** - uvědomila jsem si, že když díla získají stav PX, tak **nejsou ze seznamu vyřazené**, ale jedná se o **pravděpodobně volná díla, což je kurátorský stav**. Běžnému uživateli (nakladatel/knihovna) se totiž příznak pravděpodobně volného díla neukáže, takže vidí u děl pouze původní stav (tedy A, PA nebo NL). **Pouze kurátor vidí u děl původní stav (tedy A, PA nebo NL) + kurátorský stav PX**. Problém vidím v tom, že kurátor musí tato díla posoudit jednotlivě, protože hromadný návrh na změnu (cílový stav X?) nemůže udělat, viz issue #260.

**Neměl by být cílový stav pro automatické vyřazení (vlivem např. hromadného posunutí hranice roku) N nebo X?**

Příklad dat, kdy nedošlo k příznaku PX:

![NL_do_1910png](https://user-images.githubusercontent.com/92719629/161242029-8e23e3c3-3536-4fa8-b7aa-c47a89ffe668.png)

![PA_do_1910](https://user-images.githubusercontent.com/92719629/161242048-d61d7c71-20c9-44eb-ad01-182a670b18e6.png)

**Comment by Lichtenbergova** [comment]
Stav PX slouží kurátorovi SDNNT jako informace, např. že záznam může ignorovat, pokud na něj odkáže kontrola oproti distributorům. Jinak ale dílo zůstane A-PX až do chvíle, kdy převezmeme informaci o tom, že je volné, z Krameria.

**Comment by Cypzirschova** [comment]
@CIZKOVAL 
Níže dám příklady, proč nelze plně automaticky (bez nějaké menší kontroly kurátora) vyřazovat na základě roku vydání:

Níže označené dílo přišlo v kontrole oproti Kram. Podle roku vydání (1998) mi přišlo zvláštní, proč je dílo veřejné v DK. Po konzultaci jsem se dozvěděla, že na dílo má NK licenci volně zpřístupňovat. Pokud je licence jen pro NK, tak se rozhodlo, že dílo v SDNNT zůstane.  
![1910_VDK](https://user-images.githubusercontent.com/86351100/161245414-8a11cfbc-c440-4fe8-b2d0-3ce1c9e814dc.png)

Níže je kontrola od p. Zahoříka. Vybraná díla, která vyšla 1910 a níže. V posledním sloupci je rozhodnuto u většiny děl ponechat v seznamu (A). Jsou tam různé důvody např. jsou stále platná autorská práva atd.  
![1910](https://user-images.githubusercontent.com/86351100/161245430-c28c2636-5496-4924-af87-cdc3d8447c69.png)

Minimálně z těchto důvodů se nemůžeme plně spolehnout na automatické vyřazování bez nějaké menší kontroly.

**Comment by CIZKOVAL** [comment]
@Lichtenbergova @Cypzirschova Děkuji za reakce - mě zarazilo to automatické vyřazování, když o vyřazení vlastně nejde. 
Dílo tedy bude mít stav A/PA/NL + PX a v momentě kdy přijde kontextová informace o tom, že je dílo volné i v Krameriich, tak ho kurátor může vyřadit. Pozor - kontextovou informaci získávají pouze díla, která mají link do některého z Krameriů, takže o zbytku bude kurátor rozhodovat individuálně např. podle kontrol od p. Zahoříka?

**Comment by Cypzirschova** [comment]
Mám pocit, že p. Zahořík se už nebude asi podílet na SDNNT, ale možná se mýlím? @Lichtenbergova

**Comment by Lichtenbergova** [comment]
ad O zbytku... - Z. Vozár zmiňoval možnost zapojení kurátora Krameria do budoucna. Ne všechna naše PX budou akceptována, to je zřejmé, ze záznamů nevyčteme všechny možné nositele práv.
Protože již nebude existovat báze DNT, kontroly oproti Alephu  možné nebudou.

**Comment by JanMeritus** [comment]
@Lichtenbergova @Cypzirschova @annie @JanaHrzinova
FYI @smallcubes @jahhoo 


### Reasoning

- kontextova informace z DK do SDNNT by mala vyznamne zjednodusit proces rozhodovani `kuratora SDNNT`
- je esencialni aby v ramci budouci rozvojove faze vznikla role `kurator DK` a `vedouci kuratoru DK` (ten bude mit prehled a moznost revize jednotlivych rozhodnuti kuratoru DK v pripade nejasnosti). V roli `kurator DK` budou vystupovat kuratori DK vsech partnerskych knihoven, ktery by meli mit moznost:

### Pravomoci kuratoru DK a vazby na roli kurator SDNNT 

- v pripade ze` kurator SDNNT` nebude jisty se kontextovou informaci / pripadne standardne (vzdy) - bude rozhodovat o revizi "dostupnosti" `kurator dotcene DK` 

#### Vazba na procesy:
- posuzovani navrhu na zarazeni 
    - `kurator SDNNT` muze eskalovat nejiste navrhy na `hlavniho kuratora DK` ten pak pripadne na dalsi `kuratory DK`
    - `kurator DK` muze u libovolneho dila v navrhu signalizovat diskrepance, rozhoduje o nich vzdy `kurator SDNNT`
- revize zarazenych a platnych del ( `kurator DK`  by mel mit moznost v pripade potreby eskalovat dilo na vyrazeni ze seznamu / znepristupneni, zmenu licence na `kuratora SDNNT` z duvodu externich licencnich ujednani mimo rozsah licence SDNNT, ktere sjednavaji` kuratori DK`, nebo jsu na tyto jednani napojeni)
- automatickeho vyrazovani ze seznamu v souvislosti s pohyblivou stenou - dila ktere vypadavaji ze SDNNT muzu nadale pouzivat specificke licencni ochrany, bylo by nezadouci aby je system diki automaticke integraci uvolnoval jako dila volna, bez dobrozdani 'kuratoru DK'

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o revizi, dle teorie ok, v praxi se dle @CIZKOVAL vyse komentar nepropisuje

**Comment by smallcubes** [comment]
@pavel-stastny @JanMeritus 
aktuální nastavení proces:
```json
"automaticke_vyrazovani_dle_data": {
		"type":"date_px_check",
		"cron":"00 20 09 01 * ?",
		"iteration":{
				"date_range":"[* TO 1910]",
				"states":["A","PA","NL"],
				"fmt":"BK"
		},
		"results":{
				"state":"PX"
		}
},                       
```

**Comment by pavel-stastny** [comment]
@CIZKOVAL Díval jsem se na díla `cnb001263776`, `cnb000561719`.  Myslím, že to možná bude potřeba konzultace s paní 
 @Cypzirschova  @Lichtenbergova.  Proces používá datum uvedený v controlfield 008 a tam je uvedeno následující: 

- `030215q19001917xr     e      ||| p cze`       Tedy   roky  1900 - 1917
- `030107q19001920xr     j      000 d cze`    Tedy  roky  1900 - 1920

Markove pole 260c, které se zobrazuje v kartě vyhledávání je  ma uvedeno "[1900]" respektive "[1902]".  Které pole je pro procesy vyřazování rozhodující?

**Comment by Lichtenbergova** [comment]
Rozhodující by mělo být rozmezí dat nebo datum v 008.

**Comment by pavel-stastny** [comment]
@Cypzirschova @Lichtenbergova A ještě podotázka související s procesem.  Pokud je uvedeno rozmezí, pak je při vyřazování zohledňována horní mez.  Tedy  pro rozpětí 1900 - 1917 bude muset být proces nastaven pro všechna díla starší nebo rovno roku 1917.  Souhlasíte ?

**Comment by CIZKOVAL** [comment]
@pavel-stastny jak je to tedy nastaveno ted? Bere se v potaz pole 008 a horní mez? Že bychom zkusili spustit znovu - připravím si nějaká data.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ano, pole 008 a horni mez.

**Comment by CIZKOVAL** [comment]
Nastavila jsem si data a otestovala současné nastavení procedury.

**Knihy**, které byly ve stavu **A/PA/NL** a zároveň splňovaly **podmínku dle pole 008** získaly kurátorský stav PX (cnb000839041, cnb001198526, cnb001757139). 

Data, která nesplňovala nějakou z podmínek tento stav nezískala (cnb001106708 (horní mez 1930), cnb001086813 (stav N), cnb001861181 (stav N, NPA), cnb000816613 (horní mez 1913), cnb002501422 (seriál).

@Cypzirschova, @Lichtenbergova prosím jenom o potvrzení toho, že se má brát v úvahu horní mez, viz [zde](https://github.com/NLCR/SeznamDNNT/issues/174#issuecomment-1088649907)

**Comment by Lichtenbergova** [comment]
Ano, je to tak, v případě rozmezí se bere v úvahu horní mez v 008, jak píšete. 
Kromě číslic se na pozicích 008/11-14 může vyskytnout písmeno u, tento případ by mohl být ignorován (nedávat PX), nebo by mohlo být bráno u=9
008 ......q189019uu...
008 ......q19uu1929...
008......q1892191u

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o kontrolu ad pismeno u, jak je to v procesu nastaveno

**Comment by CIZKOVAL** [comment]
@Cypzirschova předpokládám, že procedura se má spouštět 1x týdně, na jaký čas a hodinu ji máme nastavit?

**Comment by Cypzirschova** [comment]
@CIZKOVAL Nejspíše ano, čekám ještě na vyjádření od paní @Lichtenbergova. Nastavila bych to nejspíše z pondělí na úterý třeba o půlnoci?

**Comment by Cypzirschova** [comment]
@CIZKOVAL Potvrzeno 1x týdně.

**Comment by CIZKOVAL** [comment]
@Cypzirschova děkuji, mezitím ji @smallcubes nastavil na sobotu 21:00, navazuje mu to na ostatní procedury, nevadí to takto?

**Comment by Cypzirschova** [comment]
@CIZKOVAL vůbec to nevadí.

**Comment by CIZKOVAL** [comment]
Pokud by se znaky "u" nahrazovaly, viz tento [kometář](https://github.com/NLCR/SeznamDNNT/issues/174#issuecomment-1092664820), tak by to ovlivnilo i vyhledavani v katalogu SDNNT. Paní @Lichtenbergova ještě potvrdí konečné řešení.

**Comment by JanMeritus** [comment]
dle @pavel-stastny se `u` nanahradzuji, prosim o potvrzeni

**Comment by CIZKOVAL** [comment]
Provedla jsem nový test, kde se vyskytovaly i záznamy, které mají v poli 008 např. toto: 190207s1910----xr, kdy je horní mez definovaná znakem `-` Tyto záznamy získaly příznak PX. Ještě vyzkouším záznamy, kde se vyskytuje znak `u` až je získám od p. Zahoříka.

Příklad ID: cnb001043702, cnb001046196, cnb000567598, cnb002092929


![sd_vybor_basni](https://user-images.githubusercontent.com/92719629/166640311-75544aac-5a48-4f98-a139-9b1bdb90dcc9.png)

![PX_vybor_basni](https://user-images.githubusercontent.com/92719629/166640344-9be34a02-001b-49dc-bb58-7d751d95dd60.png)

**Comment by CIZKOVAL** [comment]
FYI @Lichtenbergova

**Comment by CIZKOVAL** [comment]
Paní @Lichtenbergova - to co popisujete výše je očekávané chování? Já jsem právě zmiňovala, že pokud jsou tam zástupné znaky `--` nebo `uu`, tak že je chyba, že se bere v potaz dolní mez (kdy rok je <=1910). 

**Níže tedy raději vyznačuji očekávané chování versus chyba.** 

Pokud je v poli **dolní mez** rok **<= 1910** a zároveň 

a)	horni mez `--` tak se MÁ přidat PX --> **OK, PX SE PŘIDÁVÁ**
b)	horni mez `uu` tak se NEMÁ přidat PX --> **TOTO JE TEDY CHYBA, PX SE PŘIDÁVÁ**

Pokud je v poli **dolní mez** rok **> 1910** a zároveň 

a)	horni mez `--` tak se NEMÁ přidat PX --> **OK**
b)	horni mez `uu` tak se NEMÁ přidat PX --> **OK**

V klasických případech kdy jsou v poli horní i dolní mez roky, tak se bere v potaz horní mez --> **OK**

Prosím paní @Lichtenbergova o kontrolu

**Comment by Lichtenbergova** [comment]
OK, jen raději upřesnění - řešíme tím už jen otázku přítomnosti nečíselných hodnot - formát BK -  pokud na pozici 008/06 je q

**Comment by CIZKOVAL** [comment]
@pavel-stastny prosím tedy o úpravu, viz [zde](https://github.com/NLCR/SeznamDNNT/issues/174#issuecomment-1125741302)

**Comment by CIZKOVAL** [comment]
Retest OK

Záznamy, které mají v poli **008/7-10 <=1910 a zároveń 008/11-14 zástupný znak uu** NEDOSTALY příznak PX.

Zároveň jsem provedla retest i na ostatních datech, viz data v příloze:
_
[automat_vyrazovani_data.docx](https://github.com/NLCR/SeznamDNNT/files/9101445/automat_vyrazovani_data.docx)_
