### ISSUE TITLE
Stav funkcionality: Konfigurovatelné subsety pro veřejnost

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#175]
Dobrý den,
lze někde konfigurovat zobrazení jednotlivých subsetů pro veřejnost (např. nepřihlášený uživatel)?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Tady to dost naráží na to co bylo domluveno domluveno ohledně viditelnosti/dohledatelnosti s paní @Lichtenbergova a  @albertoh.  Bylo vyspecifikováno co má která role (případně nepřihlášený uživatel) vidět a dle toho byly postaveny filtry.  Úplně měnit tyto filtry moc nejde protože pak vznikají tyto typy issues: 

#159  #164

Doporučil bych nejdříve prodisktuovat reálnou potřebu mít jiné filtry (než ty které jsou teď navázané na role)  s kurátory (paní @Cypzirschova  a paní @Lichtenbergova) a pak, pokud jsou potřeba, vyspecifikovat co se má  přidat.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o update jak je to reseno ve verzi 1.0.2

**Comment by pavel-stastny** [comment]
@JanMeritus Subsety konfigurvatelné nejsou.  Měl jsem pocit, že jsem to popsal v komentáři výše.

**Comment by pavelkocourek** [comment]
Subsety + filtr se definují v konfiguraci, přidáme do dokumentace.

**Comment by pavel-stastny** [comment]
@JanMeritus Já ještě doplním Pavla.  Pokud se jedná o konfigurovatelné OAI (tedy dostupné pro všechny uživatele , přihlášené i nepřihlášené) je možné měnit konfiguraci následovně: 
```  "OAI": {
    "rowsPerPage": 100,
    "repositoryName": "Seznam děl nedostupných na trhu",
    "adminEmail": "sdnnt@nkp.cz",
    "sets": {
      "SDNNT-ALL": { "name": "Seznam děl nedostupných na trhu (všechny stavy)", "filter": "dntstav:*"},
      "SDNNT-A": { "name": "Seznam děl nedostupných na trhu (zařazeno)", "filter": "dntstav:A"},
      "SDNNT-PA": { "name": "Seznam děl nedostupných na trhu (dílo publikováno jako návrh)", "filter": "dntstav:PA"},
      "SDNNT-N": { "name": "Seznam děl nedostupných na trhu (ne zařazeno)", "filter": "dntstav:N"},
      "SDNNT-NL": { "name": "Seznam děl nedostupných na trhu (omezení na terminál / plánované vydání po získání licence)", "filter": "dntstav:NL"},
      "DNNTO": { "name": "Seznam děl nedostupných na trhu (Licence pro online přístup)", "filter": "license:dnnto"},
      "DNNTT": { "name": "Seznam děl nedostupných na trhu (Licence pro terminálový přístup)", "filter": "license:dnntt"}
    }
  },        
```

**Comment by JanMeritus** [comment]
@smallcubes prosim o zkuseni

projistotu pro vsechny FYI @CIZKOVAL OAI je dostupno pro vsechny bez rozdilu

**Comment by smallcubes** [comment]
@pavel-stastny omlouvám se, ale jsem trochu zmaten. Konfigurovatelnost OAI (viz výše) je až od 1.0.3, nebo se mýlím? Taky bych se chtěl zeptat, zdali `"rowsPerPage": 100` znamená počet záznamů v jedné dávce.

**Comment by JanMeritus** [comment]
prosim ASAP otestovat a doplnit v tabulce @smallcubes

**Comment by smallcubes** [comment]
@JanMeritus funguje přidávání a odebírání setů, stanovení počtu záznamů v jedné dávce, nastavení jména oai repozitáře a  admin e-mailu. 

Ale nepodařilo se mi nastavit více jak jeden filtr např. `"dntstav:PA"` a `"fmt":"bk"`. Samotný filtr `"fmt":"bk"` nefunguje. Možná jsem ho nastavil špatně. @pavel-stastny

**Comment by pavel-stastny** [comment]
@smallcubes fmt:BK

**Comment by smallcubes** [comment]
Lze vytvářet nové sety i skrze kombinace filtrů. Issue uzavírám. @CIZKOVAL
