### ISSUE TITLE
Stav funkcionality: kontextového ztotožení

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#176]
Dobrý den,

měl bych dotaz ohledně kontextového ztotožení. Viz zadávací dokumentace. Tedy je provázání objektů s jinými DB implementováno? Pokud ano, v jakém je to stavu a formě?

Zadávací dokument (sekce D):
*„Pokud je to možné, provést kontextové ztotožnění, případně indexové provázání záznamu v SDNT (objektu) a záznamů z externích bází dostupných via API (např. prostřednictvím jednoznačných identifikátorů, zejména pomocí ISBN, ISSN, EAN, CCNB, id SK CR, id Autorit, urn:nbn:cz, UUID, unifikovaný název, pokud jsou dostupná) k danému záznamu v databázích velkých distributorů (Kosmas, Kanzelsberger, ...). Tyto záznamy slouží k utvoření vyhodnotitelného kontextu pro ruční nebo mechanické vyloučení děl ze seznamu a další kontroly. “*

Děkuji za odpověď.

**Comment by pavel-stastny** [comment]
Je to řešeno importy

**Comment by JanMeritus** [comment]
@smallcubes prosim o overeni jestli je to funkcni

**Comment by smallcubes** [comment]
@JanMeritus @pavel-stastny předpokládám, že se jedná o proceduru pro získání kotextové informace (viz níže). Chtěl bych se zeptat:

1. Jak mohu přidat nebo odebrat nového Krameria (tak aby se zahrnul do kontroly kontextové informace) např. od MZK nebo KNAV
2. V současné době se kontextová informace získává pouze z Krameria. Z jiných zdrojů např. od nakladatelů, lze tuto informaci získat v podobě improtů. Stačí to takhle? @JanMeritus 

aktuální nastavení procedury:
```json
 "krameriove_kontextova_informace": {
                                "type":"kramerius_px_check",
                                "cron": "0 0 0 ? * WED *",
                                "iteration": {
                                        "date_range": "[* TO 2020]",
                                },
                                "results": {
                                        "ctx": true
                                }
                        },
```

**Comment by pavel-stastny** [comment]
> Jak mohu přidat nebo odebrat nového Krameria (tak aby se zahrnul do kontroly kontextové informace) např. od MZK nebo KNAV

To se děje, respektive je to řízeno daty. Dílo musí mí v katalogizačním záznamu odkaz do daného krameria.

**Comment by smallcubes** [comment]
V současné době fungují importy od distributorů (Kosmas...).
