### ISSUE TITLE
Stav funkcionality: kontrola záznamů z Krameriu

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#177]
Dobrý den,

měl bych dotaz, zdali byla implementovaní funkce kontroly skutečného stavu děl pomocí UUID z různých Krameriů. Zároveň s tím nejspíše i trochu souvísí bod 3.

zadávací dokumentace:
1. sekce (D): *„Z veřejného API systému Kramerius jednotlivých knihoven je možné kontrolovat pomocí UUID skutečný stav díla a jeho podmnožin na úroveň ročníků (kontrolní funkce, zveřejňování linku v rámci prezentace, apod.);“*
2. sekce (Technická specifikace: A) Zdroje dat): *„Kontextové zdroje dat jsou rovněž databází distributorů s povoleným API rozhraním pro dotaz na stav konkrétního záznamu (Toto UUID v jakém je stavu i jiný KRAM než v NK ČR)“*
3. sekce (D): *„Možnost synchronizace dokumentů k určených k zařazení / odstranění přes API  (možnost konfigurace příkazu a autentizace, napojení např. na: API Krameria, API SOLR, …)“*

Děkuji Vám za odpověď.

**Comment by Cypzirschova** [comment]
Kontrola by měla být hromadná + pravidelná tzn., měla by zkontrolovat všechna díla v SDNNT oproti Krameriovi NK. Ideální by bylo, kdyby kurátorovi přišla hromadná žádost, aby to mohl případně zkontrolovat a odsouhlasit/zamítnout.

**Comment by Cypzirschova** [comment]
Zde by se mělo jednat také o pravidelnou kontrolu.

**Comment by pavel-stastny** [comment]
@Cypzirschova Souhlas... A neměl by se přes žádosti řešit i ten druhý problém a to posouvání hranice let kdy mají být díla zpřístupňována  Viz [tento ](https://github.com/NLCR/SeznamDNNT/issues/167#issuecomment-987762371)komentář ?

**Comment by Cypzirschova** [comment]
Pro celý nadcházející rok se hranice posouvat nebude. Myslím, že snad do roku 2024 se to asi posouvat nebude. Teď si nejsem na 100% jistá. Zřejmě nám pak situaci změní novela autorského zákona, která se bude projednávat nadcházející rok. Jak moc nám práci změní, to nedokážu teď posoudit.

**Comment by pavel-stastny** [comment]
Přidán proces, který umožní kontrolu vůči krameriům. Kontrolu provádí oproti linkům, které jsou uvedeny v SKC.  Pokud je link zastaralý, případně nelze určit jádro, je zde konfigurační možnost přesměrovat na aktuální verzi jádra: 
```
		  "check_kramerius":{
			"urls":{
				"https://www.digitalniknihovna.cz/mzk/" :{
					"api":"https://kramerius.mzk.cz/search/"
				},
				"http://www.digitalniknihovna.cz/mlp/" :{
					"api":"https://kramerius4.mlp.cz/search/"
				},
```

Výsledkem je nový typ žádosti, PNX, který přistane u kurátora v položce moje konto.  Stav po schválení je  X.  Proces lze omezit na časové období. (Omezení procházení a vygenerování menšího počtu žádostí).

V obrazovce pro správu žádostí přibyl nový filtr pro typ žádostí generovaných systémem případně uživatelské žádosti.

**Comment by smallcubes** [comment]
nastavení jsem přidal na server

**Comment by CIZKOVAL** [comment]
Dobrý den,
funkcionalitu jsem ověřila na **DEV**.

Nyní se tedy do žádosti PXN dostanou díla, která splňují podmínku níže:

**Všechna díla, která nejsou ve stavu X (volná) a mají odkaz na některý z Krameriů** (NK, MZK, KNAV, MLP, atd..), **kde je dílo volné (veřejné)**

Shodli jsme se s kurátory SDNNT, že by se měly kontrolovat **pouze** díla, která jsou ve stavu **PA** nebo **A** **a zároveň jsou v některém z Krameriů vedená jako volné (veřejné) dílo**. Díla, která jsou tedy v tomto rozporu se dostanou do žádosti PXN a dále kurátor posoudí co s takovými díly (jestli mají být vyřazeny ze seznamu apod.)

Nicméně informace o tom, že je v Krameriích **jakékoliv** dílo veřejné je pro nás také užitečná a to např. proto, aby knihovny nezařazovaly volná díla na seznam. Na to je založené nové issue #269, kde ale požadujeme **pouze zobrazení  informace o tom, že je dílo volné, nikoliv překlopení do stavu X.** **Nepůjde tedy o žádosti.**

__**Důležitá poznámka:**_ namátkou jsme s p. @Cypzirschova kontrolovaly některá díla, která jsou nyní v žádosti PXN (na DEV) a ani jedno jsme nenašly ve filtru "zobrazit i díla mimo seznam" v SDNNT. Pouze když nějaké schválím, tak se překlopí do stavu X a pak se najde._

_Příklady:
cnb001204148, cnb001120735_

**Comment by pavel-stastny** [comment]
@CIZKOVAL Prodiskutujeme na schuzce.

**Comment by JanMeritus** [comment]
@Cypzirschova prosim o potvrzeni filtru

**Comment by CIZKOVAL** [comment]
Ještě doplňuji, že v žádosti PXN budou zachovány 2 možnosti finálního rozhodnutí kurátora SDNNT:

**Schválit** - dílo se dostane do stavu X (tím pádem je vyřazené ze seznamu, protože díla ve stavu X uvidí pouze kurátor a knihovna, přičemž navrhovat na seznam ho může pouze kurátor ruční změnou stavu)

**Zamítnout** - dílo bude mít původní stav (PA/A/N?)

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Je to tak, že jsme domluveni?  Procházet se má A, PA, N  (Stav NL ne).  Akce schválit a zamítnout jsou popsány výše.   Kontextovou informaci zmiňovanou v issue #269  v tomto případě nezapisovat ?

**Comment by Cypzirschova** [comment]
Procházet se určitě bude PA, A, NL. 
U stavu N ještě nemohu na 100% potvrdit. Během zítřka potvrdím.

**Comment by Cypzirschova** [comment]
Díla se stavem N se nebudou procházet.
Takže prosím upravit takto - procházet stav: PA, A, NL.

**Comment by JanMeritus** [comment]
@smallcubes prosim o vyjadreni

**Comment by smallcubes** [comment]
@JanMeritus jakmile doběhne reindex, vyzkouším to

**Comment by smallcubes** [comment]
@pavel-stastny joby definované s typem `kramerius_px_check` berou odkazy z `"check_kramerius"`, je to tak správně?

**Comment by smallcubes** [comment]
Kontrola záznamu jsem nastavil, aktuálně vypadá následovně: 

```json
"krameriove_kontextova_informace": {
        "type":"kramerius_px_check",
        "cron": "0 02 12 * * ?",
        "iteration": {
                "date_range": "[* TO 2020]",
                "states": ["A","PA","NL","N"]
        },
        "results":{
                "ctx": true
        }
},
```

**Comment by smallcubes** [comment]
@CIZKOVAL @Cypzirschova může být kontrola záznamů vuči krameriovi nastavena tak, že se prochází `"A","PA","NL"` a vytvoří se žádost `PXN` o velikosti 60 položek? Má tam patřit i `"N"`?

```json
"kram_kontrola_zaznamu":{
          "type":"kramerius_px_check",
          "cron": "0 02 12 * * ?",
          "iteration":{
                  "states":["A","PA","NL"]
          },
          "results":{
                  "request":{
                          "items":60,
                          "type":"PXN"
                  }
          }
  },
```

**Comment by Cypzirschova** [comment]
N tam prosím nedávat.

**Comment by smallcubes** [comment]
nechal jsem tedy nastavení bez `"N"`

**Comment by Cypzirschova** [comment]
Jde tam nastavit at kontrola chodí jen 1x týdně?

**Comment by smallcubes** [comment]
@Cypzirschova nastavil jsem, ať kontrola vždy běží v sobotu v 00:00 
`0 0 * * 6`

**Comment by Cypzirschova** [comment]
Super, děkuji!
@smallcubes

**Comment by CIZKOVAL** [comment]
Dobrý den,
v žádostech PXN u některých děl chybí příznak volného díla v DK, viz issue #269 

_Pokud dílo v žádosti PXN zamítnu, tak zůstane původní stav (PA/A/NL) a zůstává také příznak volného díla v DK, to je v pořádku._

@pavel-stastny Jak to bude fungovat v situaci, že když už jednou dílo ve stavu PA/A/NL příznak volného díla má (**zamítnuto v PXN nebo nerozhodnuto v PXN**) - bude každý další týden v nové žádosti PXN? Nebo už se v nové žádosti neobjeví?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Proces nepřidá titul do nové žádosti pokud již v nějaké figuruje.

**Comment by CIZKOVAL** [comment]
Kontrola záznamů proti Krameriům by se měla spouštět každý týden v sobotu. Tuto sobotu, tedy 19.3. 2022 spuštěna nebyla. Poprosím @smallcubes o výpis z logu. Děkuji

**Comment by smallcubes** [comment]
dle #269 přenastaveno následovně:
```json
"krameriove_kontrola_zaznamu":{
                                "type":"kramerius_px_check",
                                "cron":"0 0 0 ? * SAT *",
                                "iteration":{
                                        "states":["A","PA","NL"]
                                },
                                "results":{
                                        "request":{
                                                "items":60,
                                                "type":"PXN"
                                        }
                                }
                        },
```

**Comment by smallcubes** [comment]
@pavel-stastny @CIZKOVAL ještě jsem pro vyzkoušení dočasně nastavil čas na 11:45 tento den a setkal jsem se s opakujícím výpisem chyb:

```
21-Mar-2022 11:45:00.002 INFO [QuartzScheduler_Worker-4] cz.inovatika.sdnnt.sched.Job.fire Job krameriove_kontrola_zaznamu fired
21-Mar-2022 11:45:00.011 INFO [QuartzScheduler_Worker-4] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.check Current iteration filter [id_pid:uuid, fmt:BK, dntstav:(A OR PA OR NL)]
21-Mar-2022 11:45:00.039 INFO [QuartzScheduler_Worker-4] cz.inovatika.sdnnt.index.IterationSupport.iterate Iteration rows 1000

21-Mar-2022 11:45:34.635 SEVERE [QuartzScheduler_Worker-4] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.clearBuffer Server returned HTTP response code: 500 for URL: https://kramerius5.nkp.cz//search/api/v5.0/search?q=PID:(PID%3A%28uuid%5C%3A83fa5050-5585-11e6-ab2f-005056827e52+OR+uuid%5C%3A4e222500-3d52-11e3-9c86-005056827e51+OR+uuid%5C%3Aa90c3820-5292-11e3-ac69-005056827e51+OR+uuid%5C%3A3a6fea20-bc74-11e6-b333-005056827e51+OR+uuid%5C%3Aeab8d4b0-b868-11e6-a108-005056827e51+OR+uuid%5C%3Aadd09ef0-6944-11e3-8fee-005056827e51+OR+uuid%5C%3Abeaf8a30-52f1-11e6-ab2f-005056827e52+OR+uuid%5C%3A1ab7e360-b867-11e6-88f6-005056827e52+OR+uuid%5C%3A195670c0-c5c6-11e5-bef4-005056827e51+OR+uuid%5C%3A01f3dab0-0346-11e4-9789-005056827e52+OR+uuid%5C%3Afa5d10f0-ffdc-11e6-8830-005056827e51%29)&wt=json
        java.io.IOException: Server returned HTTP response code: 500 for URL: https://kramerius5.nkp.cz//search/api/v5.0/search?q=PID:(PID%3A%28uuid%5C%3A83fa5050-5585-11e6-ab2f-005056827e52+OR+uuid%5C%3A4e222500-3d52-11e3-9c86-005056827e51+OR+uuid%5C%3Aa90c3820-5292-11e3-ac69-005056827e51+OR+uuid%5C%3A3a6fea20-bc74-11e6-b333-005056827e51+OR+uuid%5C%3Aeab8d4b0-b868-11e6-a108-005056827e51+OR+uuid%5C%3Aadd09ef0-6944-11e3-8fee-005056827e51+OR+uuid%5C%3Abeaf8a30-52f1-11e6-ab2f-005056827e52+OR+uuid%5C%3A1ab7e360-b867-11e6-88f6-005056827e52+OR+uuid%5C%3A195670c0-c5c6-11e5-bef4-005056827e51+OR+uuid%5C%3A01f3dab0-0346-11e4-9789-005056827e52+OR+uuid%5C%3Afa5d10f0-ffdc-11e6-8830-005056827e51%29)&wt=json
                at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
                at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
                at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
                at cz.inovatika.sdnnt.utils.SimpleGET.getFinalURL(SimpleGET.java:19)
                at cz.inovatika.sdnnt.utils.SimpleGET.getFinalURL(SimpleGET.java:24)
                at cz.inovatika.sdnnt.utils.SimpleGET.getFinalURL(SimpleGET.java:24)
                at cz.inovatika.sdnnt.utils.SimpleGET.get(SimpleGET.java:31)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.simpleGET(PXKrameriusServiceImpl.java:258)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.clearBuffer(PXKrameriusServiceImpl.java:223)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.checkBuffer(PXKrameriusServiceImpl.java:201)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.check(PXKrameriusServiceImpl.java:189)
                at cz.inovatika.sdnnt.sched.Job$Actions$3.doPerform(Job.java:188)
                at cz.inovatika.sdnnt.sched.Job.fire(Job.java:58)
                at cz.inovatika.sdnnt.sched.Job.fire(Job.java:51)
                at cz.inovatika.sdnnt.sched.Job.execute(Job.java:94)
                at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
                at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by Cypzirschova** [comment]
@smallcubes stále platí, že kontrola běží pravidelně každou sobotu?

**Comment by CIZKOVAL** [comment]
Dobrý den,
procedura byla spuštěna naposled 30.3. 2022. Vytvořily se žádosti PXN a dnes večer, konkrétně 5.4. ve 23:00 jsme nastavili, aby se procedura spustila znovu. Chci otestovat, že vzorek záznamů v žádostech bude menší, protože by mělo platit, že pokud už dílo v žádosti je, pak se do nové žádosti nedostane.

Do budoucna to nastavíme na každou sobotu.

**Comment by Cypzirschova** [comment]
Děkuji za zprávu. Chtěla jsem si ověřit, zda kontroly fungují a chodí pravidelně.

**Comment by smallcubes** [comment]
Zkoušeli jsme ještě jednou kontrolu (krameriove_kontrola_zaznamu) a kontrola nejspíše doběhla, ale není to moc dobře vyhledatelné. Nemohlo by se objevit nějaká hláška obsahující slovo FINISHED, jako je tomu u jiných procedur? @pavel-stastny 

```
06-Apr-2022 10:47:39.898 INFO [QuartzScheduler_Worker-2] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.clearBuffer Testing url is http://krameriusndk.nkp.cz/search/api/v5.0/search?q=PID%3A%28uuid%5C%3Aa4ab0d30-ff0d-11e6-8830-005056827e51+OR+uuid%5C%3Ab05ab310-c42e-11e2-8b87-005056827e51+OR+uuid%5C%3A75354840-45cb-11e2-9b88-005056827e51+OR+uuid%5C%3A1ea2c000-6eb3-11e2-b9fa-005056827e52+OR+uuid%5C%3A5be6cb00-6c33-11e2-8ed6-005056827e52+OR+uuid%5C%3A8199eea0-5368-11e3-ae59-005056827e52+OR+uuid%5C%3A6b76c940-1898-11e4-8f64-005056827e52%29&wt=json&rows=7 and list of identifiers [oai:aleph-nkp.cz:DNT01-000022580, oai:aleph-nkp.cz:DNT01-000120936, oai:aleph-nkp.cz:DNT01-000120935, oai:aleph-nkp.cz:DNT01-000022589, oai:aleph-nkp.cz:DNT01-000022588, oai:aleph-nkp.cz:DNT01-000022587, oai:aleph-nkp.cz:DNT01-000120939]
06-Apr-2022 10:47:39.964 INFO [QuartzScheduler_Worker-2] cz.inovatika.sdnnt.sched.Job$Actions$3.doPerform Number of found candidates 0
```

**Comment by JanMeritus** [comment]
@pavel-stastny prida info a vycleni do samostatnych logu

**Comment by smallcubes** [comment]
@pavel-stastny @JanMeritus pro výpis logů viz samostatné issue: #363

**Comment by CIZKOVAL** [comment]
Čas spouštění procedury pro vytváření žádostí PXN bude každou **neděli v 22:00**

**Comment by CIZKOVAL** [comment]
@pavel-stastny prosím o informaci, jak je to s žádostí PXN. Poslední vygenerovanou žádost máme z 5.4. 2022, poslední spuštění proběhlo tuto neděli 17.4. ve 22:00. V logu zatím není informace, zda proces doběhl a novou žádost PXN mezi žádostmi nevidím. Nedokážu posoudit, jestli proces doběhl v pořádku nebo jestli se nenašel žádný vhodný záznam, který by odpovídal kritériím pro žádost (pokud vycházím z předpokladu, že do žádosti se dostane pouze dílo, které nefiguruje v předešlých žádostech).

**Comment by pavel-stastny** [comment]
@CIZKOVAL No, s procesem a žádostí je to jak píšete. Pokud je dílo již v žádosti PXN, tak není již kontrolováno.  Ohledně běhu procesu, v rámci #363 popíšu jak nastavit logování do samostatných souborů.

**Comment by smallcubes** [comment]
zde byl myslím problém s tím, že procedura pro PXN bežela příliš dlouho

**Comment by smallcubes** [comment]
@smallcubes zkontrolovat délku běhu PXN

**Comment by smallcubes** [comment]
myslím, že se může uzavřít
