### ISSUE TITLE
Upresnit readme projektu a aktualizovat harmonogram

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#18]
Ahoj,

prosim o zajisteni pripravy na zverejneni repozitare a reportovani stavu pripravenosti pro zverejneni.

Zdravim,

Z.

**Comment by JanMeritus** [comment]
@pavelkocourek prosim o update harmonogramu dle protokolu

**Comment by pavelkocourek** [comment]
Doplněno dle premovacího protokolu
