### ISSUE TITLE
Stav funkcionality: nápověda dle role uživatele

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#180]
Dobrý den,
je implementovaná nápověda dle role uživatele? Nyní je nápověda prázdná, dle ZD by mělo být.

**Comment by Cypzirschova** [comment]
Prosím, alespoň o krátkou odpověď. @pavel-stastny @JanMeritus 
Text bude jeden a pro všechny viditelný nebo se bude podle role lišit (uživatel - nakladatel/knihovna)?
Bude moci text do nápovědy vkládat/měnit admin?

**Comment by pavel-stastny** [comment]
@Cypzirschova Dobrý den, omlouvám se, nyní jsem na jiném projektu. Ano, ve verzi 1.0 jsou pro každou roli samostatná nápověda.  (Editovatelný soubor na straně serveru)

**Comment by CIZKOVAL** [comment]
Retest OK - v administraci lze přidávat texty pro nápovědu.

Zatím doplněna nápověda pro roli user (nakladatel). Další texty budu doplňovat tak jak přijdou.
