### ISSUE TITLE
Přidání korespondence k výzvě/žádosti

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#182]
Dobrý den,

bylo by možné v rozhraní vytvořit někde položku pro korespondenci? Tato položka by se měla zobrazovat samostatně vedle polí: "Poznámka, Odůvodnění" a je vázaná k žádosti/výzvě.

Zadávací dokument sekce (C): *„Možnost přidávat extrakty korespondence k jednotlivým případům“*

Předem Vám děkuji za odpověď

**Comment by pavel-stastny** [comment]
Přidáno tlačítko a dialogbox

![image](https://user-images.githubusercontent.com/675753/146735793-8aa70473-f3aa-4aea-83f0-ea952e6b3291.png)

![image](https://user-images.githubusercontent.com/675753/146735886-a4273504-84c8-45e2-acc3-f1573e996f36.png)

Dostupné pouze kro kurátory

**Comment by Cypzirschova** [comment]
Při uložení mi vyskočí chyba.

**Comment by pavel-stastny** [comment]
@smallcubes Do buildu jsem zapomněl připsat poznámku, že je potřeba upravit schéma pro žádost.  Bylo tam přidáno pole pro email komunikaci.    V souboru "[solr.zip](https://github.com/NLCR/SeznamDNNT/releases/download/1.0/solr.zip)" adresář "zadost", soubor "managed_schema".  Postup jak nahrát nové jádro by měl být [zde](https://github.com/NLCR/SeznamDNNT/wiki/Instalace-aplikace#znovu-na%C4%8Dten%C3%AD-j%C3%A1drajader ):

**Comment by smallcubes** [comment]
@pavel-stastny solr bylo aktualizováno

**Comment by smallcubes** [comment]
poprosil bych paní @Cypzirschova o schválení, zdali takto implementovaná funkce vyhovuje. Po schválení issue uzavřu.

**Comment by Cypzirschova** [comment]
@smallcubes 
Za mě OK.

**Comment by smallcubes** [comment]
@Cypzirschova děkuji Vám za odpověď. Issue uzavírám. 

@CIZKOVAL
