### ISSUE TITLE
Zobrazení licence 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#185]
Dobrý den,
v aplikaci se zobrazuje 3. licence s 1 dílem, viz níže.
![licence](https://user-images.githubusercontent.com/86351100/145040571-4498c365-3b68-4bc8-8f1d-280b676d7eeb.png)
![licence2](https://user-images.githubusercontent.com/86351100/145040778-709e9db9-5db3-42b0-b313-c5eb8d3c1a7a.png)
Cypzirschová

**Comment by CIZKOVAL** [comment]
To vzniklo vzhledem k chybě #161 . Když se při ruční změně stavu nevybrala licence, tak tam vzniknul tento "bazmek".
Nyní už by k této situaci nemělo docházet, pole s licencí nemůže být null.

**Comment by Cypzirschova** [comment]
Ok, u díla jsem vložila ručně licenci a zavírám.
