### ISSUE TITLE
Úprava záložek na úvodní stránce

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#186]
Dobrý den,

bylo by možné upravovat záložky, které se zobrazují na úvodní stránce? Tedy přejmenování záložky např. z O SDNNT na O aplikaci a přidání nebo odstranění záložky.

Předem Vám děkuji za odpověď.

**Comment by pavel-stastny** [comment]
Je to možné klientskou konfigurací.  Standardně je nastaveno následovně: 

`  "homeTabs": ["about", "news", "readers", "authors",  "libraries", "api"],
`

**Comment by smallcubes** [comment]
@pavel-stastny @pkudela přidávání i odstraňování záložek funguje. Ještě bych poprosil o návod, jak mohu záložky přejmenovat pro českou i anglickou verzi?  (např. přidám do pole string "test" a následně se vytvoří home.test)

**Comment by pkudela** [comment]
Dobry den @smallcubes, pokud pridate do konfigurace tab s nazvem "test", tak musite doplnit jeho klic do ceske a anglicke verze -> "/assets/i18/cs.json" a "/assets/i18/en.json" viz. screenshoty nize. Jen upozornim, na editaci tech prekladu opatrne, vzdy doplnit do ceske i anglicke verze a na stejny radek, to je velmi dulezite pro pripadne odstranovani chyb, pocet radku v obou souborech musi byt 1:1.

![image](https://user-images.githubusercontent.com/16591052/154520705-becc2bbc-8317-4b62-a8d7-c734ad7dfed3.png)

![image](https://user-images.githubusercontent.com/16591052/154522014-3a426647-53bb-4e0b-89fd-8a582e6a158a.png)

<img width="393" alt="image" src="https://user-images.githubusercontent.com/16591052/154522074-d84984be-7547-4148-81db-8fe77400418f.png">

**Comment by pkudela** [comment]
@smallcubes prosim tedy o uzavreni tohoto issue.

**Comment by smallcubes** [comment]
@pkudela děkuji za popis i implementaci, funguje a uzavírám.

**Comment by smallcubes** [comment]
konfigurace se nachází v `.../sdnnt/assets/i18n/en.json|cs.json`
