### ISSUE TITLE
Teritorialita u záznamu

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#188]
V budoucnu by měl záznam obsahovat i informace o teritorialitě a poskytovatele.

Zadávací dokument (sekce D): *„Propagace změn stavů, jednotlivých stavů a licencí: Mezi základní poskytovaná data patří: 1. Stav díla a unikátní technické identifikátory 2. Bibliografické údaje 3. Poskytovatel licence 4. Druh licence (např.: Na místě samém / Vzdálený přístup) 5. Teritoriální působnost licence (ČR / EU / stát)“*

**Comment by JanMeritus** [comment]
Definice pozadavku dle schuzky 2.2.:

-zadani D.5: Teritoriální působnost licence (ČR / EU / stát)

Navrhovany spusob realizace: 
- pro kazde dilo zarazeno do navrhu na SDNNT, pridelit defaultne teritorialni pusobnost licence ve formatu _pole stringu_, ted jenom s jedinym zaznamem - ["CZ"]
- tento typ zaznamu do budoucna by mel umoznit pridavani dalsich krajin, nebo celku, typicky napr: ["CZ","DE"], nebo ["CZ","EU"]
- tato informace musi byt dale poskytovana via OAI a REST API

FYI @smallcubes @CIZKOVAL @jahhoo

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Po konzultaci s @albertoh:  OAI obsahuji pouze marcova pole, je tedy nutne rozhodnout, jak bude teritorialita licence v OAI vypadat.   (Ve formatu marc21)

**Comment by JanMeritus** [comment]
@smallcubes prosim o dotestovani

**Comment by smallcubes** [comment]
Teritorialitu **nemohu** zjistit v API endpoitu u žádného z veřejného API: 
  - `/lists/added/dnntt`
  - `/lists/added/dnntt/csvexport`
  - `/lists/added/dnnto`
  - `/lists/added/dnnto/csvexport`
  - `/lists/removed/dnntt`
  - `/lists/removed/dnntt/csvexport`
  - `/lists​/removed​/dnnto`

V části API, kde je nutný token, nemohu přidat v žádosti teritorialitu. To je asi správně, ale uvádím to pouze pro úplnost.
Teritorialitu vidím v endpointu `/catalog`, pod klíčem `"territoriality": "CZ"`.
Ve front-endu teritorialitu nezjistím.

@JanMeritus

**Comment by pavel-stastny** [comment]
@smallcubes 

Ad UI:  paní @Cypzirschova @Lichtenbergova.
Ad endpointy.  Jsou pojaty jako sycnhronizační endpointy, především pro stranu Krameria.   Nemá smyslu to tam dávat.

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Verze bude už řešená banchí v githubu, až 1.0.5 bude reálný milestone

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Pro `budoucí `napojení na cokoliv vznikne nový endpoint. Z těch synchronizačních endpointů tu informaci vyhodím. Tam opravdu nemá co dělat.

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za informaci

**Comment by smallcubes** [comment]
v 1.4.0.6 teritorialita není přístupná

**Comment by smallcubes** [comment]
teritorialita jde vidět ve veřejné i neveřejné API
