### ISSUE TITLE
Aktivizace uzivatele

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#19]
Uzivatel po odeslani zaujmu o clenstvi a potvrzeni clenstvi dostane aktivacni mail, klikne na odkaz a nasledne v rozhrani si nastavi heslo

**Comment by pavel-stastny** [comment]
Nyni se generuje heslo na serveru. Chovani by melo byt takove, ze uzivatel vzdy bude nastavovat heslo na zaklade kliku na link z mailu.

**Comment by pavel-stastny** [comment]
@JanMeritus Resene pres link na nastevni hesla.   
Build afe209e

**Comment by JanMeritus** [comment]
@smallcubes prosim o dotestovani, uz je to tu 24 dni

**Comment by smallcubes** [comment]
@JanMeritus  @pavel-stastny vypadá to v pořádku. Děkuji Vám za vyřešení.
