### ISSUE TITLE
OAI-PMH: vytváření subsetů

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#190]
Dobrý den,

chtěl bych se zeptat, zdali je možné vytvářet subsety pro OAI-PMH. Pokud ano, tak jak? Připadně lze subsety někde definovat, filtrovat?

**Comment by pavel-stastny** [comment]
#175

**Comment by smallcubes** [comment]
@pavel-stastny @JanMeritus issue uzavírám, kvůli tomu, že se jedná o duplikát.
