### ISSUE TITLE
Seznam konfiguračních souborů a místo jejich uložení

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#192]
Bylo by možné zde napsat seznam všech konfiguračních souborů aplikace? Poprosil bych o kontrolu a případné doplnění. 

Seznam konfiguračních souborů:
- konfigurace e-mailu pro docházející poštu z aplikace (notifikace, registrace, šablony pro e-maily, cron jobs): [`installation/config.json`](https://github.com/NLCR/SeznamDNNT/blob/main/installation/config.json), [pro více informací viz wiki](https://github.com/NLCR/SeznamDNNT/wiki/Instalace-aplikace)
- konfigurace institucí pro registraci: (notifikace, registrace, šablony pro e-maily, cron jobs): [`installation/config.json`](https://github.com/NLCR/SeznamDNNT/blob/main/installation/config.json), [pro více informací viz wiki](https://github.com/NLCR/SeznamDNNT/wiki/Instalace-aplikace)
- nastavené lhůt pro žádosti/výzvy: [`installation/config.json`](https://github.com/NLCR/SeznamDNNT/blob/main/installation/config.json), #163 
- #174

**Comment by pavel-stastny** [comment]
@smallcubes Výše zmíněné smažu. Píšu to [sem](https://github.com/NLCR/SeznamDNNT/wiki/Soupis-konfigura%C4%8Dn%C3%ADch-parametr%C5%AF)

**Comment by smallcubes** [comment]
@pavel-stastny dobře, issue uzavírám.
