### ISSUE TITLE
Žádosti VNZ se neseskupují

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#195]
Dobrý den,
když zadám více žádostí VNZ (omezení na terminál), tak se v nové verzi 0.9 už neseskupují, ale pro každé dílo je nová žádost VNZ.
Tím pádem i žádost VNL není seskupená, protože žádosti VNZ lze překliknout do VNL.

![Žádosti VNZ se neseskupují](https://user-images.githubusercontent.com/92719629/145227286-140ab20c-814b-4f2d-8401-535f84265877.png)

**Comment by JanMeritus** [comment]
@CIZKOVAL je to pozadovana vlastnost, bug nebo kuratormi zadana feature?

**Comment by CIZKOVAL** [comment]
@JanMeritus žádosti se seskupují, dokud nejsou odeslány. Žádosti VNZ se seskupovat přestaly.

**Comment by CIZKOVAL** [comment]
Retest OK, žádosti se seskupují.
