### ISSUE TITLE
Přechod ze stavu NLX nefunguje správně

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#196]
Dobrý den,
díky přenastavení lhůt se některá díla dostala do stavu **NLX** tímto způsobem:

1. N --> NZN -->NPA --> PA
2. PA --> VNL --> NL -- NLX

**Očekávané chování:** 
u stavu NLX by měl kurátor **rozhodnout** o tom, zda bylo dílo nakladatelem publikováno.
**a)** ano, dílo bylo vydáno NLX --> N
**b)** ne, dílo nebylo vydáno NLX --> A (bez čekání na lhůtu 1). Předpokládám, že s původní licencí, která byla u PA.

**Výsledné chování:**
u stavu NLX je pouze 1 možnost a to schválit žádost
**a)** ano, dílo bylo vydáno NLX --> N

![NLX](https://user-images.githubusercontent.com/92719629/145240035-95e30bf9-e350-4c36-8899-a1e7067a5058.png)

![NLX_textace](https://user-images.githubusercontent.com/92719629/145239995-fc3aea35-b9f6-4a2b-97a3-c04bc3c30fac.png)

**Comment by CIZKOVAL** [comment]
Ještě přikládám diagram, kterého se to týká:

![NLX_diagram](https://user-images.githubusercontent.com/92719629/145241129-3a9297f8-76ff-4a7b-8de6-db81370a1959.png)

**Comment by Cypzirschova** [comment]
> **Očekávané chování:** 
u stavu NLX by měl kurátor **rozhodnout** o tom, zda bylo dílo nakladatelem publikováno. 
**a)** ano, dílo bylo vydáno NLX --> N 
**b)** ne, dílo nebylo vydáno NLX --> A (bez čekání na lhůtu 1). Předpokládám, že s původní licencí, která byla u PA.
> 
> **Výsledné chování:** 
u stavu NLX je pouze 1 možnost a to schválit žádost **a)** ano, dílo bylo vydáno NLX --> N

Souhlasím, chybí tam možnost, že nakladatel nic nevydal. Pak se to vrací do původního stavu s původní licencí, jak je výše.

**Comment by JanMeritus** [comment]
@CIZKOVAL jde o rozsireni modelu?

**Comment by CIZKOVAL** [comment]
@JanMeritus jde o model, ktery byl predmetem #66, takze bug

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Tu jednu moznost jsem tam dal schvalne.  Ta logika byla takova, ze pokud vydal, zmackne tlacitko ze dilo bylo vydano, pokud nevydal, pouze zadost oznaci za zpracovanou.     

Udelam upravu aby to nebylo tak matouci. K dispozici bude tlacitko pro "Vydal" a "nevydal" . Zadost pujde oznacit az po vybrani jedne z moznosti.

**Comment by Cypzirschova** [comment]
Pokud by to bylo, jak jste popsal, tak by přece po schválení přešlo dílo do stavu A.

**Comment by pavel-stastny** [comment]
@Cypzirschova Hlavni stav nyni zustava ten ktery je, tedy A nebo PA (Pokud PA pak je predmetem preklopeni ale v jine zadosti) a licence dnntt .  Ziskal ji  diky zadosti VNL.   

Jenom aby v tom bylo jasno:  

-  Po nalezeni u nakladatelu je stav N ?
-  Po nenalezeni zustava puvodni stav A nebo PA, licence se preklapi na dnnto (dnntt byt nemohla, jinak by neslo dat zadost VNL) ?  
 - A kuratorsky stav?   Nyni zustava NLX ?  Ma zmizet?

**Comment by pavel-stastny** [comment]
@Cypzirschova  Jeste se divam na diagram a mate pravdu v tom, ze ma rovnou prejit do A, bez cekani.  Chovani zmenim,

**Comment by CIZKOVAL** [comment]
Nyni nelze retestovat, blokovano chybou #218

**Comment by CIZKOVAL** [comment]
Retest OK, ze stavu NLX je rozhodovací manévr a díla končí ve správných stavech.

Zadáno issue #233 na změnu tlačítek.
