### ISSUE TITLE
Zpracování žádostí VNL (stav NLX) lze i bez uložení rozhodnutí

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#197]
Dobrý den,
pokud mám dílo uvnitř žádosti **VNL** ve stavu **NLX** (proběhla již lhůta 4), pak čeká na posouzení kurátorem.

Omylem jsem označila žádost jako zpracovanou, aniž bych se vnořila dovnitř a potvrdila rozhodnotí, zda nakladatel dílo vydal nebo ne (nyní je tam jen 1 možnost, na to je zadaná jiná chyba).

**Žádost se označila jako zpracovaná, aniž by mě systém varoval, že žádost uvnitř nebyla potvrzena nebo odmítnuta.**

Výsledek je, že dílo v žádsoti zůstane ve stavu NLX a nelze ho změnit (pouze ručním zásahem kurátora).

![NLX_rovnou_zpracovat](https://user-images.githubusercontent.com/92719629/145251112-6150e6fc-c8cc-4773-8bc9-5253546ce682.png)

**Comment by Cypzirschova** [comment]
Souhlasím, problém stále přetrvává.

**Comment by JanMeritus** [comment]
@CIZKOVAL jde o bug nebo chybi ujistovavaci formular/zruseni rozbehnute akce ?

**Comment by CIZKOVAL** [comment]
@JanMeritus jde o bug. Formular na schvaleni/odmitnuti tam je, ale nejsem nucena ho vybrat.

**Comment by CIZKOVAL** [comment]
Nyni nelze retestovat, blokovano chybou #218

**Comment by CIZKOVAL** [comment]
Dobrý den, retest OK. Žádost nelze označit jako zpracovanou, pokud se uvnitř nachází dílo, u kterého nepadlo rozhodnutí kurátora.

![retest_VNL_zpracovat](https://user-images.githubusercontent.com/92719629/149929306-8e049cf3-28de-4046-a6a8-b241e574f481.png)
