### ISSUE TITLE
Žádosti VNL běží nadále lhůta i když byla zamítnuta

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#198]
Dobrý den,
provedla jsem následující test 1 zadost obsahovala pouze 1 dilo:

1. N --> NZN --> NPA --> PA
2. PA -- > VNL --> zamitnuti dila v zadosti --> PA --> lhuta 1 --> A

Toto je OK, ale **i nadále běží žádost VNL**, tj, v tomto okamžiku běží stále lhůta 4 (18 měsíců). Žádost po uplynutí lhůty nelze potvrdit (chybí tlačítko, to je OK), ale musí se označit jako zpracovaná, jinak neustále čeká na zpracování. Ničemu to ve výsledku nevadí, dílo má správný stav, ale takto se tam budou žádosti hromadit a je to zavádějící.

![VNL_zamitnuta](https://user-images.githubusercontent.com/92719629/145253595-4b0879ef-80d0-450a-9067-ef87f42522a6.png)

**Comment by CIZKOVAL** [comment]
Totéž bude nejspíš u všech žádostí, které byly zamítnuty. Běží i nadále lhůta (čeká na automatické zpracování).

další příklad: NZN - zamítnuto - běží i nadále lhůta 0, i když se v určený čas dílo nepřeklopí.

**Comment by Cypzirschova** [comment]
Souhlasím, takto by se to nemělo chovat. Pokud zamítnu - lhůta by neměla dál pokračovat.

**Comment by JanMeritus** [comment]
@CIZKOVAL @Cypzirschova dle meho jde o bug, po vykonani rozhodne cinnosti, musi byt casovani odstraneno/zresetovano vzhledem na dalsi akci

**Comment by pavel-stastny** [comment]
@JanMeritus Nejde o bug.  Jak jiz bylo receno, ve vysledku to nicmemu nevadi.  (Zadost probehne bez toho aniz by se stavy zmenily.)

**Comment by pavel-stastny** [comment]
Pokud je nyní žádost kompletně zamítnuta neběží žádná lhůta a přesune se rovnou do stavu `"processed"`

**Comment by Cypzirschova** [comment]
@pavel-stastny Zatím je tam stále chyba, viz #218.

**Comment by CIZKOVAL** [comment]
Dobrý den,
retest OK. Pokud je v žádosti pouze 1 dílo, které se zamítne, tak po označení zpracované žádosti se ukončí proces a žádost je ve stavu zpracována - další lhůta neběží. 
Vyzkoušeno u VNL (přechod do NL, NLX zamítnut, tj. lhůta 4 neběží) , NZN (přechod do NPA, PA zamítnut, tj. lhůta 0 neběží).
