### ISSUE TITLE
Funkcionalita - kontrola volneho dila v NDK

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#20]
Dilo v NDK.cz, ktere je volne a je zaroven v navrhu na DNNT:
- by nemelo byt mozno zaradit jako DNNT (nebot je volny)
- pokud je uz zarazeno ako DNNT musi byt ze seznamu vyrazeno (dilo NK nasledne nepovazuje za nedostupny v technickom slova zmyslu)
- kurator by mel mit moznost videt tento kontext pri posuzovani navrhu

**Comment by pavel-stastny** [comment]
Z veřejného kramerius API získávat informace o tom, zda dílo je volné a informaci přindexovat do catalog indexu.

**Comment by pavel-stastny** [comment]
@JanMeritus 

Obecně, opět by to stálo za to to prodistkutovat. Problémy které zde vidím jsou: 

- Pokud se bude získávat ta informace při indexaci, neúměrně to prodlouží čas 
- Může se to řešit ext post, tedy job na pozadí, který bude dotahovat data ale pak se musí počítat s tím, že data nemusí být v daný okamžik aktuální. 
- Ajax request při zobrazení stránky s výsledky. Tady se naráží na neaktuálnost linků.  Jsou tam odkazy do staré digitalizace (Nejenom u NK), server nemusí existovat, bude se čekat až dotaz vytimeoutuje, atd.. 
- Odkazů může být víc a mohou se různit (v jedné digitální knihovně může být dílo public v druhé private) a to z toho důvodu, že nedostupnost mají řešenou jiným nastavením práv (například moving wall, atd..)
