### ISSUE TITLE
Přidělování licencí - z NPA na PA

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#200]
Dobrý den,
není správně nastavené přidělování licencí. Když se díla překlopí ze stavu NPA na PA je automaticky všem dílům přiřazena licence DNNTO. 

- DNNTO - dílům vydaným do roku 2000
- DNNTT - dílům vydaným od r. 2001-2007

Týká se to jen monografií (formát BK). Je potřeba to vyřešit. U seriálů je to trochu komplikovanější (formát SE). Periodika (seriály) se rozdělují na pravá a nepravá. To záleží na periodicitě. U pravých periodik mají licence DNNTO - musí vycházet nejméně 2x ročně. U nepravých periodik se licence přiděluje stejně jako u monografií. K seriálům ještě poprosím paní Lichtenbergovou o komentář. @Lichtenbergova
Cypzirschová

![licence pa22](https://user-images.githubusercontent.com/86351100/145358342-a30ef74a-1f43-4bfd-85b6-37b0a42916ed.png)
![licence pa](https://user-images.githubusercontent.com/86351100/145358357-12578aa0-1941-47cd-b305-0b6479ab55a8.png)

**Comment by Lichtenbergova** [comment]
Ano je to tak. A ještě by se se rozmezí mělo od 1.1.22 posouvat
DNNTO - dílům vydaným do roku 2001
DNNTT - dílům vydaným od r. 2002-2007

**Comment by Cypzirschova** [comment]
Děkuji a u nepravý periodik je to tedy 2001-2010 - DNNTT?

**Comment by JanMeritus** [comment]
@Lichtenbergova @Cypzirschova byla tato specifikace v #66 ?

**Comment by Cypzirschova** [comment]
Bohužel jsem to tam nenašla. V současné době, jak je to nastaveno v aplikaci, bych musela u všech děl, které přejdou do stavu PA, ručně procházet a měnit licence podle roku vydání, jak je výše popsáno. 

V současné době v bázi DNT01 je ta licence vlastně řešená stavem NZ, který tady v nové aplikaci zmizel.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Oznacil jsem jako enhancement.  Nikde v zadani nebo v issues to nebylo sepcifikovano => Nemohlo byt implementovane.

**Comment by Cypzirschova** [comment]
Doplním jen ještě info, že licence, které se nastaví z NPA na PA - licence musí být stejné jako při překlopení z PA na A.

**Comment by Cypzirschova** [comment]
Z důvodu novely AZ, to nebude potřeba. Issue uzavírám.
