### ISSUE TITLE
API: generování CSV

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#202]
Při generování CSV by měla být možnost vygenerování jen seznamu s UUID

**Comment by pavel-stastny** [comment]
@JanMeritus Nepřiřazovat mě na issues, prosím

**Comment by pavel-stastny** [comment]
@jahhoo Muze byt ale jaky to ma duvod ?

**Comment by jahhoo** [comment]
@pavel-stastny Náročnost / velikost souboru. Případně přímý import do Krameria

**Comment by zabak** [comment]
Nemohlo by to být tak, že když zavolám API a nedám seznam údajů které chci dostat, tak mi to ze základní množiny vrátí několik default údajů, pokud ale dám seznam polí, tak mi to vrátí jen požadovaná pole, tj. když řeknu že chci jen uuid, tak to vrátí jen uuid?

**Comment by pavel-stastny** [comment]
Přidána možnost vybrat si pole, které mají být v cvsku přítomny.  Pokud se nic neuvede jsou tam všechny ty které jsou pro export podporovány: `pid`, `instituce`, `název`, `identifikátor`.   Pid je povinný.

**Comment by jahhoo** [comment]
Funguje. Díky
