### ISSUE TITLE
API: popis vyhledávání v katalogu

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#203]
Chybí popis tvorby dotazu pro vyhledávání v katalogu ( /api/v1.0/catalog ). 

a) Podle kterých polí lze vyhledávat? 

b) Lze najít záznamy dle UUID z Krameria? To by se velice hodilo..

**Comment by jahhoo** [comment]
Pokud zadám toto:

`identifier:"oai:aleph-nkp.cz:DNT01-000240689"`

nenajde mi nic..

**Comment by pavel-stastny** [comment]
@jahhoo endpoint `/catalog` v API je analogie toho co uživatel vidí v UI.  Tedy neměla by být nutná znanost schématu, jenom vyhledávat dle identifikátoru (případně titulku atd..) Tedy zadat `oai:aleph-nkp.cz:DNT01-000240689` případně  `"oai:aleph-nkp.cz:DNT01-000240689"`

a ad b)  Pokud je naindexované, tak by to mělo najít.

**Comment by jahhoo** [comment]
Díky. 

Vyhledávání dle UUID opravdu funguje. Např. https://sdnnt-url.cz/sdnnt/api/v1.0/catalog?query=%22uuid%3Ac2274ba0-f2e3-11e3-a2c6-005056827e51%22&rows=20&page=0
