### ISSUE TITLE
Úprava zobrazení stavu NL

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#206]
Dobrý den,
prosím o následující úpravy v zobrazení stavu NL:

- [x] šedá barva u stavu NL -- > prosim změnit barvu [viz zde](https://github.com/NLCR/SeznamDNNT/issues/160#issuecomment-987867100)

- [x] zkrátit popisek (prosím o nápady p. @Cypzirschova)

**Comment by JanMeritus** [comment]
@CIZKOVAL  dobre je ze barvy jsou dle vyjadreni @pkudela konfigurovatelne. Nicmene stale neni doresena ma zadost o zmenu barevneho skalovani a grafickeho odliseni kde vyuzivaji licence jinou paletu nez stavy. prosim o dokonceni:

https://github.com/NLCR/SeznamDNNT/issues/78#issuecomment-963565416

**Comment by Cypzirschova** [comment]
Zkrácení popisku:

- Plánované vydání díla

Nechala bych asi takto obecně, protože to lze využít, jak po získání licence, tak po vydání díla (odborná lit.), které je tematicky obdobné.

**Comment by pkudela** [comment]
@CIZKOVAL dobry den, chcete zkratit popisek u stavu NL vsude, nebo jen ve facetech? Mam na mysli tooltip atd.

**Comment by CIZKOVAL** [comment]
@pkudela tak kdyz uz, tak prosim vsude, dekuji

**Comment by CIZKOVAL** [comment]
Retest OK...akorát je použito počáteční písmeno velké, na to založím nové issues, aby bylo velké i u ostatních stavů.

![NL_velke pismeno](https://user-images.githubusercontent.com/92719629/153186469-525bca71-12ec-4341-a43a-11b46e11ca20.png)
