### ISSUE TITLE
Registrační formulář - neukládá se Instituce

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#207]
Dobrý den,
v registračním formuláři se přestala ukládat Instituce.

Uživatel vybere při registraci Instituci např. NKP, ale po registraci není instituce uložena.

![instituce_registrace](https://user-images.githubusercontent.com/92719629/145795053-90982963-08df-4b7e-a704-014f6211d933.png)

![instituce_neulozena](https://user-images.githubusercontent.com/92719629/145795080-6f78f445-20ac-4223-b20a-f987d023f102.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, retest NOK, Instituce se neuložila a nelze ji ani změnit.

![retest_instituce](https://user-images.githubusercontent.com/92719629/148192708-3c1237b1-d5c6-4a48-a3aa-f4615098655f.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, instituce už se při registraci ukládá, ale nelze ji změnit (ani změna osobních údajů, ani v rámce administrace).
@pavel-stastny je to v pořádku?

**Comment by pavel-stastny** [comment]
Změněno.  Instituce se nyní ukládá. (V obou případech)

**Comment by CIZKOVAL** [comment]
Retest OK, instituci lze změnit jak při změně osobních údajů, tak při administraci.

![retest_instituce_v2](https://user-images.githubusercontent.com/92719629/152365953-efbdd9c8-a8aa-49eb-b19c-1f2281270b8e.png)
