### ISSUE TITLE
Změna stavu na NL

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#209]
Dobrý den,
při ruční změně stavu na NL zmizí licence, ale v historii je vidět, viz níže.
![NL](https://user-images.githubusercontent.com/86351100/146326844-193eed41-6b6f-46e5-9c63-65662e1a1578.png)
![NL2](https://user-images.githubusercontent.com/86351100/146326852-96bc96d0-0ad2-4e68-9786-c2bca64bd1c5.png)
Cypzirschová

**Comment by Cypzirschova** [comment]
Ještě poznatek - v historii se ukládá původní licence, správně má být dnntt.

**Comment by JanMeritus** [comment]
@CIZKOVAL odpovida to nasim tabulkam?

**Comment by CIZKOVAL** [comment]
@JanMeritus - ano, řádek 16

**Comment by Cypzirschova** [comment]
Nyní je vše funkční, zavírám.
