### ISSUE TITLE
Odhlašování z uživatelského účtu

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#21]
Dobrý den,

při běžné kontrole jsme narazili na problém. Jsou-li dva uživatelé přihlášeni z různých PC, tak je některý z přihlášených uživatelů odhlášen. Stalo se to v případech, kdy PC1 = knihovna a PC2 = knihovna nebo PC1 = knihovna, PC2 = kurator.
Na jednom PC se mi tento problém nepodařilo reprodukovat.

Děkuji za reakci.

**Comment by albertoh** [comment]
Nemuzu to reprodukovat.
Meli jste vybrano "Zustat prihlasen"?
Pri jake prilezitosti se to stalo? 
Kazdopadne, doba prihlaseni je nastavena na 4 h. Mozna vyprsel cas?

**Comment by smallcubes** [comment]
Na problém jsme narazili včera. Bohužel, nemohu přesně popsat - kde přesně se to stalo. (Ale docházelo k tomu třeba i jen pár minut po přihlášení, např. jsem vyhledal knihu -> vybral knihu na vyřazení -> potvrdil -> klikl na moje konto = v tento moment mě to odhlásilo) Možná může přiblížit více @JanMeritus.

**Comment by smallcubes** [comment]
Dobrý den, 

problém stále přetrvává. Možná to není dáno příhlášením dvou účtů, nevím. Nicméně se mi opět stalo, že jsem byl na účtu (knihovna) po 2-3? minutách odhlášen. (bez zaškrtnutí zůstat přihlášen)

**Comment by albertoh** [comment]
Oprava jeste nebyla na serveru :)
Ted uz tam je

**Comment by smallcubes** [comment]
Vypadá v pořádku. Děkuji za vyřízení.
