### ISSUE TITLE
Tooltip informace v přehledu žádostí

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#210]
Dobrý den,
při najetí kurzoru na íčko v přehledu žádostí se zobrazí text s překlepem a napůl v angličtině.

![íčko_CZ](https://user-images.githubusercontent.com/92719629/146342047-25753233-d2ac-43ed-8b3e-02c8fa2c2050.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL @JanMeritus Preklep Verze opraven.   Ta poznamka a pozdavek jsou texty, ktere uzivatel zadava pri posilani zadosit...   => nemohou byt lokalizovany,.

**Comment by CIZKOVAL** [comment]
Tooltip OK
