### ISSUE TITLE
Vyhledávání zohledňuje nesprávné ISSN (pole 022 podpole y)

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#211]
Dobrý den,
narazili jsme na to, že po vyhledání ISSN 1804-7149 se zobrazí záznam, u kterého je v SKC toto ISSN označené jako nesprávné - nachází se v poli **022** v podpoli **y**. Již dříve se tu řešily zrušené identifikáry, tedy ty, které se zapisují do podpole **z** (issue #105 ). Myslím, že ani podpole **y** by se nemělo brát v potaz při vyhledávání. 
Build: 6e6cc2e
![image](https://user-images.githubusercontent.com/43740512/146505193-7e006a9e-cdbe-41a0-b92c-01fce04708e9.png)
![image](https://user-images.githubusercontent.com/43740512/146505300-50b97685-7cbe-47c4-a506-d187e903fcf0.png)

**Comment by JanMeritus** [comment]
@Cypzirschova prosim o vyjadreni FYI @CIZKOVAL

**Comment by Cypzirschova** [comment]
Souhlasím s paní Krutskou. Pole 022 podpole y by mělo být vyloučené. Je to obdobný problém jako u #105.

**Comment by pavel-stastny** [comment]
Pole 022 je z vyhledávání vyřazeno.

**Comment by marketakrutska** [comment]
Otestováno, je to v pořádku. Děkuji za opravu. Issue uzavírám.
