### ISSUE TITLE
Nesrovnalosti při vyhledávání podle ISBN a ISSN

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#212]
Dobrý den,
narazili jsme na nějaké nesrovnalosti při vyhledávání podle ISBN a ISSN. 
Např. ISBN 978-80-200-1809-0. Když hledám podle tohoto ISBN v SKC, najde mi to správný záznam (Bohemia docta). V SDNNT mi to ale najde jinou knihu (O vzniku druhů přírodním výběrem).

Dále např. ISSN 2336-1921. Když to vyhledám v SKC, najde mi to jeden správný výsledek (Biblio Literární noviny), když to ale vyhledám v SDNNT, tak mi to najde 9 různých záznamů, z nichž ani jeden není ten správný. Zjistila jsem, že u těch 9 záznamů má ISSN stejný začátek - 2336. Tak možná je problém v tom. To, že mezi výsledky není ten správný záznam, je nejspíše v pořádku, protože to vycházelo až od roku 2013, takže to ani na SDNNT nemá být. Jde mi ale o to, že se tam zobrazuje 9 jiných záznamů.

Build: 6e6cc2e

**Comment by pavel-stastny** [comment]
@marketakrutska Oba dva záznámy jsou naindexovány ale jsou vyfiltrovány dle kritérií.   V komitu číslo a16c96f486f96ae912e5c754882385d59a16260f jsme implementovali přesnou shodu, tedy pokud bude potřeba hledat přesný identifikátor nebo přípdně název díla, stačí dát vše do uvozovek:  `"978-80-200-1809-0"`  případně `"Bohemia docta"` .

**Comment by marketakrutska** [comment]
Děkuji za info. U vyhledávání názvů mi ty uvozovky samozřejmě dávají smysl. Tedy přijde mi v pořádku, že když zadám název bez uvozovek, tak se mi vyhledají i dokumenty, které mají podobný název a nejedná se o přesnou shodu. 
Ale identifikátorů mi ty uvozovky přijdou zvláštní. Když mám k dispozici přesný identifikátor, třeba to ISSN 2336-1921, tak neočekávám, že se mi podle něho vyhledají dokumenty, které mají podobné ISSN. U vyhledávání podle identifikátorů bych očekávala jen přesnou shodu a nenapadlo by mě dát identifikátor do uvozovek.
Nebo je to tak, že ty záznamy mají v sobě nějak obsažené to ISSN 2336-1921, a proto jsou ve výsledcích vyhledávání?

**Comment by CIZKOVAL** [comment]
Aplikace se chová následovně:

V Souborného katalogu se pod ISBN 978-80-200-1809-0 skrývá dílo: Bohemia docta : k historickým kořenům vědy v českých zemích / Alena Míšková, Martin Franc, Antonín Kostlán (eds.)

- pokud dám ISBN do uvozovek **"978-80-200-1809-0"**, tak se v SDNNT nenajde **žádný záznam** (zřejmě je to tím, že se jedná o dílo z roku 2010, dle všeho v SDNNT neexistuje - nelze vyhledat ani podle názvu)

- pokud uvozovky nepoužiju, tedy: **978-80-200-1809-0**, tak se najde 1 záznam, ale jiný (O vzniku druhů přírodním výběrem...), které má podobné ISBN, nikoliv shodné (978-80-200-1492-4).

**Nyní to tedy funguje tak, že pokud má být přesná shoda, pak musí být vyhledávaný pojem v uvozovkách.**

Koukala jsem např. v aplikaci Kramerius, že tam se také musí použít uvozovky pro vyhledání přesného výrazu.

@JanMeritus můžeš se prosím k tomu vyjádřit?

**Comment by CIZKOVAL** [comment]
Ještě doplním, že v případě ISSN 2336-1921 (záznam s totožným identifikátorem v SDNNT neexistuje) se najde 9 jiných záznamů, protože jsou stejná první čtyři čísla 2336...

**Comment by Cypzirschova** [comment]
Vyzkoušela jsem si zadat ISSN 2336-1921 a srovnala s prvním záznamem, který to nabízí:

Čechy a Řím : dějepisný časopis lidovýchovný
Německý Brod : Kroužek přátel osvěty, 1920-1921

V katalogizačním záznamu není v žádném poli obsažené stejné ISSN. Pouze je shoda u prvních 4 čísel.

To by se asi dít nemělo, když máme jednoznačné identifikátory, tak by to mělo hledat pouze přesnou shodu a podle mě i bez uvozovek. Běžný uživatel by to nemusel dávat do uvozovek.

**Comment by CIZKOVAL** [comment]
Po konzultaci s p. @cypzirschova dodávám, že požadavkem je, aby se u polí ISBN (pole 020) a ISSN (pole 022) hledala pouze přesná shoda (i bez uvozovek). **Podobné identifikátory nemají být vyhledány**.

Dále by se totéž mělo týkat čísla ČNB (pole 015) a systémového čísla (které asi v aplikaci není). V OPACu bývá vždy i systémové číslo např.: https://aleph.nkp.cz/F/?func=direct&doc_number=000234316&local_base=NKC, bývá uvedené úplně dole v MARC je to SYS.

**Comment by zabak** [comment]
Srovnání s portálem knihovny.cz:

Pokud hledám 978-80-200-1809-0 tak mi to vrátí 3 výskyty. V prvním případě se jedná o tu správnou knížku, ve druhých dvou případech jsou to knihy, které tu první citují. Ve všech třech případech jde o nález výskytu ve fulltextu.
Pokud hledám 9788020018090, tak mi to najde konkrétní dokument. Pokud ale zvolím pokročilé hledání v poli ISBN, tak dotaz https://www.knihovny.cz/Search/Results/?bool0%5B%5D=AND&type0%5B%5D=adv_search_isbn_issn_ismn&lookfor0%5B%5D=978-80-200-1809-0&join=AND&searchTypeTemplate=advanced&database=Solr&limit=20&sort=relevance&page=1 - tedy bez uvozovek - mi vrátí jen tu jednu příslušnou knihu. 

Proč to tak je a co by se mělo změnit v SDNNT a v Krameriu: Pokud zadám vyhledávací dotaz, neměly by se pomlčky v něm uvedené měnit na mezery. Měly by se buď zachovat, nebo vypustit bez náhrady. Pokud mám indexovat metadata, měla by se ISBN i ISSN indexovat buď pouze bez pomlček, nebo v obou variantách (s pomlčkami i bez pomlček). Oba zásahy (do indexace i do vyhledávacího dotazu) by měly být navzájem koordinované.

Navrhuji:
- indexovat ISBN a ISSN identifikované v metadatech ve dvou variantách: s pomlčkami a bez pomlček. 
- vyhledávací dotaz buď neupravovat (ponechat v něm pomlčky) nebo pokud je z jiných důvodů nutné pomlčky odstraňovat, tak dané znaky zcela z dotazu odstranit, nenahrazovat je mezerami
- v případě, že uživatel vyhledává specificky ISBN/ISSN, tak pomlčky z dotazu odstranit.

**Comment by JanMeritus** [comment]
@zabak souhlas

Obecne: ISBN/ISSN by melo jet s pomlckami i bez nich

@CIZKOVAL aktualni chovani je vadne - pokud uzivatel zada "neco" musi mu to najit _neco_

**Comment by pavel-stastny** [comment]
Změněno.  Identifikátory nyní nejsou tokenizovány.  U issn a isbn lze hledat varianty i bez pomlček.   U pidů lze hledat bez prefixu uuid.

**Comment by JanMeritus** [comment]
@marketakrutska @zabak  prosim o reakci

**Comment by marketakrutska** [comment]
Děkuji za úpravu! Už to funguje, jak jsem si představovala. Issue zavírám.
