### ISSUE TITLE
Některá díla DNNTT mají v historii licenci DNNTO

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#213]
Dobrý den,
některá díla, která jsou dostupná pouze na terminálech a mají tedy licenci DNNTT jsou v historii zobrazená s licencí DNNTO.
Zdá se, že se jedná se o záznamy, které neprošly standardním workflow, ale byly do seznamu přidány dávkou (batch).

![terminal](https://user-images.githubusercontent.com/92719629/146523429-5667cfb1-e9df-4355-9a5a-5609bd2d4e47.png)

![licence_terminal](https://user-images.githubusercontent.com/92719629/146523604-016824a6-6b2c-4b8f-93e6-1e187c596be9.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Proběhl reindex, prosím o ověření na DEVu

**Comment by CIZKOVAL** [comment]
Na DEV retest OK

![DEV_retest](https://user-images.githubusercontent.com/92719629/159889451-5236dda4-3ee9-4530-b713-9135da577acc.png)

**Comment by Cypzirschova** [comment]
Na testu je to také OK.
![Zelený klíč](https://user-images.githubusercontent.com/86351100/161910230-5034d5fe-b548-4994-bc6b-69f4e2e6db51.png)

**Comment by JanMeritus** [comment]
@CIZKOVAL @Cypzirschova mozne uzavrit?

**Comment by Cypzirschova** [comment]
Za mě ano.

**Comment by CIZKOVAL** [comment]
OK, namatkou jsem zkontrolovala i jina dila.
