### ISSUE TITLE
Verze v EN připomínky

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#214]
Dobrý den,
testovala jsem nyní UI v angličtině a zatím jsem narazila na následující nedostatky:

**1. Úvodní stránka**
1.1 chybí překlad "Kurátorský stav" - **_prelozeno_**
1.2 "show document...." popis by měl vystihovat, že tam jsou všechny dokumenty (v češtině máme "zobrazit **i** dokumenty, které nejsou na seznamu") - _**zmeneno na Also display documents that are not in the list**_
1.3 "show notifcations with notifications" - _**zmeneno na Show records with notifications**_
1.4 řazení dle Relevance je v EN dle "Score" - _**zmeneno na Relevancy**_
1.5 stav A je Clasified, lepší je Included - _**zmeneno na Included**_
1.6 Follow record, lepší watch nebo track - _**zmeneno na watch record**_

**2. Historie** - nejsou přeloženy záložky - _**opraveno**_

**3. Odesílání žádosti** - není přeloženo Poslat - _**opraveno**_

**4. Moje požadavky**
4.1 podivný text v infu - _**opraveno**_
4.2 některé lhůty nejsou přeloženy - _**toto by melo byt take prlozeno**_
4.3 Priorita a Delegovaný kurátor nejsou přeloženy - _**opraveno**_
4.4 Žádost překládána jako application, možná lepší requirement - _**zmeneno**_
4.5 Filtr typ návrhu (Type od design + možnosti filtru) asi lepší Type of proposal a možnosti filtru také jinak nazvat) - _**zmeneno**_
4.6 Priorita nepřeloženo v hlavičce u hl. kurátora - _**opraveno**_

**5. Licence** - VNZ, VNL lépe nazvat - _**upraveno**_

**6. Změna stavu** - _**osadil jsem pro jistotu tooltipy**_

![EN_uvodni_stranka](https://user-images.githubusercontent.com/92719629/146524842-c6f07232-c445-4ccf-b8f9-13ab725159fa.png)

![EN_status_A](https://user-images.githubusercontent.com/92719629/146525534-5a540099-0806-4de1-947d-00f91e452964.png)

![EN_follow](https://user-images.githubusercontent.com/92719629/146525814-863e2a76-eb95-4855-8b27-d4936610da38.png)

![EN_zalozky_historie](https://user-images.githubusercontent.com/92719629/146526022-9adc1f61-05e9-4f06-8d5d-0c4664bd0a7b.png)

![SEND](https://user-images.githubusercontent.com/92719629/146526261-f107cc03-5c18-4118-accc-a36b43545d64.png)

![íčko_EN](https://user-images.githubusercontent.com/92719629/146526355-ab8fbb5b-13bd-44b9-b7d4-c7d8481f6306.png)

![EN_lhuty](https://user-images.githubusercontent.com/92719629/146526665-c96d3388-ee48-4a49-bf27-c8bc8f2c7361.png)

![prio,dele](https://user-images.githubusercontent.com/92719629/146526765-a68ffd27-e659-44cd-86d4-cae377df4f9b.png)

![design_navrh](https://user-images.githubusercontent.com/92719629/146526921-b2685727-f8eb-45e6-8dce-36ec1375f7fe.png)

![EN_priority](https://user-images.githubusercontent.com/92719629/146528142-b3430be4-f669-4264-bc81-d5ae5814e863.png)

![EN_licence](https://user-images.githubusercontent.com/92719629/146527581-84f46bc1-9c13-415e-a6ae-841c1acbeab9.png)

![EN_stavy](https://user-images.githubusercontent.com/92719629/146527757-22e7b867-efd7-4174-b2d4-01875a5fa805.png)

**Comment by JanMeritus** [comment]
@pkudela @pavel-stastny preklady si umime udelat/opravit sami pokud k nim bude nejaky konfigurak

**Comment by pkudela** [comment]
Dobry den,. @CIZKOVAL, prosel jsem to a je to hotovo, viz. me komentare k jednotlivym bodum. Preklady si pak budete mit moznost upravovat v konfiguracnich souborech. Jinak dekuji za screenshoty, takto to se mi jednotlive body lepe identifikuji. Jakmile bude k testovani, pridam label.

**Comment by pkudela** [comment]
@CIZKOVAL prosim, pokud je otestovano, zavrete toto issue, dekuji.

**Comment by CIZKOVAL** [comment]
Dobrý den,
položky z tohoto issue byly opravené a jsou OK. Namátkou jsem našla nějaké maličkosti, ještě to budu projíždět celé v EN, pokud něco najdu založím nové issue. Děkuji
