### ISSUE TITLE
Přidání dalšího distributora do SDNNT

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#215]
Dobrý den,

chtěl bych se pouze zeptat, zdali je možné přidat nějakého distributora (pokud splňuje všechny technické požadavky) např. Brainest.  Pokud ano, tak jakým způsobem je lze přidat?

Předem Vám děkuji za odpověď.
(Označil jsem Vás, jelikož byl tento požadavek označen jako priorita)

**Comment by pavel-stastny** [comment]
Tady to skoncilo na rozdilnem formatu od tohoto konkretniho distributora.  Blizsi info @albertoh

**Comment by smallcubes** [comment]
@pavel-stastny neměl jsem ani tak na mysli konkrétní instituci, jako spíše **funkcionalitu** přidání nějakého distributora. Tedy lze ho přidat? (Pokud vše splňuje)

**Comment by albertoh** [comment]
Dobry den.
Pokud format je uplne stejny jako u jich existujicich (Kosmas, distri.cz) lze pridat.
Pokud ne, musi se napsat tridu pro spracovani formatu.

**Comment by smallcubes** [comment]
@albertoh děkuji moc za odpověď. Mohl byste prosím ještě napsat připadně jak a kde?

**Comment by smallcubes** [comment]
@albertoh poprosil bych o reakci

**Comment by albertoh** [comment]
Moc nerozumim. V kodu existujou tri classy, ktere zpracujou odpovedi stavajich distributoru, a to: 

  distri.cz (albatros) -> XMLImporterDistri.java
  heureka -> XMLImporterHeureka.java
  kosmas -> XMLImporterKosmas

Tyto tridy jsou napsane pro specificky typ komunikace s API distributoru. Pokud novy distributor ma jiny format, jiny API, musi se pridat do kodu novou tridu, a plne programovat je. Nelze to nejak obecne delat. Nemuzu popsat jak napsat tridu pro zpracovani nejaky novy format.
 
 Mozna nerozumim spravne co mate na mysli

**Comment by smallcubes** [comment]
@albertoh chyba je na moji straně. Z nějakého důvodu nefungují importy na sdnnt-test a měl jsem za to, že jsem třeba něco zapomněl nastavit. Nevěděl byste, kde by mohla být chyba, když né v konfiguraci?

**Comment by smallcubes** [comment]
@albertoh moc děkuji vyzkouším

**Comment by smallcubes** [comment]
@JanMeritus přidat nového distributura lze pouze skrze napsání nové Java třídy. Ohledně testování stávajících distributorů viz #248. Issue uzavírám.
