### ISSUE TITLE
Změna konečného stavu NL

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#216]
Dobrý den,

dnes jsme se domluvily s paní Lichtenbergovou, že bychom potřebovaly upravit konečné rozhodnutí stavu NL. Týká se výstupu, kdy dílo bylo vydáno. Stav nebude N, ale A s licencí DNNTT. Vzhledem k obsáhlé problematice je potřeba to upravit, protože nakladatelé nemohou vyřazovat díla jiných nakladatelů ze SDNNT. 

NL → dílo bylo vydáno → A, licence DNNTT

Cypzirschová
@Lichtenbergova

**Comment by Cypzirschova** [comment]
Ještě dodám, že druhý výstup - nakladatel dílo nevydal by byl A, licence DNNTO.

**Comment by pavel-stastny** [comment]
Jo, jo.. je to naimplementovane.  Zároveň je řešené issue #197.  Nyní po uplynutí lhůty 18 měsíců kurátor musí rozhodnout (jinak se žádost neuzavře)  a možnosti jsou  stav A a licence dnntt  (Dřívější volba stavu N) nebo stav A a licence dnnto.

**Comment by CIZKOVAL** [comment]
Retest je blokovany chybou #218

**Comment by Cypzirschova** [comment]
Děkuji za změnu, uzavírám.
