### ISSUE TITLE
Pri plne indexaci SKC byva katalog casto nedostupny 

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#217]

**Comment by smallcubes** [comment]
@pavel-stastny bylo by možné ještě udělat, aby se reindex znovu spustil automaticky? Pokud nastane chyba ohledně nedostupnosti katalogu. 

Konkrétněji:
```
{"indexed": {
  "ellapsed": "0:02:29.902",
  "resumptionToken": "201412292127114999999999999999SKC:SKCM",
  "indexed": 3510,
  "error": "org.apache.http.conn.HttpHostConnectException: Connect to aleph.... [aleph.../....] failed: Connection timed out (Connection timed out)"
}}
```
@JanMeritus

**Comment by smallcubes** [comment]
např. 4x by se to pokusilo o restart a až potom by to spadlo

**Comment by smallcubes** [comment]
@pavel-stastny poprosil bych jenom o potvrzení, případně o vyjádření k výše uvedenému

**Comment by smallcubes** [comment]
@pavel-stastny  Poslední reindex (dntset) se musel restartovat **78x**. Verze (1.1)

@JanMeritus

**Comment by pavel-stastny** [comment]
@smallcubes Uff... tak zde bych určitě doporučoval vyřešit ten síťový problém.: "`Connect to aleph.... [aleph.../....] failed: Connection timed out (Connection timed out)`   On je naimplentováno čekání pro případ, že dostane přímo hlášku o nedostupnosti a nebyl by problém to rozšířit o výjimku, že se nemůže spojit se serverem ale myslím, že by to nic nevyřešilo.   Pokud by aplikace u čtvrtého pokusu čekala 20 minut, tak u 78 pokusech by proces jenom převážně čekal.

**Comment by smallcubes** [comment]
@pavel-stastny děkuji za reakci, ohledně síťového problému a alephu jsem kontaktoval kolegy

**Comment by smallcubes** [comment]
@pavel-stastny 

Dle prosby od @JanMeritus, bylo by možné ještě doimplemenovat následující? Aplikace bude automaticky restartovat reindex, na základě konfigurace. Konfigurace bude obsahovat dva parametry: kolik pokusů o restart se má realizovat a nakonfigurování časových odstupů mezi jednotlivými pokusy o restart.

**Comment by smallcubes** [comment]
@pavel-stastny label `to test` jsem odebral, jelikož k restartu nedochází. Změnila se pouze to, že se vypisuje error, který identifikuje nepřístupnost alephu. Je to tak správně? Pokud ne, opravte mě prosím.

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Dochází.  Respektive reaguje na stránku o vytíženosti SCK viz: 
![image](https://user-images.githubusercontent.com/675753/151664088-e48f405a-b41d-4d53-87a8-973257ac50a9.png)

Počet opakování a doba čekání v jedné iteraci se nastaví následovně: 
 ```
"OAIHavest": {
    "url": "http://aleph.nkp.cz/OAI",
    "numrepeat": 3,
    "seconds": 30
  },
```

Ostatní výjimky. (Síťové, IO a podobně)  nejsou nyní podporovány

**Comment by smallcubes** [comment]
@pavel-stastny děkuji za reakci, vyzkouším znova reindex s nastavením

**Comment by smallcubes** [comment]
Zkoušel jsem reindex příkaz: `/api/index/full` s nastaveným konfiguračním souborem. Index běžel cca. 2 sekundy ("0:02:24.228") a pak to spadlo. V logu se pak objeví řádek `cz.inovatika.sdnnt.index.OAIHarvester.full full FINISHED. Indexed 0:02:24.228 in 3,588`

**Comment by smallcubes** [comment]
@pavel-stastny v případě reindexu DNT setu `.cz/sdnnt/api/index/import_dntset` se mi ještě stalo, že to padá jako minule. Bez restartu.

**Comment by pavel-stastny** [comment]
@smallcubes Jedná se o síťovou výjimku (ConnectionTimeout). Jak jsem psal výše, tato nebyla podporována.  Nicméně přidal jsem  do situací, kdy se může čekat ale doporučil bych, aby se ten connectionTimeout řešil jinak než čekáním.

**Comment by smallcubes** [comment]
@pavel-stastny restart pro `curl http://localhost:18080/sdnnt/api/index/full` funguje, děkuji Vám za implementaci.

**Comment by smallcubes** [comment]
Restart funguje a toto issue uzavírám. Pro budoucí problémy s reindexem se vytvoří případně nové issue. V současné době je existuje jeden viz #317.
