### ISSUE TITLE
Zobrazování záznamů žádost VNL - kurátor

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#218]
Dobrý den,
při zpracování žádosti VNL se mi nezobrazují všechny záznamy, které v žádosti jsou. Konkrétně v této žádosti (viz níže) mají být 3 díla, ale jako kurátor vidím jen 1. Nahoře je i informace, že to má obsahovat 3 díla, ale nic takového nevidím. Nejde ani u toho jediného díla schválit stav nebo ho zamítnout. Vedle díla tři tečky (více) nejde také rozkliknout.
Cypzirschová
![vnl - chyba](https://user-images.githubusercontent.com/86351100/148024462-374480c6-04da-4aea-b42f-c50fafb8922a.png)
![vnl - chyba2](https://user-images.githubusercontent.com/86351100/148024470-2d2b320f-ddef-4de5-9d15-f734accfe2f0.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, ano potvrzuji stejný problém.

**Comment by pavel-stastny** [comment]
@Cypzirschova Týká se všech žádostí typu VNL nebo jenom této konkrétní 

@smallcubes @CIZKOVAL Chtěl bych se podívat přímo na test server. Můžu poprosit o účet pro knihovníka.

**Comment by Cypzirschova** [comment]
@pavel-stastny  Týká se všech žádostí VNL.

**Comment by Cypzirschova** [comment]
@pavel-stastny Abych byla konkrétní, tak všech nových žádostí VNL. U minulých žádostí VNL, to zůstalo, jak bylo dříve nastaveno. Zřejmě se to děje po nasazení nové verze?

**Comment by CIZKOVAL** [comment]
@pavel-stastny ano, týká se to všech nových žádostí VNL. 

Zasílam ucet pro knihovnu na test:

jmeno: knihovna
password: DlouhoKratka2.silnice

**Comment by Cypzirschova** [comment]
Žádosti už fungují správně, uzavírám.
