### ISSUE TITLE
NPA - filtr

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#219]
Dobrý den,
pokud si vyfiltruji kurátorský stav NPA, tak se k němu automaticky přidá i veřejný stav N. Nová díla, která byla schválena jako návrh se stavem jen NPA, tato díla se v tom filtru vůbec nezobrazují.
Cypzirschová
![NPA - filtr](https://user-images.githubusercontent.com/86351100/148026468-9a3ca133-cf91-4067-b08b-4ff0d6e15bca.png)
![NPA - filtr02](https://user-images.githubusercontent.com/86351100/148026508-eac6d71f-3674-4b4d-82d2-ba25ddb8819a.png)

**Comment by CIZKOVAL** [comment]
Dobrý den,
koukala jsem na to a filtr se chová následovně:

1. **N --> NZN --> NPA** 
kurátorský stav=NPA
běžný stav = N

Když se použije filtr NPA, tak se automaticky vyhledají záznamy se stavem N, tj. OK

2. **Nezařazená díla, tj. mimo seznam (bez stavu) --> NZN --> NPA** 
kurátorský stav=NPA
běžný stav = null

Když se použije filtr NPA, tak se tyto záznamy neobjeví - objeví se pouze v případě, kdy je zaškrtnutý checkbox **"zobrazit i díla která jsou mimo seznam"**. To je podle mě v pořádku, protože díla jsou stále mimo seznam a běžný uživatel je v tomto okamžiku vidět nemá.

![NPA_bez stavu](https://user-images.githubusercontent.com/92719629/148033521-07ebed9a-f85a-4c4f-bc90-7b6ec5185056.png)

**Comment by Cypzirschova** [comment]
Máte pravdu, je to tak. Při testování mi to v danou chvíli nedošlo. Uzavírám.
