### ISSUE TITLE
Odkazy do více digitálních knihoven

### ISSUE THREAD

**Issue by annie-cz** [NLCR/SeznamDNNT#222]
Mám spíš dotaz: 

Počítá se s tím, že odkazy na digitální dokument budou do všech digitálních knihoven? Toto bylo několikrát předmětem jednání na PR schůzích a bylo nám tehdy řečeno, že se s tím počítá. Ale raději bych se ujistila, že to tak skutečně je. :)

Na aktuálním starém seznamu toto bohužel moc nefunguje a povětšinou vedou linky v případě společných dat MZK a NK jen do ndk.cz. 

Bylo by vhodné, aby tam byly linky do obou knihoven.

**Comment by pavel-stastny** [comment]
@annie-cz Vše záleží na datech.  Pokud je v SKC okdaz přítomný, tak v aplikaci vidět bude.

**Comment by annie-cz** [comment]
Oka, díky moc! To mi bohatě stačí.

**Comment by annie-cz** [comment]
@pavel-stastny Po dohodě ze schůzky NK x MZK - skutečně se s tímto issue počítá? Pro nás je toto opravdu velmi důležité.

**Comment by smallcubes** [comment]
@pavel-stastny @CIZKOVAL u knihy  „Marie Vobecká : medailonek / Karel Dobeš“ (čnb: cnb000403951) není uveden v záznamu (sdnnt-test) odkaz do ndk.cz, nicméně v katalogu (SKC) v datech odkaz uvedený je.

**Comment by zabak** [comment]
@pavel-stastny upřesním předchozí komentář: u té knihy jsou v SKC odkazy do NK i MZK, ale v SDNNT se nezobrazí ani jeden (a chceme aby se zobrazily oba).

**Comment by pavel-stastny** [comment]
@zabak @annie-cz Ok. Podivame se na to a dame vedet.

**Comment by pavel-stastny** [comment]
@zabak @annie-cz  Zdravím.  Zde je problém duplicity záhnamů v setu DNT a SKC.  Záznám v SKC byl updatován a jdou zde vidět dva linky.  (MZK a NK) 

![image](https://user-images.githubusercontent.com/675753/152947695-d60fa8ee-2306-4252-845b-acf4a9be6687.png)

![image](https://user-images.githubusercontent.com/675753/152947927-03d231b5-1176-489e-8bdc-1093ceaef0d4.png)

Již existující záznamy získané z báze DNT neupdatujeme. Důvody jsme diskutovali v několika issues, naposledy v issue 98.  

Téma se řešilo na poslední schůzce s paní @Lichtenbergova a paní @Cypzirschova.    Až to bude vyřešeno metodicky,  přeneseme to do aplikace.

**Comment by Cypzirschova** [comment]
Po vypnutí báze DNT01 v Aleph, by měly být záznamy přetaženy ze SKC. V tomto případě by tam zřejmě měly být oba odkazy do DK. Aplikace SDNNT neslouží jako místo, odkud by čtenáři měli přistupovat do digitálních knihoven. Pro vstup do DK slouží stránky https://dnnt.cz/. Aplikace má primárně sloužit pro nakladatele, knihovny a pro vyřízení agendy SDNNT. Nicméně aktualizace záznamů v SDNNT oproti SKC je žádoucí (do SDNNT se promítnou opravy, aktualizace životních dat autorů…).

V issue 98 se řešil jiný problém, připojování dalších podobných záznamů ze SKC k záznamu v SDNNT. Pokud má knihovna záznam v SKC a v SDNNT je jiný záznam pro dílo (tzn. v SKC duplicita), tak by knihovna měla požádat o deduplikaci. Aktualizace záznamů v SDNNT dle SKC (1:1) je naopak v pořádku. Do SDNNT se dostanou aktualizované údaje (např. dohledaná životní data autorů). 
@Lichtenbergova

**Comment by CIZKOVAL** [comment]
@pavel-stastny Dobrý den, prosím o informaci, v jakém stavu je toto issue?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Já měl za to, že jsem to popsal v mém komentáři výše.

**Comment by CIZKOVAL** [comment]
@pavel-stastny - omlouvám se, nevšimla jsem si komentáře výše. Chci se tedy zeptat, **odkaz na digitální dokument se objeví pouze pokud se záznam v SKC updatuje - toto se nezobrazí automaticky?**

Např. dílo číslo nár. biblio: cnb000688743 Dieta při otylosti je také v **NK a MZK** a **nevidím tam žádný odkaz na digitální dokument.**

![odkazy](https://user-images.githubusercontent.com/92719629/156533455-d936fc6b-d61e-41a2-9e53-ee1ca6cd084b.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Musí se provést update SKC jinak to nejde.   Ten záznam ze SKC má timestamp: `2021-12-07T23:27:50.166Z` pokud linky přibyly až po té, pak v indexu nejsou.

**Comment by JanMeritus** [comment]
@CIZKOVAL @smallcubes jaky je zde stav, muze byt @annie-cz spokojena?

**Comment by CIZKOVAL** [comment]
Ted jsem koukala na to konkrétní dílo _Dieta při otylosti_.

Jedná se zde o duplicitu - vyskytuje se 1x mimo seznam (zdroj báze SKC) a 1x v seznamu SDNNT (zdroj báze DNT).

Ten záznam, který není na seznamu má odkazy do NDK i MZK, ten který je na seznamu má odkaz pouze do NDK.

![SKC_odkaz](https://user-images.githubusercontent.com/92719629/161233797-51793076-be9f-4c09-a722-038d3e142635.png)

![DNT_odkaz](https://user-images.githubusercontent.com/92719629/161233815-b48dfbe1-a4bd-4892-9d31-7bd97d4904ad.png)

**Comment by annie-cz** [comment]
Ahoj, spokojená moc nejsem. Hned první dokument, co jsem si otevřela, odkazuje pouze na NK. Dokument má přitom klasicky NK i MZK. Někde vám tam asi něco ještě hapruje nebo nevím.

Viz:

![image](https://user-images.githubusercontent.com/43028501/162143679-7978373c-f909-43e8-844f-b9777ac1e5d5.png)

https://sdnnt-test.nkp.cz/sdnnt/search?q=franti%C5%A1ek%20ronovsk%C3%BD&page=0

**Comment by annie-cz** [comment]
Druhý náhodně rozkliknutý dokument ... stejný případ.

![image](https://user-images.githubusercontent.com/43028501/162144609-e5b00c1c-2d58-4b85-92b6-db7cbc296f98.png)

https://sdnnt-test.nkp.cz/sdnnt/search?dntstav=A&rows=100&page=0

**Comment by CIZKOVAL** [comment]
Podívala jsem se na oba dokumenty.

_František Ronovský: obrazy, kresby 1971-1981..._
- vyskytuje se jak záznam z báze DNT (na seznamu A online), tak záznam z báze SKC (mimo seznam). Oba dokumenty mají odkaz pouze do krameria NKP. V SKC vidím, že v poli 911 je uvedená pouze digitalizace v NKP. V MZK je to ale zdigitalizované také, ale obávám se, že se berou data z aleph, tudíž data se přebrala správně.

_Miloslav Holý: zátiší a květiny..._
- vyskytuje se jak záznam z báze DNT (na seznamu A online), tak záznam z báze SKC (mimo seznam). Dokument z DNT má odkaz pouze do krameria NKP, dokument ze SKC má odkaz do krameria NKP i MZK.. V SKC vidím, že v poli 911 jsou uvedeny digitalizace jak v NKP, tak v MZK. Toto je stejný případ jako mnou uváděné dílo _Dieta při otylosti_.

@pavel-stastny, @JanMeritus , @Cypzirschova - předpokládám, že se vyřeší v momentě kdy budou vyřešené duplicity, viz issue #326 

![911_NK](https://user-images.githubusercontent.com/92719629/162153367-e89df046-b9f3-4b4e-87a1-0a49f9d21ec8.png)

![911_Holy](https://user-images.githubusercontent.com/92719629/162153391-cf0e0360-ed09-4cff-b24b-dd5af91eeea2.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ano, je to tak.  A porad plati ten muj komentar vyse, tedy nejdrive se to musi vyresit metodicky..

**Comment by annie-cz** [comment]
Jak to prosím vypadá? 

Testuji poslední verzi SDNNT dle domluvy z emailu a první, co jsem našla, je dokument, který opět směřuje pouze do NK.

Vidím, že v #384 je napsáno, že "je potřeba nadefinovat jak zacházet se záznamy z SCK. Je to na domluvě mezi pani @Lichtengergova a pan Záhořík."

V jakém stavu to prosím je? Ten komentář tam visí od 29. dubna, což je už nějaká doba. Došlo prosím k nějaké domluvě? Bude se SDNNT nasazovat bez vyřešení tohoto problému?

**Comment by annie-cz** [comment]
![image](https://user-images.githubusercontent.com/43028501/174972697-8fcb7f52-cf9d-46d8-958b-5e3bf69d2078.png)

https://www.digitalniknihovna.cz/mzk/uuid/uuid:ea26af90-341c-11e4-8e0d-005056827e51
https://kramerius5.nkp.cz/uuid/uuid:abb6d2c0-3dc3-11e4-8f33-5ef3fc9ae867

**Comment by CIZKOVAL** [comment]
Dobrý den,
vypadá to, že jste měla "štěstí" na dokument, který se do SDNNT neměl vůbec dostat - máme tam problém cca u 50 záznamů, které nyní prověřujeme - podíváme se i na tento a ještě dám vědět.

Jinak došlo k napárování záznamů z báze DNT s těmi ze SKC. Záznamy z DNT mají nyní kurátorský stav D a ten záznam vidí pouze kurátor a hlavní kurátor. Ostatní role už vidí pouze jeho dvojče ze SKC a tam jsou správné odkazy.

Můžete se podívat na ostatní záznamy z tohoto issue, zkontrolovala jsem je všechny a je to tam v pořádku:

cnb000403951 Marie Vobecká : medailonek / Karel Dobeš

oai:aleph-nkp.cz:SKC01-003801702 Miloslav Holý : zátiší a květiny : Svaz českých výtvarných umělců - Špálova galerie, Praha 1973 - Oblastní galerie Liberec, 1974 - Galerie výtvarného umění Gottwaldov, 1974 / [katalog výstavy Jiří Mašín, Miloslav Holý]

cnb000688743 Dieta při otylosti / Jiří Šonka, Marie Přibylová-Čárková a Marie Večeřová

 
![odkazy_dig](https://user-images.githubusercontent.com/92719629/175019931-fb88f8be-b195-4a1e-be97-a3dfa4720111.png)

**Comment by annie-cz** [comment]
Zdravím, díky za informaci. Nicméně na SDNNT ten problém obecně pořád je, nejde o jednotlivé dokumenty. Opět, otevřu SDNNT, vyberu namátkou první dva náhodné dokumenty po sobě z první stránky a je to pořád to stejné.

![image](https://user-images.githubusercontent.com/43028501/178928428-8e613453-5f70-4e5a-bcae-0e0ba99df306.png)

BINTEROVÁ, Zdeňka. Dějiny Chomutova. Chomutov: Městský úřad, 1997. ISBN 80-238-1756-6. Dostupné také z: https://digitalniknihovna.cz/mzk/uuid/uuid:621a7170-1c7d-11e8-a0cf-005056827e52

JANATA, Oldřich a Josef BRÁZDA. Děvčata v modrém: škola pozemních specialistů letectva Žamberk. Praha: ISV, 1997. ISBN 80-85866-25-0. Dostupné také z: https://digitalniknihovna.cz/mzk/uuid/uuid:a6413180-f2bc-11e2-9923-005056827e52

**Comment by CIZKOVAL** [comment]
@annie-cz prosím napište mi, v jakém prostředí SDNNT se na záznamy díváte a jejich ččnb nebo jiné ID ze SDNNT.

Já tam vidím toto:

![devcata](https://user-images.githubusercontent.com/92719629/179393750-9739f965-7db3-4df9-98bf-88a030a12001.png)
![dějiny](https://user-images.githubusercontent.com/92719629/179393756-efc4c49b-d11e-40e9-9377-5755e45d2449.png)

**Comment by zabak** [comment]
@CIZKOVAL  my na to koukali na sdnnt.nkp.cz. Verze na testu je tedy v pořádku z toho hlediska, že to ukazuje odkazy do více digitálních knihoven. Problém je v tom, co to ukazuje: 

Ani link do MZK ani do NK není správně: pro MZK by mělo být digitalniknihovna.cz/mzk, pro NK ndk.cz. Ten třetí link v prvním příkladu je ve skutečnosti link na obálku a nemá tam co dělat. Vzhledem k tomu, že jde o data ze SK, tak předpokládám, že by se měly ignorovat odkazy v polích 856 a brát jen ty z polí 911. Ty by navíc měly být transformovány, protože ani SK neodkazuje na URL co je v záznamu. Sice v obou případech (NK i MZK) funguje přesměrování, ale může to mást uživatele, když kliká na úplně jiný link než na jaký je následně přesměrován.

**Comment by CIZKOVAL** [comment]
Dobře, rozumím - původní problém, který komentovala @annie-cz se týkal produkčního prostředí, kde to nemohlo být správně, protože nová verze SDNNT je nasazena až od neděle 17.7. 2022. Já jsem záznamy ověřovala na **testovacím prostředí** kde to bylo **v pořádku v tom smyslu, že se odkazovalo do více digitálních knihoven, včetně MZK**, což byl původní problém v tomto issue. 

Co se týče chyby ve stávajících odkazech, ať už na testovacím nebo na produkčním prostředí, tak se tedy jedná o:

- zobrazení odkazu (nemá být zobrazené formou URL, ale odkazem na webovou stránku knihovny)
- úprava logiky přebíraní odkazů ze SKC 

Pokud problém chápu správně, tak navrhuji zadat nové issue a toto uzavřít. @zabak @annie-cz Souhlasíte?

**Comment by annie-cz** [comment]
Používala jsem prostředí sdnnt.nkp.cz, nicméně teď už to tam vidím také. Tj. asi je to tedy v rámci tohoto issue v pořádku. Díky!

Zobrazování a pár dalších věcí mi nepřijde ideální, ale to je kdyžtak na jiné issue. Tady asi zavřít můžeme.

**Comment by annie-cz** [comment]
Tak kolegyně přeci jen ještě něco našla ...

> Identifikátory záznamu: Historie Svorné sedmy / Jaroslav Foglar
> Aleph identifier oai:aleph-nkp.cz:SKC01-000660576
> Číslo nár.bibl. cnb000806231
> Interní identifikátor 9cffa774b8fc4d892be62d2e5d1eb435
> 
> Identifikátory záznamu: Život v poklusu / Jaroslav Foglar
> Aleph identifier oai:aleph-nkp.cz:SKC01-005856182
> Číslo nár.bibl. cnb002497326
> ISBN 80-900050-7-1,80-900150-6-9
> Interní identifikátor aa4787e1139ef82a0c163b08823804fb
> 
> V případě vícesvazkových děl (jako je třeba ten Život v poklusu) jsou navíc rozbité i linky do NKP, hlásí to Stránka nenalezena.

**Comment by CIZKOVAL** [comment]
@annie-cz můžeme zde uzavřít? Tento [problém](https://github.com/NLCR/SeznamDNNT/issues/222#issuecomment-1192454372) se řešil v jiném issue, které je již zavřené.

**Comment by zabak** [comment]
Odpovím za @annie-cz: můžeme uzavřít - linky z výše uvedeného Života v poklusu fungují, pokud je nějaký další problém, založíme nové issue.
