### ISSUE TITLE
Vyřizování žádostí - odůvodnění u jednotlivých děl

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#223]
Dobrý den,

dnes jsem narazila na jeden problém, který se týká vyřizování žádostí. U jednotlivých děl kurátor píše odůvodnění schválení/zamítnutí změny. Pokud kurátor označí celou žádost jako zpracovanou, tak komentář/odůvodnění zmizí a není dohledatelný. Zkoušela jsem se dívat i do profilu knihovny, zda alespoň druhá strana vidí odůvodnění a není tomu tak. 

Toto je velmi problematické, protože zrovna včera jsem vyřizovala několik žádostí od jednoho nakladatele a do odůvodnění jsem mu popisovala, proč jsem tak rozhodla.

Posílám níže výňatek z e-mailové komunikace s paní Čížkovou, jaké jsou nyní možnosti v aplikaci:

- Pokud kurátor schválí dílo v žádosti, tak píše komentář a vzhledem k tomu, že jde o schválení tak se změní i stav díla a tím pádem je v historii kurátorského stavu vidět tento komentář (níže obrázek).

- Pokud se ale dílo v žádosti zamítne, tak se píše odůvodnění – protože ale u díla zůstává zachován původní stav, tak se nezapisuje do historie kurátorského stavu nic a tím pádem odůvodnění nikde není.

Schváleno:
![schvaleno_komentar](https://user-images.githubusercontent.com/86351100/149118403-397fd144-b588-4f7b-b1f8-3520c38ebc81.png)

Testování:
![komentář](https://user-images.githubusercontent.com/86351100/149118600-7e64d6e3-95e3-4981-9fd6-277728b65500.png)
![komentář1](https://user-images.githubusercontent.com/86351100/149118620-a356839a-f37c-4af7-b8de-4356402b7f21.png)
![komentář2](https://user-images.githubusercontent.com/86351100/149118628-2c90e3d7-ff24-49f7-8178-45beae9442ee.png)

Prosím o vyřešení tohoto problému. Ty komentáře by v žádostech měly být zachovány.
Cypzirschová
@CIZKOVAL @Lichtenbergova @JanMeritus

**Comment by pavel-stastny** [comment]
@Cypzirschova A ten tooltip je dostačující ?  Resp. všiml jsem si, že po zpracování mizela ikona `"schváleno"` a `"zamítnuto"` tak jsem to opravil. Nicméně teď (v chytané verzi) je to vidět jenom v tooltipu nad ikonou `"zamítnuto"` ?

**Comment by Cypzirschova** [comment]
Za mě asi ano. Určitě bude stačit, když tam zůstane ten komentář. Je to zpětná vazba i pro druhou stranu, proč se tak rozhodlo.
Nyní to úplně celé zmizí. Pokud si bude nakladatel kontrolovat vyřízené žádosti a bude chtít vědět, proč se zamítlo, tak se to z komentáře dozví. Je to důležité i pro kurátory. Pokud by kurátor rozhodl zamítnout změnu u díla, tak se to dá vždy dohledat v těch žádostech, z jakého důvodu tak učinil.

**Comment by CIZKOVAL** [comment]
Ještě jsem si všimla, že v tooltipu je při schvalování i zamítání pole "Odůvodnění". 
"Odůvodnění" se používá u zamítnutých žádostí, "Komentář" u schválených. Nešlo by toto sjednotit? Aby tooltip odpovídal názvům polí?

**Comment by pavel-stastny** [comment]
Ok.

**Comment by Cypzirschova** [comment]
Po testování, OK. Uzavírám.
