### ISSUE TITLE
Záznam z katalogu - na proklik nereaguje

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#224]
Pokud stisknu odkaz na "Záznam z katalogu" - ne vždy vyskočí nové okno do Alephu. V některých případech jsem na to musel opakovaně klikat a Aleph se otevřel například až na 7. pokus.

**Comment by pavel-stastny** [comment]
@jahhoo To je otázka response z Alephu.

**Comment by jahhoo** [comment]
Tomu nerozumím. Pokud nevyskočí vůbec nové okno, předpokládám, že vůbec nedojde k požadavku na Aleph. Chápu to, že okno vyskočí a Aleph "oděpíše", že systém je přetížen. Ale tady evidentně nereaguje proklik.
Ani síťová komunikace v prohlížeči nenaznačuje žádnou snahu o návázání komunikace...

**Comment by pavel-stastny** [comment]
@jahhoo Už to vidím. Nedařilo se mi to nasimulovat.  Ten proklik funguje vždy  (je to standardní a href) ale je zabalen v elementu button. Když se najede jenom na tlačítko, budí to dojem že se kliknulo.   Je to stejné i u odkazu na digitální knihovnu.

**Comment by jahhoo** [comment]
@pavel-stastny půjde prosím dodělat onclick i na celé tlačítko? U identifikátoru to funguje i mimo oblast textu, tak aby to bylo u všeho stejně..
