### ISSUE TITLE
Filtrovací fasety - zvýraznění

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#225]
Fasety pro filtrování by se měly zvýraznit při najetí myši. Například podobně jako je to Krameriovi. Takto není pro nové uživatele zřejmé, že se jedná o klikací prvek.

**Comment by pavel-stastny** [comment]
Hmm.. nemyslim si ale  poprosil o nazor @pkudela

**Comment by jahhoo** [comment]
@pkudela prosím o vyjádření

**Comment by pkudela** [comment]
Bude dostupne a k otestovani v pristi verzi.

**Comment by JanMeritus** [comment]
@pkudela @CIZKOVAL jaky je zde stav, je mozne uzavrit?

**Comment by CIZKOVAL** [comment]
Fasety se při najetí myší podbarví, uzavírám.

![podbarveni](https://user-images.githubusercontent.com/92719629/161235618-42aac372-6b63-4080-9050-85a5d0e333ac.png)
