### ISSUE TITLE
Více u záznamů - pro nepřihlášené uživatele

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#226]
Rozklikávací nabídka "Více" u každého záznamu by se měla zobrazovat i nepřihlášeným uživatelům. Uživatelé by měli mít možnost odkazu do Krameria, Alephu a měli by vidět identifikátory. Historie změn by pro ně neměla být dále přístupná.

@JanMeritus souhlas?

**Comment by JanMeritus** [comment]
urcite ano. Aplikace by pro uzivatele v ramci zmen verejnych stavu a odkazu mela byt pristupna.

**Comment by pavel-stastny** [comment]
@jahhoo @JanMeritus Zde bych urcite jeste uvital shodu jeste s pani @Cypzirschova a pani @Lichtenbergova

**Comment by Cypzirschova** [comment]
Za mě to tak může být. Ještě čekám na odpověď od paní Lichtenbergové.

**Comment by Cypzirschova** [comment]
Mám potvrzeno, že to takto může být. @pavel-stastny @JanMeritus

**Comment by jahhoo** [comment]
@pavel-stastny kdy bude prosím implementace? Pro nás je toto dost zásadní..

**Comment by jahhoo** [comment]
Díky.

**Comment by CIZKOVAL** [comment]
Dobrý den,
nepřihlášený uživatel má v nabídce "Více" odkaz do Krameria a Identifikátory, ale **nevidí odkaz do Aleph (SKC)**. Dle mě by měl mít dále možnost vidět **granuralitu**, souhlasíte, paní @Cypzirschova?

**Nepřihlášený uživatel:**
![neregistr](https://user-images.githubusercontent.com/92719629/163168930-3c007b03-a265-4548-9e66-4278228ddcf0.png)

**Přihlášený uživatel - kurátor:**
![neprihlaseny](https://user-images.githubusercontent.com/92719629/163168951-fa6c9836-5270-481e-8a6b-22778513c7df.png)

**Comment by Cypzirschova** [comment]
S tou granularitou není problém, ale nejsem si teď jistá s tím odkazem do SKC, protože se na jedné schůzce řešily licence. Tady bych poprosila o názor @JanMeritus @Lichtenbergova. (#314)

**Comment by pavel-stastny** [comment]
@Cypzirschova @CIZKOVAL Granularita přidána.

**Comment by CIZKOVAL** [comment]
@pavel-stastny na schůzce s paní @lichtenbergova bylo dohodnuto, že nepřihlášený uživatel uvidí pouze Identifikátor a odkaz do Krameriů. Omlouvám se - granuralitu mu tedy prosím odeberte. Děkuji.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Opet odebrano

**Comment by CIZKOVAL** [comment]
Retest OK

![NEPRIHLASENY_U](https://user-images.githubusercontent.com/92719629/164651838-9f8b7fe0-a93b-47de-90f4-47dc1b187e9e.png)
