### ISSUE TITLE
Aplikace není optimalizovaná pro mobilní zařízení

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#227]
Aplikace není absolutně optimalizovaná pro mobilní zařízení jako je v dnešní době standardem.

**Comment by jahhoo** [comment]
![Snímek z 2022-01-12 19-09-35](https://user-images.githubusercontent.com/33415849/149197866-d80812bb-544c-4980-a90c-6fe52ccd40eb.png)
![Snímek z 2022-01-12 19-09-47](https://user-images.githubusercontent.com/33415849/149197863-a76296f5-0b5e-49a3-b6a1-12006795c316.png)
![Snímek z 2022-01-12 19-10-05](https://user-images.githubusercontent.com/33415849/149197861-f6d71e06-c9f1-4b7b-9868-02c6a9b29a43.png)
![Snímek z 2022-01-12 19-10-11](https://user-images.githubusercontent.com/33415849/149197859-ff6321f2-12fb-4001-8952-c2e482478741.png)
![Snímek z 2022-01-12 19-11-02](https://user-images.githubusercontent.com/33415849/149197856-9c73dfe2-85b7-4397-9425-e06ac0ac95eb.png)
![Snímek z 2022-01-12 19-11-13](https://user-images.githubusercontent.com/33415849/149197835-d24ba80e-ac0c-4ec9-9c0d-2735e5a1fed9.png)

**Comment by pkudela** [comment]
Dobry den @jahhoo, jiz nekolikrat jsem na schuzkach rikal, ze nebudu optimalizovat aplikaci pro mobilni zarizeni do doby, nez bude aplikace ve "finalnim" stavu, alespon co se tyce designu. Za posledni dobu se UI znacne prekopalo vcetne layoutu jednotlivych component, pribylo se spousta novych veci, takze ladit aplikaci pro responsivni chovani by bylo kontraproduktivni. Az budeme vedet, ze se prvni faze vyvoje blizi ke konci, tak pak se do toho pustime. Dekuji za pochopeni.

**Comment by jahhoo** [comment]
Dobrý den,
já měl za to, že se již jedná o finální verzi (v1.0) a je požadována akceptace.

@JanMeritus

**Comment by pkudela** [comment]
Dobry den, ja po pravde receno nevim, porad se tam neco upravuje a pridava. Ted s kolegou zrovna budeme resit pridani moznosti hromadne upravy a to bude vyzadovat vymyslet to nejak smysluplne, aby se to tam veslo a prave i s ohledem na to, aby pak bylo mozne zohlednit chovani pro mobilni zarizeni. Kazdopadne abych Vas neuvedl v omyl, domluvim se s kolegou a dam Vam vedet.

**Comment by jahhoo** [comment]
@pkudela pro nás je optimalizace dost zásadní - bez ní nemůžete dodání aplikace akceptovat. Máte prosím už časový odhad, kdy bude provedena?

**Comment by pkudela** [comment]
![image](https://user-images.githubusercontent.com/16591052/151707017-75ede99e-a7ab-49a7-b86f-be35049ead25.png)

![image](https://user-images.githubusercontent.com/16591052/151707037-7096653e-27b2-4076-9db4-10b95ec11882.png)

![image](https://user-images.githubusercontent.com/16591052/151707050-a21a8601-5296-4634-ac61-9e172e518fc3.png)

![image](https://user-images.githubusercontent.com/16591052/151707066-073c4f98-1c03-452f-b186-eefa95224bfe.png)

![image](https://user-images.githubusercontent.com/16591052/151707078-139a1a16-8cf6-4edf-9d58-f73a99c2411b.png)

![image](https://user-images.githubusercontent.com/16591052/151707102-1ac102ee-d98d-440f-82e1-01631c0f8065.png)

![image](https://user-images.githubusercontent.com/16591052/151707127-2a68cf2c-bd1a-41dc-9844-72cc44baf356.png)

![image](https://user-images.githubusercontent.com/16591052/151707158-2a33f6bf-f229-486f-a7dc-81abd3979d2e.png)

![image](https://user-images.githubusercontent.com/16591052/151707208-d93c0647-e247-4582-b19a-55da7cb8a884.png)

![image](https://user-images.githubusercontent.com/16591052/151707235-dee2d36c-1140-4119-bca4-dac2c224acd3.png)

![image](https://user-images.githubusercontent.com/16591052/151707289-52a808f5-147f-42ec-a523-3cc9e55c3d6d.png)

![image](https://user-images.githubusercontent.com/16591052/151707314-b2a0423b-f74d-45f9-a915-59651da73bfc.png)

![image](https://user-images.githubusercontent.com/16591052/151707321-f612a6de-5e71-4b06-8f10-7c68ea0375aa.png)

![image](https://user-images.githubusercontent.com/16591052/151707338-a0d050fc-02a5-4b8f-b790-3f32072f145f.png)

**Comment by jahhoo** [comment]
@pkudela Prosím o dodělání optimalizace tabulek

![Snímek z 2022-02-02 17-36-02](https://user-images.githubusercontent.com/33415849/152197141-da457024-2210-4a1e-a1b8-f48b101dfc2b.png)
![Snímek z 2022-02-02 17-35-53](https://user-images.githubusercontent.com/33415849/152197151-ada9f893-fa44-47ab-957b-23cfe2f969b0.png)

Pokud se tabulka nevejde na obrazovku, měla by se dle moderních trendů zobrazit po řádcích - např.:
![Snímek z 2022-02-02 17-40-22](https://user-images.githubusercontent.com/33415849/152197552-3a94022f-c169-4375-a3c5-726c6d0eff4d.png)

**Comment by pkudela** [comment]
Moderni trendy tady posledni dobou docela litaji, stejne jako s tlacitkem zpet :-) Otazka je, co je pro danou tabulku vhodne, jestli zmenit pri nejakem breakpointu layout tabulky a pak hodne vertikalne scrollovat, nebo naopak nechat horizontalne scrollovat v ramci containeru tabulky. Tak jako tak jsem vyhovel a udelal zmenu layoutu, v tomto pripade to asi dava smysl viz. screenshot nize. Udelal jsem to i pro tabulku importu. Jakmile bude k testovani, priradim label.

![image](https://user-images.githubusercontent.com/16591052/152333754-bfb861b2-3a25-470b-83d6-6e5b262512bd.png)

![image](https://user-images.githubusercontent.com/16591052/152333918-65f5b8a0-f8d6-4bd5-a154-bbc0a87a9727.png)

**Comment by smallcubes** [comment]
@pkudela bylo by možné přemístit vyhledávaní pod hlavní lištu s logem SDNNT a logo zmenšit. Něco na způsob jako tady: https://www.onb.ac.at/. Nejdříve bych, ale poprosil o schválení. + By v té liště mohla být i ikonka filtru, ale to se tam možná nevleze @CIZKOVAL @Cypzirschova @JanMeritus

**Comment by Cypzirschova** [comment]
@smallcubes Logo mi nepřijde velké.

**Comment by smallcubes** [comment]
@Cypzirschova já to spíše myslel v případě, kdyby tam přibyla lišta s vyhledáváním pod tím logem

**Comment by Cypzirschova** [comment]
@smallcubes Já bych to asi nechala takhle, jak je, ale ať se ještě vyjádří i ostatní.

**Comment by Cypzirschova** [comment]
Spíš mi tam chybí nějaká šipka, která mě hodí na začátek, když jsem úplně dole.

**Comment by pavel-stastny** [comment]
@smallcubes Tady bych trošku poprosil o selský rozum.  Konkrétně u obrazovek pro administrátora (Povolení API) nebo jenom pro kurátory (Grafy).    Neočekávám a myslím, že to neočekává ani NKP, že se bude aplikace administrovat z mobilu.  Jasně, šlo by to řešit ale poměr cena/výkon a dosažený užitek je naprosto minimální.

Stejně tomu tak je u grafů pro kurátora(y) . Jedná se o grafickou informaci pro kurátora pouze na straně NKP.. Nečekal bych, že kurátor bude fungovat přes mobil.

Myslím, že mě ještě doplní @pkudela

**Comment by pkudela** [comment]
Ano, jiz na zacatku jsem chtel zduraznit, ze se jedna o webovou aplikaci, nikoliv mobilni aplikaci, cili muzeme ocekavat nejake rozumne zobrazeni a razeni prvku pro mobilni zarizeni, ale urcite ne tak dokonale, jak to byva u mobilnich zarizeni. Take bychom meli brat v potaz rozliseni konkretniho mobilniho zarizeni, zkratka responsivni chovani konkretni webove aplikace ma take sve hranice a melo by slouzit predevsim uzivatelum a nikoliv administratorum, jak napsal @pavel-stastny , to uz by se muselo jednat o uplne jiny nastroj.

**Comment by smallcubes** [comment]
@pavel-stastny @pkudela dobře pokud je to za ostatní v pořádku @CIZKOVAL @JanMeritus @Cypzirschova, tak za mě taky

**Comment by JanMeritus** [comment]
Administrativni funkce nemusi byt optimalizovany pro mobilni zarizeni,
narozdil od vsech uzivatelskych obrazovek

Dňa št 17. 2. 2022, 14:18 smallcubes ***@***.***> napísal(a):

**Comment by smallcubes** [comment]
@JanMeritus @Cypzirschova @pkudela @pavel-stastny dle domluvy ze schůzky 21/2/2022 nemusí být prostředí být optimalizované pro: administrátora a kurátora

**Comment by jahhoo** [comment]
Díky, vypadá to dobře. 

Jen si říkám, zda by nebylo lepší - skrývat při vyhledávání filtrování - pod nějaké tlačítko. Většina webů to tak má. Pokud nyní zadám nějaký požadavek do vyhledávání, musím hodně scroolovat dolů než narazím na požadované dílo...
@JanMeritus

**Comment by jahhoo** [comment]
@pkudela po dohodě s @JanMeritus prosím o upravení pro mobilní zařízení - při vyhledávání díla zobrazit neaktivní filtry zabalené (viz. screen)

![Snímek z 2022-03-09 14-49-13](https://user-images.githubusercontent.com/33415849/157454621-343b0e94-b6bf-45da-b648-9882c6a2b1c5.png)

**Comment by pkudela** [comment]
Hotovo, pri breakpointu kdy se facety roztahnou na 100% delky obrazovky vracim pro atribut "expanded" false, takze vsechny facety jsou zabalene.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/16591052/157706320-5e47f08a-2bb9-45ec-8c74-7250f6ddd7ef.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/16591052/157706380-6a80d16c-35e2-4c7d-8184-8b3d2c31e559.png">

**Comment by pkudela** [comment]
@jahhoo jakmile bude nasazeno na testu, oznacim.

**Comment by JanMeritus** [comment]
@pkudela @smallcubes jaky je zde stav?

**Comment by smallcubes** [comment]
Filtry se hezky schovají, jen by bylo ještě možná dobré nějak uspořádat informace o stránce, poču položek atd. viz obrázek níže

![obrazek](https://user-images.githubusercontent.com/78028909/161227974-b66d53a6-c50d-40f1-8a39-1e6c785bd5ad.png)

**Comment by pkudela** [comment]
Dobry den, toto je jedna komponenta angular materialu a s tim vice neudelam, zarovnani pod sebe neni nic proti nicemu, pro uzivatele stale viditelne a dostupne.

**Comment by smallcubes** [comment]
Pokud se s tím nedá nic dělat, tak asi v pořádku. Nenapadá-li někoho ještě něco jiného @jahhoo @JanMeritus @Cypzirschova @CIZKOVAL, issue bych uzavřel.

**Comment by JanMeritus** [comment]
@smallcubes prosim na tuto vec vytvorit enhancement RFC pozadavek s priznakem UI a wontfix, zde odkazat a uzavrit

**Comment by smallcubes** [comment]
@JanMeritus požadavek byl přenesen do issue #360. Issue uzavírám.
