### ISSUE TITLE
Problém s registrací právnické osoby

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#229]
Při registraci jako "Právnická osoba" mi systém neustále vrací chybovou hlášku "Chyba při registraci uživatele." "Špatné jméno". Takže profil nejde zaregistrovat (viz. screen).

Nehledě na to, že text "Špatné jméno" se zobrazuje místo klasického tlačítka "Zavřít" / "X"

![Snímek z 2022-01-12 15-59-33](https://user-images.githubusercontent.com/33415849/149165379-ca5dff7b-9d20-4e55-9b2b-8c2db3028a8c.png)

**Comment by pavel-stastny** [comment]
Jiz reseno v ramci issue #220
