### ISSUE TITLE
Nefunční odkaz do Alephu

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#23]
Dobrý den,

záznam: _"Zima v ráji" (celé: "Zima v ráji / Harry Harrison ; překlad: Martin Janda", ISBN: 80-902704-7-6)_  je uvedeno dvakrát a první výsledek nemá funkční odkaz na: _"Záznam z katalogu"_
Stejně tak i: _"Pravda o zkáze Sodomy"  (celé: "Pravda o zkáze Sodomy / Ivan Kříž", ISBN: 80-85272-99-7)_.

Děkuji za reakci.

**Comment by albertoh** [comment]
Opraveno

**Comment by smallcubes** [comment]
Vypadá v pořádku. Děkuji za vyřízení.
