### ISSUE TITLE
Nápověda

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#232]
Bylo by prosím možné přidat nápovědu do editace stránek, aby bylo možné nápovědu psát pomocí wysiwyg editoru? Samozřejmě i s možností anglické mutace.

**Comment by pavel-stastny** [comment]
Jiz reseno a bude pristupne ve verzi 1.0.1

**Comment by CIZKOVAL** [comment]
@jahoo některé texty pro nápovědu už od p. Cypzirschové mám a s p. Šťastným jsem domluvená, že v nové verzi aplikace bude možnost je vložit a editovat.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Je to v te verzi 1.0.1   Jsou tam záložky podle rolí (`uživatel`, `knihovna`, `kurátor`, atd...)  a pak je tam jedna která se jmenuje jenom Nápověda a ta je pro nepřihlášené uživatele.

**Comment by jahoo** [comment]
@CIZKOVAL Myslím, že jsi myslel @jahhoo , ne @jahoo.

**Comment by CIZKOVAL** [comment]
Mám k dispozici texty nápovědy pro knihovny a users. V administraci vidím, že vznikly nové sekce v editace - pro nápovědu. Doplním zítra.

**Comment by jahhoo** [comment]
Nevím, jestli to považovat za bug, ale je to pro mě neočekávané chování. Pokud v češtině edituji např. text "O SDNNT" a přepnu na anglickou mutaci - zobrazí se mi menu s anglickými texty, ale stále zůstanu v editoru české verze textu "O SDNNT"

**Comment by jahhoo** [comment]
Za mě je to OK. Díky
