### ISSUE TITLE
Smyčka v přesměrování

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#235]
Při zadání URL https://sdnnt-url.cz/neco dojde ke smyčce v přesměrování na: https://sdnnt-url.cz/sdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntneco

**Comment by jahhoo** [comment]
Nejde tedy například Shibboleth: https://sdnnt-url.cz/sdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntsdnntapi/user/shib_login_redirect

**Comment by pavel-stastny** [comment]
Jedna se o nastaveni apache proxy, tedy ne samotne aplikace.  Pokud je to na testu, pak prosim o zmenu konfigurace @smallcubes

**Comment by jahhoo** [comment]
@pavel-stastny tento problém je i na devu, takže není problém v konfiguraci na testovacím serveru.

**Comment by pavel-stastny** [comment]
@jahhoo Je to apache proxy. Na devu muzeme opravit ale DEV chapeme pouze jako vyvojovy.

**Comment by pavel-stastny** [comment]
@jahhoo @smallcubes Na devu by to melo byt vyreseno.

**Comment by smallcubes** [comment]
@pavel-stastny vypadá to, že to funguje. Akorát pokud zadám sdnnt-dev.nkp.cz/sdnnt bez lomítka za /sdnnt, vznikne sdnnt-dev.nkp.cz/sdnnt/sdnnt

**Comment by pavel-stastny** [comment]
@smallcubes Tak ted.

**Comment by smallcubes** [comment]
V Chromu mi to funguje, ale ve firefoxu se děje to samé. (sdnnt-dev)

Mohl bych se zeptat, co jste změnil? Nastavení je identické ssl.conf, .htaccess, redirect.conf, ale beze změny na sdnnt-test.nkp.cz ohledně problému s lomítkem.

**Comment by smallcubes** [comment]
@pavel-stastny změnil jsem regex v ProxyPassMatch a už vše funguje.

**Comment by smallcubes** [comment]
@jahhoo poprosil bych o kontrolu a případné uzavření

**Comment by jahhoo** [comment]
Vyřešeno. Díky
