### ISSUE TITLE
Nastavení anglické verze - neuloží se

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#236]
Pokud zvolím anglickou verzi a obnovím stránku - aplikace zapomene zvolení anglické mutace a text se opět zobrazuje v české verzi. Toto by mělo být ideálně řešeno přes Cookies.

**Comment by smallcubes** [comment]
@jahhoo kliknu-li na tlačítko pro *en* verzi a obnovím web, překlad zůstane. Poprosil bych o schválení a případně uzavření.

**Comment by jahhoo** [comment]
Vyřešeno, díky
