### ISSUE TITLE
Přehled žádostí - tlačítko zpět

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#237]
Otevřu-li "Moje požadavky" a následně "Přehled žádostí" nemohu se dostat zpět na moje požadavky - chybí tlačítko "zpět na moje požadavky".

**Comment by pkudela** [comment]
K tomuto slouzi standardni navigace viz. screenshot, takze pokud se dostanete na "Prehled zadosti" velice snadno se dostanete opet na "Moje pozadavky" kliknutim na polozku v hlavni navigaci.

![image](https://user-images.githubusercontent.com/16591052/151612076-9cf0a6ef-011d-4ea5-8132-996d6a6bc419.png)

**Comment by jahhoo** [comment]
To nepovažuji za intuintivní ovládání. Zvlášť k bugu #238

**Comment by albertoh** [comment]
Nechapu. Pri pouzivani standardni tlacitko zpet v browseru vsechno funguje jak ma, vcetne razeni.

**Comment by CIZKOVAL** [comment]
Kolega se odkazuje na problem v issue #238, kdy nezůstává zachované nastavené řazení. 

Moje požadavky - nastavím si řazení (např. dle data vyřízení sestupně), vnořím se do žádosti - tlačítko Zpět zde není, tak použiji klik na Moje požadavky - řazení je v defaultu (tedy dle data zadání vzestupně).

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o revizi

**Comment by pkudela** [comment]
Co se tyce tlacitka "Zpet", tak tento prvek se dnes uz vetsinou nepouziva, pokud to nema nejaky spefificky vyznam, nebo pokud se nejedna o mobilni aplikaci. Implementoval jsem bradcrumb navigaci coz je dnes standardni reseni - pouziva Alza, CZC, Cesky rozhlas atd. a snad mi nikdo nebude tvrdit, ze to nejsou moderni weby ;-) Mimo zadosti jsem tuto navigaci implenentoval take do detailu importu. Jamile bude nasazeno, dam k testovani.

![image](https://user-images.githubusercontent.com/16591052/151990818-0d133fd3-c4f2-4d05-9057-f5e004dbdd74.png)

**Comment by jahhoo** [comment]
Dobré řešení, díky.
