### ISSUE TITLE
Výkonnostní optimalizace / timeout

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#241]
Snažil jsem se získat všechny DNNTO záznamy adresou: https://sdnnt-url.cz/sdnnt/api/v1.0/lists/added/dnnto?institution=ABA001&from=2021-07-27T16%3A31%3A05.169Z&rows=1000000&resumptionToken=%2A
Bohužel to padlo na timeout.

Celkový počet dostupných záznamů: 302010
Po 41sec padlo na timeout
Velikost souboru: 2,16MB
Získáno: 8829 záznamů

To je bohužel velice špatný výsledek a bude potřeba výkonnostní optimalizace

![Snímek z 2022-01-19 20-51-04](https://user-images.githubusercontent.com/33415849/150203543-da949c14-94a7-4eef-93dc-05323d6f7999.png)

**Comment by pavel-stastny** [comment]
@jahhoo Myslím, že nebude. To API (a zajimave je, ze o tomto jsem se bavil s @JanMeritus ) ma pro iterování částí výsledků definovaný  resumptionToken. Tedy iteruje se po malých částech dokud nedostanete prázdnou stranu. 

Nicméně dvě věci upravím.  První je aby nebylo možné získávat tak velký počet výsledků najednou. Zbytečně to zatěžuje solr a druhá věc, kterou jsem si všiml: nestejné stránky a to opravím

**Comment by pavel-stastny** [comment]
@JanMeritus Odebírám bug label protože takto API nebylo koncipované

**Comment by JanMeritus** [comment]
@pavel-stastny @pavelkocourek   doporucuji ad hoc technicku schuzku dnes, napr. o 12, je to mozny?

FYI @Cypzirschova

**Comment by pavel-stastny** [comment]
@JanMeritus Za me ok.

**Comment by JanMeritus** [comment]
az bude update @jahhoo zmeri vi resumption tokeny a csv

**Comment by jahhoo** [comment]
@JanMeritus maximální povolený limit je 8000 záznamů. U DNNTO mi to vrátilo za 4,11sec.

**Comment by pavel-stastny** [comment]
@jahhoo Pořád jsem jinde s časem.  Testováno na devu i testu z vnitřních adres: 

`time curl  -X 'GET'   'https://xxxxx/sdnnt/api/v1.0/lists/added/dnnto?rows=8000&resumptionToken=%2A'   -H 'accept: application/json'`

a výsledek na devu: 

![image](https://user-images.githubusercontent.com/675753/152952302-df1775d2-cd56-4e7a-8b99-5b69569e074a.png)

a testu:

![image](https://user-images.githubusercontent.com/675753/152952396-98e00c93-faba-4cf2-bf79-d9184833c3b6.png)

**Comment by pavel-stastny** [comment]
@jahhoo Pokud máte stejné výsledky a není zde nic dalšiho k řešení, poprosil bych uzavřít.

**Comment by JanMeritus** [comment]
@jahhoo prosim o reakci

**Comment by jahhoo** [comment]
Získáno 8000 záznamů za 1,6 sec
