### ISSUE TITLE
Řazení neodeslaných žádostí dle data 

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#242]
Dobrý den,
při používání aplikace lze požadavky v "Moje konto" řadit (vzestupně nebo sestupně). 

Nejčastěji používám já a předpokládám, že i další uživatelé řazení dle **Data zadání sestupně** - vidíme tak nové žádosti.

Pokud ale žádost není ještě odeslaná, tak v tomto případě datum chybí (přidělí se až po odeslání žádosti). 
Tyto žádosti se při použití daného filtru proto řadí na konec, přitom jde o žádosti nejnovější.  Nešlo by toto nějak vyřešit?

![Datum zadani](https://user-images.githubusercontent.com/92719629/150386339-e3e27d1f-921d-47cc-9daf-73de31fef400.png)

![neodeslane zadosti](https://user-images.githubusercontent.com/92719629/150386405-0caeffbd-5ae6-42ad-a4b3-7c563ae3f439.png)

**Comment by JanMeritus** [comment]
@Cypzirschova prosim o vyjadreni, dle meho neni podstatny pokud nedochazi k prepinani roli

**Comment by JanMeritus** [comment]
@CIZKOVAL zde uzatvaram, by default jsou zadosti navrhu az po zmene filtru jsu posunuty jinam
