### ISSUE TITLE
Žádosti ve stavu NL mají možnost VN

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#243]
Pokud uživatel provede u díla žádost VNL (omezení na terminál - po dobu 18m), tak je dílo ve stavu NL s licencí omezeno na terminál.

Je zde ale možnost **"Návrh na vyřazení"** a tuto žádost **LZE schválit,** takže dílo, kterému běží lhůta 18m se mezitím dostane do stavu N.

Poprosim p. @Cypzirschovou o komentář, podle mě by tam možnost vyřazovat tato díla být neměla.

![NL_vyrazeni](https://user-images.githubusercontent.com/92719629/150946545-4706ceb5-8ba5-42a5-9be0-d26752a1eff4.png)

**Comment by Cypzirschova** [comment]
@CIZKOVAL 
No teoreticky by to vlastně šlo, protože tuto žádost použije nakladatel, který původní dílo nevydal. Takže nakladatel, který dílo vydal by mohl požádat o vyřazení díla. Ještě se poradím s paní Lichtenbergovou a napíšu.

**Comment by Cypzirschova** [comment]
@CIZKOVAL 
Je to tak, jak jsem psala výše. Za nás to takto je v pořádku. Nakladatel A vydá knihu a nakladatel B omezí - VNL. Nakladatel A bude chtít vyřadit svou knihu a vyřadí ji. Pro nakladatele B je to ku prospěchu, protože jeho cílem je, omezit (znepřístupnit) knihu, aby se ta jeho nová kniha prodávala.

**Comment by CIZKOVAL** [comment]
Dobře, děkuji za výklad, zavírám.
