### ISSUE TITLE
Importy - chybí informace

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#248]
Chybí informace o importech - tabulka je prázdná

![Snímek z 2022-02-02 17-22-15](https://user-images.githubusercontent.com/33415849/152198256-86ac267b-7dc5-4ff1-9ad1-c5899a59f8a2.png)

**Comment by albertoh** [comment]
Na devu nevidim problem, tam fungujou.

**Comment by smallcubes** [comment]
@albertoh mohl byste prosím napsat, kde by mohla být chyba? Případně, kde se importy konfigurují a jak?

**Comment by smallcubes** [comment]
@pavel-stastny @albertoh issue bylo přiřazeno k 1.0.3, nicméně problém přetrvává. Chtěl bych se zeptat, co je potřeba udělat na z mojí strany?

**Comment by smallcubes** [comment]
vymazal jsem obsah jader dle [imports a imports_documents](https://github.com/NLCR/SeznamDNNT/issues/215#issuecomment-1047007496), následně jsem vyzkoušel příkaz `curl 'http://test/sdnnt/api/index/import_heureka?url=https://www.palmknihy.cz/heureka.xml'` a dostal jsem odopověď: `curl: (52) Empty reply from server`. 

Error v `catalina.out`
```log
14-Mar-2022 12:14:50.391 INFO [http-nio--exec-7] cz.inovatika.sdnnt.index.XMLImporterHeureka.fromUrl Processing https://www.palmknihy.cz/heureka.xml
14-Mar-2022 12:15:23.541 SEVERE [http-nio--exec-7] org.apache.coyote.AbstractProtocol$ConnectionHandler.process Failed to complete processing of a request
        java.lang.OutOfMemoryError: GC overhead limit exceeded
```

@albertoh  @pavel-stastny

**Comment by smallcubes** [comment]
zvýšil jsem parametry `-xms` a `-xmx`, poté se to rozběhlo. 
Jak by parametry měly být optimálně nastaveny @albertoh @pavel-stastny?

**Comment by smallcubes** [comment]
@jahhoo @CIZKOVAL @Cypzirschova importy byly provedny na těchto distributorech: **Palmknihy**,  **Distri**.
Při jednom pokusu mi to vyhodilo error viz níže. Po druhém spuštění se error už neobjevil. 
```json
"error": "com.ctc.wstx.exc.WstxIOException: Premature end of Content-Length delimited message body (expected: 44,896,589; received: 1,556,040)",
  "skipped": 0
```
@215 @95

**Comment by Cypzirschova** [comment]
Jsou tam duplicitní kontroly.
![Importy - stejné](https://user-images.githubusercontent.com/86351100/161208090-5f5389b5-8b75-4894-907f-d00315ebfb3e.png)

**Comment by smallcubes** [comment]
@Cypzirschova kontrolu jsem spouštěl několikrát, nejspíše je to tím. Možná by bylo dobré, aby nový záznam obsahoval pouze ty položky, které nejsou v předchozích záznamech? @JanMeritus @pavel-stastny

**Comment by Cypzirschova** [comment]
@smallcubes souhlasím. Pak tam budeme mít zbytečně x stejných kontrol.

**Comment by Cypzirschova** [comment]
@smallcubes Je to už nastavené, aby ty kontroly běžely 1x týdně?

**Comment by smallcubes** [comment]
@Cypzirschova zatím jsem to pouze spouštěl manuálně, týdenní kontrolu nastavím

**Comment by smallcubes** [comment]
@Cypzirschova @CIZKOVAL Pokud jsem vše správně nastavil, tak by se kontroly měly spouštět následovně:
- kontrola Palmknihy.cz: v 00:00 každý pátek
- kontrola Distri.cz: v 22:00 každý pátek

**Comment by smallcubes** [comment]
@Cypzirschova @CIZKOVAL upravil jsem nastavení a už by mělo být vše v pořádku, datum zůstalo stejné

**Comment by Cypzirschova** [comment]
@smallcubes ted se tam objevila nová kontrola z Palmknih, tak uvidíme po pátku, zda to bude fungovat.

**Comment by Cypzirschova** [comment]
@smallcubes 
V aplikaci se vytvořily nejspíše duplicitní kontroly v různých časech.
![Importy - duplicity](https://user-images.githubusercontent.com/86351100/161546025-a8447485-8ab2-4268-bc00-04974550a604.png)

**Comment by smallcubes** [comment]
@Cypzirschova ne raději jsem to zkoušel několikrát, abych si ověřil, že vše funguje. Ohledně opakování požadavků viz [předchozí komentář](https://github.com/NLCR/SeznamDNNT/issues/248#issuecomment-1085610745)

**Comment by Cypzirschova** [comment]
Dobře, díky za info.

**Comment by Cypzirschova** [comment]
@smallcubes Pravidelná kontrola proběhla ve výše uvedených časech.

**Comment by smallcubes** [comment]
@Cypzirschova můžeme tedy uzavřít? Ohledně opakování záznamu v předchozích importech můžeme vytvořit nové issue, souhlasíte?

**Comment by Cypzirschova** [comment]
Souhlasím, duplicitní záznamy v importech se řeší v #95.

**Comment by smallcubes** [comment]
Importy se již v rozhraní objevují, Distri a Palmknihy fungují, avšak nefunguje Kosmas viz #365. Duplicitní záznamy viz #95.
@Cypzirschova @CIZKOVAL
