### ISSUE TITLE
Změnit osobní údaje - Registrační formulář

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#249]
Pokud zadám požadavek na změnu osobních údajů - neměl by se zobrazovat nadpis registrační formulář, ale nadpis "Změnit osobní údaje"

![Snímek z 2022-02-02 17-47-10](https://user-images.githubusercontent.com/33415849/152198672-4ede4853-2a14-41a7-9719-6f6c7b152456.png)

**Comment by pkudela** [comment]
hotovo, jakmile bude k testovani, oznacime

**Comment by pkudela** [comment]
@jahhoo prosim je to na dev serveru nasazene, otestujte a pripadne zavrete issue, diky.

**Comment by CIZKOVAL** [comment]
Retest OK

![FO_zmena](https://user-images.githubusercontent.com/92719629/156784356-f8d70546-5d51-481b-ad21-26b999030e19.png)
