### ISSUE TITLE
Ztrácí se návrhy na zařazení, vyřazení

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#25]
Dobrý den,

výtvořím-li třetí NZN (_návrh na zařazení_) z účtu _knihovna_, tak některé NZN zmizí (buď ten původní návrh nebo ty předcházející). Chvilku se tam sice objeví, ale cca. po minutě zmizí. Děje se to i u _návrh na vyřazení_.

Děkuji za reakci.

**Comment by albertoh** [comment]
Vidim problem. V te roszpracovane zadosti NZN je jeden zaznam opakovan dvakrat. V poctech j videt 3 zaznamy, ale jen dva z nich jsou jine.
 Osetrim opakovani

**Comment by smallcubes** [comment]
Záznamy se už neztrácejí. Děkuji za vyřízení.

**Comment by smallcubes** [comment]
Dr. Edvard Beneš ve fotografii : historie velkého života

**Comment by smallcubes** [comment]
Záznamy se už neztrácejí. Děkuji za vyřízení.

**Comment by smallcubes** [comment]
Záznamy se už neztrácejí. Děkuji za vyřízení.

**Comment by smallcubes** [comment]
Záznamy se už neztrácejí. Děkuji za vyřízení.
