### ISSUE TITLE
Změna fyzické osoby na právnickou - bezpečnostní bug

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#250]
Změna fyzické osoby na právnickou je zakázaná parametrem u checkboxu - disabled. Pokud ale otevřu konzoli prohlížeče a parametr "disabled" smažu. Hodnota se i přesto uloží. 

Toto je potřeba ošetřit v jádru aplikace.

**Comment by pavel-stastny** [comment]
@jahhoo Změněno na obou stranách..    Nicméně neodpustím si poznámku k titulku.  Volba mezi právnickou nebo fyzickou osobou je volná informace a uživatel si ji volí sám (Při registraci).   O bezpečnostní bug se rozhodně nejedná.

**Comment by pavel-stastny** [comment]
Hotovo na DEVU

**Comment by jahhoo** [comment]
Vyřešeno. Možnost změny z fyzické osoby na právnickou byla v editaci zrušena.
