### ISSUE TITLE
Chybí ochrana nevyplněných povinných údajů

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#251]
Pokud v editaci uživatele nevyplním povinné pole, aplikace data i tak uloží. Takže mohu mít profil např. beze jména, příjmení a hlavně e-mailu.

Měla by zde být ochrana jak ve frontendové, tak backendové části.

**Comment by CIZKOVAL** [comment]
Tento problém se tam už dříve vyskytl, pak byl ale opraven. V této verzi nefunguje..

**Comment by CIZKOVAL** [comment]
Retest #138 OK, tedy i toto zaviram
