### ISSUE TITLE
Stránkování není v českém jazyce

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#252]
Popisky u stránkování nejsou v českém jazyce.

Např.  Items per page, Next Page, Previous Page

 
![Snímek z 2022-02-02 17-57-14](https://user-images.githubusercontent.com/33415849/152200657-1d551430-670f-4ecf-aa2f-1349cbad8bca.png)

**Comment by CIZKOVAL** [comment]
Toto je duplicita k issue #44, které bylo zadáno 4.8. 2021...

**Comment by pavel-stastny** [comment]
@CIZKOVAL @jahhoo Provedeno a deployováno na devu

**Comment by CIZKOVAL** [comment]
Retest #44 OK, tedy i toto zaviram

![per_page](https://user-images.githubusercontent.com/92719629/156755444-dbd06df1-0701-4ea2-8ccf-daea2ce2c28b.png)
