### ISSUE TITLE
Statistiky - barvy grafů

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#253]
Bylo by prosím vhodné sladit barvy grafů do stejných odstínů jako jsou boxů nahoře. Takto to absolutně k sobě neladí.

![Snímek z 2022-02-02 18-02-06](https://user-images.githubusercontent.com/33415849/152201353-393055b3-d995-4216-bc74-7c8c633c2a0d.png)

**Comment by pkudela** [comment]
hotovo, jakmile bude nasazeno na devu, oznacim

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/16591052/154436889-984d6caf-e144-4097-92b8-58a7203bd303.png">

**Comment by pkudela** [comment]
Prosim o otestovani a pripadne o uzavreni tohoto issue.

**Comment by smallcubes** [comment]
@jahhoo barvy jsou změněné a sedí s boxy, bylo by možné ještě barevně odlišit `X: Volné dílo` a  `NL: Plánované vydání díla` @pkudela? Přijdou mi úplně stejné.

**Comment by JanMeritus** [comment]
@smallcubes nezmizli tam procenta (absolutni cisla) ?

**Comment by smallcubes** [comment]
potvrzuji, že čísla zmizela, ale jdou vidět pouze po najetí myší

@JanMeritus

**Comment by CIZKOVAL** [comment]
Řešeno i v issue #257
