### ISSUE TITLE
API: lists nevrací žádné záznamy

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#256]
API lists nevrací žádné záznamy - viz např.:

https://sdnnt-url.cz/sdnnt/api/v1.0/lists/added/dnntt?institution=ABA001&from=2021-07-27T16%3A31%3A05.169Z&rows=10&resumptionToken=%2A

![Snímek z 2022-02-02 18-23-47](https://user-images.githubusercontent.com/33415849/152204964-478886dc-31fe-4635-a1d0-d0366bfc6956.png)

**Comment by pavel-stastny** [comment]
@jahhoo Na testu doslo misto a neprobehl reindex.  Je to stejne jako u #173 resp  #247.

**Comment by jahhoo** [comment]
Po reindexu OK
