### ISSUE TITLE
Hromadné žádosti - irelevantní návrhy u některých stavů

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#259]
Dobrý den,
1. pokud si vyfiltruji stav **PA**, pak zde mám možnost podat následující hromadné žádosti:

**Návrh na zařazení** - toto by běžný user neměl mít, stejně jako tato možnost není u podání jednotlivých žádostí. Běží zde lhůta 1 (6 měsíců) a možnost přejít rovnou do stavu A má pouze kurátor při změně stavu.
Návrh na vyřazení - OK
Omezit na terminál - OK

2. pokud si vyfiltruji stav **NL**, pak zde mám možnost podat následující hromadné žádosti:

**Omezit na terminál** - toto je irelevantní, když už jsou díla ve stavu NL na terminálu
Návrh na vyřazení - OK

![PA_navrh na zarazeni](https://user-images.githubusercontent.com/92719629/152314158-3ea8f8a8-da44-4ed7-b4b9-1bf5d34a6eca.png)

![NL_terminal](https://user-images.githubusercontent.com/92719629/152314528-fad2cb81-3501-49d7-bc59-a5ef722859ec.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ten test je v nekonzistentnim stavu. (doslo misto na disku)   Muzete verifikovat i na DEVu ?

**Comment by CIZKOVAL** [comment]
@pavel-stastny ja mam do dev přístup pouze pro admin a tam nevidim hromadne zadosti vubec...muzete mi prosim na email poslat heslo pro usera? Dekuji

**Comment by CIZKOVAL** [comment]
@pavel-stastny děkuji za hesla, na dev PA stejne chovani jako na TEST, u NL nelze podavat hromadne navrhy.

![DEV_PA](https://user-images.githubusercontent.com/92719629/152331760-e049028c-082a-471f-ab8a-5c0afe7aebf1.png)

![DEV_NL](https://user-images.githubusercontent.com/92719629/152331772-dfc5574d-4b57-46f3-b0e1-05d8c6269647.png)

**Comment by JanMeritus** [comment]
@CIZKOVAL @Cypzirschova - dle zakona by mel byt spravne pisemna formulace moznosti, jak u hromadnych navrhu tak i jednotlivosti - "navrh na zarazeni" a "vyzva k vyrazeni"

97f AZ:

(2) **Návrh na zařazení** díla do seznamu může podat nositel práv, knihovna podle knihovního zákona[19)](https://www.zakonyprolidi.cz/cs/2000-121#f6027128) nebo příslušný kolektivní správce. Návrh na zařazení díla do seznamu uveřejní Národní knihovna bez zbytečného odkladu na svých internetových stránkách.

a

(5) Nositel práv je oprávněn Národní knihovnu písemně **vyzvat k vyřazení** svého díla ze seznamu. Národní knihovna dílo ze seznamu vyřadí nejpozději poslední den následujícího kalendářního měsíce, v němž jí byla výzva doručena. Vyřazením díla ze seznamu není dotčena platnost oprávnění k výkonu práv na užití podle § 97e odst. 4 písm. i), které bylo poskytnuto před datem vyřazení.

**Comment by pavel-stastny** [comment]
Opraveno na DEVu

**Comment by CIZKOVAL** [comment]
Retest OK.

Díla ve stavu PA mají možnost hromadně vyřadit nebo omezit na terminál. Díla ve stavu NL lze vyřadit.

![PA_retest](https://user-images.githubusercontent.com/92719629/158355454-fd32c116-8f7a-484f-9ec3-7d8ce4a5d31d.png)

![NL_retest](https://user-images.githubusercontent.com/92719629/158355517-555f8d93-3b8b-455c-a294-80a8d2b2a4cf.png)
