### ISSUE TITLE
Hromadné žádosti - kurátor nemá možnost hromadně měnit stavy

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#260]
Dobrý den,
mám otázku k hromadným žádostem. User a knihovna mají možnost podávat jednotlivé i hromadné žádosti.
Kurátor může měnit stavy u jednotlivých děl. Neměl by mít tedy i možnost měnit hromadně stavy u skupiny děl?

**Comment by Cypzirschova** [comment]
Určitě by to bylo dobré zlepšení do aplikace.

Knihovny mají možnost pouze vyřazovat/omezovat - což dělat nebudou a ani snad na to nemají práva. Možná by bylo dobré, kdyby i knihovny mohly v aplikaci hromadně zařazovat?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Prosim verifikovat i na DEVu.  Kuratorovi by se melo objevit nasledujici: 

![image](https://user-images.githubusercontent.com/675753/152317141-81ac9bcc-4186-48b4-963a-7f276e719183.png)

**Comment by CIZKOVAL** [comment]
@pavel-stastny to neni o hromadnem schvalovani zadosti, ale o hromadne zmene stavu

**Comment by CIZKOVAL** [comment]
@Cypzirschova - knihovny mohou hromadne zarazovat, maji stejne moznosti jako user...

**Comment by Cypzirschova** [comment]
Situace, kdy může dojít k hromadné změně stavu děl:

1. Posun licence o rok (např. online licence se o rok navyšuje - v současné době do r. vyd. 2001)
2. Změna AZ (např. na seznamu budou pouze díla do r. vyd. 2000)
3. Změna Memoranda (např. změna licence terminál)

@Lichtenbergova
@JanMeritus

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim nezmichavat role kurator a knihovna

**Comment by CIZKOVAL** [comment]
@Cypzirschova - prosím o rozuzlení tohoto issue - ze schůzky 21.2. vyplynulo, že není nutné, aby měl **kurátor možnost hromadně měnit stavy**. Kurátor bude mít možnost měnit stavy **pouze jednotlivě** a bude **schvalovat hromadné návrhy** od knihoven. Je to takto v pořádku?

_Poznámka - předmětem diskuze není podání hromadných žádostí - to kurátor nedělá - jedná se o změnu stavu natvrdo, což může dělat u jednotlivých děl._

**Comment by Cypzirschova** [comment]
Zatím nemám informaci, zda nastavení licencí DNNTT a DNNTO mají nějakou časovou hranici, která by se dala posouvat? Pokud by to tak bylo, tak by to vyřešilo většinu toho, co jsem výše popisovala.
@pavel-stastny

**Comment by CIZKOVAL** [comment]
Hromadné přesuny např. požadavek na změnu spodní/horní hranice pro díla v SDNNT by měla umožňovat procedura automatického vyřazování, která je předmětem issue #174

**Comment by JanMeritus** [comment]
bude reseno #167 a dale #174 , zde uzaviram
