### ISSUE TITLE
Hromadné žádosti - zařazení děl, která jsou mimo seznam

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#261]
Dobrý den,
pokud si uživatel zobrazí **_i díla, která jsou mimo seznam_** a chce hromadně zařadit díla, která ještě **NEJSOU** na seznamu (nemají žádný stav), tak v Hromadném návrhu není možnost **"Návrh na zařazení"**. Při podávání žádosti jednotlivě u stejných děl ta možnost existuje.

**Hromadné podání:**
![Mimo seznam_hromadne](https://user-images.githubusercontent.com/92719629/152338384-fe87a709-6f04-4edb-a8c4-0190d41aba49.png)

**Jednotlivé podání:** 
![Mimo seznam_jednotlive](https://user-images.githubusercontent.com/92719629/152338401-29d38b0b-1bd1-4585-a948-f86b7ef45fd8.png)

**Comment by Cypzirschova** [comment]
Po dnešním testování stále nefunkční.
![Hromadný návrh](https://user-images.githubusercontent.com/86351100/152939553-c5d96f21-61b9-4d81-a982-b9dc03a0ff7a.png)
![Hromadný návrhM](https://user-images.githubusercontent.com/86351100/152939566-6d77c01c-18b7-45fd-8396-8f4ab3c48d52.png)

**Comment by pavel-stastny** [comment]
Opraveno na DEVu, prosim o verifikaci @CIZKOVAL .

**Comment by CIZKOVAL** [comment]
@pavel-stastny na DEV OK.

![DEV_hromadne](https://user-images.githubusercontent.com/92719629/153172631-5b1c5016-3635-47ac-8908-d8c5787b98ff.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, na TESTu hromadný návrh pro díla mimo seznam stále není.

![mimo_seznam_hromadne](https://user-images.githubusercontent.com/92719629/153575678-1adc79a3-3ae0-470d-b224-460497e53de7.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Na test se to dostane az s novym buildem.

**Comment by CIZKOVAL** [comment]
Retest OK

![NZN_hromadne](https://user-images.githubusercontent.com/92719629/156783558-9db376b3-33bc-45c0-b73a-1b3a44dc80d5.png)
