### ISSUE TITLE
Konfigurovatelne logo aplikace SDNNT

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#262]
pokud je to nekde jiz rozjednano prosim prenest zadani tam, myslim ze v minulosti se to resilo - mailem urcite. Dle posledniho setkani pro rad to davam sem aj s aktualni informaci.

- prosim o zaneseni moznosti konfigurovatelne zmeny loga pro adminy
- pripadne  (pro zjednoduseni) identifikaci mista kde to muzu zmenit primo v kodu
- aktualni graficke materialy se najdou zde: https://dnnt.nkp.cz/downloads.html -> Graficke materialy

FYI @CIZKOVAL

**Comment by pkudela** [comment]
Logo lze nyni zmenit bez problemu v konfiguraci, nicmene upozornuji na to, ze kazde logo ma jine proporce, takze jeho necitliva vymena muze. a nemusi znamenat rozbiti layoutu, pripadne nabourani responsivniho chovani. Na zacatku projektu se logo, ktere jsem navrhl a vytvoril libilo, mel jsem zpetnou vazbu od Pavla, takze  ted uplne nechapu, proc ho chcete menit, ale asi to ma sve duvody. Jakmile bude nasazeno na devu, oznacim k testovani.

**Comment by pkudela** [comment]
Prosim o otestovani a pripadne o uzavreni tohoto issue.

**Comment by JanMeritus** [comment]
@jahhoo prosim spolu s @smallcubes o citlivou vymenu loga za to "oficialni", dostupne zde https://dnnt.nkp.cz/downloads.html

**Comment by JanMeritus** [comment]
@smallcubes jaky je zde stav?

**Comment by smallcubes** [comment]
@pkudela dobrý den, nové logo se umísťuje přes konfiguraci v jsonu? Pokud ano, jaký klíč k tomu můžu použít?

**Comment by smallcubes** [comment]
@pavel-stastny dle dnešního setkání Vás prosím o reakci

**Comment by smallcubes** [comment]
@pavel-stastny @pkudela připomínám se s dotazem

**Comment by smallcubes** [comment]
Logo lze konfigurovat následovně:
1. obrázek je nutné umístit do složky: `$TOMCAT_HOME/webapps/sdnnt/assets/img`
    - převěd vlastníka souboru na uživatele, pod kterým se spouští Apache Tomcat např.  `# chown tomcat:tomcat $TOMCAT_HOME/webapps/sdnnt/assets/img/logo.png`
2. do `$TOMCAT_HOME/.sdnnt/config.json` přidat klíč s cestou:
```json 
"client": {
  "logo": "/sdnnt/assets/img/logo.png"
}
```
