### ISSUE TITLE
Nefunkční OAI sety

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#263]
Dobrý den, 

v současné době nefungují dva sety: `SDNNT-PA` a `DNNTT` pro oai-pmh.

**Comment by albertoh** [comment]
Na devu nevidim problem, tam fungujou.

**Comment by smallcubes** [comment]
@albertoh Potvrzuji funkčnost na DEVu. Je nutné něco nastavit, pro funkčnost obou těchto setu na TESTu?

**Comment by smallcubes** [comment]
@albertoh odpověď serveru je: `500: org.json.JSONException: JSONObject["link"] not found.`

**Comment by albertoh** [comment]
Opraveno. @pavel-stastny az bude na devu nasazeno, prosim oznacit k testu

**Comment by smallcubes** [comment]
@albertoh @pavel-stastny oba sety: `SDNNT-PA` a `DNNTT` pro oai-pmh už jsou dostupné. Uzavírám a děkuji za opravu.
