### ISSUE TITLE
Moje požadavky - nepamatuje si stránkování

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#264]
Pokud u stránky "Moje požadavky" změním " Items per page: " následně otevřu požadavek a vrátím se zpět na "Moje požadavky" - vyresetuje se počet položek na původních 20.
(Předpokládám, že si to nebude pamatovat ani otevřenou stranu)

**Comment by CIZKOVAL** [comment]
Retest:
Změním počet položek na stránce (např. 5), potom se vnořím do žádosti.
- překliknu se šipkou zpět, tak je vše OK - zůstává zobrazen daný počet záznamů (např. 5)
- zpět se dostanu klikem na Moje požadavky u vnořené žádosti - pak je zde defaultní počet záznamů, tedy 20 - to je nejspíš v pořádku, je to tak, @jahhoo?. Zůstává zde ale nastavena změna počtu záznamů (např. 5)

![požadavky_počet_záznamů](https://user-images.githubusercontent.com/92719629/159000000-97b4b7b7-7c27-4854-a209-1ca8995c07b9.png)

**Comment by smallcubes** [comment]
@pavel-stastny tohle asi bude ve verzi 1.0.5?

**Comment by CIZKOVAL** [comment]
Retest OK, funguje jak vrácením přes šipku zpět, tak návratem přes Moje požadavky. Pamatuje si to i poslední otevřenou stránku.
