### ISSUE TITLE
Hromadné žádosti - problém pokud je dílo předmětem více žádostí

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#265]
Dobrý den,
provedla jsem několik hromadných žádostí. 2 následující díla byla předmětem více žádostí, viz níže.

Dílo 
 _--a co jsem ještě neřekla / Ljuba Hermanová (cnb000074846)_
CIZEK/žádost **VNZ**/7f7dd52b/ překlopení ze stavu A online do A dnntt
CIZKOVAL/žádost **VNZ**/**350d2b6b**/ **už je ve stavu A dnntt - nelze podruhé**

_América Latina : condiciones de trabajo y de vida de los trabajadores de la industria del Cuero, Calzado y Peletería_
CIZEK/žádost **VN**/597f0f90/ překlopení ze stavu A online do N
CIZKOVAL/žádost **VNZ**/**350d2b6b**/ **je ve stavu N - nelze překlopit do stavu A dnntt**

V žádosti **VNZ 350d2b6b** je celkem 16 děl - kliknu na Vyřízení žádosti --> Hromadně schválit -- > **nic se nestane, žádná hláška** --> označit jako zpracované --> objeví se hláška "Ne všechny záznamy jsou zpracované"

**Očekávala bych, že se hromadně schválí záznamy, které schválit lze.** To se nestane, neschválí se žádný záznam. Lze je schválit pouze jednotlivě a záznamy, kde je kolize se musí zamítnout, což je v pořádku.

**Comment by Cypzirschova** [comment]
Zatím jsem netestovala 1 dílo ve více žádostech a hromadné vyřízení. Měly by se hromadně schválit díla, která lze schválit.

**Comment by Cypzirschova** [comment]
Chyba stále přetrvává, dnes otestováno.

**Comment by Cypzirschova** [comment]
Vytvořila jsem žádost VNL, kde bylo i 1 dílo, které bylo předmětem jiné žádosti a ta byla přednostně vyřízena (VN). Z výše popsané chyby mi nešlo hromadné schválení (viz níže). Poté jsem tedy vše hromadně zamítla a to fungovalo, ale po označení žádosti za vyřízenou, se čeká na automatické vyřízení (viz níže). V žádosti není ani jedno dílo, které by bylo ve stavu schváleno i podle stavu. Žádost nemá na co čekat, když jsou všechna díla zamítnuta v této žádosti. Jedná se o žádost d837caa6.

![VNL_hr](https://user-images.githubusercontent.com/86351100/153350712-5f5bc539-28a9-438d-8d0d-44ebc854ebaf.png)

![VNL-automat](https://user-images.githubusercontent.com/86351100/153350638-78cfeb04-9def-4449-afe9-666c54abcd82.png)

**Comment by JanMeritus** [comment]
@Cypzirschova doda specifikaci k:

"V žádosti není ani jedno dílo, které by bylo ve stavu schváleno i podle stavu. Žádost nemá na co čekat, když jsou všechna díla zamítnuta v této žádosti. "

**Comment by Cypzirschova** [comment]
_"V žádosti není ani jedno dílo, které by bylo ve stavu schváleno i podle stavu. Žádost nemá na co čekat, když jsou všechna díla zamítnuta v této žádosti. "_
Po konzultaci se nechá, jak je nastaveno teď. Je potřeba, ale opravit hromadné schvalování, které popsala výše paní @CIZKOVAL.

**Comment by CIZKOVAL** [comment]
Dílo cnb000084499 figuruje v těchto žádostech
1. VN d4598c35, která byla schválena 
2. hromadná žádost VNL **ba302d0a**

Dílo cnb000137647 figuruje v těchto žádostech
1. VNZ 6a291040, která byla schválena 
2. hromadná žádost VNL **ba302d0a**

Když chci schválit hromadně žádost VNL, tak se neschválí nic.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Nedaří se mi nasimulovat na DEVu, respektive:  Mám jedno dílo ve dvou žádostech. V prvním schválim změnu stavu a v druhém na mě vyběhne hláška, že není možno schálit ?   Můžete verifikovat, případně připravit tu situaci na DEVu ?

**Comment by CIZKOVAL** [comment]
@pavel-stastny a jsou ty zadosti hromadne a schvalujete hromadne?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ano, schvaluji i odmitam hromadně.   V žádosti mám více položek a ždy jednu z nich dám jinou žádostí nebo přímým zásehem do stavu, kdy nejde celá žádost hromadně schválit.  Zkusím hromadně schválit, dostanu se do stavu kdy se mi schválí jenom to co jde a dostanu hlášku, že není možné žádost hromadně schválit a musím zbylé položky odmítnout. (ručně nebo hromadně).

**Comment by pavel-stastny** [comment]
@CIZKOVAL Zkuste jenom na DEVu udělat přimo tu sitaci, která nejde schválit. To bude stačit.

**Comment by CIZKOVAL** [comment]
@pavel-stastny - mate pravdu, na DEV to funguje, podivam se jeste jednou na test

**Comment by CIZKOVAL** [comment]
Už jsem přišla na to, kde je zakopaný pes, v popsaném [případě výše](https://github.com/NLCR/SeznamDNNT/issues/265#issuecomment-1067855879).

Pokud jsou díla v hromadné žádosti **VNL** a zároveň je některé dílo v žádosti **VNZ**, která je schválená jako první, pak při pokusu o hromadné schválení VNL to vypadá, že se nic nestane a není žádná hláška. Ve skutečnosti se ale díla, která lze schválit schválí a kolizní dílo se poté musí zamítnout. **To se ale projeví až po aktualizaci stránky**.

To se děje pouze v tomto případě, pokud je dílo předmětem např. VNZ a pak je ještě v další hromadné žádosti VNZ, tak se projeví změna hned. Nebo pokud je dílo předmětem VN a pak je ještě v další hromadné žádosti VNL, tak také OK (tento případ byl testován na DEV)

**Comment by JanMeritus** [comment]
resi @pavel-stastny a bude v 1.04

**Comment by CIZKOVAL** [comment]
Retest OK
