### ISSUE TITLE
Filtr Instituce a priorita u kurátora

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#266]
Dobrý den,
jsem přihlášená jako kurátor a filtruji si žádosti v menu Moje požadavky.

Filtr Instituce obsahuje pouze instituci NKP a poté frekvenci (den, týden)
Filtr Priorita - lepší by bylo zobrazení vzestupné Priorita 1, Priorita 2, Priorita 3

![filtr_kurator](https://user-images.githubusercontent.com/92719629/153175802-fa3be728-a963-487a-9cfa-dbfc71343db8.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Je to v datech.  Vypada to, jakoby uzivatele `knihovna-cyp` a `nakladatel-cyp` meli nejakou dobu nastavenu instituci: den a tyden.

**Comment by CIZKOVAL** [comment]
@pavel-stastny a ta priorita na přeskáčku?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ok. To je razeno dle vyskytu v dokumentech. To opravim..

**Comment by pavel-stastny** [comment]
@CIZKOVAL Hotovo. Nasezeno na DEVu.

**Comment by CIZKOVAL** [comment]
Retest OK.

@pavel-stastny Stále zůstává instituce **den** a **týden** u nakladatele-cyp a knihovny-cyp, ale pokud je to daty viz tento [komentar](https://github.com/NLCR/SeznamDNNT/issues/266#issuecomment-1033610049), tak zavru.

![instituce_den_tyden](https://user-images.githubusercontent.com/92719629/156782639-fc515f43-66e1-4871-8099-5365752a9792.png)

**Comment by JanMeritus** [comment]
@CIZKOVAL je zde stale stejny stav? co a kdo je nutne udelat ?

**Comment by CIZKOVAL** [comment]
@pavel-stastny pokud je problem v datech, tak nešlo by instituci den a tyden na testu nějak odmazat, aniz by se poskodily nejake vazby? Dekuji.

**Comment by CIZKOVAL** [comment]
Retest OK

![retest_kol](https://user-images.githubusercontent.com/92719629/175495529-e5595d44-ac63-4e81-a8ae-62c286d28465.png)
