### ISSUE TITLE
Sjednocení velikosti počátečních písmen

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#268]
Dobrý den,
prosím o sjednocení malých/velkých písmen u popisu stavů, kurátorských stavů a licencí. Vhodnější by mi přišlo všude velké počáteční písmeno, paní @Cypzirschova souhlasíte?

![Pocatecni_pismeno_filtr](https://user-images.githubusercontent.com/92719629/153190068-12637c2a-9b78-428e-89f3-64de5bd000ba.png)

![Pocatecni_pismena_uvod](https://user-images.githubusercontent.com/92719629/153190089-4547444b-f87c-47bc-a4cf-4afeab3fa330.png)

**Comment by Cypzirschova** [comment]
@CIZKOVAL 
Souhlas, všude velká počáteční písmena.

**Comment by pkudela** [comment]
@Cypzirschova delam to sjednoceni velkych pismen a pritom jsem narazil na neprelozenou plozku "fmt.VM" viz. screenshot, nevite co "VM" prosim znamena?

<img width="366" alt="image" src="https://user-images.githubusercontent.com/16591052/154488087-cf268538-8cd7-45d3-8776-8bf498e87f17.png">

**Comment by pkudela** [comment]
Dekuji, doplnim to tak, pokud by byl duvod to zmenit, neni problem, bude to v prekladech.

**Comment by pkudela** [comment]
Prosim o otestovani a pripadne o uzavreni tohoto issue.

**Comment by CIZKOVAL** [comment]
Retest OK.

![268_retest](https://user-images.githubusercontent.com/92719629/158153003-46c66394-dec6-4b1b-ab10-7a012018df3a.png)
