### ISSUE TITLE
Kramerius: volně dostupná díla

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#269]
Dobrý den,

v SDNNT by se mělo pracovat s informací z Krameria o tom, zdali je dílo **volně dostupné** tzn. je volně přístupné z Krameria např. ndk.cz bez omezení. Informace, že dané dílo je volně dostupné (**neplést se stavem X - volné v SDNNT**), by se měla zobrazit rolím knihovna/kurátor v  prostředí katalogu a moje požadavky. Návrh názvu příznaku ze setkání: **potencionálně volné dílo**. Jedná se tedy o dodatečnou informaci k záznamu, nikoliv o stav v SDNNT.

Toto souvisí s issue: #177

Poprosil bych o kontrolu: @JanMeritus @CIZKOVAL @Cypzirschova @Lichtenbergova

**Comment by Cypzirschova** [comment]
Ještě mě napadl název: Volné dílo v DK? - digitální knihovně?

**Comment by pavel-stastny** [comment]
@smallcubes @Cypzirschova To je to co se děje v issue #177.

**Comment by CIZKOVAL** [comment]
@pavel-stastny doplnila jsem do issue #177 komentar k poyadovane funkcionalite

**Comment by JanMeritus** [comment]
@pavel-stastny jde o tzv kontextovou informaci pro Knihovny navrhujici dila

**Comment by pavel-stastny** [comment]
@Cypzirschova @CIZKOVAL Proces mění stav na PX a zároveň zapisuje do objektu "kontextovou informaci", která bude reprezentována hláškou " Volné dílo v DK "?

**Comment by Cypzirschova** [comment]
Mělo by to být bez stavu, protože stav PX pro nás znamená - vytipovávání pravděpodobných volných děl ze seznamu, nikoliv v celém SKC. Takto by se to tam zbytečně pletlo. Měla by tam být jen kontextová informace, která bude viditelná hlavně pro knihovny a kurátory.

**Comment by pavel-stastny** [comment]
Jo, jo..  U PX jsem měl na mysli pouze kurátorský stav, veřejný stav zůstane nezměněný (buď prázdný nebo ten původní)

**Comment by Cypzirschova** [comment]
Nechala bych to bez jakéhokoliv stavu. Pouze jen přiřadit tu informaci.

**Comment by pkudela** [comment]
Dobry den @Cypzirschova, vytvoril jsem oznaceni "Volne dilo v DK", viz. screenshot. Do tooltipu se da dat cokoliv, nazev v tom markeru musi byt kratky a vystizny. Dejte mi prosim vedet, jestli Vam to takto vyhovuje.

![image](https://user-images.githubusercontent.com/16591052/154458491-fc9ea64e-3197-443b-9df3-e111573f36bf.png)

**Comment by Cypzirschova** [comment]
Přemýšlím, zda nebude zavádějící "Kramerius", aby zde nedošlo k mylné informaci, že se jedná o všechna díla, která jsou v DK. Zatím mě nenapadá, jak to nazvat, aby to bylo tak krátké.

**Comment by pkudela** [comment]
Teoreticky by ten Vas puvodni zkraceny napad viz. komentar vyse, nemusel co se tyce mista, zas tak vadit.

![image](https://user-images.githubusercontent.com/16591052/154460655-ac2886fb-d97e-4b1e-903d-7c4402f20a32.png)

**Comment by Cypzirschova** [comment]
Pokud by se tam vešel ten druhý poslední návrh, tak bych volila tento.

**Comment by pkudela** [comment]
OK, cili tak jak je to v poslednim screenshotu - Volne dilo v DK, tak tak to necham, ok?

**Comment by Cypzirschova** [comment]
Souhlasím.

**Comment by pkudela** [comment]
Dekuji za rychle vyjadreni, @pavel-stastny dodela funkcionalitu a pak nasadime na vyvojovy server.

**Comment by smallcubes** [comment]
@CIZKOVAL @pavel-stastny @Cypzirschova 

Získání kontextové informace je nastaveno a vypadá následovně: 
```json
"kram_kontextova_informace": {
        "type":"kramerius_px_check",
        "cron": "0 15 11 * * ?",
        "iteration": {
                "date_range": "[* TO 2020]",
                "states": ["A","PA","NL","N"]
        },
        "results":{
                "ctx": true
        }
},
```

**Comment by smallcubes** [comment]
"kram_kontextova_informace": {
        "type":"kramerius_px_check",
        "cron": "0 15 11 * * ?",
        "iteration": {
                "date_range": "[* TO 2020]",
                "states": ["A","PA","NL","N"]
        },
        "results":{
                "ctx": true
        }
},

**Comment by Cypzirschova** [comment]
Chtěla jsem se zeptat, jak funguje ta kontextová informace. V žádosti PXN některá díla mají tuto informaci a některá ne. V DK se mi zdá, že obě díla jsou volná, ale nejsem si tím na 100% jistá.
![PXN](https://user-images.githubusercontent.com/86351100/158120492-91d2b48a-6888-45c2-8868-3f8c394149fe.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova Tam je možné, že ty dva procesy mají nastavené jiné filtry pro procházení.  Napište mi nějaké dílo, které máte v žádosti a nemá kontextovou informaci.

**Comment by Cypzirschova** [comment]
Simon Petlura, héros national ukrainien / V. Koroliv ; traduction d'après le manuscript par Nathalie Kowalewska
Prague : Čas ; 1919
Je to hned 2. dílo, viz výše.

**Comment by Cypzirschova** [comment]
Má stav PA, licence online, ale není zde ta kontextová informace.

**Comment by Cypzirschova** [comment]
Další dílo např.:
Na šachtě : původní román o třech dílech : druhá samostatná část ostravské trilogie "Černé království" / Fr. Sokol-Tůma
9. vyd.
Praha : Julius Albert, 1932

Stav A, online, bez kontextové inf. - v DK mi přijde jako volné.

**Comment by Cypzirschova** [comment]
K tomu dílu Na šachtě od Fr. Sokola-Tůmy. Je zde granularita a ve stavu má X, ale v historii nic nevidím jen, že to bylo natažené do SDNNT 1.1.2020 - stav A, dnnto
![Na šachtě - PXN](https://user-images.githubusercontent.com/86351100/158129483-a973650b-f815-4401-966f-68495f606a4c.png)
![NA šachtě-2-PXN](https://user-images.githubusercontent.com/86351100/158129489-6c6bbd7f-9b43-4c41-be6b-7d504996a473.png)
![NA šachtě-3- PXN](https://user-images.githubusercontent.com/86351100/158129843-b8587d4d-10f8-484f-bb90-9d82908db264.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova Historie granulovanych stavu zaznamenava az aplikace. Zaznamy, ktere dostavame z DNT setu obsahuji pouze historii  hlavniho zaznamu ( ne jeho casti ).  Muzeme probrat na ctvrtecni schuzce.

**Comment by Cypzirschova** [comment]
Simon Petlura, héros national ukrainien / V. Koroliv ; traduction d'après le manuscript par Nathalie Kowalewska
Prague : Čas ; 1919
Toto dílo nemá žádnou granularitu a nemá tu kontextovou inf. - V DK to vypadá jako volné. Je to možné?

**Comment by Cypzirschova** [comment]
Při hledání děl mimo seznam jsem narazila na toto dílo:
České pohádky / Karel Jaromír Erben ; Otiskl V. Tille
7., rozmn. vyd.
Praha : Laichter, 1924
 
Chybí zde kontextová informace, protože v DK je dílo volné.

![Volné dílo v DK](https://user-images.githubusercontent.com/86351100/158171433-f5c338e0-1973-4f63-a1c5-8d167fbfb256.png)
![Volné dílo v DK1](https://user-images.githubusercontent.com/86351100/158171439-b7fbc695-e5a6-4602-9ef8-3e6489022d21.png)

**Comment by CIZKOVAL** [comment]
@Cypzirschova @pavel-stastny @smallcubes pokud to dobře chápu, tak díla **mimo seznam se neporovnávají** s Krameriem (do žádosti PXN se mají dostat pouze díla, která mají stav **PA**, **A** nebo **NL** a zároveň **mají odkaz** do některého z Krameriů, **kde jsou evidovány jako volná díla**). 

- V kontextu výše popsaného mi tento [komentář](https://github.com/NLCR/SeznamDNNT/issues/269#issuecomment-1066725010) přijde irelevantní.

- V proceduře je **navíc** nastaven i stav "N" [zde](https://github.com/NLCR/SeznamDNNT/issues/269#issuecomment-1065140172).

Relevantní je tedy např. dílo zmiňované paní @Cypzirschova výše, jedná se o žádost PXN, id ee3e275f-92db-41b0-b17d-875bc1be785e a dílo cnb002737422, které je v NDK volné.

![PXN_volne dilo](https://user-images.githubusercontent.com/92719629/158777106-69eb25d6-e134-4a75-a9be-2e1378c8c082.png)

![Petrula](https://user-images.githubusercontent.com/92719629/158777144-a6372ebb-6d64-45aa-9a27-02f51676788c.png)

**Comment by CIZKOVAL** [comment]
@JanMeritus - ještě otázka - v tomto issue je uvedeno, že kontextovou informaci má vidět knihovna/kurátor, nyní je ale zobrazena i nepřihlášenému uživateli.

**Comment by pavel-stastny** [comment]
@Cypzirschova @CIZKOVAL Ohledně kontextové informace: 

Takto je proces nastavený na testu: 

```
 "type":"date_px_check",
  "cron":"00 19 14 * * ?",
     "iteration":{
          "date_range":"[* TO 1910]",
           "states":["A","PA","NL"],
            "fmt":"BK"
        },
       "results":{
          "state":"PX"
  }

```

Toto dílo je vydáno až v roku 1919, nesplňuje tedy podmínku do roku 1910.

**Comment by smallcubes** [comment]
@pavel-stastny @CIZKOVAL trochu jsem se ztratil, ale tohle není job pro kontextovou informaci. Pokud jsem špatně porozuměl nastavení procesu, poprosil bych Vás o opravu.

Měla by to být tato:
```
"krameriove_kontextova_informace": {
                                "type":"kramerius_px_check",
                                "cron": "0 20 11 * * ?",
                                "iteration": {
                                        "date_range": "[* TO 2020]",
                                        "states": ["A","PA","NL","N"]
                                },
                                "results": {
                                        "ctx": true
                                }
                        },
```

Zároveň jsem se setkal s dlouhým výpisem errorů se stejnou chybou.
Příklad opakující chyby:
```
20-Mar-2022 11:20:00.000 INFO [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.sched.Job.fire Job krameriove_kontextova_informace fired
20-Mar-2022 11:20:00.000 INFO [QuartzScheduler_Worker-3] cz.inovatika.sdnnt.sched.Job.fire Job zadost_po_minute fired
20-Mar-2022 11:20:00.002 INFO [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.check Current iteration filter [id_pid:uuid, fmt:BK, rokvydani:[* TO 2020], dntstav:(A OR PA OR NL OR N)]
20-Mar-2022 11:20:00.013 INFO [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.index.IterationSupport.iterate Iteration rows 1000
20-Mar-2022 11:20:40.441 SEVERE [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.clearBuffer A JSONObject text must begin with '{' at 1 [character 2 line 1]
        org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
                at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
                at org.json.JSONObject.<init>(JSONObject.java:222)
                at org.json.JSONObject.<init>(JSONObject.java:406)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.clearBuffer(PXKrameriusServiceImpl.java:224)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.checkBuffer(PXKrameriusServiceImpl.java:201)
                at cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.check(PXKrameriusServiceImpl.java:189)
                at cz.inovatika.sdnnt.sched.Job$Actions$3.doPerform(Job.java:188)
                at cz.inovatika.sdnnt.sched.Job.fire(Job.java:58)
                at cz.inovatika.sdnnt.sched.Job.fire(Job.java:51)
                at cz.inovatika.sdnnt.sched.Job.execute(Job.java:94)
                at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
                at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by smallcubes** [comment]
@pavel-stastny ještě mi přijde, že se job spustil ve špatný čas, nebo log patří k jiné službě? Job `krameriove_kontextova_informace`: `0 20 11 * * ?` = dle [wiki](https://en.wikipedia.org/wiki/Cron) 20:00 každý 11 den v měsící

```
20-Mar-2022 11:20:00.000 INFO [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.sched.Job.fire Job krameriove_kontextova_informace fired
20-Mar-2022 11:20:00.002 INFO [QuartzScheduler_Worker-9] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.check Current iteration filter [id_pid:uuid, fmt:BK, rokvydani:[* TO 2020], dntstav:(A OR PA OR NL OR N)]
```

**Comment by pavel-stastny** [comment]
@smallcubes Dost pravdepodobne pujde o stary nebo nexistujici link do krameria ulozeny v SKC.  

Add expression.  Pouziva se scheduler Quartz a ten ma navic i vteriny: Viz [link](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html#format)

Vyse uvedeny vyraz tedy znamena kazdy den v 11:20

**Comment by CIZKOVAL** [comment]
Dobrý den,
dnes jsme spustili proceduru pro přidání kontextové informace.

U všech děl zmíněných v tomto issue už je příznak volného díla v DK. S výjimkou děl mimo seznam. Procedura se totiž týká děl, která mají odkaz do některého z Krameriů a zároveň jsou v SDNNT ve stavech "A","PA","NL","N" a byla vydaná do roku 2020.

**@Cypzirschova - otázkou je, zda by se neměla kontextová informace přidávat právě i dílům mimo seznam, tj. aby tato díla knihovny nezařazovaly na seznam SDNNT.** 

_Poznámka: předpokládám, že pro tento účel stačí pouze upravit procedura, je to tak @pavel-stastny?_

**Comment by Cypzirschova** [comment]
@CIZKOVAL  
Myslela jsem, že to tak bude. Nevím, jestli jsem to špatně pochopila, ale z předchozích schůzek na toto téma, jsem to tak pochopila, že to bude přiřazováno i dílům mimo seznam. Pokud se má předejít návrhům na zařazení do seznamu volných děl, tak by to mělo být i u děl mimo seznam.

Pochopila jsem to tak, že se dílům (i mimo seznam) přiřadí jen informace Volné dílo v DK a nic víc se s tím dít dál nebude. Bude to jen sloužit jako informace, aby se nám nezačal vytvářet další "seznam volných děl". Pochopila jsem to správně @CIZKOVAL? Případně mě prosím opravte.

**Comment by CIZKOVAL** [comment]
@Cypzirschova @JanMeritus prosím o určení, která díla mají mít příznak volného díla v DK, tedy kontextovou informaci.

Určitě to mají být díla, která mají link do některého z Krameriů a **NEJSOU** na seznamu. **Mají být předmětem i díla, která jsou v SDNNT v nějakém stavu?**

**Comment by Cypzirschova** [comment]
@CIZKOVAL Ještě to proberu s paní @Lichtenbergova a dám sem vědět, jak se rozhodlo.

**Comment by smallcubes** [comment]
@pavel-stastny pokud bych chtěl vybrat díla i mimo seznam, jak příznak by měl být zvolený případně znak?

**Comment by CIZKOVAL** [comment]
@Cypzirschova takže raději dáme do podmínky všechny stavy + díla bez stavu?

**Comment by Cypzirschova** [comment]
@CIZKOVAL Souhlasím.

**Comment by CIZKOVAL** [comment]
Dobrý den,
v pátek jsme spustili proceduru, která je nyní nastavena takto - prohledává se v seznamu i mimo seznam a pokud existuje link do Krameria a dílo je tam volné, tak se přiřadí kontextová informace "Volné dílo v DK" (do roku 2020).

"krameriove_kontextova_informace": {
		"type":"kramerius_px_check",
		"cron": "0 52 13 1 * ?",
		"iteration": {
				"date_range": "[* TO 2020]",
		},
		"results": {
				"ctx": true
		}
},

Zkontrolovala jsem díla z tohoto issue a všechna příznak volného díla mají. Poprosím paní @Cypzirschova pokud má vytipovaná další díla, ať je prosím zkontroluje.

Ještě mám 4 otázky @JanMeritus , @Cypzirschova:

1. s jakou frekvencí se má procedura spouštět (tj. jak často se mají kontrolovat volná díla)? Nyní nastaveno na 1. v měsíci 13:52
2. má se vždy porovnávat celý seznam (i mimo seznam) nebo pouze nějaký inkrement?
3. co se stane, když se z volného díla stane v Krameriu neveřejné dílo? Neměla by být i opačná kontrola (tj. díla, která mají příznak volného díla, tak aby se tento příznak vypustil)
4. komu má být kontextová informace zobrazena? Nyní ji vidí všichni, včetně nepřihlášeného uživatele.

**Comment by Cypzirschova** [comment]
> 1. s jakou frekvencí se má procedura spouštět (tj. jak často se mají kontrolovat volná díla)? Nyní nastaveno na 1. v měsíci 13:52
> 2. má se vždy porovnávat celý seznam (i mimo seznam) nebo pouze nějaký inkrement?
> 3. co se stane, když se z volného díla stane v Krameriu neveřejné dílo? Neměla by být i opačná kontrola (tj. díla, která mají příznak volného díla, tak aby se tento příznak vypustil)
> 4. komu má být kontextová informace zobrazena? Nyní ji vidí všichni, včetně nepřihlášeného uživatele.

1. Týdně
2. [Informace by měla být u všech děl v seznamu a hlavně u děl mimo seznam. Tato informace bude sloužit hlavně knihovnám při vytváření nových návrhů na zařazení.](https://github.com/NLCR/SeznamDNNT/issues/269#issuecomment-1084390960)
3. Nevím, jak často se toto děje. Doufáme, že by nám kurátor Krameria dal vědět, kdyby se tak stalo. @JanMeritus 
4. Knihovna a kurátor

@CIZKOVAL @Lichtenbergova

**Comment by CIZKOVAL** [comment]
Čas spouštění procedury pro kontextovou informaci bude každý **pátek v 00:00** (z pátku na sobotu)

**Comment by smallcubes** [comment]
problém s časem je opraven v branchi test

**Comment by CIZKOVAL** [comment]
Vypuštěna horní hranice roku.
Příznak volného díla vidí pouze knihovna a kurátor/hlavní kurátor.
Příznak získají díla mimo seznam (bez stavu) a všechna ostatní díla, která splní podmínku rozporu (vynechávají se stavy X, PX, D).

"krameriove_kontextova_informace": {
"type":"kramerius_px_check",
"cron": "0 52 13 1 * ?",
"iteration": 
"results": {
"ctx": true
}
},
