### ISSUE TITLE
Chybí kniha (dotaz)

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#27]
Dobrý den,

chtěl bych se pouze zeptat: Proč nemohu zaslat návrh na zařazení pro knihu: Harry Potter a Kámen mudrců - knihu vůbec nenaleznu, pokud se jí pokusím vyhledat. Možná to má nějaký dobrý důvod, ale raději se Vás ptám. 

Děkuji za reakci.

**Comment by albertoh** [comment]
Pracuju na implementaci podminek pro zobrazovani zaznamu od p. Lichtenbergove. Muzete prosim mi poslat link zaznamu do alephu? Staci identifikator. Podivam se na MARC a odpovim proc neni zaznam videt

**Comment by smallcubes** [comment]
příklad: https://aleph.nkp.cz/F/QIXAYXXU52UVVBDQ9FYUUP3EY5F27AQA6UR4N3LXTM35JKLP6U-51543?func=full-set-set&set_number=132183&set_entry=000002&format=999

**Comment by albertoh** [comment]
Tato kniha ma datum 2017. Podle podminek bereme jen mezi 1910 a 2007

**Comment by smallcubes** [comment]
rozumím, tady tato je z roku: [Harry Potter a kámen mudrců (2000)](https://aleph.nkp.cz/F/KR57Y4F1K2XKDMRYTJ6C2BIQVFV3MTYG4I7JXJP4E8FY3GX5ED-18685?func=full-set-set&set_number=192016&set_entry=000017&format=999)

**Comment by albertoh** [comment]
A tady problem je nepritomnost pole 338. 
Cekam na vysvetleni kolem nastaveni filtru, podle emailu
Asi pole 338 neni povinni, ale radsi si necham to dovysvetlit :)

**Comment by JanMeritus** [comment]
@albertoh @smallcubes jak to s Harrym dopadlo?

**Comment by albertoh** [comment]
Uz je videt

**Comment by smallcubes** [comment]
@albertoh něměla by se zobrazovat i tato: [Harry Potter a kámen mudrců (2000, ISBN: 80-00-00788-6)](https://aleph.nkp.cz/F/GFU1CJGRV8FTKRGFKCD4PHNHLTJ347LVU5L7RKP97M56KJE5UQ-07399?func=full-set-set&set_number=156866&set_entry=000002&format=999)? Nemohu ji dohledat.

**Comment by CIZKOVAL** [comment]
Knihu jsem objevila, ale je mimo seznam. tj. zadám ISBN 80-00-00788-6 a zaškrtnu "Zobrazit i dokumenty, které nejsou zařazeny na seznamu".

@Cypzirschova - prosím o informaci, zda je v pořádku, že je kniha mimo seznam. Ona jde zařadit, ale spíše mě zajímá jestli by nemělo dojít k nějakému automatickému zařazení (je z roku 2000, na trhu dle všeho už toto vydání není). Jedná se v tomto případě o požadavek na automatickou kontrolu proti distributorům?

**Comment by Cypzirschova** [comment]
Díla se automaticky nezařazují do seznamu. Je to vždy na základě návrhu na zařazení, který dělají knihovny nebo sami autoři/nositelé práv. Na knihu se podívám.

**Comment by Cypzirschova** [comment]
Kniha s tímto ISBN nikdy nebyla zařazena v SDNNT, tudíž ji nemůžete nalézt v SDNNT. Zařazení děl do SDNNT má své podmínky, které musí být splněny.

**Comment by CIZKOVAL** [comment]
Issue tedy uzavírám, kniha nemá být v seznamu DNNT:
