### ISSUE TITLE
Dotaz - hromadné hlášení dokumentů, které nejsou vůbec v aplikaci 

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#270]
Dobrý den,
chtěla bych se zeptat, jak se má postupovat, když chci na SDNNT zařadit dílo, které tam vůbec ještě není. Na té hlavní stránce jsem našla tuto informaci:
_Návrhy do Seznamu může podávat autor nebo jiný nositel práv (nakladatel, dědic apod.), dále kolektivní správce a knihovna. K tomu může využít aplikaci, v níž se navrhovatel zaregistruje a následně označuje tituly ze Souborného katalogu ČR, které chce navrhnout k zařazení._

Jak přesně probíhá to označování titulů ze SKC? Nemůžu na to přijít. Je možné, že na to nemám práva?

**Comment by marketakrutska** [comment]
Dobrý den, moc Vám děkuji za odpověď! Takže problém je v tom, že nemám oprávnění "knihovna"? Protože tuto možnost tam nevidím. Ani na webu https://sdnnt-test.nkp.cz/sdnnt/home, a ani na webu https://195.113.133.53/sdnnt/home. Mám dva účty, jeden jsem si založila jako právnická osoba, ale zřejmě to nestačí.
![image](https://user-images.githubusercontent.com/43740512/153856616-d0ea650b-11f9-488c-8670-9abd75c61558.png)
![image](https://user-images.githubusercontent.com/43740512/153856681-3f8bc3c6-3355-4e7f-b954-a4869af5de3d.png)

**Comment by CIZKOVAL** [comment]
pokud chcete zmenim vam prava

**Comment by marketakrutska** [comment]
Tak pokud to je možné, tak prosím o změnu oprávnění. Třeba u toho účtu pro právnickou osobu, tam je přihlašovací jméno marketa.krutska

**Comment by CIZKOVAL** [comment]
Hotovo, zkuste

**Comment by marketakrutska** [comment]
Bohužel to tam stále nevidím. Zkusila jsem si vymazat cache a taky jsem zkusila jiný prohlížeč, ale nepomohlo to.

**Comment by CIZKOVAL** [comment]
Mate pravdu, nefunguje to. Zjistim a dam vedet.

**Comment by CIZKOVAL** [comment]
založeno issue #272

**Comment by Cypzirschova** [comment]
Jen doplním informaci, že je tam doplněná nápověda pro knihovny, která je viditelná po přihlášení.

**Comment by marketakrutska** [comment]
Již mám změněnou roli, issue zavírám.
