### ISSUE TITLE
Nefunkční změna stavu v rámci granurality

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#273]
Dobrý den,
pokud si jako kurátor zobrazím granuralitu, pak je zde možnost Změnit stav. Po stisku tlačítka se ale nic neděje.

_Poznámka: měl by jít měnit stav na úrovni jednotlivých ročníků, toto lze přes Více--> Změna stavu, ale nebylo by vhodné, aby to bylo i zde (dotaz také v issue #51)?_

![zmena_stavu](https://user-images.githubusercontent.com/92719629/154047416-4543232b-dedf-496e-819d-6c6288557434.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Spatny preklad tlacitka.   Zmenit stav lze jenom pres zmenu stavu

**Comment by CIZKOVAL** [comment]
@pavel-stastny jaký má mít tedy tlačítko překlad a význam? Nestačí pouze tlačítko "Zavřít", které už tam je?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Změna stavu tam být nemá.  Má tam být jenom tlačítko zavřít.

**Comment by CIZKOVAL** [comment]
Prosím tedy o odebrání tlačítka "Změna stavu" v rámci granurality.

**Comment by CIZKOVAL** [comment]
Retest OK, je zde pouze tlačítko "Zavřít"

![Gran_zmenit](https://user-images.githubusercontent.com/92719629/156785638-5c1329a0-d26e-410e-aa52-0733e0eb2e54.png)
