### ISSUE TITLE
Rozpor mezi stavem díla jako celku a na úrovni ročníků

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#274]
Dobrý den,
v SDNNT se vyskytují díla (periodika), která mají stav **A online** a když si pak rozkliknu **jednotlivé ročníky** (granuralitu), tak jsou ve stavu **N**.

_Poznámka: Stav A online nebyl upraven v rámci testování, ale dostal se tam dávkou (batch)._ 

např. cnb000361162

![Lidovky_magazin](https://user-images.githubusercontent.com/92719629/154051546-eaf96bea-f9aa-4564-b945-53cc2da3cf59.png)

![rocniky_stavy](https://user-images.githubusercontent.com/92719629/154051172-cfa89b59-fd42-4f73-8a05-9056ede1dc77.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ziskano z dat.

**Comment by Cypzirschova** [comment]
Rozpor to není, protože roky 2012-2016 nemohou být v SDNNT zpřístupněny. Periodiku začalo vycházet od roku 1997 a zdigitalizovány jsou pouze ročníky 2012-2016. Periodikum je zařazeno, protože vychází už od roku 1997 - tedy celek jako periodikum má A a pak se řeší jednotlivé ročníky.

**Comment by CIZKOVAL** [comment]
Děkuji, zavírám.
