### ISSUE TITLE
Pokud změním licenci u ročníku seriálu, tak se nepropíše  

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#275]
Dobrý den,
změnila jsem **stav a licenci** u konkrétního ročníku periodika z **N --> PA, licence dnntt**.

**Poté zobrazím granuralitu a vidím, že se stav u daného ročníku změnil, ale licence je prázdná.**

_Poznámka: v historii změn je uvedená změna stavu pro celek, nikoliv po jednoltivých ročnících, je to v pořádku?_

např. cnb001962850

![licence_SE](https://user-images.githubusercontent.com/92719629/154053850-3e2b57d2-b5e3-4d61-8ae0-c455a4e15d76.png)

![granuralita_PA](https://user-images.githubusercontent.com/92719629/154053894-70972853-27a9-4077-8a7a-dc3e678fd089.png)

**Comment by Cypzirschova** [comment]
Určitě by tam ta historie měla být úplná, tzn. i jednotlivé ročníky. Teď jsem si také zkoušela měnit stav u 1 ročníku a zbytek jsem nechala, jak je a vůbec se ta změna nepropsala do historie.

**Comment by Cypzirschova** [comment]
Vyřadila jsem 2 ročníky a zbytek nechala, jak je.
![Ročníky-změna](https://user-images.githubusercontent.com/86351100/154068062-b6831578-ec1c-4255-aaf4-1d6564e45f86.png)
![ročníky-změna00](https://user-images.githubusercontent.com/86351100/154068082-fd8a5ad6-7aa5-41bc-8cef-a07d819b93c1.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Přibyla nová záložka histore pro ročníky.

**Comment by CIZKOVAL** [comment]
Retest OK,
při zobrazení granurality se zobrazí změněná licence u jednoltivých ročníků.

V historii změn přibyla nová karta "Historie ročníků", kde jsou zobrazeny změny na úrovni ročníků.

![licence_rocniky](https://user-images.githubusercontent.com/92719629/159470404-7e5c702a-6c65-4100-81ea-eda7fc6ab63b.png)

![historie rocniku](https://user-images.githubusercontent.com/92719629/159470419-81049469-ba53-49f2-a8d2-8d402ee44137.png)
