### ISSUE TITLE
Aktualizace dat - PA nové návrhy

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#277]
Dobrý den,
jak často se aktualizují data na testu? K 1. 2. byly vystaveny nové návrhy (PA) a počet děl v aplikaci tomu neodpovídá.
Cypzirschová
![návrhy_PA](https://user-images.githubusercontent.com/86351100/154061613-8c93cc10-4a04-4af8-be82-40407f760396.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova Pokud vím, tak poslední update dnt setu na testu probíhal minulý nebo předminulý týden.  @smallcubes

**Comment by smallcubes** [comment]
spustím tedy reindex znovu: `api/index/import_dntset`

**Comment by pavel-stastny** [comment]
@smallcubes Já bych doporučil nejdříve vyřešit ten connection timeout.

**Comment by JanMeritus** [comment]
@smallcubes tvrdi ze harvest udelal

**Comment by Cypzirschova** [comment]
[cnb000131617, ISBN 80-202-0602-7](https://aleph.nkp.cz/F/?func=direct&doc_number=000558654&local_base=DNT)
[cnb000785406, ISBN 80-85920-56-5](https://aleph.nkp.cz/F/?func=direct&doc_number=000579630&local_base=DNT)
[cnb000397400](https://aleph.nkp.cz/F/?func=direct&doc_number=000609357&local_base=DNT)
[cnb000397401](https://aleph.nkp.cz/F/?func=direct&doc_number=000609358&local_base=DNT)
[cnb000486607, ISBN 80-902312-4-1](https://aleph.nkp.cz/F/?func=direct&doc_number=000571748&local_base=DNT)
[cnb000114859, ISBN 80-85984-03-2](https://aleph.nkp.cz/F/?func=direct&doc_number=000611000&local_base=DNT)
[cnb000027677](https://aleph.nkp.cz/F/?func=direct&doc_number=000610589&local_base=DNT)

Posílám namátkou 7 děl, které by měly mít stav PA od 1.2. Koukala jsem na to v aplikaci a našla jsem je všechna ve stavu A - dnnto, ale v historii je zapsaný pouze stav PA. Možná je to tou upravenou lhůtou, kterou tam máme na testování z PA na A? Vypadá to, že se tam díla dostala, ale po té zkrácené lhůtě se přehoupla do stavu A?
![PA1](https://user-images.githubusercontent.com/86351100/154969699-c139ba22-5f5c-4a42-acd6-8d1133423774.png)
![PA](https://user-images.githubusercontent.com/86351100/154969712-60bb431d-805c-4ad4-a27b-06866cbac688.png)

**Comment by Cypzirschova** [comment]
@pavel-stastny Udělala jsem kontrolu cca 10 děl, co jsou nově ve stavu PA a sedí to i ten celkový počet by mohl odpovídat.

**Comment by JanMeritus** [comment]
@Cypzirschova prosim pak po nasazeni o kontrolu na TEST

**Comment by Cypzirschova** [comment]
Počty sedí. Toto issue zavírám.
![Počty záznamů](https://user-images.githubusercontent.com/86351100/158121294-72726c0d-2e6a-44ad-9ebc-555f3f5a0483.png)
