### ISSUE TITLE
Některá díla nelze dohledat mimo seznam

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#278]
Dobrý den,
některá díla nelze dohledat ve filtru **"zobrazit i díla mimo seznam"**, příklady: 

**cnb001204148** - Název: Františka Matauše Klácela Dobrowěda

**cnb001120735** - Název: Démantová garnitura : polodrama / J. Arbes

- v Krameriovi ndk jsou díla vedená jako veřejná, očekávám tedy, že dílo by měl vidět pouze kurátor nebo knihovna ve filtru "zobrazit i díla mimo seznam". Filtr je nenajde ani podle identifikátoru ani podle názvu.

_Poznámka: už jsem zmiňovala v issue #177, ale dávám sem, aby nezapadlo._

![mimo_seznam_nenajde](https://user-images.githubusercontent.com/92719629/154064059-eb0e4718-cbc6-4bb5-b8c9-91ea49c2ec36.png)

cnb001120735

**Comment by pavel-stastny** [comment]
@CIZKOVAL Implicitní filtry.  Ještě v ranných dobách projektu @albertoh s paní @Lichtenbergova definovali filtry, které se mají vždy uplnatnit dle roku vydání knihy/časopisu.  Později se k tomu přidalo i filtr pro zahraniční díla. (Viz issue #164).  Ty také nepůjdou dohledat.

**Comment by CIZKOVAL** [comment]
Dobrý den, prosím tedy pana @albertoh o doplnění, jak je nyní filtr pro díla mimo seznam nastaven. 
Děkuji

**Comment by pavel-stastny** [comment]
@CIZKOVAL Jeste poznamka. Pokud má dílo jakýkoliv stav A,PA,N, NL ,X,PX pak už je dohledatelné i mimo tyto implicitní filtry, přičemž platí že stav X je viditelný až od knihovny výše.

**Comment by CIZKOVAL** [comment]
Děkuji, zavírám
