### ISSUE TITLE
HTTP 404: při zpracování

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#28]
Dobrý den,

zpracovávám-li pod účtem (`kurátor`) nějaký seznám a během toho refreshnu stránku, tak mi to vyhodí `HTTP status code 404`.

Děkuji za reakci.

**Comment by albertoh** [comment]
Opraveno

**Comment by smallcubes** [comment]
Odzkoušeno. Děkuji za vyřízení.
