### ISSUE TITLE
Notifikace - stav versus licence

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#283]
Dobrý den,
uživatel má na následujících dílech nastavenou denní notifikaci.

Díla byla původně ve stavu **PA online**, **A online** - jiný uživatel provedl žádost **VNZ** (omezení na terminál), kterou kurátor schválil - tím se změnila pouze licence na **dnntt** a změna se zapsala do historie změn.

V notifikacích je u těchto děl změna stavu na PA, A, i když se stav nezměnil.

**Nabízí se otázka, zda by v notifikacích neměla být zároveň informace o licenci.**

Název: Atletika v dělnických tělocvičných jednotách / Přemysl Ježek.
Identifikator: oai:aleph-nkp.cz:SKC01-001390999
Stav: PA
Odkaz: https://sdnnt-test.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-001390999

Název: Žižkova lebka v nálezu čáslavském / sepsal Ladislav Haškovec
Identifikator: oai:aleph-nkp.cz:DNT01-000427204
Stav: A
Odkaz: https://sdnnt-test.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:DNT01-000427204

**Comment by Cypzirschova** [comment]
Přikláním se k variantě přidat i licenci a změnit text u notifikace: Změna stavu/licence

**Comment by JanMeritus** [comment]
@CIZKOVAL @Cypzirschova souhlas, pro vydavatele je zasadni licence

**Comment by pavel-stastny** [comment]
@JanMeritus @Cypzirschova @CIZKOVAL Do sablony pridana moznost/vlastnost - `license`

**Comment by Cypzirschova** [comment]
Je toto již nasazené? Mám nastavené hromadné notifikace a v textu chybí info o změně licence, viz níže.
![Brambory1](https://user-images.githubusercontent.com/86351100/160988605-0064fa93-ce23-420d-9485-3c7c93d3242e.png)
![Brambory](https://user-images.githubusercontent.com/86351100/160988616-9678a17f-d317-4e1f-96b6-9bc18472d347.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova @smallcubes Musí se ještě modifikovat šablona na serveru.  Přidat následující řádek: 

`License: {{license}}`

**Comment by smallcubes** [comment]
@CIZKOVAL přenastaveno

**Comment by CIZKOVAL** [comment]
Dobrý den,
licence se **správně přiřadí** u **HROMADNÝCH** notifikací (vyzkoušeno VN-bez licence, VNZ-změna licence na terminál). Ještě ověřím NZN.

U notifikací, které jsou nastavené **JEDNOTLIVĚ** **se licence nepropíše**. Vyzkoušeny případy, kdy jde o změnu licence VNZ, NZN.

NZN - původně N, nyní A s licencí dnnto:

Název: Z Krásné knihy plné parády / V.H.B. ; [úvod] Kakejta
Identifikator: oai:aleph-nkp.cz:DNT01-000374783
Stav: A
**Licence:** 
Odkaz: https://sdnnt-test.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:DNT01-000374783

VNZ - původně A dnnto, nyní A dnntt:

Název: Výtvarná asanace obcí : Urbanistický přehled a směrnice / Předml.: Jaromír Štván
Identifikator: oai:aleph-nkp.cz:DNT01-000240765
Stav: A
**Licence:** 
Odkaz: https://sdnnt-test.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:DNT01-000240765

_Poznámka: u všech děl, které se zařadí do seznamu na základě NZN se automaticky přidá licence dnnto, je to v pořádku? Už se někde myslím řešilo..._

**Comment by Cypzirschova** [comment]
@CIZKOVAL K poznámce, založené issue #200

**Comment by CIZKOVAL** [comment]
Vyzkoušeno i hromadné NZN - licence OK. Dílům, která jsou v hromadné notifikaci se v emailu licence přiřadí, dílům z jednotlivé notifikace ne.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Vyřešeno komitem výše. Nechal jsem označené Done a až vydám verzi, označím ToTests

**Comment by Cypzirschova** [comment]
Včera otestováno a za mě je to OK. Díla, která měla jednotlivou notifikaci a změnila se licence, tak u těch vše proběhlo i v e-mailu byly všechny údaje včetně změny licence.

**Comment by CIZKOVAL** [comment]
Já jsem si nastavila data a zkontroluji 28.4. 2022

**Comment by CIZKOVAL** [comment]
Retest OK, licence se propisuje i u jednotlivých notifikací.

Vyzkoušeno VNZ, NZN, VNL, VN
