### ISSUE TITLE
Anonymní režim: automaticky přihlášen

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#29]
Dobrý den,

nevím, zdali je to spřávné chování, ale přijde mi to trochu zvláštní. Spustím-li _anonymní režim_ (Firefox, Chrome, Edge), tak jsem automaticky přihlášený pod nějakým účtem (_kurátor_).

Děkuji za reakci.

**Comment by albertoh** [comment]
Opraveno

**Comment by smallcubes** [comment]
Dobrý den, 

problém stále pořád přetrvává, pokud je už jedno okno v anonymním režimu (v tomto okně je už přihlášený uživatel) a otevřete-li nové v anonymním režimu, tak jste opět přihlášen. (Firefox, Chrome) - možná je to takto správně, ale nevím

**Comment by smallcubes** [comment]
@albertoh poprosím jenom o vyjádření, že se jedná o běžné chování (tak jak jsme se domluvili na setkání 20/7/2021)

**Comment by pavel-stastny** [comment]
@smallcubes Ano, jedná se o běžné chování. (Údaje o uživateli jsou uloženy v localStorage a ta se v případě nového tabu nebo okna sdílí. Pokud chrome kompetně zavřete a znovu otevřete v anonymním módu, localStorage je opět prázdná)

**Comment by smallcubes** [comment]
@pavel-stastny @albertoh děkuji za vyřešení a reakci. Opraveno a uzavírám.
