### ISSUE TITLE
OAI: počet záznamů v setu neodpovídá počtu uvedeném na frontpage

### ISSUE THREAD

**Issue by black23** [NLCR/SeznamDNNT#292]
Zkoušel jsem sklidit set "SDNNT-A". Na webu je uvedený počet záznamů 585600, přes OAI se jich stahovalo přes 4 mio, než jsem ho zastavil. Je to tak správně? Očekával jsem spíše ten stejný počet, jaký je uvedený.

**Comment by albertoh** [comment]
Opravil jsem zpusob strankovani.
Az bude nasazeno na devu muzete testovat. Ale doporucil bych to testovat na mensim setu, napriklad SDNNT-N

**Comment by black23** [comment]
Testovat na setu, který nepotřebujeme není řešení. Alespoň jednou potřebujeme celý set, abychom viděli, jak vypadají metadata, abychom zhodnotili jejich použitelnost pro použití v katalozích knihoven. Nyní se pokouším stáhnout set DNNTO, který by měl obahovat přesně ty záznamy, které potřebujeme. Zatím to stále běží.

**Comment by cbvk** [comment]
stahuji znovu set
https://sdnnt-test.nkp.cz/sdnnt/oai?verb=ListRecords&metadataPrefix=marc21&set=DNNTT

melo by vratit cca 32 000 zaznamu
vraci ale pres 600 000 zaznamu

???

diky za opravu

**Comment by JanMeritus** [comment]
@pavel-stastny @albertoh toto je kriticke issue, stale neopraveno, prosim o reakci na @cbvk

**Comment by black23** [comment]
DNTTO by měl obsahovat podle homepage 546887 záznamů, v odpovídajícím setu je to 700+. Problém není pravděpodobně ve stránkování, ale ve výběru záznamů do jednotlivých setů. 
Další dost důležitá věc: v NDK je online dostupných 107916, nikoli přes půl milionu záznamů.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/5516936/157873041-5feb6fb0-2fe1-4541-9d10-801b9132d6bb.png">
Pokud to k něčemu má být, potřebujeme v OAI setu mít je skutečně ty záznamy, které můžeme nalinkovat a uživatel si je může číst. Tituly, které do skupiny pod online licenci spadají, ale nejsou v žádném z Krameriů online nás vlastně nezajímají, protože takové záznamy stejně zahodíme. Jsme schopni si s tím poradit, ale bude s tím zbytečná práce na straně katalogů, nehledě na zbytečnou režii. Stáhnout 100k nebo 500k záznamů je obrovský rozdíl v čase k tomu potřebném. A stáhnout 500k a 400k zahodit je vyložené mrhání.
Také by mělo docházet při vyřazení ze DNNT také k označení záznamů jako "deleted" ve všech odpovídajících setech. Aby bylo snadné takové záznamy nadále nenabízet.

**Comment by JanMeritus** [comment]
@pavel-stastny @albertoh @pavelkocourek zde by sme ocenili hotfix bez nutnosti znova sklizet kompletne celu databazi, prosim dnes o reakci k dalsimu postupu - pripadne jsem k dispozici telefonicky

**Comment by pavel-stastny** [comment]
@JanMeritus Po domluvě s @albertoh.  

Tak při prvním pohledu na testovací instanci to vypadá v pořádku.  Resp. počet záznamů které vidíme v OAI response odpovídá uvodní stránce.   
Zkoušené sety:

-  https://test/sdnnt/oai?verb=ListRecords&metadataFormat=marc21&set=DNNTO
-  https://test/sdnnt/oai?verb=ListRecords&metadataFormat=marc21&set=DNNTT

![1](https://user-images.githubusercontent.com/675753/158143299-82f9e356-c91b-4f9e-9be8-25fedc525fda.PNG)
![2](https://user-images.githubusercontent.com/675753/158143317-5a001f12-04aa-4a75-8090-22e9f8e2e9e3.PNG)
![header](https://user-images.githubusercontent.com/675753/158143339-d9628e3e-3300-42ab-9977-6a3603bc4910.PNG)

Zkusíme proiterovat celé sety a dáme vědět.

**Comment by black23** [comment]
Zkuste si některý ze setů stáhnout harvesterem. Parametr "completeListSize" zobrazuje sice "546880"záznamů, ale při pokusu je harvesterem stáhnout jsem to zařízl na 700k+, protože to stále běželo. Konkrétně set DNNTO.

**Comment by black23** [comment]
Prosím, věnujte se i počtu záznamů v setu DNNTO. Nemá valného významu tam vystavovat záznamy, které nelinkují do Krameia na dokument, k prohlížení. Tzn bez vyplněného pole 856. Případně k tomu může být ještě další speciální set. Tam by mělo být lehce přes 100k záznamů. Rozumím proč je jich tak 500k. Jsou to všechny, které odpovádají licenci pro online přístup. Ale pokud jich kolem 400k není zatím zdigitalizováno, nepotřebujeme je do katalogů dávat. Potencionální zájemce ze strany uživatelů by to jen odradilo od používání. Naráželi by na značný počet záznamů, které si online stejně neprohlédnou. Má smysl vystavovat jen ty záznamy, které skutečně online jsou = obsahují odkaz do Krameria a pdpovídají licenci pro online prohlížení.

**Comment by pavel-stastny** [comment]
@black23 Zatím testováno pouze  na DEVu (ziskavali jsme pouze identifikatory a vypisovali cas): 

set DNNTT:  Pocet ziskanych identifikatoru 38228,  celkovy cas 406308 ms (necelych 7 minut) 
set DNNTO:  Pocet ziskanych identifikatoru 546932,  celkovy cas 4302024 ms (necelych 72 minut) 

Večer vyzkouším na testu.  

> Nemá valného významu tam vystavovat záznamy, které nelinkují do Krameia na dokument, k prohlížení. Tzn bez vyplněného
> pole 856. Případně k tomu může být ještě další speciální set

Popíšem jak to nakonfigurovat a NK se rozhodne, zda upraví stávající sety nebo vytvoří nové.  Necháme na zvážení @JanMeritus a @smallcubes

**Comment by JanMeritus** [comment]
@pavel-stastny diki za informaci

**Comment by pavel-stastny** [comment]
@zabak TEST nebo DEV ?

**Comment by black23** [comment]
@pavel-stastny rychlost na DEV tedy nedovedu posoudit, ale na TEST jsem 500k stahoval i 7 hodin. Není možné, že při připojení více klientů dojde k nějakému zpomalení? Myslím, že to systém měl být dimenzovaný na minimálně na stovky klientů zároveň. Pokud tedy uvažujeme o tom, že toto OAI bude primárním zdrojem pro data do katalogů knihoven. Což jediné dává smysl. Je z povahy OAI jasné, že celé sety se ideálně stáhnou 1x na začátku a následně už jen rozdíly. Ale stejně by měl systém být dostatečně robustní.

**Comment by pavel-stastny** [comment]
@zabak @cbvk @black23 Uz vidime kde je chyba.    Je to v implementaci.  Opravime a dame na dev a  test.

**Comment by pavel-stastny** [comment]
@black23 
> rychlost na DEV tedy nedovedu posoudit, ale na TEST jsem 500k stahoval i 7 hodin. 

To je hodne divne.  Po oprave vyzkousime pro iterovat vsechny sety.

**Comment by zabak** [comment]
V případě DC není potřeba to hrotit, stačí použít například toto https://www.loc.gov/standards/marcxml/xslt/MARC21slim2OAIDC.xsl

**Comment by JanMeritus** [comment]
@pavel-stastny bude mozne opravu nasadit bez kompletni reindexace stavajici 1.03? Radi by sme tento problem nechali otestovat ASAP

**Comment by pavel-stastny** [comment]
@JanMeritus Ano

**Comment by pavel-stastny** [comment]
@zabak Petře, můžete, prosím vyzkoušet OAI na testu ?  Je tam nasazena ta poslední oprava  3e018b2.   A případně jaké jsme měli časy při sklízení ?

**Comment by zabak** [comment]
@pavel-stastny počty sedí

DNNT 38320 záznamů, 3 min 11s
DNNO 546889 záznamů, 30 min 53s

**Comment by pavel-stastny** [comment]
@zabak Diky

**Comment by black23** [comment]
@pavel-stastny @zabak 
DNNO 546889: 57 minut 54 sekund

**Comment by pavel-stastny** [comment]
@black23 Díky :-)

**Comment by JanMeritus** [comment]
prosim jeste @cbvk o potvrzeni ze OAI odpovida (byla nasazen hotfix), dekuji

**Comment by cbvk** [comment]
Dobry den,

potvrzuji stazeni OK se spravnycmi pocty zaznamu
jeste studuji data

diky za vyreseni

s pozdravem
---
Jiri Nechvatal

sprava site JVK Ceske Budejovice
spravce projektu obalkyknih.cz
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Lidicka 1, 370 01 Ceske Budejovice, CZ
https://www.cbvk.cz
***@***.***
+420-386-111-202
+420-608-706-067
skype: nechvatj

Dne 2022-03-17 17:56, JanMeritus napsal:

**Comment by black23** [comment]
souvisí s #344

**Comment by pavel-stastny** [comment]
@black23 Toto issue bych už zavřel.  Titulek ani popis issue neodpovídá tomu co se řeší v issues #344.
