### ISSUE TITLE
Žádosti VNL a skrytí zpracovaných děl

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#293]
Dobrý den,
při zpracování žádosti VNL, kde uběhla lhůta 18 měsíců, se v žádosti skryjí i díla, která nejsou ještě zpracovaná (rozhodnutá kurátorem).
<img width="938" alt="VNL-rozhodnutí" src="https://user-images.githubusercontent.com/86351100/154674706-5ee43cf8-1728-4f91-9285-c566971bfbe3.png">
<img width="938" alt="VNL-rozhodnutí01" src="https://user-images.githubusercontent.com/86351100/154674711-3b9f03de-3584-481a-af30-f436a3d1a911.png">
Cypzirschová

**Comment by Cypzirschova** [comment]
@pavel-stastny

**Comment by CIZKOVAL** [comment]
@Cypzirschova toto je duplicita s https://github.com/NLCR/SeznamDNNT/issues/234

Podívejte a tuto kdyztak zavrete. dekuji

**Comment by Cypzirschova** [comment]
@CIZKOVAL Uzavírám, duplicitní s #234
