### ISSUE TITLE
Úvodní stránka: u záložek se neaktualizuje text

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#294]
Dobrý den,

pokud kliknu na *úvodní obrazovce* na záložku *Statistiky* a následně překliknu na jíné záložky, tak se text pro jednotlivé záložky neaktualizuje. (Firefox)

Problém jsem nalezl jenom na: Testu

https://user-images.githubusercontent.com/78028909/154972800-c2557874-e2d9-4f2d-b3b9-ba058896e629.mp4

**Comment by pavel-stastny** [comment]
@smallcubes Nedaří se mi nasimulovat.

**Comment by smallcubes** [comment]
@pavel-stastny zkoušel jsem to znova a také mi to nejde. Možná můžeme issue uzavřít a případně ho znova otevřeme?

**Comment by pavel-stastny** [comment]
@smallcubes S dovolením issue zavřu.

**Comment by smallcubes** [comment]
@pavel-stastny souhlasím, děkuji
