### ISSUE TITLE
Problematické řazení dle relevance

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#297]
Dobrý den,
v defaultu je zobrazeno řazení zobrazených děl dle relevance vzestupně (tj. od nejméně relevantního po nejvíce relevantní). Ve skutečnosti se ale řadí dle relevance sestupně, což je v pořádku (tj. od nejvíce relevantního po nejméně relevantní)

1. prosím tedy o **úpravu zobrazené šipky**
2. **je nutné mít možnost řadit dle relevance vzestupně?** viz komentář v [tomto issue](https://github.com/NLCR/SeznamDNNT/issues/65#issuecomment-939869195)
3. když zvolím jiné řazení, odhlásím se a poté se přihlásím (pod stejným nebo jiným uživatelem), tak se řadí dle relevance sestupně, ale **v názvu filtru zůstává viset poslední použité řazení**

### **1. prosím o úpravu šipky v defaultu**

![relevance_vzestupně_default](https://user-images.githubusercontent.com/92719629/155291906-9d601148-6a17-4ff4-a66e-c8a1e6d3ad49.png)

![relevance_sestupně](https://user-images.githubusercontent.com/92719629/155291993-1a3d6503-71b4-4ac5-91cd-5d5f7df6009d.png)

### **2. zajímá někoho nejméně relevantní dílo?**

![relevance_vzestupne](https://user-images.githubusercontent.com/92719629/155292015-6894685a-d952-48ac-96d3-5f2e7811ad31.png)

### **3. zůstává viset název posledního použitého filtru**

![rok_vydani_vzestupne](https://user-images.githubusercontent.com/92719629/155292486-78e02ffb-f442-4200-8cde-9c5425264fe0.png)

![nove_prihlaseni](https://user-images.githubusercontent.com/92719629/155292507-a6657034-c9a2-432e-ba86-cff34a41e121.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL 
1) Změněno
2) Nyní relevance jenom sestupně
3) Po odhlášení se ruší nastavené třídění

**Comment by CIZKOVAL** [comment]
Retest OK, zavírám.
