### ISSUE TITLE
SDNNT API /request - Návrhy a požadavky, vráti len status "waiting_for_automatic_process"

### ISSUE THREAD

**Issue by Romx98** [NLCR/SeznamDNNT#298]
Dobrý deň,

chcel by som sa informovať, či som správne pochopil endpoint /request. Skúšal som obmedziť dielo na terminál / VNL. Zobrazil sa mi v state: waiting.
![waiting](https://user-images.githubusercontent.com/47435706/155539499-0a397992-dcbf-4d2d-8013-d7e905dfab0c.png)

Predpokladám, že ak by som si chcel pozrieť Moje požiadavky, tak môžem použiť endpoint /request, kde sa nachádza sekcia status v ktorej si vyberiem waiting a pozriem sa ako sú natom moje žiadosti. Avšak, jediný výstup dostanem proces so statusom "waiting_for_automatic_process". Poprípade ak nezvolím žiaden parameter tak sa mi zobrazí znovu len proces "waiting_for_automatic_process". 
![request](https://user-images.githubusercontent.com/47435706/155540323-43417d52-8c94-4afa-b698-187c4e9fcdda.png)

Moja otázka znie, k čomu slúží status: waiting ? 

Vopred ďakujem za odpoveď.

**Comment by pavel-stastny** [comment]
@Romx98 Dobrý den,  jenom abych rozuměl.  Vy jste podal žádost VNL přes API a tu nevidíte ve výpisu všech žádostí ani v API ani v UI ? 

Ad stavy žádostí 

- status:`waiting` - Čeká na posouzení kurátorem
- status: `waiting_for_automatic_process`  - Čeká na automatické zpracování.  Například u stavu PA, kdy musí být dílo nejdříve 6 měsíců ve stavu návrhu a pak se může překlopit do stavu A (Je na seznamu)

**Comment by Romx98** [comment]
@pavel-stastny Dobrý deň, procesy waiting vidim na UI, avšak pomou API vidim len procesy s označením waiting_for_automatic_process.

Viz. screenshot mojich požiadavok.
![obrazek](https://user-images.githubusercontent.com/47435706/155684692-54f83db5-938f-41cb-913c-030cc24ac980.png)

**Comment by pavel-stastny** [comment]
@Romx98 Prověříme.   Přes API by mělo být vidět vše co uživatel vidí v UI.

**Comment by JanMeritus** [comment]
@smallcubes pokud mozno zaridit u nas, prosim o retest

@Romx98 prosim o retest

**Comment by smallcubes** [comment]
@pavel-stastny @Romx98 vypadá to v pořádku issue uzavířám
