### ISSUE TITLE
Tlačítko: Schválení pro terminál - nefunguje

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#30]
Dobrý den,

při zpracování _návrhu na vyřazení_ pod účtem _kurátor_ mi přijde, že nefunguje tlačítko: _Schválit změnu pouze na terminál_ nebo není dána nějaká zpětná vazba.

Děkuji za reakci.

**Comment by albertoh** [comment]
To je nedoresena funkce z me strany. Spise otazka: jaky stav bude pro provedeni toto akci, NZ? nebo A a NZ?

**Comment by smallcubes** [comment]
@Cypzirschova @JanMeritus myslím, že se dotaz od @albertoh řešil, ale pro jistotu upozorňuji.

**Comment by JanMeritus** [comment]
po provedeni teto akce bude dilo ve stavu `NZ` - podstatne vsak je ze bude mit priznak ktery se mapuje na licenci `DNNTT`

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o status

**Comment by pavel-stastny** [comment]
@JanMeritus Je jiz soucasti buildu.  Stavy, ktere dilo ma po omezeni jsou "A" a "NZ"

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za vyřešení.
