### ISSUE TITLE
Žádost - NZN

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#300]
Dobrý den,
v aplikaci dorazila žádost s podivným záznamem. 
![NZN](https://user-images.githubusercontent.com/86351100/156120972-f31b6571-8b3a-4272-b10a-e75098506147.png)
Cypzirschová

**Comment by Cypzirschova** [comment]
@pavel-stastny

**Comment by CIZKOVAL** [comment]
@Cypzirschova tuto žádost založil kolega z MZK zřejmě přes API, ověřuji přes email

**Comment by Cypzirschova** [comment]
Děkuji za informaci.

**Comment by CIZKOVAL** [comment]
Dobrý den,
zavírám toto issue, tuto žádost založil kolega z MZK přes API a data jsou smyšlená.

**Comment by Cypzirschova** [comment]
Dobrý den, děkuji za informaci. To si tam může takhle kdokoliv vymýšlet nějaké informace? Myslela jsem, že vybírají ze svých děl ze svého katalogu?
D. Cyp.

**Comment by pavel-stastny** [comment]
@Cypzirschova To dilo musi byt pritomno v katalogu, resp indexu ktery odpovida katalogu.  Jinak by to neproslo ani pres API a neslo by to videt ani v UI.

**Comment by Cypzirschova** [comment]
@pavel-stastny 
Děkuji za info.
