### ISSUE TITLE
VNL - 2 žádosti a stejný obsah žádosti

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#301]
Dobrý den,
v mých požadavcích mám 2 totožné žádosti a obsahem je 1 stejné dílo. Nejde mi to schválit ani jedna žádost. Zkoušela jsem to hromadně i ručně a ani jedno nefunguje. @pavel-stastny 
![VNL- stejné dílo](https://user-images.githubusercontent.com/86351100/156121888-9cf55f07-0cb3-432a-adcc-816edd6c0aaa.png)
![VNL- stejné dílo1](https://user-images.githubusercontent.com/86351100/156121902-f13d5091-0e10-42ce-9780-138e32a22e36.png)
Cypzirschová

**Comment by CIZKOVAL** [comment]
@Cypzirschova u těch vaich žádostí to skutečně nejde schválit. Já jsem založila 2 stejné žádosti VNL (každá obsahovala 2 stejná díla) a 1 žádost schválit šla, druhá už ne, tedy v pořádku.

**Comment by Cypzirschova** [comment]
Tady bohužel nejde ani jedna.

**Comment by pavel-stastny** [comment]
@Cypzirschova Dílo má již licenci dnntt.  Proto nejde schválit.

**Comment by Cypzirschova** [comment]
Uzavírám, vyřešeno - moje nepozornost.
