### ISSUE TITLE
Připomínky k aplikaci 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#303]
Dobrý den,
dostali jsme od pana R. Zahoříka zpětnou vazbu na aplikaci. Níže přikládám připomínky, které jsme dostali:

"z pohledu neprihlaseneho uzivatele – ctenare:
-	po vyhledani zaznamu dostavam seznam vysledku, ve kterem chybi informace o existenci digitalni kopie, prip. odkaz na digitalni kopii a nelze zobrazit detail zaznamu
-	seznam vysledku nelze omezit pouze na digitalizovane dokumenty

Z pohledu prihlaseneho / registrovaneho uzivatele – ctenare:
-	po vyhledani zaznamu dostavam seznam vysledku, ve kterem chybi informace o existenci digitalni kopie
-	seznam vysledku nelze omezit pouze na digitalizovane dokumenty
-	nelze zobrazit detail zaznamu, pouze zobrazit zaznam v katalogu – v pripade statusu „A“ a „N“ vede odkaz do baze DNT, která od 1.4.2022 jiz nebude existovat! 
-	pokud je u zaznamu vice odkazu na digitalni kopie, odkazy nejsou odliseny popiskem 

Tagy „Licence pro online pristup“ a „Licence pro terminal“ a prislusne pocty zaznamu mohou byt zavadejici. Mely by byt pridelovany pouze dokumentum
zdigitalizovanym v NK, MZK resp. KNAV, které poskytuji digitalni obsah v rezimu DNNT

Pokud jde o odkazy do katalogu – toto „reseni“ je opravdu nezadouci, protoze
-	aplikace DNNT byla od zacatku postavena jako zcela samostatna, navrh na moznost komunikace s Alephem přes API byl hned na zacatku odmitnut. Aplikace ma k dispozici
kompletni metadata stazena ze SKC a je tedy mozne zobrazit detail zaznamu primo v aplikaci  
-	aplikace DNNT a Souborny katalog jsou graficky nekompatibilni
-	kazde zobrazeni zaznamu znamena vycerpanou WWW-licenci Aleph. V pripade prohlizece Firefox se po kliknuti na odkaz zobrazi zaznam v katalogu 2x – tj. 2 vycerpane WWW-licence
(v ostatnich prohlizecich se to nestava)".

Cypzirschová
@JanMeritus @Lichtenbergova

**Comment by JanMeritus** [comment]
Tagy „Licence pro online pristup“ a „Licence pro terminal“ a prislusne pocty zaznamu mohou byt zavadejici. Mely by byt pridelovany pouze dokumentum zdigitalizovanym v NK, MZK resp. KNAV, které poskytuji digitalni obsah v rezimu DNNT

- prosim o vyjadreni @Cypzirschova @Lichtenbergova

**Comment by Cypzirschova** [comment]
Nechalo by se tak, jak je nastaveno v aplikaci, akorát by bylo někde v úvodu upozornění, že se jedná o nástroj, kde jsou evidované **možné licence. Uplatní se v DNNT na digitalizovaná díla.** 

Odkazy do katalogu viz #314

**Comment by Cypzirschova** [comment]
1. **Z pohledu neprihlaseneho uzivatele – ctenare:** Aplikace je určená primárně pro knihovny a nositele práv (vyřízení požadavků - návrhy na zařazení, návrhy na vyřazení atd.).
2. **Z pohledu prihlaseneho / registrovaneho uzivatele – ctenare:** Lze vyfiltrovat díla, která mají odkazy do DK + se lze dostat na odkazy do DK - jsou odlišeny. Jsou zde i odkazy na záznamy do SKC.
3.  založeno issue #314
