### ISSUE TITLE
Pridat filtr digitalni kopie

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#306]
Pridat filtr pro zobrazeni subsetu zaznamu obsahujicich jenom odkazy do digitalnich knihoven

**Comment by luckajirku** [comment]
Podle D. Cypzirschové se toto issue týká našeho problému, takže připisuji...
Pokud je to jen trochu možné, prosíme o přidání fasety Digitální knihovna.
Abychom mohli reagovat ve smluvně stanovené lhůtě reagovat na změny v SDNNT, potřebujeme mít možnost si jednoduše vyfiltrovat pouze tituly, které máme v naší DK. 
Faseta Sigla problém neřeší, potřebujeme tu množinu omezit pouze na ty tituly, které máme v DK, nikoli vyhledat všechny, které máme fyzicky ve fondu (nezávisle na tom, jestli je máme zdigi nebo ne). 
Pro DK, která vše ověřuje ručně, je tohle dost podstatné (ať už pro cílené kontroly či základní nastavení notifikací).

**Comment by smallcubes** [comment]
Faseta digitální knihovna byla zřízena
