### ISSUE TITLE
Špatné označení díla po posouzení návrhu

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#31]
Dobrý den,

pokud zařadím dílo pod účtem _(knihovna)_ na seznam _návrh na vyřazení_ a poté ho jako _kurátor_ zamítnu, tak se změní stav záznamu na vyřazeno: _vyřazeno - dílo bylo na seznamu (A)_

Děkuji za reakci.

**Comment by smallcubes** [comment]
pokud nejprve záznam _schválím_ a následně ho _zamítnu_, tak dílo zůstane vyřazené: _vyřazeno - dílo bylo na seznamu (A)_

**Comment by albertoh** [comment]
Po schvaleni zmizi moznost zamitnout

**Comment by smallcubes** [comment]
@albertoh asi v pořádku, i když je škoda, že už to nelze změnit (tak jak to bylo předtím). Děkuji Vám za vyřízení a uzavírám.
