### ISSUE TITLE
Pridat odkaz do SKC i pro role Knihovna

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#310]

**Comment by JanMeritus** [comment]
@smallcubes @CIZKOVAL je to overeno?

**Comment by smallcubes** [comment]
Odkaz se zobrazuje u děl mimo seznam (SKC) pro roli knihovna, viz obrázek. Pro dílo na seznamu se mi žádný odkaz nepodařilo dohledat. @CIZKOVAL @Cypzirschova 

![obrazek](https://user-images.githubusercontent.com/78028909/161962053-2080f321-bf15-472e-b754-c14ad3a5010b.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova @CIZKOVAL Toto bylo asi nedorozumění...  Takže odkaz do SCK na dílo se stejným ČČNB má být dostupné i pro roli knihovna ?

**Comment by Cypzirschova** [comment]
@pavel-stastny 
Ano, mělo by to být dostupné pro kurátory a knihovny.

**Comment by Cypzirschova** [comment]
Za mě je to OK.

**Comment by smallcubes** [comment]
@Cypzirschova děkuji, issue uzavírám.
