### ISSUE TITLE
Odkaz se dvakrat otevre - Firefox

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#311]
> V pripade prohlizece Firefox se po kliknuti na odkaz zobrazi zaznam v katalogu 2x – tj. 2 vycerpane WWW-licence

vcera sme testovali, taky u nas (tj tyka se Win i Ubuntu)

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Již by se tak nemělo chovat. můžete verifikovat na DEVu ?

**Comment by JanMeritus** [comment]
@smallcubes @CIZKOVAL prosim o retest

**Comment by smallcubes** [comment]
Je-li tím myšleno odkaz do SKC, tak je to v pořádku a issue se může uzavřít. @JanMeritus
