### ISSUE TITLE
Dockerizace

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#316]

**Comment by smallcubes** [comment]
@pavel-stastny @JanMeritus Nasazení sdnnt v Dockeru proběhlo úspěšně na **produkci** [sdnnt.nkp.cz](https://sdnnt.nkp.cz). Nic dalšího jsem zatím netestoval.

Při zprovoznění jsem narazil na následující:
- Base image je nejspíše CentOS 7, ten by se měl asi za něco změnit? @JanMeritus 
- V repozitáři chybí soubor `usage`, bez něj mi nešelo vytvořit docker images (+ chybí informace o tom, že by soubory měly být executable)
- pro překlad záložek na hlavní straně se musí nastavit mapování v sdnnt: `assets/i18n/cs.json` a `assets/i18n/en.json` to se dělá velmi těžko v Dockeru, Mohlo by to být v config.json nebo mohla by si to aplikace udělat automaticky?
- během buildu image na mě vykočil Warning, ale nevím jak moc je to důležité (raději to uvádím): 
```
s2i build WARN: `I0414 12:30:34.571588 1624296 sti.go:715] npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

**Comment by smallcubes** [comment]
@pavel-stastny nakonec by bitnami solr image měl být dle repozitáře založen na [debianu](https://github.com/bitnami/bitnami-docker-solr), takže asi vše v pořádku.
