### ISSUE TITLE
Reindex: trvá příliš dlouho

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#317]
Reindex trvá přiliš dlouho, první část běžela cca 6 dnů. Konkrétně se jednalo o příkaz `curl .../sdnnt/api/index/full`

Nastavení v `.sdnnt/configu.json`:
```
"OAIHavest": {
  "url": "http://aleph.nkp.cz/OAI",
  "numrepeat": 3,
  "seconds": 30
},
```

1. část: `curl /sdnnt/api/index/full`
```
 {"indexed": {
  "ellapsed": "142:56:13.346",
  "resumptionToken": "202203090902064999999999999999SKC:SKCM",
  "indexed": 8124235
}}
```

2. část `curl /sdnnt/api/index/import_dntset`
```
{
  "resumptionToken": "202108011221274999999999999999DNT-ALL:DNT-ALLM",
  "error": "cz.inovatika.sdnnt.index.exceptions.MaximumIterationExceedException: Maximum number of waiting exceeed"
}
```

Known issues: 
- síťový problém na straně alephu `Connect to aleph.... [aleph.../....] failed: Connection timed out (Connection timed out)`, pro více viz #217 

@JanMeritus

**Comment by smallcubes** [comment]
na záladě 2. části byl počet opakování zvýšen na 30 ` "numrepeat": 30`

**Comment by JanMeritus** [comment]
@nk-mila to tu hladal

**Comment by nk-mila** [comment]
@smallcubes  @JanMeritus  analyzoval jsem komunikaci SDNNT -> aleph:80 na straně alephu, tj. provoz ve veřejné síti 195.113.134.1 -> 195.113.132.85 s tímto závěrem: Na aleph přijde v rozmezí cca 60s několik žádostí o komunikaci ( SYN packet ), aleph je zhusta ignoruje ( nevidím ACK,SYN ). Když odpoví, pak stahování dat probíhá plynule: na cca 6k5 dat odeslaných z DNNT aleph vrátí 300 až 420kB v každé z cca 90 výměn ( flows ). To se mi zdá normální. Nenormální je fakt, že neodpoví na SYN packet, tj. otevření session ( sekvence flows ). Důvodem může být např. přetížení nebo pokus odeslat data zpět vnitřní sítí ( kdyby se domákl, že SDNNT je v interní síti ) - to nevím odkud. Ale je tam od léta předřazeno iptables. Ještě se podívám na jinou komunikci z veřejné sítě pro porovnání....

**Comment by nk-mila** [comment]
@JanMeritus @inowit  Vcelku bez výsledku jsem změnil výstupní adresu do veřejné sítě na 195.113.133.50. Komunikace je v příloze. Syn paket odesílaný z CDH  ( port11) neprojde z port12 do vlan knihovna. To se stává občas, nakonec se podaří, ale trvá to i minuty. nechápu proč je to tak nahodilé. Test v neděli kolem 16:00, provoz na FG nevýznamný ( pod 100Mb/s ) Problém zřejmě nesouvisí s vypnutím KLM boxu, dle analyzátoru problémy se SYN  byly i před 3.3T14:xx. Prosím předat s přiloženým txt souborem na Inowit (p.Loupalovi). Děkuji
[sdnnt-aleph-err.txt](https://github.com/NLCR/SeznamDNNT/files/8240010/sdnnt-aleph-err.txt)

**Comment by inowit** [comment]
@JanMeritus @nk-mila 
Předal jsem na Petra

**Comment by JanMeritus** [comment]
@inowit jsu nejake vysledky? toto je zasadni blocker

**Comment by inowit** [comment]
@JanMeritus 

Opraveno, bylo limitováno DOS senzorem který nedělal rozdíl mezi interním a externím trafficem. 
Upraveno tak aby se ignorovaly limity pro interní traffic.
Další téma pro koncepci FW.

**Comment by JanMeritus** [comment]
@inowit  diki, overime

@smallcubes prosim pri dalsi sklizni uvest zde casovy posun

**Comment by smallcubes** [comment]
poslední reindex DNT setu (`curl /sdnnt/api/index/import_dntse`) trval 1h 24m verze 1.0.4 `cz.inovatika.sdnnt.index.DntAlephImporter.getRecords FINISHED: 606,069. reqTime: 1:24:02.377. procTime: 0:00:45.449. solrTime: 0:35:36.119`

**Comment by smallcubes** [comment]
poslední reindex SKC (`curl /sdnnt/api/index/full`) na sdnnt-prod trval 34h 45m verze 1.0.4

`30-Mar-2022 20:28:20.666 INFO cz.inovatika.sdnnt.index.OAIHarvester.full full FINISHED. Indexed 34:45:39.045 in 8,132,075`

@JanMeritus @pavel-stastny

**Comment by smallcubes** [comment]
@pavel-stastny chtěl bych se ještě zeptat, zdali mohu nějak nastavit inkrementální reindex pro SKC

@JanMeritus

**Comment by pavel-stastny** [comment]
@smallcubes `sdnnt/api/index/update`

**Comment by smallcubes** [comment]
@CIZKOVAL @JanMeritus inkrementální update je nastaven na: každé pondělí ve 02:00

**Comment by smallcubes** [comment]
Reindexy probíhají rychle. Děkuji @pavel-stastny za úpravu.
