### ISSUE TITLE
Rozhraní (účet: knihovna) je rozbité

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#32]
Dobrý den,

rozhraní pro účet _knihovna_ je rozbité viz obrázek (Firefox, Chrome). Možná probíhají změny, ale raději upozorňuji.

![obrazek](https://user-images.githubusercontent.com/78028909/126148796-38448eb0-d1c9-48be-89bc-e7e42d0dc7c3.png)

**Comment by albertoh** [comment]
Byly tam rozbita data, kvuli opravam co jsem delal, behem dne.
Procistil jsem to

**Comment by smallcubes** [comment]
Problém se už nevyskytuje.

**Comment by smallcubes** [comment]
Problém byl vyřešen. Děkuji za vyřízení.
