### ISSUE TITLE
Díla mimo SDNNT - omezení

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#320]
Dobrý den @pavel-stastny, 
je možné v aplikaci měnit omezení na díla mimo SDNNT, která jsou v aplikaci nastavená. Konkrétně myslím roky. Zřejmě je tam teď nastaven asi rok 2007, ale do budoucna je potřeba tuto hranici posouvat. Je možné, aby to p. @smallcubes mohl upravovat?
Níže pro ukázku - díla vydána v r. 2009. 
![Díla mimo SDNNT](https://user-images.githubusercontent.com/86351100/157869759-c12d537a-a510-41fa-bda6-5aa7f27219c5.png)
D. Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova @smallcubes Vyhledávání je možno ovlivnit konfigurací: 

```
"search": {
    "fromYear": 1911,
    "yearsBK": 14,
    "yearsSE": 10
  },

```

Určující je rok vydání. Klíč `fromYear `určují spodní hranici, `yearsBK `a `yearsSE `pak horní.  Horní hranice je počet let dozadu od nynějšího roku.

**Comment by Cypzirschova** [comment]
@smallcubes Je to pro Vás dostačující? Mohu issue uzavřít?

**Comment by smallcubes** [comment]
@CIZKOVAL 

zkoušel jsem následující nastavení:
```json
"server": {
	"search": {
			"fromYear": 1911,
			"yearsBK": 07,
			"yearsSE": 14
	},
}
```
Přijde mi, že strop nefunguje. Nastavil jsem 2007, ale viděl jsem knihy mimo seznam i nad rok 2007 např. 2008 = 28277

**Comment by Cypzirschova** [comment]
@smallcubes 
Také mi to našlo stejný počet a nedostanu se na záznamy. Odkáže mě to na záznam, který už neexistuje. 
![SKC1](https://user-images.githubusercontent.com/86351100/161757054-464edc90-ed33-4dca-9afc-a37bce21689b.png)

![SKC](https://user-images.githubusercontent.com/86351100/161757037-0a40ee5a-93a4-4271-9ec3-28271318f8f0.png)

**Comment by pavel-stastny** [comment]
@smallcubes Ta horní hranice je pohyblivá a klíč určuje počet let od nynějšího roku. Tedy  pokud zadáte 7, měly by se ve výsledcích objevovat tituly do roku 2015.    

A stejně jako tomu bylo u procesu vyřazování, používá se controlfield 008.

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova zkusil jsem tedy nastavit následovně: `"yearsBK": 1` (Aktuální hranice by měla být 2007, takže rok 2008). Nicméně po vyzkoušení roku 2010 vidím 26094 záznamů mimo seznam.

**Comment by Cypzirschova** [comment]
Také jsem vyzkoušela a mám stejný počet záznamů. Díla nejdou zařadit do SDNNT, viz níže.
![Mimo seznam](https://user-images.githubusercontent.com/86351100/161925084-56289436-0e9a-4c36-b40c-ef434bd6db38.png)

**Comment by pavel-stastny** [comment]
@smallcubes To je vše až do roku 2021.    Pro rok 2008 dejte následující konfiguraci: 

`"yearsBK": 14
`

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova  zkusil jsem nastavit  `"yearsBK": 14` a omezí to až od roku 2010. 2009 má 3 záznamy.

nastavení: 
```json
"server": {
    "search": {
            "fromYear": 1911,
            "yearsBK": 14,
            "yearsSE": 14
    },
},
```

**Comment by smallcubes** [comment]
Díla:
1. Horoskopy pro každého na rok 2009 / Olga Krumlovská, 978-80-7360-792-0
2. Celostní ošetřování kopyt koní / Hiltrud Straßer ; [z německého originálu ... přeložila Pavlína Ziková], cnb002778695, 978-80-86975-99-3
3. Manželka pro krále / Rebecca Wintersová ; překlad Tomáš Ječný, 978-83-238-5776-1 :

**Comment by pavel-stastny** [comment]
@smallcubes @Cypzirschova 

> Horoskopy pro každého na rok 2009 / Olga Krumlovská, 978-80-7360-792-0

Pole 008:        `090122s2008    xr           u||| | cze`  
Marc_260:      `2009`

> Celostní ošetřování kopyt koní / Hiltrud Straßer ; [z německého originálu ... přeložila Pavlína Ziková]

Pole 008:       `080128s2007    xr a   e f    000 0 cze`  
Marc_260:    `2009`

> Manželka pro krále / Rebecca Wintersová ; překlad Tomáš Ječný,

Pole 008:       `121020s2007    xr ||||||||cze000 0|cze d`  
Marc_260:    `c2009`

**Comment by Cypzirschova** [comment]
@pavel-stastny 
Ověřila jsem, je to špatně zpracované v SKC (první dva případy). 

U toho třetího jsem dnes v SKC našla záznam se správnými údaji:
V poli 008 - r. 2009 i v poli 260, ale místo vyd. je Polsko.

**Comment by pavel-stastny** [comment]
@Cypzirschova U toho třetího záznamu pomůže update SKC indexu.

**Comment by Cypzirschova** [comment]
@pavel-stastny 
První dva záznamy jsem předala dál k ověření.

**Comment by pavel-stastny** [comment]
@Cypzirschova U třetího díla vidím po updatu následující: 

`121020s2009    pl ||||||||cze000 0|cze d`

Na devu již dohledatelné není

**Comment by Cypzirschova** [comment]
@smallcubes Bylo by možné otestovat posun u BK na rok 2008 - navrhovat se budou knihy vydané v r. 2008 ze SKC? Po otestování bych issue uzavřela. Chci si jen ověřit, že to funguje.

**Comment by Cypzirschova** [comment]
@smallcubes oprava - rok 2009

**Comment by CIZKOVAL** [comment]
@smallcubes prosím nastav proceduru, aby se braly díla do roku 2009 včetně, tj.:

"search": {
    "fromYear": 1911,
    "yearsBK": 13,
    "yearsSE": 13
  },

diky

**Comment by smallcubes** [comment]
@CIZKOVAL @Cypzirschova přenastaveno

**Comment by Cypzirschova** [comment]
@CIZKOVAL @smallcubes Pouze knihy (BK) do roku vydání 2009-včetně.

**Comment by Cypzirschova** [comment]
Zatím mi to našlo pouze 5 knih, pokud omezím mimo seznam a rok 2009.

**Comment by Cypzirschova** [comment]
Už je to funkční. Ve vyhledávání mi to našlo přes 25 tisíc výsledků. Za mě je to v pořádku. Nevím, zda bude ještě paní @CIZKOVAL testovat nebo jestli mohu uzavřít?

**Comment by CIZKOVAL** [comment]
@Cypzirschova ano, také mi to našlo přes 25 tisic zaznamu, ale pak jsem si dala vyfiltrovat knihy i mimo seznam po roce 2009 a naslo mi to 3 díla (to 1. je OK, protože je na seznamu, takze se ho omezeni netyka, ale ty dalsi 2 maji v poli 008 horni hranici roku 2003 a 2009 jestli tomu dobre rozumim). Tato díla by se zde vyskytovat neměla...

Kdo byl kdo je kdo na východní Moravě. Fi-Ju / [Josef Fabián, Kateřina Janásková, Hana Ševčíková a kolektiv]
oai:aleph-nkp.cz:SKC01-004333046

008: 100825m20092009xr-c|||e|d||||000-0ccze||

Volání na ďábla / Wilbur Smith ; [z anglického originálu ... přeložil Václav Vanduch]
oai:aleph-nkp.cz:SKC01-008169706

008: 030718s2003----xr-----e------000-1-cze--


![knihy](https://user-images.githubusercontent.com/92719629/164457073-62fbd84d-e048-481d-90ea-6bd1b05596f8.png)

![2009](https://user-images.githubusercontent.com/92719629/164457133-d751e370-5d10-49f0-8705-530a6a5f5200.png)

![2003](https://user-images.githubusercontent.com/92719629/164457108-30f5d0cb-dc34-4fbd-9ce7-15421b156a78.png)

**Comment by CIZKOVAL** [comment]
@Cypzirschova, @smallcubes po vyřešení problému pak ještě prosím, jak má být nastaveno omezení pro knihy a seriály mimo seznam, abychom to vrátili do původního stavu.

**Comment by Cypzirschova** [comment]
Mě při stejném nastavení filtru našlo pouze dílo Volání na ďábla. 

Tady tomu moc nerozumím, protože kdyby se hledalo jen podle pole 008, tak ve Vašem nastavení let, by se ta díla neměla objevit (2009 a 2003).

 V poli 260 je rok 2010, 2011 a Vy jste si roky omezila 2010-2022. Tak jsem teď trochu zmatená, podle jakého pole se vyhledává v SKC. Prosím @pavel-stastny, podle jakého pole se tedy vyhledávají záznamy ze SKC do seznamu?
> Kdo byl kdo je kdo na východní Moravě. Fi-Ju / [Josef Fabián, Kateřina Janásková, Hana Ševčíková a kolektiv] _oai:aleph-nkp.cz:SKC01-004333046_
> 
> **008: 100825m20092009xr-c|||e|d||||000-0ccze||**
> 

Tady je chybně zpracovaný záznam. V 008 je rozpětí let 2009-2009 a v 260 je rok 2010. 

> Volání na ďábla / Wilbur Smith ; [z anglického originálu ... přeložil Václav Vanduch] _oai:aleph-nkp.cz:SKC01-008169706_
> 
> **008: 030718s2003----xr-----e------000-1-cze--**

Stejná situace jako výše. V poli 008 rok 2003, ale v poli 260 rok 2011.

**Comment by pavel-stastny** [comment]
@Cypzirschova 

> Tady tomu moc nerozumím, protože kdyby se hledalo jen podle pole 008, tak ve Vašem nastavení let, by se ta díla neměla objevit (2009 a 2003).
> 
> V poli 260 je rok 2010, 2011 a Vy jste si roky omezila 2010-2022. Tak jsem teď trochu zmatená, podle jakého pole se vyhledává v SKC. Prosím @pavel-stastny, podle jakého pole se tedy vyhledávají záznamy ze SKC do seznamu?
> 

Abychom si rozuměli, tak to radši rozdělím na dvě části:   

**Implicitní filtry.** 

Ty které jsou na pevno svázané s rolí a uživatel nevyhledá/nedostane žádné dílo mimo tyto filtry.  Nejdou uživatelsky měnit, nedá se, třeba přes api, vyhledat dílo mimo tyto filtry. 

**Běžný uživatel** má možnost hledat/ filtrovat mezi díly, které mají nějaký stav ale nesmí to být stav X 
**Knihovna/kurátor/hlavní kurátor** má možnost hledat/filtrovat mezi všemi díly které mají nějaký stav (včetně stavu X) a zároveň má možnost "přidat" díla mimo seznam ale pro ně platí podmínka z konfigurace. Pole 008 a datum v rozmezí dané konfigurací. Pro výše zmíněnou konfiguraci 

```
"search": {
   "fromYear": 1911,
       "yearsBK": 13,
        "yearsSE": 13
},

```
to je vše mezi lety 1911 - 2009 včetně. 


**Uživatelské filtry/fasety.** 

Pokud už má uživatel seznam výsledků (a ten je dán těmi konfiguračními pravidly) může nad seznamem filtrovat podle toho co mu nabízí fasety na levé straně (Sigla, Formát, Nakladatel, Datum vydání).  Ale ty jsou většinou složeny z marcových polí a odpovídají tomu, co uživatel vidí v kartách výsledků.

![image](https://user-images.githubusercontent.com/675753/164661515-fad3df78-58ec-45ee-988e-36918d4d82ec.png)
¨
![image](https://user-images.githubusercontent.com/675753/164665282-20549e3b-9bd7-4d76-876c-ae77ac09fee0.png)

A to je příklad i data vydání.  Zobrazuje se datum vydání z marc_260 proto se **uživalsky** filtruje i dle tohoto pole. 

K výše uvedeným příkladům.  Myslím že tituly s roky 2003 a 2009  (dle pole 008) se ve výsledích objevit měly.  U těch dvou titulů je problém chybně zpracovanýh záznamech, resp. rozdílných honotách v polích 008 a marc_260. 


Snad jsem to vysvětlil srozumitelně.

**Comment by CIZKOVAL** [comment]
@pavel-stastny děkuji za vysvětlení. Já rozumím tomu, že když uživatel vidí na kartě u konkrétního záznamu nějaké další údaje, tak ve fasetách nalevo už je nabídka omezená právě podle vyfiltrovaných výsledků (tedy uvidím v tom mém konkrétním příkladě ve filtru "Rok" ty roky 2010 - 2011). Nerozumím ale tomu, proč vůbec původní filtr na knihy od roku 2010-2022 **vrátil 2 výsledky mimo seznam**, které mají v MARC poli 008 záznam 100825m20092009xr-c|||e|d||||000-0ccze|| (tj. **horní hranice 2009** a 030718s2003----xr-----e------000-1-cze-- (tj. **horní hranice 2003**).

![mimo](https://user-images.githubusercontent.com/92719629/164682861-b315d100-4312-4dbc-a47a-16724ffb4984.png)

**Comment by pavel-stastny** [comment]
> Nerozumím ale tomu, proč vůbec původní filtr na knihy od roku 2010-2022 vrátil 2 výsledky mimo seznam, které mají v MARC poli 008 záznam 100825m20092009xr-c|||e|d||||000-0ccze|| (tj. horní hranice 2009 a 030718s2003----xr-----e------000-1-cze-- (tj. horní hranice 2003).

Já nevím, asi si nerozumíme.   Původní filtr  (uživatelský) to vrátl proto, protože má v marc poli uvedenou hodnotu 2011. Dokonce to je i vidět v tom screenshotu, co jste poslala..    

Dohledatelné (jakkoliv, třeba přes filtry na levé straně nebo klidně přes název, čČNB podobně..) je to proto, protože má v poli 
008 hodnotu 2009 a ta konfigurace říkala, že se má hledat vše co je v rozmezí 1911 - 2009.

(Předpokládám, že se bavíme o konfiguraci výše.)




   

"Volání ďábla" se Vám může objevit ve výsledcíh (ať budete hledat přes název, nebo identifikátor nebo přes datum) proto, protože má v poli 008 uveden datum

**Comment by CIZKOVAL** [comment]
@pavel-stastny děkuji, už se mi rozsvítilo :-) já jsem se tím filtrem 2010-2022 snažila zjistit, jestli se mimo seznam nevyskytují i knihy vydané po roce 2009. Oni se tam ale vyskytují, protože ve skutečnosti jsou z roku 2003 a 2009 (pole 008), ale ten uživatelský filtr je vyhledá podle popisu 2010 a 2011, to mě zmátlo. Je to tedy v pořádku.

**Comment by Cypzirschova** [comment]
@CIZKOVAL Mohu tedy uzavřít?

**Comment by CIZKOVAL** [comment]
@smallcubes ještě poprosím o návrat do původního stavu - tedy tyto roky:

Původní nastavení (pro rok 2022) má být:
BK: do roku 2007
SE: do roku 2011

"search": {
"fromYear": 1911,
"yearsBK": 15,
"yearsSE": 11
},

@Cypzirschova az to Jirka udela, tak zkontroluji (vytipovala jsem si nejaka data, ktera by se tam pak nemela objevit a naopak melo by neco pribyt).

**Comment by Cypzirschova** [comment]
@CIZKOVAL děkuji za info.

**Comment by smallcubes** [comment]
@Cypzirschova @CIZKOVAL přenastaveno, můžete to vyzkoušet

**Comment by Cypzirschova** [comment]
Použila jsem filtr rok vyd. 2008-2008, Formát BK a našlo mi to 21 výsledků, ale po kontrole je vše OK. Všech 21 záznamů má v poli 008 rok vyd. 2007 a níže.
Ještě poprosím paní @CIZKOVAL o otestování.

**Comment by CIZKOVAL** [comment]
Ano, je to OK, mnou vytipovaná díla se tam po změně už nevyskytují.
