### ISSUE TITLE
Nova komponenta "Hromadne akce" nahrazuje button "Hromadny navrh" 

### ISSUE THREAD

**Issue by pkudela** [NLCR/SeznamDNNT#323]
Vytvoreni nove komponenty "Hromadne akce", ktera nahradi button "Hromadny navrh":

- [x] vytvoreni noveho buttonu "Hromadne akce" s menu
- [x] menu bude obsahovat  button "Hromadny navrh" a "Hromadne notifikace"
- [x] vytvorit odpovidajici funkce pro "Hromadne notifikace"
- [x] preklady
- [x] dialog pro provedeni hromadne notifikace
- [x] nova polozka v menu uzivatele "Notifikace" s ikonou nastaveni
- [x] dialog pro uzivatelske nastaveni notifikace
- [x] implementace novych stavu ikony notifikace v result-item
- [x] backend

**Comment by pavel-stastny** [comment]
@pkudela @Cypzirschova @CIZKOVAL Nasazeno na DEVu

**Comment by pavel-stastny** [comment]
Pro hromadne notifikace se otevrelo nove issue, toto zaviram.
