### ISSUE TITLE
Moje požadavky - vyhledání dle ID žádosti

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#325]
Dobrý den,
bylo by možné, aby kurátor mohl vyhledávat v přehledu žádostí (Moje požadavky) dle ID žádosti?

![ID_zadosti](https://user-images.githubusercontent.com/92719629/158596417-9536f016-be25-4e9b-b0c2-460df54367c1.png)

**Comment by pkudela** [comment]
Vymyslet a pripravit umisteni vyhledavaciho okna pro vyhledavani dle ID zadosti (podone jako v administraci)

**Comment by pkudela** [comment]
Pripraveno, jakmile bude funkcni, prosim @pavel-stastny  prehod to zase na me.

**Comment by pavel-stastny** [comment]
@smallcubes @CIZKOVAL @Cypzirschova Nakonec vyřešeno vyhledávacím polem, které filtruje žádosti 
![image](https://user-images.githubusercontent.com/675753/162675234-6fbc069a-e05b-4fdc-b43d-689f6873ae86.png)

Filtruje se dle prefixu a dle 
- jména uživatele
- id žádosti 
- zkráceného id žádosti (to co jde vidět v tabulce)

**Comment by pavel-stastny** [comment]
Možnost přidána pouze pro kurátory

**Comment by smallcubes** [comment]
`curl "http://localhost:<port>/sdnnt/api/account/_update_zadost"` bylo spuštěno a může být issue otestováno. (viz [dokumentace](https://github.com/NLCR/SeznamDNNT/wiki/Instalace-a-konfigurace))

**Comment by Cypzirschova** [comment]
Filtrování nefunguje správně, viz níže.

Uživatel knihovna-cyp - nic mi to nenašlo až když jsem zadala jen knihovna a dohledala.
![žádosti](https://user-images.githubusercontent.com/86351100/165075293-ea3314dc-22b1-46ad-8894-7c32b46a2f4d.png)
![žádosti01](https://user-images.githubusercontent.com/86351100/165075319-619f0ce1-7f6a-4a99-918a-a5a2fd5b1550.png)

Uživatel právnická osoba - ukazuje počet 8 žádostí, ale žádná se nezobrazí.
![žádosti03](https://user-images.githubusercontent.com/86351100/165075459-c72710cd-99f9-4966-8c50-467ac33c2af5.png)

Zkrácené ID žádosti - ukazuje počet nalezených žádostí 1, ale samotná žádost se nezobrazí.
![žádosti04](https://user-images.githubusercontent.com/86351100/165075556-f24ffec8-00c9-4577-b07d-7fa525be2263.png)

**Comment by CIZKOVAL** [comment]
Vypadá to, že je zde nějaký problém se znakem ``-`` Pokud je ve jméně uživatele pomlčka, tak se nevyhledá. Totéž když se hledá podle celého id žádosti, záznam se nenajde. Část id žádosti, které je viditelné v přehledu se najde, jakmile doplním ``-`` a chci psát dále, tak už se nic nevyhledá.

**Comment by CIZKOVAL** [comment]
@Cypzirschova když si vyhledám id te zadosti "c460cbce", tak ji vidim, stejne tak "právnickáosoba". Tam kde vám to ukazuje nějaký počet nalezených žádostí, tak je vidím. Problém mám jen s filtrováním, které popisuji výše - s pomlčkou.

**Comment by Cypzirschova** [comment]
Zkusím to ještě jednou. Nejdřív jsem hledala uživatelské jméno s pomlčkou a pak vždy text smazala a doplnila další, tak možná proto mi to nešlo. Stránku jsem neaktualizovala, ale jen smazala text a napsala nový.

**Comment by CIZKOVAL** [comment]
tak ted mi to nenachazi vubec nic...@smallcubes - Jirko, nebezi tam jeste neco? Prostredi je nestabilni, to mi to pred chvili naslo, uz to nenajde...

**Comment by smallcubes** [comment]
@CIZKOVAL nemělo by
dle wiki byl proveden níže uvedený příkaz, je to takto v pořádku?
```bash
curl "http://<solr_server>:<solr_port>/solr/catalog/update/?commit=true" \
-H "Content-Type: text/xml" \
-d "<delete><query>NOT id_sdnnt:*</query></delete>"
```

**Comment by pavel-stastny** [comment]
@Cypzirschova @CIZKOVAL @smallcubes Zde bude stačit pouze změna schématu.  

@smallcubes Pošlu postup

**Comment by CIZKOVAL** [comment]
@smallcubes, @Cypzirschova - už to zase nefunguje, zobrazí pouze počet nalezených výsledků...

**Comment by Cypzirschova** [comment]
@CIZKOVAL mě to zatím funguje, ale včera mi to blblo.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Myslim, že jste jenom na následující stránce.   Filtrování drží stav:  Filtry, třídění  a i stránkování.

**Comment by pavel-stastny** [comment]
@smallcubes Nahrajte, prosím, schéma z tohoto [linku ](https://github.com/NLCR/SeznamDNNT/releases/download/1.0.4.5/solr_zadost_schemapatch.zip) a dejte `curl http://localhost:<port>/sdnnt/api/account/touch`

**Comment by smallcubes** [comment]
@pavel-stastny hotovo, 

```json
{
  "numberOfObjects": 638,
  "bulkResults": [{
    "message": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<response>\n\n<lst name=\"responseHeader\">\n  <int name=\"status\">0<\/int>\n  <int name=\"QTime\">467<\/int>\n<\/lst>\n<\/response>\n",
    "statusCode": 200
  }]
}
```

@CIZKOVAL @Cypzirschova poprosil bych o opětovné otestování

**Comment by Cypzirschova** [comment]
Za mě OK.

**Comment by CIZKOVAL** [comment]
Dobrý den,
vyhledává se i podle typu žádosti? Zkusila jsem zadat např. VNZ a vyhledalo to 9 záznamů - žádostí VNZ tam je ve skutečnosti 112. Tak bych buď čekala, že se vyhledá všch 112 žádostí nebo nic, pokud se podle toho nemá vyhledávat.

![VNZ_pozadavky](https://user-images.githubusercontent.com/92719629/165498476-2e002541-4e3e-4316-a1ed-ee96d980dfdf.png)

**Comment by Cypzirschova** [comment]
@CIZKOVAL vyhledávání podle typu žádosti mi přijde zbytečné, když je vlevo filtr.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Uff... To puvodní issue bylo umožnit řadit nebo vyhledat dle id žádosti případně dle uživatele. Já tam navíc přidal možnost hledat dle prefixu slova v komentáři, protože mně to přišlo přínosné.    Nicméně dá se vyhodit pouhou změnou schématu.

**Comment by pavel-stastny** [comment]
> pole pro vyhledávání je neintuitivní, uživatele možná napadne, že může vyhledat podle ID, ale už ne, že to lze i podle uživatele. Nebylo by možné dát buď do okna pro vyhledávání popisek (např. zadejte ID žádosti, uživatele...) nebo nějaký tooltip?

No, ona ta vlastnost je přítomna jenom u kurátora nebo hlavního kurátora, tedy jenom jenom u dvou osob:   Paní @Cypzirschova  a paní @Lichtenbergova.   Abych se přiznal, tak mě ani nenapadlo dělat něco navíc v UI když je to popsané v tomto issue výše.  Ale  tooltip nebo popisek do prázdného pole se tam může dát.

**Comment by Cypzirschova** [comment]
Co se týče počtu kurátorů, kdo bude aplikaci používat, tak jsme zatím na čísle tři a pro kurátory vytvářím podrobné nápovědy i s obr., které budou mít k dispozici. Za mě tam ten popisek může být i nemusí.

**Comment by CIZKOVAL** [comment]
@pavel-stastny - já nepožaduji vyhledávání dle typu žádosti, přijde mi taky zbytečné, když se dá podle toho filtrovat. 
Jenom mě zmátlo, že pokud zadám VNZ, tak, že to něco najde, ale ne vše - ať to tedy nevyhledá nic.

Za popisek se přimlouvám.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ja to napsal již výše.  Přišlo mi zajímavé zahrnout i do vyhledávání klíčová slova  z textového odůvodnění v  žádostech.. To co jste vyhledala nebylo proto, že to je typ VNZ ale že v odůvodnění obsahovalo slovo VNZ.  

Nicméně pořád platí poznámka výše, je to jenom o schématu.

**Comment by CIZKOVAL** [comment]
@pavel-stastny - aha, tak to jsem nepochopila, že se to vyhledalo podle prefixu z pole oduvodneni - to asi není na škodu a může to tak být, je to tak, paní @Cypzirschova?

**Comment by Cypzirschova** [comment]
@CIZKOVAL může a ten popisek tam klidně dejte.

**Comment by CIZKOVAL** [comment]
@Cypzirschova - Dominiko, asi bych to doplnila jenom do nápovědy pro kurátora a hlavního kurátora, že uživatel může prohledávat žádosti dle id žádosti, zkráceného id žádosti, uživatele a prefixu slova v komentáři. Pak je možno uzavřít.

**Comment by Cypzirschova** [comment]
@smallcubes Prosím zavřít, nápovědy jsem před několika měsíci Lucce odevzdala.
