### ISSUE TITLE
Duplicita vlivem 2 bází a problémy se změnou stavu

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#326]
Dobrý den,
v SDNNT narazil p. Zahořík na následující problém.

Dílo _Příručka pro uživatele mozku : praktické informace a návody pro každodenní život / Pierce J. Howard ; [z amerického originálu ... přeložil František Koukolík]_ se vyskytuje v SDNNT celkem 6x. 

K duplicitě dochází u 1. a 2. vydání díla. Původně byla **4 díla mimo seznam** (bez stavu), **2 díla v SDNNT**. **Kurátor změnil u všech děl mimo seznam stav na PA s licencí online**. Tím se dostala všechna díla do SDNNT (vidí je tedy i nakladatel nebo nepřihlášený uživatel). V důsledku toho může dojít k tomu, že 1 dílo (v tomto případě dílo z roku 1998, 1. vydání) má jak stav PA online (dílo s odkazem do báze SKC), tak stav A online (dílo s odkazem do báze DNT).

Který stav je tedy pro dané dílo relevantní?
![duplicita_RZ](https://user-images.githubusercontent.com/92719629/158904273-d9bf7848-3e68-491d-a523-948ab85e5602.png)

![duplicita_sdnnt](https://user-images.githubusercontent.com/92719629/158905218-597bde7a-59bd-4edf-82b4-22c3cd29a6d9.png)

**Comment by CIZKOVAL** [comment]
Souvisí s issue #131

**Comment by JanMeritus** [comment]
@pavel-stastny pokud vim sme se domlouvali ze pokud zaznam ma stejny identifikatory - ccnb a isbn  a stejny nazev, zaznam by se nemel zobrazovat jako moznost navrhu

puvodne @albertoh mel delat pruzkum kolik takychto zaznamu je a jestli je nelze sparovat s SKC

**Comment by pavel-stastny** [comment]
@JanMeritus Tak o te domluve nic nevim abych se priznal.   

Ad parovani dle ccnb (lze to zjistit z vysledku procesu, ktery dela alternativni linky do SKC).  Na DEVu je v DNT bazi  605338 titulu, a zaznamy dle ccnb lze sparovat u 598019.

**Comment by JanMeritus** [comment]
coz znamena ze jde o drtivu mnozinu zaznamu

**Comment by CIZKOVAL** [comment]
Dobrý den,
pokud kliknu na záznam z katalogu, tak mě oba dovedou do báze SKC a ten původně z DNNT má v popisu _"Záznam z katalogu se stejným..."_. Došlo k nějaké úpravě? Včera mě jeden záznam nasměroval do SKC a druhý do DNNT.

...a ještě koukám, že záznam ze SKC má odkaz do NKP i MZK, zatímco ten druhý z DNNT má odkaz pouze do NKP

Předpokládám, že obojí bude vyřešeno až se záznamy spárují tam, kde to lze.

![katalog](https://user-images.githubusercontent.com/92719629/158995779-cbf953b3-0153-4f20-bf71-e7888bf15ca2.png)

![SKC_odkazy](https://user-images.githubusercontent.com/92719629/158995793-52817a35-33cd-42d6-ab22-32684fe5a1e4.png)

**Comment by pavel-stastny** [comment]
>pokud kliknu na záznam z katalogu, tak mě oba dovedou do báze SKC a ten původně z DNNT má v popisu "Záznam z katalogu se stejným...". Došlo k nějaké úpravě? Včera mě jeden záznam nasměroval do SKC a druhý do DNNT.

To je přítomno od verze 1.0.3.

> Předpokládám, že obojí bude vyřešeno až se záznamy spárují tam, kde to lze.

No, jo i ne.. respektive nejdřive se to musí řešit metodicky.  Například podobně jak se řeší volná díla, tedy  stavem, který vyjadřuje že je titul duplicitní a s čím. 

Paní  @Lichtenbergova  můžu poprosit o komentář?

**Comment by Lichtenbergova** [comment]
Párování dle ččnb by pomohlo, ale u části  záznamů ččnb chybí. A rychle se dodělat nedá, návrhy se hodně důkladně prověřují, expedují se publikace pro porovnání...
 
K výše uvedenému příkladu:
z vyřazeného záznamu (jako kurátor jsem PA změnila na N, druhý záznam s A zůstal, což by samozřejmě neměl): https://aleph.nkp.cz/F/?func=direct&doc_number=000953530&local_base=SKC
ze zařazeného záznamu téhož https://aleph.nkp.cz/F/?func=direct&doc_number=000953530&local_base=SKC

takže stejné sysno SKC jako další pomocné vodítko, že se jedná o chybu (i když sysno samozřejmě není jedinečný identifikátor)?

**Comment by JanMeritus** [comment]
> Párování dle ččnb by pomohlo, ale u části záznamů ččnb chybí. A rychle se dodělat nedá, návrhy se hodně důkladně prověřují, expedují se publikace pro porovnání...

@Lichtenbergova ale tam kde CCNB je? Nepomohlo by to vyrazne? (predpokladam ze u DNT zaznamu chybi SKC identifikator)

**Comment by Lichtenbergova** [comment]
OK, párování alespoň dle ččnb by výrazně pomohlo. 
Ve stávajícím  DNT je pole 910 se siglou a identifikačním číslem záznamu knihovny, podle kterého se dá do SKC navigovat
910 $aABA001$xcpk20021090967$sdíl 1-5...
tato pole se v SKC "skladují", i když se záznam deduplikuje.

**Comment by JanMeritus** [comment]
@pavel-stastny 

- konfigoruvatelne moznost pri navrhovani - pokud obsahuje ccnb stejny 
- prosim o vytvoreni stavu/kontextove informace "Pravdepodobna duplicita" pro dila se stejnym CCNB

**Comment by pavel-stastny** [comment]
@JanMeritus Bude řešeno až po verzi 1.0.5 ...  Označil jsem to enhancement.

**Comment by CIZKOVAL** [comment]
Přidávám komentář od p. Zahoříka, kdy navrhuje, že pro pocatecni – tj. jednorazove sparovani zaznamu stazenych z baze DNT-ALL se zaznamy SKC doporucuji jednoznacne pouzit systemova cisla uvedena v poli 996. Parovani podle 910 $ax nemusi byt jednoznacne.

**Comment by CIZKOVAL** [comment]
Vyřešeno spárováním záznamů dle issue #387
