### ISSUE TITLE
Dotaz - označení DNNT-T dokumentů

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#327]
Dobrý den,
narazila jsem na dokumenty, které mají stav "A NZ" a licenci mají uvedenou "dnnto". Mě tam mate to písmeno "o". Pokud to chápu správně, tak stav "A NZ" znamená, že to je zařazeno na seznam a je to omezeno na terminál. My kurátoři rozlišujeme označení DNNT-O a DNNT-T, takže pro mě ta zkratka "dnnto" značí, že to může být přístupné na dálku, což tak ale není.
Můžu se zeptat, Vy na SDNNT nerozlišujete DNNT-O a DNNT-T? Jakože zkratka "dnnto" znamená, že to je na seznamu, a až ten stav "A NZ" teprve určuje, že to je omezené na terminál?

![image](https://user-images.githubusercontent.com/43740512/158958641-cf33ac5d-f883-418c-a9e1-e4ca1a1f14ec.png)

**Comment by CIZKOVAL** [comment]
Dobrý den, toto je nějaký nepořádek v datech nebo chyba. Stav A NZ neexistuje (původně existoval stav NZ, což znamenalo omezení na terminál)

**Nyní rozlišujeme pouze tyto stavy: N, A, PA, NL a tzv. kurátorské stavy NPA, PX, X, NLX)**

**Označení pro licence používáme tyto: dnnto (přístupné online), dnntt (přístupné na terminálu).** DNNT-O, DNNT-T nepoužíváme. Podrobněji je to v tabulce STAVY_v6.xls, kterou jsem zasílala.

**Zobrazení granurality u tohoto díla je ale divné - stav by neměl být A NZ, ale některý z výše popsaných.**

_Poznámka: Když chci jako kurátor změnit stav, tak by se mi měla nabídnout i změna stavu u jednotlivých ročníků, což u tohoto konkrétního díla není._

Prosím o prověření @pavel-stastny 

![granuralita_ronika](https://user-images.githubusercontent.com/92719629/158963989-e36331c3-6841-46b1-8051-f3a3c6251f45.png)

**Jiný seriál, který má také granuralitu a lze měnit stavy na úrovni ročníků:** 
![granuralita_jine_dilo](https://user-images.githubusercontent.com/92719629/158964004-d69858b5-6ade-41a4-ae3a-f7c76042d375.png)

**Comment by CIZKOVAL** [comment]
Zřejmě souvisí s issue #213

**Comment by pavel-stastny** [comment]
@CIZKOVAL Na DEVu dobehla reindexace. 

Ad zmena stavu/rocniku.  Dilo ma granularitu - popsane rocniky ale nejedna se o periodikum ale knihu.

**Comment by CIZKOVAL** [comment]
Retest na DEV OK, co se týče úpravy stavu a licence - NZ už se u daných děl nevyskytuje, vždy je **A dnntt** nebo **PA dnntt**.

Když ale kliknu v granuralitě na odkaz do Krameria u ročníků, které mají licenci **dnntt**, tak je tam vidím ve většině případů jako dílo dostupné **online**.

_Ještě otázka k té změně stavu - když se jedná o knihu, tak nemá jít měnit stav a licence u jednotlivých ročníků? Dávalo by mi to smysl, kdyby byly stavy i licence u všech ročníků stejné, pokud se ale liší, tak proč by je nemělo jít měnit?_ 

![SDNNT_dnntt](https://user-images.githubusercontent.com/92719629/159894473-1ef95053-0ca3-424a-9684-2a83e80fab8b.png)

![NDK](https://user-images.githubusercontent.com/92719629/159894509-1a8f41ab-7623-4816-ab06-9c4c6ccdbf6b.png)

**Comment by pavel-stastny** [comment]
> Když ale kliknu v granuralitě na odkaz do Krameria u ročníků, které mají licenci dnntt, tak je tam vidím ve většině případů jako dílo dostupné online.

To jsou data přebraná  z Alephu z báze dnt 

> Ještě otázka k té změně stavu - když se jedná o knihu, tak nemá jít měnit stav a licence u jednotlivých ročníků? Dávalo by mi to smysl, kdyby byly stavy i licence u všech ročníků stejné, pokud se ale liší, tak proč by je nemělo jít měnit?

Tady to možná bude na debatu s paní @Cypzirschova.  Beru to z pohledu krameria, kde kniha je reprezentovaná typem monograph a ten nemá pod sebou ročníky. Má části (monographunit) nebo stránky (page).   Ročníky jsou pod typem periodical (periodikum).

**Comment by marketakrutska** [comment]
Jinak my informace bereme ze starého OAI API a tam jsou informace jen o stavech, nikoliv o licencích. Takže u těch ročníků 2003 a 2005 máme jen "A" a nemáme informaci o tom, že licence je DNNT-T. No a jelikož to dříve bylo tak, že stav A = DNNT-O, tak i my to máme v Krameriu jako DNNT-O. (Protože DNNT-T dokumenty byly označeny stavem A_NZ).

**Comment by CIZKOVAL** [comment]
retest na TEST OK, díla z tohoto issue, která měla stav A NZ, licenci dnnto se změnily na A dnntt.

**Comment by CIZKOVAL** [comment]
Založena issue #358, #359, kde se budou řešit další body.
