### ISSUE TITLE
Stav NZ v historii změn u nových návrhů

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#328]
Dobrý den,
v souvislosti s issue #327 jsem se znovu zaměřila na historii změn.

Nové návrhy na zařazení do seznamu, která jsou od 1.2. 2022 ve stavu **PA** (dostaly se tam dávkou) **a mají licenci dnntt** mají v historii změn **stav NZ** s licencí dnntt.

Vypadá to, že tyto návrhy prošly 2-krokovou změnou, nejdříve se jim v historii změn přiřadil **stav PA/licence dnnto** a následně se změnil stav na **NZ/licence dnntt**. Jakoby nebylo možné, aby bylo dílo do historie zapsáno rovnou jako **PA/licence dnntt**.

_Poznámka: historicky se stav NZ v historii změn objevuje i ve starších případech, které nesouvisí s přesunem 1.2. 2022_

![Marfologie](https://user-images.githubusercontent.com/92719629/158982803-c3bdec52-97a4-4bc3-8ee6-cb908cb97a7f.png)

![Marfologie_historie](https://user-images.githubusercontent.com/92719629/158982826-5f92934d-f7a1-4647-a109-a0fd1121f3e8.png)

**Comment by CIZKOVAL** [comment]
Souvislost s issue #327, #213

**Comment by Lichtenbergova** [comment]
Dobrý den,
zřejmě to nějak souvisí s nastavením procedur v Aleph, ze začátku se licence neřešily, jen dostupnost na trhu.

**Comment by pavel-stastny** [comment]
@Lichtenbergova @CIZKOVAL V historii stav by měl stav NZ zůstat.

**Comment by CIZKOVAL** [comment]
Zavírám, záznamy, které měly NZ dnntt se již přesunuly do A dnntt (1.2. nebo 1.8. 2022) a stav NZ je historický, nově se už neobjevuje (dříve vyjadřoval omezení na terminál).
