### ISSUE TITLE
API: požadavek a chybová hláška

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#329]
Dobrý den,

bylo by možné změnit chybovou hlášku, pokud zadám špatný/nesmyslný API dotaz? Aktuálně vrátí celý error z tomcatu. Případně by mohl být vrácen krátký string s vysvětlením (např. v tomto případě že dílo už zařazené je).

např. žádost NZN na už zařazené dílo (stav A)
```bash
curl -X 'PUT' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/request/batch/nzn' \
  -H 'accept: application/json' \
  -H 'token' \
  -H 'Content-Type: application/json' \
  -d '{
  "batch": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:DNT01-000197708"
      ],
      "pozadavek": "Dilo už je zařazene",
      "poznamka": "Pozadavek resi navrh na zarazeni/vyzvu k vyrazeni cislo 0021"
    },
  ]
}'
```

**Comment by pavel-stastny** [comment]
@smallcubes V priprade, ze se to dostane az na aplikaci tak byste mel videt hlasku o tom ze dilo je ve spatnem stavu. Viz:

```
{
  "saved": [],
  "notsaved": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:DNT01-000543536"
      ],
      "pozadavek": "Pozadavek cislo 0021",
      "poznamka": "Pozadavek resi navrh na zarazeni/vyzvu k vyrazeni cislo 0021",
      "reason": "Invalid state of these documents: [oai:aleph-nkp.cz:DNT01-000543536]"
    }
  ]
}
```

To co popisujete je spis, ze filtr jeste pred aplikaci neni schopen naparsovat vstupni json (Je tam carka navic) a z toho leti ta vyjimka z tomcatu.

**Comment by CIZKOVAL** [comment]
Retest NOK, pokud je chyba v json formátu (např. čárka navíc), tak vrátí celý error z tomcatu.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Přidána možnost validace i na úrovni jsonu.

**Comment by JanMeritus** [comment]
v 1.05 prosim @smallcubes o retest

**Comment by smallcubes** [comment]
Po zadání špatně naformátovaného jsonu, se vráti níže uvedená hláška. Snad by neměl být problém ve zveřejnění níže uvedených tříd. Pokud ano, poprosil bych  @JanMeritus o znovu otevření. 

```
Unexpected character (']' (code 93)): expected a value
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 10, column: 4] (through reference chain: cz.inovatika.sdnnt.openapi.endpoints.model.BatchRequest["batch"])
```
