### ISSUE TITLE
Schválení (kurátor): neuloží se odůvodnění

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#33]
Dobrý den,

je-li schváleno nějaké dílo (_Navrženo na zařazení_) _kurátorem,_ tak se neuloží odůvodnění. Zamítnutí funguje správně.

Děkuji za reakci.

**Comment by albertoh** [comment]
Vidim problem. Opravim

**Comment by smallcubes** [comment]
Odůvodnění se již uloží. Děkuji za vyřízení.
