### ISSUE TITLE
Editor pro texty: názvy v záložkách

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#330]
Dobrý den,

změnéné názvy v záložkách se neprojeví v editoru textů.

Např. V současné době jsou záložky pojmenovány takto:
![obrazek](https://user-images.githubusercontent.com/78028909/159013726-eb90ffec-0924-4add-843c-ebfb6e0ca68c.png)

Ale v editoru zůstane původní název:
![obrazek](https://user-images.githubusercontent.com/78028909/159013846-9b8a0e42-1f21-4d6c-9d9e-e1f94bf7659e.png)

Předem děkuji za reakci.

**Comment by albertoh** [comment]
@smallcubes Jak jste zmenil nazvy, v prekladech? Je mozne, ze zustalo v cache. Zkuste, prosim, control+f5

**Comment by smallcubes** [comment]
@albertoh Na Chromu to pomohlo, ale na Firefoxu to zůstává pořád stejné. S tím asi nepůjde nic udělat?
