### ISSUE TITLE
API: žádost se vytvoří Xkrát po X zavolání

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#331]
Dobrý den,

nevím zdali je to tak správně, ale pošlu-li **stejný** požadavek 5x vytvoří se 5 žádostí.
Neměla by být vytvořena pouze jedna a zbytek zamítnut @JanMeritus @jahhoo?

např. dotaz pro vytvoření NZN 
```bash
curl -X 'PUT' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/request/batch/nzn' \
  -H 'accept: application/json' \
  -H 'token' \
  -H 'Content-Type: application/json' \
  -d '{
  "batch": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:DNT01-000070281"
      ],
      "pozadavek": "Pozadavek API",
      "poznamka": "Pozadavek resi navrh na zarazeni/vyzvu k vyrazeni cislo 0021"
    }
  ]
}'
```

**Comment by JanMeritus** [comment]
@smallcubes je to mozne, predpokladam ze je to tim ze zadost na dilo muze podat vicero subjektu z ruznych pravnych duvodu ... u jedneho subjektu je to ale pomerne nesikovne

**Comment by smallcubes** [comment]
@JanMeritus a nemělo by to aspoň zakázat např. 10. žádost se stejným obsahem od stejného subjektu?

**Comment by JanMeritus** [comment]
Urcite ano

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Pridana validace, pokud ma uzivatel dokument pouzity v jakekoliv zadosti (ne ve stavu processed) vyvola vyjimku

**Comment by CIZKOVAL** [comment]
Výsledek retestu NOK - pokud je už žádost na dílo vytvořená, tak stejný uživatel nemůže už dílo zařadit. 
Aplikace se nyní zachová tak, že vytvoří prázdnou žádost NZN ve stavu Neodesláno (not send).
```
curl -X 'PUT' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/request/batch/nzn' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: 75491c65-7601-4b78-8c6d-31201dfcb353' \
  -H 'Content-Type: application/json' \
  -d '{
  "batch": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:SKC01-007308214"
      ],
      "pozadavek": "NZN",
      "poznamka": "uz tam je"
    }
  ]
}'
```
![API_prazdna_zadost](https://user-images.githubusercontent.com/92719629/160583745-41341a57-0532-4519-8d16-4194338f1585.png)

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim retest

**Comment by CIZKOVAL** [comment]
Retest OK, vytvoří se 1 žádost, další už ne.
