### ISSUE TITLE
API: klíče v dotazu

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#333]
Dobrý den,

v dotazu můžu zadat jakékoliv klíče (stačí mít pouze tři) a žádost se uloží.

Příklad:
```bash
curl -X 'PUT' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/request/batch/nzn' \
  -H 'accept: application/json' \
  -H 'token' \
  -H 'Content-Type: application/json' \
  -d '{
  "batch": [
    {
      "poznamka": "hello",
      "pozadavek": "Pozadavek cislo 0021",
      "user": "hi"
    }
  ]
}'

```

**Comment by JanMeritus** [comment]
toto je problem validace dotazu - zda se ze chybi alespon zakladni, @pavel-stastny prosim zde o zasah

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Pridana validace, musi byt pritomno pole pro identifikatory a musi byt neprazdne.

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Nasazeno na DEVu

**Comment by CIZKOVAL** [comment]
Retest OK, replikovan stejny pozadavek - validace probehla, zadost se neulozi.
```
{
  "saved": [],
  "notsaved": [
    {
      "identifiers": [],
      "pozadavek": "Pozadavek cislo 0021",
      "poznamka": "hello",
      "reason": "Empty array of identifiers is not allowed "
    }
  ]
}
```
