### ISSUE TITLE
API: procházení všech záznamů bez query

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#336]
Dobrý den,

v API nemůžu proiterovat všechna data request `/catalog`, jelikož je **query** povinný parametr. Zkoušel jsem i hvězdičku `"*"` a `*`.

**Comment by pavel-stastny** [comment]
@smallcubes To neni podporovano a ani nebude.    Pro jednotlive typy dat jsou vystaveny endpointy (at uz pro komunikaci s krameriem, pripadne OAI,  v pripade OAI se daji sety konfigurovat ...)   Proiterovani dat pres strankovani by bylo neefektivni.

**Comment by smallcubes** [comment]
@pavel-stastny děkuji za vyjádření, poprosil bych @JanMeritus o schválení a poté issue uzavřu

**Comment by JanMeritus** [comment]
dle domluvy ano
