### ISSUE TITLE
Historie stavu versus historie ročníku

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#337]
Dobrý den,
v souvislosti s retestem chyby #275 jsem změnila v rámci granurality **stavy a licenci u některých ročníků**.

Změny se správně zapsaly do nové karty "Historie ročníků", ale **zároveň se provedl zápis i do historie stavu**, tj. celku. 
Nic se zde nezměnilo a žádná změna zde není zapsaná, jen zde přibyla poznámka, která se týkala změny ročníků.

![historie_stavu_e](https://user-images.githubusercontent.com/92719629/159471543-33f6a53b-2304-4816-859e-eb6b5f43964a.png)

**Historie ročníku je OK:**

![historie rocniku](https://user-images.githubusercontent.com/92719629/159471601-5934ba26-ac52-4b86-a8f9-0b2f848bbeda.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL To je bohuzel nutne, z duvodu sledovani zmen pro krameria je nutne udelat zmenu i v nadrazenem periodiku,

**Comment by CIZKOVAL** [comment]
Dobře, zavírám
