### ISSUE TITLE
Vycentrování vyhledávacího políčka

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#338]
Dobrý den,

bylo by možné vycentrovat vyhledávací políčko? Např. na velkém rozlišení to vypadá zvláštně.

![obrazek](https://user-images.githubusercontent.com/78028909/159681436-177a9b40-9d69-4dc9-94b2-2c83d2197653.png)

**Comment by pkudela** [comment]
Vycentrovano v ramci navbaru, az bude nasazeno oznacime k testovani.

**Comment by smallcubes** [comment]
asi v pořádku @CIZKOVAL?
