### ISSUE TITLE
DEV-Hromadné notifikace připomínky

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#339]
Dobrý den,
provedla jsem smoke testy a zatím jsem netestovala to, jestli notifikace (email) dorazí. Zítra budu pokračovat.

**Nalezené problémy:**

_Poznámka: problémy jsem rozdělila do kategorie "Natavení notifikací" - to je okno, kde si uživatel může zkontrolovat nastavení a "Zobrazení záznamu s notifikací" - to je zobrazení děl ve filtru v rámci notifikace._

1. Nastavení notifikací - Notifikaci lze uložit i bez názvu notifikace, což je povinné pole. Notifikace se uloží jako prázdná kolonka v seznamu notifikací
2. Nastavení notifikací - je tam překlep "Snazat notifikaci" místo "Smazat notifikaci"
3. Nastavení notifikací - Interval notifikace: desc.den
4. Nastavení notifikací - podivné zarovnání
5. Nastavení notifikací - notifikaci nelze editovat - čekala bych, že minimálně název editovat půjde
6. Nastavení notifikací - chybí použitý filtr
7. Zobrazení záznamu s notifikací - chtělo by to lépe oddělit Jednotlivé notifikace od ostatních, např. názvem Hromadné notifikace
8. Nastavení notifikací - neukládají se jednotlivé notifikace
9. Zobrazení záznamu s notifikací - pokud vyberu některou z hromadných notifikací, tak se zobrazí špatný výsledek filtru. Paradoxně se hledá podle filtru, který v "Nastavení notifikací" chybí, ale nehledá se podle hledaného výrazu
10. Pokud je dílo součástí hromadné notifikace, pak je zvonek zašedlý (neaktivní) a nelze provést jednotlivou notifikaci na tento záznam s tooltipem, že dílo už je v hromadné notifikaci. Lze to ale obejít tak, že vložím toto 1 dílo do další hromadné notifikace.
11. Stejné dílo může být součástí více hromadných notifikací (souvisí s bodem 10)

### **1. + 2.** 
![Albatros_bez_nazvu](https://user-images.githubusercontent.com/92719629/159727647-5d816699-6105-4f8f-af55-e58b6323c2da.png)

![hromadne_notifikace_albatros](https://user-images.githubusercontent.com/92719629/159728000-79fb293e-bdc4-4776-997c-4995fb46d29a.png)

### **3. + 4.** 
![zarovnani, desc](https://user-images.githubusercontent.com/92719629/159728301-21c8b5f8-59a8-4e27-90fd-932766f19801.png)

### **5.**
![notifikace_editace](https://user-images.githubusercontent.com/92719629/159728637-12f18403-ea29-4a4f-bbfd-c75459ea52fb.png)

### **6.**
![1_cast_Svepomoc](https://user-images.githubusercontent.com/92719629/159728905-c5b81ec1-a4aa-453c-8f96-dd42184146a1.png)
![2_cast_Svepomoc](https://user-images.githubusercontent.com/92719629/159728935-89832d4c-e0c1-49e1-99ab-0f8ff42f2343.png)

### **7.**
![oddeleni hromadnych od jednotlivych](https://user-images.githubusercontent.com/92719629/159729532-c1036dd1-5366-414c-b731-2866ed622292.png)

### **8.**
![jednotlive_notifikace_se_neukladaji](https://user-images.githubusercontent.com/92719629/159729616-ee954f37-2ad7-4af8-a7fa-aadcfe6015cd.png)

### **9.**
![zobrazeni_hromad_not](https://user-images.githubusercontent.com/92719629/159729718-28f3079f-f51a-40fd-8f28-86235b8e9a04.png)

### **10.**
![hromadna_kdyz_uz je_soucasti](https://user-images.githubusercontent.com/92719629/159729990-69b48388-5321-4b02-bca8-7b61d783794c.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Jenom v rychlosti odpovim 

Ad bod 5)  Řešili jsme to s @pkudela. Došli jsme k závěru, že  nemá valného smuslu ten dialog dělat editační.  Jednodšší je tu notifikaci smazat a znovu vybrat filtr. 

Ad bod 6)  To vypada, že je specifické pro toho uživatele co používáte na devu. Na uživateli "pokusny" filtry vidět jsou... prozkoumáme.

Ad bod 8)  To je jenom nastavení pro notifikace.  Původně byla položka v profilu uživatele, nyní přesunuto sem.  Můžete porovnat s test prostředím. 

Ad bod 9) To bude souviset s  bodem 6. 

Ad bod 10) Ano, opět implementované chování. Filtry se mohou překrývat.  Zvonek je zašedlý  aby uživatel dostal informaci že dokument je součástí hromadné notifikace.   Teoreticky jde zařídit to aby si to ještě notifikoval ručně ale nevím k čemu by to bylo... Informace o změně dokumentu beží vždy jedna. 

Ad bod 11) Ano.  Pokud je řízeno filtry, nemá smysl dělat logiku aby se filtry nepřekrývaly.

**Comment by pavel-stastny** [comment]
@CIZKOVAL body 1 a 6 by měly být vyřešené

**Comment by CIZKOVAL** [comment]
Retest na DEV:
1 - OK
2 - překlep "Snazat" - předpokládám, že se bude řešit
3 - popisek "desc.mesic/tyden/den" - předpokládám, že se bude řešit
4 - zarovnání notifikací - předpokládám, že se bude řešit
5 - OK, neřešme
6 - OK
7 - oddělení hromadných notifikací - je to pod čarou, asi se tedy nemusi resit
8 - OK, není chyba
9 - OK
10 - OK, není chyba
11 - OK, není chyba

**Comment by CIZKOVAL** [comment]
Retest na TEST OK, vše vyřešeno.

![TEST_notifikace](https://user-images.githubusercontent.com/92719629/161710762-cf27426c-9e3a-4b82-b121-b0d6373c1bed.png)
