### ISSUE TITLE
Kniha mimo rozsah (2012)

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#34]
Dobrý den, 

kniha: _Marley a já, aneb, Život s nejhorším psem na světě_ (**2. vydání**; Marley a já, aneb, Život s nejhorším psem na světě / John Grogan ; [z anglického originálu ... přeložila Hana Mayerová]; cnb002256337; 978-80-249-1797-9)
byla vydána v roce 2012, ale je k vyhledání, nejedná se o chybu? 

příbuzné issue: #27 

Děkuji za reakci.

**Comment by albertoh** [comment]
Opraveno

**Comment by smallcubes** [comment]
Problém stále přetrvává. Knihu mohu vyhledat.

**Comment by albertoh** [comment]
Zaznam je na seznam, ma stav A. Proto lze hledat.

**Comment by smallcubes** [comment]
@albertoh  děkuji, opraveno a uzavírám.
