### ISSUE TITLE
velikost setu dnnto

### ISSUE THREAD

**Issue by cbvk** [NLCR/SeznamDNNT#341]
proc set DNNTO obsahuje 522854 zaznamu
https://sdnnt-test.nkp.cz/sdnnt/oai?verb=ListRecords&metadataPrefix=marc21&set=DNNTO

v NDK - https://ndk.cz/search - je dostupnych pouze  239536 titulu -
vsech (DNNTO, DNNTT, public)
pokud pripocitam AV - https://kramerius.lib.cas.cz/search - zde je
dostupynch 7301 dokumentu
pokud pripocitam MZK - https://www.digitalniknihovna.cz/mzk/search -
zde je dostupynch 258931 dokumentu - vetsina je jich ale zde
duplicitne s ndk.cz

na testovacim importu jsme do  testovaci databaze naimportovali pouze 113911 zaznamu s 856 linkem

---------
jsou v setech zaznamy duplicitne?
spoustu dokumentu v setu DNNTO  neobsahuje odkaz v poli "856" ...
takove dokumenty jsou pro nas v setu zbytecne
neslo by odfiltrovat?
nebo vytvorit zvlastni set

tento set nam trva importovat pres 2 dny

**Comment by black23** [comment]
Ideální by byl subset pro jen skutečně online dostupná díla (s linkem do nějakého Krameria).

**Comment by pavel-stastny** [comment]
@cbvk  Pokusím se v rychlosti odpovědět. 

> jsou v setech zaznamy duplicitne?

V rámci jednoho setu by duplicity být neměly

> neslo by odfiltrovat?

Rozhodnutí přenechávám na  @JanMeritus @smallcubes.  Zda je lepší vytvořit nový subset nebo modifikovat stávající.

**Comment by JanMeritus** [comment]
stavajici subset se menit nebude, ale diki moznosti konfigurovat subsety - jak jiz jsem psal v emailu se vytvoril novy subset dle pozadavku @cbvk a @black23 , viz #344 

je mozno zde uzavrit?

**Comment by JanMeritus** [comment]
dle @cbvk mozno uzavrit, kdyby neco prosim @black23 o otevreni
