### ISSUE TITLE
URL na digital. dokument

### ISSUE THREAD

**Issue by cbvk** [NLCR/SeznamDNNT#342]
proc URL v poli "856" neodkazuje na ostrou verzi webu - ndk.cz/...
ale na:
http://krameriusndk.nkp.cz/search/handle/uuid:9f8a4f50-8dda-11ea-a354-005056827e51

v setu jsou i  linkyi do AV:
https://kramerius.lib.cas.cz/uuid/uuid:d1058670-3aee-412e-9e4f-61f5dd8d0f91
a do MZK:
http://www.digitalniknihovna.cz/mzk/uuid/uuid:1f8c6df3-b2e0-11e0-a21b-0050569d679d

pokud je titul na vice krameriich, bude zde vice linku nebo jen jeden?
jak je preferovany link?

lze data povazovat jiz za ostra ?
muzeme importovat do ostre DB?

diky

JN

**Comment by pavel-stastny** [comment]
@cbvk Pokusím se odpovědět. 

> proc URL v poli "856" neodkazuje na ostrou verzi webu - ndk.cz/... ale na:

Jedná se o data přebíraná z SKC bez jakýchkoliv úprav.  

> pokud je titul na vice krameriich, bude zde vice linku nebo jen jeden? jak je preferovany link?

Není žádná preference linku. V ideálním případě by záznam měl obsahovat všechny linky na digitální kopie. (Včetně replikací apod.)

> lze data povazovat jiz za ostra ?

Myslím, že ne.  Až budou data na ostém (ne testovacím) serveru.   Ať mě případně doplní/opraví @JanMeritus /  @smallcubes

**Comment by JanMeritus** [comment]
@cbvk k poslednimu ne, prosim nemichat TEST a PROD. PROD zatim spustena neni, na testovacich datech probihaji testy (!)

**Comment by cbvk** [comment]
diky. kdy bude dostupna PROD?

JN

**Comment by JanMeritus** [comment]
@cbvk zhodnotime stav v pondeli, mate cas se pripojit k vyvojove schuzce v 9 ?

**Comment by cbvk** [comment]
ok, pripojim se
poslete mi odkaz 
diky

JN

**Comment by cbvk** [comment]
ukol je mozne uzavrit, nicmene stale jsem se nedozvedel, kdy je planovana ostra verze 
diky

**Comment by JanMeritus** [comment]
dle 1.05, bohuzel zatim stale nevim kdy bude release, zde uzaviram
