### ISSUE TITLE
vyznam hodnot v poli 990

### ISSUE THREAD

**Issue by cbvk** [NLCR/SeznamDNNT#343]
co obsahuje podpole 990: napr
<marc:subfield code="9">["A"]</marc:subfield>
jakych hodnot muze nabyvat ...
poznam z toho public dokument?

diky

JN

**Comment by JanMeritus** [comment]
@cbvk viz https://github.com/NLCR/SeznamDNNT/wiki/Stavy-a-licence-:-Popis-mapovani pripadne doplnky od @CIZKOVAL

**Comment by JanMeritus** [comment]
@cbvk je mozne uzavrit?

**Comment by cbvk** [comment]
je mozne uzavrit, diky
