### ISSUE TITLE
OAI: dvakrát stejné pole

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#346]
Dobrý den,

v oai setu [Test](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=ListRecords&metadataPrefix=marc21&set=TEST), se opakuje dvakrát stejné pole **990**.

příklad:
```xml
<marc:datafield tag="990" ind1=" " ind2=" ">
      <marc:subfield code="a">A</marc:subfield>
</marc:datafield>
```

**Comment by JanMeritus** [comment]
DK potrebuji jednoznacnou informaci o stavu dila, dopakovatelne pole je zde chyba

**Comment by smallcubes** [comment]
Zkontrolovány namátkově dva sety [SDNNT-ALL](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=ListRecords&metadataPrefix=marc21&set=SDNNT-ALL) a [TEST](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=ListRecords&metadataPrefix=marc21&set=TEST). Na duplikaci pole `990` jsem nenarazil. Issue uzavírám.
