### ISSUE TITLE
Moje požadavky - počet záznamů a stránkování se nepropisuje do spodní části

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#347]
Moje požadavky - počet záznamů a stránkování se nepropisuje do spodní části. Viz. screen

![Snímek z 2022-03-30 16-42-13](https://user-images.githubusercontent.com/33415849/160862233-d9501817-f275-4c75-aa70-c07958b93347.png)

**Comment by CIZKOVAL** [comment]
Stejný problém jako v katalogu, viz #313

**Comment by CIZKOVAL** [comment]
Retest - v sekci **Moje požadavky OK**...chyba se ale vyskytuje ještě **ve vnořené žádosti**.

**Nahoře zvolím počet žádostí na stránku = 5, změnilo se**
![vnorene_zadosti_nahore](https://user-images.githubusercontent.com/92719629/164678961-4a829e65-9934-4610-920f-a6c8436e6470.png)

**Dole zůstává zobrazeno počet žádostí na stránku = 20**
![vnorene_zadosti_dole](https://user-images.githubusercontent.com/92719629/164678985-17f14d42-9f0a-4455-a939-82ee9796d95e.png)

**Comment by Cypzirschova** [comment]
Chyba stále trvá. Zkoušela jsem to u kurátora v jedné žádosti.

**Comment by Cypzirschova** [comment]
Stejná chyba se vyskytuje i v Importech. @pavel-stastny

**Comment by jahhoo** [comment]
Vypadá to, že je již vyřešeno v poslední verzi.

**Comment by CIZKOVAL** [comment]
Chyba trvá ještě na stránce s importy, bylo reklamováno [zde](https://github.com/NLCR/SeznamDNNT/issues/347#issuecomment-1109646425) .

![stránkování_výchozí](https://user-images.githubusercontent.com/92719629/191238812-ad11d296-f942-43b1-b180-db2283a2a209.png)

![stránkování_změna](https://user-images.githubusercontent.com/92719629/191238845-84ed28f0-cdc4-4de9-a319-cdcbbee0e52d.png)

**Comment by Cypzirschova** [comment]
OK, děkujeme za úpravu
