### ISSUE TITLE
Přeblikávání celé obrazovky

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#35]
Dobrý den,

pokud na úvodní stránce: `.../sdnnt/home` překlikávám mezi záložkami: _O DNNT_, _Aktuality_, _Čtenářům_, _Autorům_, _Nakladatelům_, _Knihovnám_ a _Popis API_, tak dochází ke krátkém probliknutí (cca. +- 1 sekunda) celé obrazovky. Bylo by to možné odstranit? (Firefox, Chrome)

[ukázka](https://user-images.githubusercontent.com/78028909/126321042-de79f390-ac49-47b7-822b-1a35465a6dbc.mp4)

1. edit: děje se to i pokud kliknu na ikonku SDNNT a Moje konto

Děkuji za reakci.

**Comment by smallcubes** [comment]
@albertoh  děkuji, je to opravené. **Pouze ještě dojde k problikávání**, pokud kliknete na tlačítko _vyhledávání_.


https://user-images.githubusercontent.com/78028909/127134505-dd74eb2b-b622-4568-b328-5fb198096a74.mp4

**Comment by albertoh** [comment]
To je zpusobeno tim, ze odpoved je moc rychla (dotaz vrati nula vysledku). Kdyz jsou vysledky vidime "tocitko" na sedem pozadi. To pozadi je tam, aby nebylo mozne kliknout na dalsi elementy dokud operace neskoncila. Pro operace, ktere meni zaznamy to je nutnost

**Comment by smallcubes** [comment]
@albertoh  děkuji za odpověď, je škoda, že to nelze zrušit u velmi krátkých dotazech. Opraveno a uzavírám.
