### ISSUE TITLE
U kurátora zmizela možnost notifikace

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#350]
Dobrý den,
u kurátora zmizela možnost nastavit si notifikace
 - není tam zvonek u děl
 - není tam checkbox pro zobrazení děl s notifikací  
 - není tam možnost hromadné notifikace.

Tento problém se týká role kurátor, hlavní kurátor. U ostatních rolí je to v pořádku.

![Kurator_notifikace](https://user-images.githubusercontent.com/92719629/161022031-0bc96fef-60d7-4f13-914e-2199d6060fea.png)

**Comment by CIZKOVAL** [comment]
Kurátor už možnost notifikace má, hlavní kurátor nikoliv. V issue jsem zmiňovala, že se chyba týká i hlavního kurátora.

@Cypzirschova - předpokládám, že i hlavní kurátor by měl mít možnost notifikací, je to tak?

**Comment by Cypzirschova** [comment]
@CIZKOVAL ano, je to tak.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Nedari se mi to nasimulovat...  Na DEVu, posledni verze a u hlavniho kuratora zvonecky vidim.

**Comment by CIZKOVAL** [comment]
Retest OK, jeste bezel reindex, ted uz se to tam objevuje.
