### ISSUE TITLE
OAI Historie zmen - pole 992

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#354]
Prosim o copy paste pole 992 nad importovanym zaznamem z Alephu set DNT a co leze zo SDNNT po zmene zaznamu u daneho dila, 

- stara historie se nemodifikuje
- jak se po novu vyjadri prechod dila mezi licencemi v ramci historie

**Comment by smallcubes** [comment]
Testováno na záznamu: 
- identifikátor: `oai:aleph-nkp.cz:DNT01-000000002`
- cnb: `cnb000356128`
- název: `Amatérské radio. časopis pro radiotechniku a amatérské vysílání Ř. B, Pro konstruktéry :`

**[V aleph.nkp.cz (set DNT-ALL)](http://aleph.nkp.cz/OAI?verb=ListRecords&metadataPrefix=marc21&set=DNT-ALL)**
```xml
<record>
...
<marc:datafield tag="992" ind1=" " ind2=" ">
	<marc:subfield code="s">A</marc:subfield>
	<marc:subfield code="a">20200101</marc:subfield>
	<marc:subfield code="b">batch</marc:subfield>
</marc:datafield>
...
</record>
```

**Před změnou stavu v SDNNT (SDNNT-ALL), Stav: A**:
```xml
<record>
...
<marc:datafield tag="992" ind1=" " ind2=" ">
	<marc:subfield code="a">20200101</marc:subfield>
	<marc:subfield code="b">batch</marc:subfield>
	<marc:subfield code="s">A</marc:subfield>
</marc:datafield>
...
</record>
```

**[Po změně stavu v SDNNT (SDNNT-ALL)](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=GetRecord&identifier=oai:aleph-nkp.cz:DNT01-000000002&metadataPrefix=marc21)**
- byla zadáná žádost o vyřazení `VN`, identifikátor žádosti: `82c2a483-cdbe-4029-8246-d8b94c45e79a`, stav VN se neprojeví v OAI-PMH, následně byla žádost schválena kurátorem a označena za zpracovanou
```xml
<record>
...
<marc:datafield tag="992" ind1=" " ind2=" ">
	<marc:subfield code="s">A</marc:subfield>
	<marc:subfield code="a">20200101</marc:subfield>
	<marc:subfield code="b">batch</marc:subfield>
</marc:datafield>
...
</record>
```

Změna stavu se do OAI nepřenesla viz [dotaz](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=GetRecord&identifier=oai:aleph-nkp.cz:DNT01-000000002&metadataPrefix=marc21). Možná je nutný nějaký pravidelný reindex nebo se musí spustit nějaká procedura? Pokud ano, poprosil bych o popsání způsobu konfigurace reindexu/procedury.

@JanMeritus @pavel-stastny @CIZKOVAL

**Comment by JanMeritus** [comment]
toto je na @albertoh a @pavel-stastny dle commitu by melo byt v pristi verzi vyresno?

**Comment by pavel-stastny** [comment]
@JanMeritus Ano

**Comment by smallcubes** [comment]
Retestováno na záznamu:
- identifikátor: `oai:aleph-nkp.cz:DNT01-000000001`
- cnb: `cnb002196137`
- název: [Neue Film-Revue : Wochenschrift für Film und Kinofreunde
](https://sdnnt-test.nkp.cz/sdnnt/search?q=cnb002196137&page=0)

[V aleph.nkp.cz (set DNT-ALL)](http://aleph.nkp.cz/OAI?verb=ListRecords&metadataPrefix=marc21&set=DNT-ALL)
```xml
<marc:datafield tag="992" ind1=" " ind2=" ">
 <marc:subfield code="s">A</marc:subfield>
 <marc:subfield code="a">20200101</marc:subfield>
 <marc:subfield code="b">batch</marc:subfield>
</marc:datafield>
```

[V SDNNT OAI (oai:aleph-nkp.cz:DNT01-000000002)](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=GetRecord&identifier=oai:aleph-nkp.cz:DNT01-000000002&metadataPrefix=marc21)
```xml
<marc:datafield tag="992" ind1=" " ind2=" ">
 <marc:subfield code="s">A</marc:subfield>
 <marc:subfield code="a">20200101</marc:subfield>
 <marc:subfield code="b">batch</marc:subfield>
 <marc:subfield code="l">dnnto</marc:subfield>
</marc:datafield>
```

[Po změně stavu: z A -> N]()
```xml
<marc:datafield tag="992" ind1=" " ind2=" ">
 <marc:subfield code="s">A</marc:subfield>
 <marc:subfield code="a">20200101</marc:subfield>
 <marc:subfield code="b">batch</marc:subfield>
 <marc:subfield code="l">dnnto</marc:subfield>
 <marc:subfield code="s">N</marc:subfield>
 <marc:subfield code="a">20220428</marc:subfield>
 <marc:subfield code="b">kurator</marc:subfield>
 <marc:subfield code="k">issue 354</marc:subfield>
</marc:datafield>
```
Změna se projevila snad okamžitě, jen si nejsem jistý, zdali by nemělo být vytvořené nové 992. Jinak vypadá vše v pořádku. @JanMeritus

**Comment by CIZKOVAL** [comment]
@smallcubes @pavel-stastny @JanMeritus 
Na stejný problém narazil i p. Zahořík a zmiňuje v emailu níže, že každá položka historie by měla být v samostatném výskytu pole 992.

Dobry den,

dnes jsem narazil na další problem spojeny s OAI – udaje o historii zaznamu se v setu SDNNT-ALL predavaji všechny
v jednom vyskytu pole 992:

          <marc:datafield tag="992" ind1=" " ind2=" ">
            <marc:subfield code="s">PA</marc:subfield>
            <marc:subfield code="a">20200731</marc:subfield>
            <marc:subfield code="b">batch</marc:subfield>
            <marc:subfield code="l">dnnto</marc:subfield>
            <marc:subfield code="s">A</marc:subfield>
            <marc:subfield code="a">20210201</marc:subfield>
            <marc:subfield code="b">batch</marc:subfield>
            <marc:subfield code="l">dnnto</marc:subfield>
          </marc:datafield>

Je k tomu nejaky duvod? V zaznamech predavanych z baze DNT01 je kazda polozka historie v samostatnem
vyskytu pole 992. To je pro zpracovani mnohem vhodnejsi.

**Comment by CIZKOVAL** [comment]
Prosím o vyjádření paní @lichtenbergova jak by to mělo správně být?

**Comment by Lichtenbergova** [comment]
V záznamech předávaných z báze DNT01 je každá položka historie v samostatném
výskytu pole 992, důvod pro sloučení do jednoho pole 992 nevidím. Pole 992 si vytvořil jako opakovatelné pan Zahořík, nevidím důvod, proč to měnit.

**Comment by smallcubes** [comment]
Poprosil bych ještě pana @albertoh o změnu. (Tak jak píše paní @Lichtenbergova)

**Comment by albertoh** [comment]
Opraveno.

**Comment by smallcubes** [comment]
změna se projeví hned a každá změna má samostatné pole 992
