### ISSUE TITLE
OAI: identifikátor formální stránka

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#355]
Dobrý den, 

poprosil bych o úpravu identifikátoru v hlavičce OAI záznamů. Dle požadavku pana R. Záhoříka by identifikátor záznamu neměl odkazovat na **aleph-nkp.cz** na bázi DNT01, viz [oficiální specifikace OAI](http://www.openarchives.org/OAI/2.0/guidelines-oai-identifier.htm).

příklad **`oai:aleph-nkp.cz:DNT01-000157861`**:
```xml
<record>
  <header>
    <identifier> oai:aleph-nkp.cz:DNT01-000157861</identifier>
    <datestamp>2022-03-29T08:12:15.752Z</datestamp>
    <setSpec>SDNNT-N</setSpec>
  </header>
  ...
</record>
```
@JanMeritus

**Comment by smallcubes** [comment]
Identifikátor byl změněn. 
![obrazek](https://user-images.githubusercontent.com/78028909/165076829-f8b5f7cc-6229-4522-bf43-e9ec0835dba2.png)

@pavel-stastny chtěl bych se zeptat, neměl by se identifikátor celý skládat ze dvou částí: `namespace-identifier ":" local-identifier`? A u namespace by neměla být celá doméná (sdnnt.nkp.cz)?

**Comment by pavel-stastny** [comment]
@smallcubes Části mají být tři ` oai-identifier = scheme ":" namespace-identifier ":" local-identifier` ale namespace měl být konfigurovatelný. Tady bude ještě jeden komit.

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za reakci

**Comment by smallcubes** [comment]
@pavel-stastny ještě jsem narazil na případ, kdy je identifikátor `oai:aleph-nkp.cz:DNT01-000000001` stále přítomný viz [dotaz](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=GetRecord&identifier=oai:aleph-nkp.cz:DNT01-000000002&metadataPrefix=marc21).

**Comment by pavel-stastny** [comment]
@smallcubes To ne, spíš že ty identifikátory jsou interně zaměnitelné  [viz ](https://sdnnt-test.nkp.cz/sdnnt/oai?verb=GetRecord&identifier=oai:sdnnt:868ef8f852e17aa892c9e70a6a25f344&metadataPrefix=marc21)

**Comment by smallcubes** [comment]
@pavel-stastny děkuji za informaci, to se asi hodí. 

Nebyl by s tím nějaký problém @JanMeritus?

**Comment by smallcubes** [comment]
Prozatím issue uzavírám.
