### ISSUE TITLE
Špatně se poskládá název, je-li tvořen z několika částí

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#356]
Dobrý den,

v SDNNT se špatně poskládá název, pokud se skládá z několika částí.

Příklad **`cnb000356128, oai:aleph-nkp.cz:DNT01-000000002`**: 
- v SDNNT má dílo název: `Amatérské radio. časopis pro radiotechniku a amatérské vysílání Ř. B, Pro konstruktéry :`
- v SKC má stejné dílo název: `Amatérské radio. Ř. B, Pro konstruktéry : časopis pro radiotechniku a amatérské vysílání`

**Comment by smallcubes** [comment]
@Cypzirschova mohu tedy issue uzavřít?

**Comment by Cypzirschova** [comment]
Za mě určitě. V aplikaci to máme správně.

**Comment by smallcubes** [comment]
@Cypzirschova děkuji a issue uzavírám.

**Comment by Cypzirschova** [comment]
Ještě na to koukám, že je tam špatně diakritika, ale to je nejspíš tím, jak se to přebírá ze SKC, ale řazení je správné.
