### ISSUE TITLE
Ve vysouvací liště se nezobrazí jméno pro eduID uživatele

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#357]
Dobrý den,

ve vysouvací liště se nezobrazí jméno pro eduID uživatele, viz níže.

https://user-images.githubusercontent.com/78028909/161721775-8ec9a324-506c-4def-9182-a402711fff8d.mp4

**Comment by pkudela** [comment]
Fixed, jakmile bude nasazeno, priradim k testovani.

**Comment by smallcubes** [comment]
Jméno už vidím, děkuji Vám @pkudela za úpravu.
