### ISSUE TITLE
Vícesvazkové knihy - změna stavu a licence na úrovni svazku

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#358]
Dobrý den,
na základě issue #327 zakládám nové issue s otázkou, zda má být u knihy, která obsahuje více svazků možnost měnit stavy a licence na úrovni svazků (granurality). U formátu seriálu takto měnit jednotlivé ročníky lze, u knih lze měnit pouze na úrovni celku.

![test_granuralita](https://user-images.githubusercontent.com/92719629/161946548-faa44c04-b77b-45b7-b983-b3965563841a.png)

![zmena_stavu_gr](https://user-images.githubusercontent.com/92719629/161946576-bc9d3e41-e965-48cc-a912-346d54147871.png)

**Comment by CIZKOVAL** [comment]
Paní @Cypzirschova, poprosím o posouzení.

**Comment by Cypzirschova** [comment]
Už jsem posílala mail paní @Lichtenbergova, čekám na odpověd.

**Comment by pavel-stastny** [comment]
Dobrý den,  paní @Cypzirschova a paní @Lichtenbergova.  Jaké je rozhodnutí?  Má se nakonec povolit granularita u typu BK ?

**Comment by smallcubes** [comment]
@Cypzirschova @Lichtenbergova @CIZKOVAL poprosil bych o reakci

**Comment by Cypzirschova** [comment]
Tady bych poprosila paní @Lichtenbergova o rozhodnutí, zda se bude řešit granularita i u BK.

**Comment by Lichtenbergova** [comment]
Ano, granularita se bude řešit i u BK.

**Comment by smallcubes** [comment]
bude prověřena možnost použití pole $300, $505

**Comment by Lichtenbergova** [comment]
Vícesvazkové monografie - návěští, pozice 19 (počítají se od 0, jako u kódovaných údajů), hodnota a
Př:: -----nam-a22------aa4500

**Comment by CIZKOVAL** [comment]
@pavel-stastny mohu zavřít? Nevidím zde žádný commit, ale u vícesvazkových monografií lze měnit stav a licenci.

**Comment by CIZKOVAL** [comment]
Granuralita je zobrazena i u vícesvazkových monografií a kurátor může měnit stav na úrovni svazku.
