### ISSUE TITLE
Chybí označení u jazyku (filtr)

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#36]
Dobrý den,

ve vyhledávacím rozhraní chybí u filtru _Jazyk dokumentu_ **označení**, viz obrázek.

![sdnnt](https://user-images.githubusercontent.com/78028909/126326882-a008a289-98f7-44cd-9884-38b476d06339.png)

Děkuji za reakci.

**Comment by albertoh** [comment]
To je problem v datech. Jsou to zaznamy, ktere maji 3 mezery jako jazyk, controlni pole 008, pozice 36-39

**Comment by smallcubes** [comment]
@JanMeritus  @Cypzirschova možná by bylo dobré rozhodnout, co s tím dále dělat (nechat tak nebo upravit).

**Comment by JanMeritus** [comment]
@albertoh tyto "prazdny" data nedavat do filtru

**Comment by albertoh** [comment]
Prazdne hodnoty odstranene

**Comment by smallcubes** [comment]
@albertoh děkuji za vyřešení a uzavírám
