### ISSUE TITLE
ISBN: špatné formátování

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#361]
Dobrý den,

u díla: "Manželka pro krále / Rebecca Wintersová ; překlad Tomáš Ječný" je špatně naformátované ISBN:  **`978-83-238-5776-1 :`**. (sdnnt-test.nkp.cz)

**Comment by pavel-stastny** [comment]
@smallcubes To je otazka dat.

**Comment by JanMeritus** [comment]
@smallcubes @CIZKOVAL nutne overit v datech

**Comment by pavel-stastny** [comment]
@JanMeritus 

![image](https://user-images.githubusercontent.com/675753/162671069-3fed6d9c-831a-40f6-bacc-6e631f56e1b8.png)

**Comment by smallcubes** [comment]
@pavel-stastny je to k otestování?

**Comment by pavel-stastny** [comment]
@smallcubes Commit se tykal jinho issue.  Ad ISBN, porad plati co je uvedeno vyse.  Je to otazka dat v SKC.

**Comment by smallcubes** [comment]
@pavel-stastny dobře, tak asi můžeme uzavřít @JanMeritus?

**Comment by JanMeritus** [comment]
je to problem zdrojovych dat, uzaviram

**Comment by pavel-stastny** [comment]
@JanMeritus  Prosím neotevírat...  Data z SKC bereme tak jak jsou.  V případě potřeby změn dat tak by bylo dobré se domluvit s @Cypzirschova a @Lichtenbergova

**Comment by Lichtenbergova** [comment]
Zrovna u tohoto díla mne překvapuje spíš, že je místo vydání jiné (Polsko). 
Jinak ta dvojtečka je důsledek neúplného zápisu, občas v SKC chyby jsou, tyto snad ne často..

**Comment by CIZKOVAL** [comment]
Issue zavírám, toto dílo se v SDNNT již nevyskytuje, jde o dílo vydané v Polsku. Pokud je ve zdroji dat (SKC) u ISBN dvojtečka, tak se záznam v SDNNT i tak dohledá.
