### ISSUE TITLE
Shibboleth: nelze přiřadit API token uživateli

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#362]
Dobrý den, 

pokud je uživatel přihlášen skrze shibboleth, tak mu nelze přiřadit token pro API. 
Možná to je tak správně, ale raději na to upozorňuju.

@JanMeritus

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Ne, teoreticky lze v ramci mapovani uzivatel priradit token a bude to i fungovat ale rozhodne to nedoporucuju.   API klic slouzi jenom pro pristup k automatizovanemu vytvareni zadosti a je to dulezity jenom pro integraci s jinymi systemy.  Naopak bych drzel seznam api klicu dostupny v admin rozhrani a rozdaval jich nejaky rozumny pocet.

**Comment by JanMeritus** [comment]
@pavel-stastny ale API klice jsou vazane na uzivatele, neni to tak? urcite jejich pocet bude mensi, ale melo by byt teoreticky jedno jestli je to ucet vznikly registraci nebo z IDP ? FYI @smallcubes

**Comment by pavel-stastny** [comment]
@JanMeritus Shibbolethi uzivatele nejsou vedeni stejne jako standardni.. tedy neuvidis vsechny v administraci, ridi se atributy a konfiguraci.  Ohledne API klice, jaky to bude mit prinos ?  Resp. K cemu by to bylo?  Pokud nekdo bude bude chtit pristup pres API, stejne musi kontaktovat administratora a je podle me lepsi pro nej vytvorit ucet.

**Comment by JanMeritus** [comment]
v tomto momente to neni nutne. Uzivatele s API klicem budu lokalni, o jejich registraci a deaktivaci zadan garantujici instituce
