### ISSUE TITLE
Výpis v logu o ukončení pro definované procedury

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#363]
Dobrý den,

bylo by možné v logu přidat procedurám nějakou hlášku, že doběhly? Třeba něco jako je u reindexu, kde je vypsáno `... FINISHED ...` . Společně s jménem a časem, jak dlouho procedura běžela?
Lepé by se to pak hledalo. 

např. automatické vyřazování dle data akorát skončí s výpisem
```
07-Apr-2022 13:00:00.593 INFO [QuartzScheduler_Worker-2] cz.inovatika.sdnnt.services.impl.PXYearServiceImpl.update Updating identifiers :[oai:aleph-nkp.cz:DNT01-000047158,...]
07-Apr-2022 13:01:00.001 INFO [QuartzScheduler_Worker-4] cz.inovatika.sdnnt.sched.Job.fire Job zadost_po_minute fired
```

**Comment by JanMeritus** [comment]
@smallcubes dle meho by zrozumitelne hlasky z dobehnuti procedur meli byt standardem

**Comment by smallcubes** [comment]
@JanMeritus odebral jsem tedy enhancement a poprosil bych o implementaci @pavel-stastny

**Comment by smallcubes** [comment]
@pavel-stastny zkusil jsem nastavit filtrování, ale nepřihlásí mě to pod uživatele. 
```json
"header":"edupersonaffiliation",
"regexp" : "employee",
```

stejně tak mi nefunguje filtrování pro filtr atribut `affiliation`:
**funguje**
```json
"header":"affiliation",
"regexp" : ".*nkp.*",
```
**nefunguje**
```json
"header":"affiliation",
"regexp" : "employee@nkp.cz",
```
zkoušel jsem i s escape char. '\', ale nepomohlo to "employee@nkp\.cz"

**Comment by pavel-stastny** [comment]
@smallcubes @JanMeritus Vyřešeno ´pro operace harvestu, kontroly oproti kramerium a reindexace v případě změny schématu.   Lze konfiguračně oddělit do samostatných log souborů.   S dovolením přidávám label enhancement.

**Comment by smallcubes** [comment]
@pavel-stastny poprosil bych ještě o popis/ukázku nastavení

**Comment by pavel-stastny** [comment]
@smallcubes Postupně měním wiki, doplním to tam. Odkazy pošlu mailem.

**Comment by smallcubes** [comment]
@pavel-stastny jenom se připomínám @CIZKOVAL

**Comment by pavel-stastny** [comment]
@smallcubes  https://github.com/NLCR/SeznamDNNT/wiki/Instalace-a-konfigurace#nastaven%C3%AD-logov%C3%A1n%C3%AD

**Comment by smallcubes** [comment]
@pavel-stastny děkuji, je to hezky popsané. Měl bych jenom pár dotazů

1. K jaké proceduře se váže `cz.inovatika.sdnnt.index.utils.handlers`?
```properties
cz.inovatika.sdnnt.index.utils.handlers=5harvest.org.apache.juli.AsyncFileHandler
cz.inovatika.sdnnt.index.utils.useParentHandlers=true
```

2. Pokud bych chtěl oddělit logy ještě více např. DNT harvest bude mít samostatný soubor, stačí přidat nový handler a jemu přiřadit danou proceduru? Nebo existuje nějaký lepší způsob? 
```properties
# Například 
handlers = ...,6harvest.org.apache.juli.AsyncFileHandler
# konfigurace handleru pro DNT 
...
6harvest.org.apache.juli.AsyncFileHandler.directory = ${catalina.base}/logs
6harvest.org.apache.juli.AsyncFileHandler.prefix = DNTHarvest.
...
# konfigurace procedury
cz.inovatika.sdnnt.index.DntAlephImporter.handlers=6harvest.org.apache.juli.AsyncFileHandler
cz.inovatika.sdnnt.index.DntAlephImporter.useParentHandlers=true
```

**Comment by smallcubes** [comment]
logování, bylo dle návodu nastaveno

**Comment by pavel-stastny** [comment]
> K jaké proceduře se váže cz.inovatika.sdnnt.index.utils.handlers, je to inkrementální update?

Ne, jedná se o utilitní třídy využívající oba dva harvestery.

> Pokud bych chtěl oddělit logy ještě více např. DNT harvest bude mít samostatný soubor, stačí přidat nový handler a jemu přiřadit danou proceduru? Nebo existuje nějaký lepší způsob?

> Bylo by možné ještě oddělit v lozích i shibboleth uživatele od normálních?

Jestli jde o to logování hlaviček, tak to bych spíš vypnul. V konfiguračním souboru je logger pro shibboleth, který má úroveň **FINE** nebo **FINEST**, stačí změnit na **INFO**

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za odpovědi.

**Comment by pavel-stastny** [comment]
@smallcubes Myslím, že ten proces nebude potřeba. Je založen na párování záznamů dle ČČNB a jak jsem pochopil, je to nedoporučovaný způsob od pana Záhoříka.

**Comment by smallcubes** [comment]
@pavel-stastny v logu u PX procedur stále nelze dobře poznat, zdali procedura doběhla. Chybí tám `FINISHED`.

**Comment by smallcubes** [comment]
Pro nastavení logů viz [Dokumentace](https://github.com/NLCR/SeznamDNNT/wiki/Nastaven%C3%AD-logov%C3%A1n%C3%AD)
