### ISSUE TITLE
Importy: Kosmas

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#365]
Dobrý den,

chtěl bych se zeptat, jak mám nastavit importy pro Kosmas (brainest). Pro Distri.cz a Palmknihy.cz, se skládá curl příkaz. Pro Kosmas jsem pouze dostal částečný popis endpointu, který musí mít v základu eany, viz níže. Mohli byste mě prosím navést? @JanMeritus @pavel-stastny 

příklad dotazu na Kosmas: `api/v1/Product/CheckProductDistribution?eans=9788085605778`

**Comment by pavel-stastny** [comment]
Ja poprosim @albertoh

**Comment by JanMeritus** [comment]
proprosim @albertoh @pavel-stastny

**Comment by albertoh** [comment]
Dobry den.
Podobne jako ostatni distributory curl:
...sdnnt/api/index/import_kosmas?url=https://www.kosmas.cz/atl_shop/nkp.xml

**Comment by smallcubes** [comment]
@albertoh tahle URL se ke mně nedostala, vyzkouším. Děkuji.

**Comment by smallcubes** [comment]
@Cypzirschova spustil jsem proceduru a do SDNNT-test se přidala, Je za Vás v pořádku?

**Comment by Cypzirschova** [comment]
Zatím nedokážu odpovědět, protože to na seznamu našlo 0 výsledků. 
![Bez názvu1000](https://user-images.githubusercontent.com/86351100/162932388-27966e8c-8834-422c-9b15-1e1d6bf98da3.png)

**Comment by albertoh** [comment]
U me taky nejsou zadne zaznamy na kontrolu, tj, zaznamy na seznamu se stavem A, PA, NL

**Comment by smallcubes** [comment]
@albertoh @Cypzirschova našel jsem dílo, kde by mohla být provedena shoda:

**Kosmas**:
```xml
<ARTICLE>
  <NAME>Světlo v září</NAME>
  <EAN>9788090027381</EAN>
  <AVAILABILITY>0</AVAILABILITY>
  <DATEEXP>1990</DATEEXP>
  <AUTHOR>Jiřina Hauková</AUTHOR>
  <PUBLISHING>H+H</PUBLISHING>
  <LANGUAGE>česky</LANGUAGE>
</ARTICLE>
```

**SDNNT**: 
`"Světlo v září / Jiřina Hauková"`, `cnb000113068`, `80-900273-8-5`

**Comment by smallcubes** [comment]
@albertoh přidávám ještě výpis, který se objeví po dokončení procedury
```json
{
  "ellapsed": "0:04:17.349",
  "total": 95501,
  "file": "https://www.kosmas.cz/atl_shop/nkp.xml",
  "indexed": 78539,
  "origin": "kosmas",
  "skipped": 0
}
```

**Comment by smallcubes** [comment]
@Cypzirschova pokusil jsem se dohledat nějaká překrývající díla:

Díla v SDNNT (stav N) i v Kosmasu:
- Moje zlatá řemesla
Díla v SDNNT (PA, A) v Kosmasu (Availability = 0):
- Portréty, Viktor Stoilov, cnb000069323

**Comment by Cypzirschova** [comment]
@smallcubes zřejmě je tam něco špatně nastavené, protože jsem zatím koukala jen na ty Portréty a rozhodně v seznamu toto dílo je.
[katalog SDNNT](https://aleph.nkp.cz/F/?func=direct&doc_number=000086139&local_base=DNT)
[Kosmas](https://www.kosmas.cz/knihy/105066/portrety/l)
[Aplikace](https://sdnnt-test.nkp.cz/sdnnt/search?q=cnb000069323&page=0)
[SKC](https://aleph.nkp.cz/F/?func=direct&doc_number=000904492&local_base=SKC)

**Comment by Cypzirschova** [comment]
Ještě doplnění - Kosmas má toto dílo skladem.

**Comment by albertoh** [comment]
Podivam se, kde je problem

**Comment by albertoh** [comment]
Opravil jsem kod. Az bude nasazeno, muzete znovu vyzkouset

**Comment by pavel-stastny** [comment]
@Cypzirschova @smallcubes Nový build je na DEV serveru, pokud chcete vyzkoušet, můžete tam.

**Comment by smallcubes** [comment]
@albertoh @pavel-stastny @Cypzirschova už doběhl import Kosmase na **DEVu**. 

![obrazek](https://user-images.githubusercontent.com/78028909/163128168-794ac9e9-07ed-4995-b7b4-ea131e5b6346.png)


Výpis:
```json
{
  "ellapsed": "0:19:38.120",
  "total": 95541,
  "file": "https://www.kosmas.cz/atl_shop/nkp.xml",
  "indexed": 7498,
  "origin": "kosmas",
  "skipped": 0
}
```

**Comment by Cypzirschova** [comment]
Chybí informace o EANU, odkazy, v záhlaví chybí autor (viz poslední obr.) - Kosmas, DEV
![Importy-kosmas1](https://user-images.githubusercontent.com/86351100/163132719-048c3413-60b6-423f-a285-2e161069dce4.png)

Takto to vypadá u kontroly Palmknihy, DEV
![importy-kosmas](https://user-images.githubusercontent.com/86351100/163132711-81d38f86-cf89-47f1-8fdf-aca270d78939.png)


Takto to vypadá na TESTu např. Palmknih:
![Importy-kosmas3](https://user-images.githubusercontent.com/86351100/163132730-7493d21c-227d-42ff-9532-ba2000b3bcb2.png)

**Comment by JanMeritus** [comment]
@pavel-stastny @albertoh v jakem je to stavu? FYI @Cypzirschova

**Comment by albertoh** [comment]
Nevsechny zaznamy v poskytovanem xml maji EAN. Proto i u nas chybi. Muzeme odstranit zpracovani zaznamu bez EANu. 
Take tam chybejiu i autori.
Nemame ani url na jejich stranky. Abychom to mohli sami sestavit, bylo by potreba aby dodali v tom xml jejich identifikator zaznamu, ktery take chybi v xml.

**Comment by Cypzirschova** [comment]
@albertoh Pokud tam není odkaz ani na stránky distributora, tak to nemám, jak zkontrolovat.

**Comment by albertoh** [comment]
Rozumim. Mam ale k dispozici jen takova informace:

<ARTICLE>
  <NAME>Válka v Pacifiku</NAME>
  <EAN>9788072033225</EAN>
  <AVAILABILITY>0</AVAILABILITY>
  <DATEEXP>2001</DATEEXP>
  <AUTHOR>Dan Van Der Vat</AUTHOR>
  <PUBLISHING>Argo</PUBLISHING>
  <LANGUAGE>česky</LANGUAGE>
  <TRANSLATOR>Jaroslav Hrbek</TRANSLATOR>
</ARTICLE>

A nebo jeste min:

<ARTICLE>
  <NAME>Abstrakce 1913-1914</NAME>
  <AVAILABILITY>0</AVAILABILITY>
  <DATEEXP>1900</DATEEXP>
  <PUBLISHING>Eminent - Patrik Šimon</PUBLISHING>
</ARTICLE>

**Comment by Cypzirschova** [comment]
Chápu, pokud tam není alespon ten odkaz do distributora, tak se spíše nabízí otázka, zda má smysl toho distributora přidávat? Prosím o vyjádření paní @Lichtenbergova.

**Comment by Lichtenbergova** [comment]
Bez odkazu na konkrétní titul u distributora nemá smysl distributora přidávat. Takže Kosmas je takto nepoužitelný.

**Comment by smallcubes** [comment]
poprosil bych @JanMeritus o posouzení a případně uzavření

**Comment by JanMeritus** [comment]
@smallcubes  je to na zvazeni, za mne pokud distributor signalizuje ze dilo ma na sklade odkaz je skor doplnkova informace k overeni sparovani (nad ramece bib informaci), na posouzeni prenechavam ale @Cypzirschova @Lichtenbergova

**Comment by Cypzirschova** [comment]
Za mě to důležité je, protože dostupnost u distributora se může změnit ze dne na den. Pokud tam není odkaz, tak si nemůžu ověřit, jaká je aktuální situace u distributora. Paní @Lichtenbergova má teď dovolenou, tak bych s konečným rozhodnutím ještě počkala až se vrátí.

**Comment by JanMeritus** [comment]
@albertoh prosim o popsani dokumentace do wiki na pozadovane pole

**Comment by smallcubes** [comment]
@albertoh připomínám se s popsním do wiki

**Comment by Cypzirschova** [comment]
@pavel-stastny @albertoh 
Bude nějak dále řešeno?

**Comment by albertoh** [comment]
Na wiki jsem napsal strucny popis importu (Kontrola proti distributerum). Poprosil bych @pavel-stastny o kontrole proti cestine :)
Neni tam zadna diakritika, a obavam se, ze i cestina bude spatna

**Comment by Cypzirschova** [comment]
Ještě posílám info, které posílal pan Zahořík v mailu:
![image](https://user-images.githubusercontent.com/86351100/178679680-be7ec432-164e-4e7b-aeff-e3f10241c90d.png)

**Comment by albertoh** [comment]
Pridal jsem vytvoreni url na titul na strankach Kosmas.

**Comment by smallcubes** [comment]
@Cypzirschova Import jsem spustil a před chvilkou doběhl.

```json
Today 2022-07-14
command: curl -Lk url
  "ellapsed": "0:07:40.509",
  "total": 96300,
  "file": "url",
  "indexed": 70918,
  "origin": "kosmas",
  "skipped": 0
}
Started:  2022-07-14
Finished: 2022-07-14
Duration: 00:07:41
```
