### ISSUE TITLE
Instituce u uživatelů přihlášených přes Shibboleth

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#367]
Dobrý den,
uživateli, který se přihlásí přes Shibboleth (není registrovaný v SDNNT) se automaticky přiřadí instituce "nkp" (zatím jsme zkoušeli jenom uživatele z NKP). Je to v pořádku? Mezi institucemi při registraci figuruje mimo jiné "NKP",  teď se tedy ve filtru objeví "nkp" i "NKP". 

![nkp](https://user-images.githubusercontent.com/92719629/162928300-5e51c15e-bd04-4725-9465-28b7bab8e60d.png)

![Instituce_test](https://user-images.githubusercontent.com/92719629/162928324-2a03f38a-9243-4e5d-8b80-79e9c64cd410.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL @smallcubes Musi se zmenit v mapovani shibboleth uzivatelu.

**Comment by CIZKOVAL** [comment]
@smallcubes Jirko, prosim koukni na to

**Comment by smallcubes** [comment]
@CIZKOVAL opraveno

**Comment by CIZKOVAL** [comment]
Retest OK, uživatelé přihlášení přes Shiboleth jsou pod institucí NKP.
