### ISSUE TITLE
Přihlášení přes Shibboleth - opakované přihlášení

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#369]
Dobrý den,
když se přihlásím přes Shibboleth (pod NKP účtem Čížková), pak se odhlásím a chci se znovu přihlásit, tak jsem rovnou přihlášená jako Čížková. Nejsem nucena vybrat instituci a vyplnit uživatele a heslo. Je to v pořádku?

**Comment by smallcubes** [comment]
@pavel-stastny  můžu přiřadit na milestone 1.0.5?

**Comment by CIZKOVAL** [comment]
@pavel-stastny Retest - přihlásím se přes Shibboleth (pod NKP účtem Čížková) --> odhlasim se --> prihlasim se - musim vybrat instituci (NKP), ale dále už nemusím zadávat jméno a heslo, je to ok?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Ano, toto je správné chování.  Http session je držena mezi Vámi a IDP a záleží na IDP kdy se "rozhodne" že session již není validní a znovu Vás donutí se přihlásit.

**Comment by CIZKOVAL** [comment]
@pavel-stastny dekuji, zaviram.
