### ISSUE TITLE
Granuralita - není zobrazena u některých seriálů

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#370]
Dobrý den,
u seriálů, které mají granuralitu by měla být možnost zobrazit ji přes tlačítko "Více" u daného díla (za předpokladu, že jsou údaje o granuralitě dostupné v SKC).

V SDNNT jsou některá díla, která tuto informaci zobrazenou nemají, v SKC ale údaje jsou.

Patrně už o tom problému víte, viz tento [komentář](https://github.com/NLCR/SeznamDNNT/issues/51#issuecomment-1048563691), ale raději zakládám nové issue.

_Např. dílo id -	oai:aleph-nkp.cz:SKC01-002318560_

![mimo_seznam_gr](https://user-images.githubusercontent.com/92719629/163165678-946b239e-d048-4257-bd46-782dec654d35.png)

![SKC_9564](https://user-images.githubusercontent.com/92719629/163165702-fb2f0279-3f85-42d8-ac33-3ca7ff04d8ec.png)

**Comment by CIZKOVAL** [comment]
@Cypzirschova pro info

**Comment by pavel-stastny** [comment]
@CIZKOVA Ja tam tu granularitu nevidim... Divate se do SKC nebo DNT ?

**Comment by pavel-stastny** [comment]
@CIZKOVAL Dilo `oai:aleph-nkp.cz:SKC01-002318560`  ma odkaz do SKC nasledujici https://aleph.nkp.cz/F/?func=direct&doc_number=002318560&local_base=SKC.

Myslim, ze ten screenshot mate z DNT baze z nasledujiciho dila   : `oai:aleph-nkp.cz:DNT01-000000533`.    Je to tak ?

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova  Pro uvedené uuid jsou v katalogu následující záznamy: 

1. `oai:aleph-nkp.cz:SKC01-000113647`
2. `oai:aleph-nkp.cz:SKC01-000111666`
3. `oai:aleph-nkp.cz:SKC01-002318560`
4. `oai:aleph-nkp.cz:SKC01-009380645`
5. `oai:aleph-nkp.cz:DNT01-000000533`

Spárované jsou pouze 1(SKC) a 5(DNT) a granularitu má pouze záznam 5.

**Comment by CIZKOVAL** [comment]
@pavel-stastny uváděné dílo je _Rudé právo orgán Československé sociálně demokratické strany dělnické_ a je ze SKC (oai:aleph-nkp.cz:SKC01-002318560). Původně bylo mimo seznam, podala jsem žádost NZN. Koukala jsem na záznam do katalogu SKC, kde byly v poli 9564 uvedeny ročníky (stejně jako je vidím v Krameriu). Bohužel dnes už v SKC vidím jiné údaje, nemůže to být tím párovacím skriptem od p. Zahoříka?

https://aleph.nkp.cz/F/4TX436RT5UTF66MFYBN43QQC3TG41115XXYVSQ5BN3Y1TCYRU9-19166?func=direct&doc_number=002318560&current_base=&format=001

**Comment by Cypzirschova** [comment]
@CIZKOVAL Jestli vidíte jiné údaje v SKC, tak to nejspíše bude úpravou záznamu někoho ze Souborného katalogu.

**Comment by CIZKOVAL** [comment]
Koukala jsem, že údaje skutečně odpovídají záznamu z DNT (oai:aleph-nkp.cz:DNT01-000000533). V UI SDNNT ale záznamy z DNT logicky nemají proklik do katalogu a já jsem včera tyto údaje našla proklikem do katalogu ze záznamu oai:aleph-nkp.cz:SKC01-002318560. 

Každopádně současná situace je v pořádku, protože v SKC není pole 9564 uvedeno.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Issue bych uzavřel

**Comment by CIZKOVAL** [comment]
Granuralita je správně u původního záznamu z DNT01 (oai:aleph-nkp.cz:DNT01-000000533) a po spárování se záznamem ze SKC (oai:aleph-nkp.cz:SKC01-000113647) ji má i tento záznam. Issue zavírám.
