### ISSUE TITLE
Kontextová informace Volné dílo - omezení viditelnosti

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#371]
Dobrý den,
z issue #269 vyplynulo, že kontextová informaci (příznak) Volné dílo má být zobrazena pouze rolím knihovna a kurátor (resp. hlavní kurátor).

Nyní ji vidí kdokoliv, včetně nepřihlášeného uživatele.

![volne_dilo](https://user-images.githubusercontent.com/92719629/163170262-64710218-c588-4969-9e45-0ea0f688620e.png)

**Comment by Cypzirschova** [comment]
Tuto informaci by měli vidět oba kurátoři (hlavní i běžný). Pokud se bavíme o viditelnosti, vždy by měli mít možnost vidět oba kurátoři.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Ok. Z výše zmíněného jsem nastavtil viditelnost příznaku pro role `knihovna`, `kurator`, `hlavní kurátor`

**Comment by CIZKOVAL** [comment]
Příznak volného díla nevidí nikdo - kurátor, hl. kurátor ani knihovna.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @smallcubes V rámci 1.0.4.5 byl vyžadován reindex dat.  Pokud tomu tak bylo, tak se sklidilo všechno znovu.  Příznaky se doplňují extra procesem. 

Otázky: 

1) Byl proveden index dat  full a pozdeji  import_dntset ? 
2) Byl spušten proces na přidání kontextové informace?

**Comment by smallcubes** [comment]
Dobrý den @pavel-stastny,

1. index dat SKC i DNT proběhl
```
# SKC
24-Apr-2022 06:58:16.590 INFO [http-nio-18080-exec-1] cz.inovatika.sdnnt.index.OAIHarvester.full full FINISHED. Indexed 37:23:18.401 in 8,148,660
# DNT
24-Apr-2022 18:03:43.346 INFO [http-nio-18080-exec-4] cz.inovatika.sdnnt.index.DntAlephImporter.getRecords FINISHED: 605,188. reqTime: 1:58:12.390. procTime: 0:01:17.474. solrTime: 0:52:09.933
```
2.  Kontextovou informací nejsem jistý, ale dle nastavení k ní mělo dojít:
```json
"krameriove_kontextova_informace": {
		"type":"kramerius_px_check",
		"cron": "0 0 0 ? * TUE *",
		"iteration": {
				"date_range": "[* TO 2020]",
		},
		"results": {
				"ctx": true
		}
},
```
```
26-Apr-2022 00:00:00.033 INFO [QuartzScheduler_Worker-10] cz.inovatika.sdnnt.services.impl.PXKrameriusServiceImpl.check Current iteration filter [id_pid:uuid, fmt:BK, ((date1_int:[* TO 2020] AND -date2_int:*) OR (date1_int:[* TO 2020] AND date2_int:[* TO 2020]))]
```

@CIZKOVAL

**Comment by pavel-stastny** [comment]
@smallcubes @CIZKOVAL To vypadá, že v  13:42:16.344 byl restart serveru a proces nedoběhl.  Doporučuji to přehodit radši na víkend.

**Comment by smallcubes** [comment]
@pavel-stastny nastavím tedy na dnešek 18:00, aby to zítra snad doběhlo (pro kontrolu a uzavření tohoto issue).

**Comment by JanMeritus** [comment]
@smallcubes prosim zde o potvrzeni korektneho dobehnuti, napsani dlouzky behu a kontrolu taky #382

**Comment by smallcubes** [comment]
Procedura *"Kontextová informace"* byla spuštěna ve čtvrtek 28/4 v 18:00 `0 0 18 ? * THU *` a doběhla v neděli 1/5 6:12 `01-May-2022 06:12:32.706` (**60h**)

Po doběhnutí se kontextová informace nezobrazila v již vytvořené PXN žádosti.

@pavel-stastny @JanMeritus @Cypzirschova @CIZKOVAL

**Comment by smallcubes** [comment]
@pavel-stastny Kontextová informace možná nedoběhla úplně správně viz logy na sdnnt-test: `pxkram.2022-05-01.log`
Pro **PXN** totiž vidím `FINISHED`, ale pro kontextovou informaci nikoliv.

**Comment by CIZKOVAL** [comment]
Retest OK.

Kontextovou informaci "Volné dílo v DK" vidí jen kurátor, hl. kurátor a knihovna.

Nepřihlášený uživatel a nakladatel (běžný user) ji nevidí.

Vyzkoušeno na záznamu: 	cnb000561209
![nakladatel_kontext](https://user-images.githubusercontent.com/92719629/186887463-ed98063a-4440-4bcd-9aab-384baedc6cf3.png)
![kurator_kontext](https://user-images.githubusercontent.com/92719629/186887483-7ab529c2-8649-4e1b-aedd-52909f140177.png)
