### ISSUE TITLE
Některá díla se dostaly zpět mimo seznam a smazala se historie

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#374]
Dobrý den,
následující díla, která byla mimo seznam jsem 7.4. 2022 zařadila na seznam pomocí žádosti NZN. **Díla se dostala do stavu A s licencí dnnto, následující den přišla notifikace.**

Dnes jsem zjistila, že díla jsou opět mimo seznam a **historie je prázdná**. Čím to je?

![mimo_sez](https://user-images.githubusercontent.com/92719629/164191755-a24c13c6-8ceb-4a90-ae97-f2c756a959fa.png)

![notif_orange](https://user-images.githubusercontent.com/92719629/164192133-c67e270c-9656-4c0e-ac6b-5c09161466d6.png)

**Comment by smallcubes** [comment]
@pavel-stastny @CIZKOVAL reimport z SKC proběhl

**Comment by CIZKOVAL** [comment]
Full index dat se používal pouze na testovacím prostředí, nyní se již nepoužívá.
