### ISSUE TITLE
Notifikace: změna času u notifikace se neprojeví

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#375]
Dobrý den,

nastavím-li jiný čas pro denní notifikaci, tak se změna neprojeví. 

Napřiklad výchozí stav:
```json
"notifikace_den": {
	"type": "notifications",
	"interval": "den",
	"cron": "0 0 0 * * ?"
},
```

po změně na: `0 0 12 * * ?` notifikace nepřijde.

**Comment by CIZKOVAL** [comment]
@smallcubes notifikace mi na uzivatele CIZKOVAL dorazila, problem bude jinde - u toho Shibboleth uzivatele musime overit, kde se nastavuje atribut pro email.
