### ISSUE TITLE
Dockerizace  - porty uprava na localhost

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#378]
dle @smallcubes je nutne prepsat porty na localhost ad docker compose https://github.com/NLCR/SeznamDNNT/blob/main/docker/docker-compose.yml

**Comment by smallcubes** [comment]
dle linku byl [docker-compose.yaml](https://github.com/NLCR/SeznamDNNT/blob/main/docker/docker-compose.yml) upraven @pavel-stastny, issue uzavírám.
