### ISSUE TITLE
ISBN: Srovnavani identifikatoru pri "importech"

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#379]
@pavel-stastny je pri srovnavani identifikatoru isbn zohladnena moznost jejich ruzneho formatovani?

eg.  `978-83-238-5776-1` vs `978-83-238-5776-1 :` nebo `9788323857761`

FYA @pavel-stastny 
FYI @CIZKOVAL @smallcubes @Cypzirschova

**Comment by pavel-stastny** [comment]
@JanMeritus Jestli se ptáš, zda se titul dohledá tak odpověď je dohledá.

**Comment by pavel-stastny** [comment]
@JanMeritus Pokud jde o EAN kód a ISBN v případě importů od distributorů.  Validuje se ISBN  pomocí knihovny [apache commons validator](https://commons.apache.org/proper/commons-validator/) a pokud není validní, negeneruje se EAN.

**Comment by smallcubes** [comment]
@JanMeritus issue je možné uzavřít?

**Comment by JanMeritus** [comment]
@smallcubes prosi o overeni moznosti knihovny pri ruznych formatovanich

**Comment by smallcubes** [comment]
Vyzkoušeno na palmknihách (`/api/index/import_heureka?url=http://127.0.0.1:8000/t.xml`)
Varianty: 
- `<ISBN>9788075117571</ISBN>`
- `<ISBN>978-80-751-1757-1</ISBN>`
- `<ISBN>978-8-07-511757-1</ISBN>`
