### ISSUE TITLE
Úpravy rozhraní (drobnosti)

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#38]
Dobrý den,

poprosil bych o zvážení těchto drobných úprav.

**Seznam drobných změn:**
1. [x] 1. **čárka za nakladatelem**: ve vyhledávacím rozhraní jsou uvedeny _čárky_ za _názvem nakladatele_ ve filtru: _Nakladatel_ (zaměněno z jazyku na nakladatele)
2. [x] 2.  **indikace stavu řazení záznamů**: ve vyhledávácím rozhraní není uvedena šipečka u _řazení záznamů_, např. chci-li seřadit vyhledané záznamy vzestupně, neukáže se k tomu odpovídající šipečka (dolů), viz obrázek
3. [x] 3. **whitespace zamítne přihlášení**: pokud se chci přihlásit jako: _"knihovna "_, tak mě to nepřihlasí

**Ukázky:**
**2. indikace stavu řazení záznamů**
před
<img width="179" alt="rokvydani" src="https://user-images.githubusercontent.com/78028909/126471430-4d94fd35-2f6a-4758-ad48-ab065b2e0825.png">

po
<img width="110" alt="rokvydani2" src="https://user-images.githubusercontent.com/78028909/126471444-f04d6b69-8128-4794-84bc-974cc5d1212d.png">

edit, 27/7/2021: změna 1. z jazyku na nakladatele

**Comment by albertoh** [comment]
ad. 1: Nevidim carky
ad. 2: Opravime
ad. 3: Opravime. Pokus o login bude ignorovat mezery na konci a zacatku

**Comment by smallcubes** [comment]
@albertoh ano, asi už tam nejsou nebo jsem si to spletl s polem _Nakladatel_
**1.  čárka za zkratkou jazyka**
![carky](https://user-images.githubusercontent.com/78028909/127132361-c553db34-e937-400d-b8c6-eb2e225fc195.png)

**Comment by albertoh** [comment]
Pole nakladatel se bere z marc 260b. Carky a jine znaky jsou v datech

**Comment by smallcubes** [comment]
2. opravena děkuji
3. možná by bylo dobré je odstranit @JanMeritus? (ale třeba to není nutné, nevím)

**Comment by smallcubes** [comment]
3. @albertoh momentálně se mi nejde přihlásit vůbec na účet: _knihovna_, _kurator_ a _nakladatel_. Ůčet: _admin_, který má heslo funguje včetně odřezání whitespaces

**Comment by albertoh** [comment]
Poslal jsem mail: vsechny ucty maji stejne heslo

**Comment by JanMeritus** [comment]
1. @albertoh @smallcubes pro prezentaci ve filtrech ano

**Comment by JanMeritus** [comment]
@albertoh zde poprosim o status

**Comment by albertoh** [comment]
Pokud odstranim carku pro prezentaci ve filtrech objevi se stejny filtr vice krat, a ruzne cisla.
Reseni by bylo odstranit jiz pri indexaci. Nejen carky, ale i ruzne jine znaky.
Vznikaji ale dalsi otazky, jak se zachovat k takovym prikladum:
nln, nakladatelství lidové noviny : 
nln, nakladatelství lidové noviny (5)

[nákl. vl.], 
[s.n.],

**Comment by smallcubes** [comment]
poprosil bych o reakci @JanMeritus @Cypzirschova

**Comment by Cypzirschova** [comment]
[nákl. vl.]
[s.n.]
[s.l.]

Musí být zachováno z hlediska katalogizace. V katalogizaci má význam: 
vydáno vlastním nákladem
neznámý nakladatel
neznámé místo vydání.

**Comment by Cypzirschova** [comment]
V poli 260 podpole **b** a  264 **b** musí být zachováno tak, jak je. Na konci každého nakladatele je čárka a ta se může odstranit. To samé platí i pro podpole **a** (260, 264) - místo vydání. Tam je v MARC 21 zase na konci dvojtečka tzn. dvojtečka se může odstranit.

**Comment by JanMeritus** [comment]
@smallcubes dle toho jako pise pani @Cypzirschova

**Comment by JanMeritus** [comment]
@smallcubes je zde posun? prosim o pripadnou dospecifikaci, ping na dodavatele nebo uzavreni

**Comment by pavel-stastny** [comment]
Čárky u nakladatele zrušeny.

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za opravu, uzavírám.
