### ISSUE TITLE
Příznak "volné dílo v DK" zmizel

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#382]
Dobrý den,
v rámci issue #371 jsem kontrolovala kontextovou informaci (příznak volného díla v DK) a nevidím ji u žádného díla.

Zároveň se včera vygenerovaly nové žádosti PXN a žádné dílo kontextovou informaci nemá, přestože je v Krameriu volné.

**Příklad díla, které kontextovou informaci mělo:**
![volne_dilo_v DK](https://user-images.githubusercontent.com/92719629/165723166-2672b9a0-63af-4a28-bbd2-330877b318cb.png)

**Dílo z nové PXN žádosti, které je volné v Krameriovi:**
![PXN_volne_dilo](https://user-images.githubusercontent.com/92719629/165723185-93189fea-d4a1-4b6c-8374-25aea0e17e0b.png)

**Comment by CIZKOVAL** [comment]
souvisí s issue #177, #269

**Comment by CIZKOVAL** [comment]
FYI @Cypzirschova, @smallcubes

**Comment by pavel-stastny** [comment]
@CIZKOVAL Viz [comment](https://github.com/NLCR/SeznamDNNT/issues/371#issuecomment-1111983047)

**Comment by CIZKOVAL** [comment]
Retest OK - kontextová informace je zobrazena pro všechny relevantní záznamy, kromě záznamů ve stavu X, PX a D.

![pohadky](https://user-images.githubusercontent.com/92719629/186888392-aa94d843-7f61-420e-a3a7-242eb7377128.png)
