### ISSUE TITLE
SKC-aktualizace dat

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#383]
Dobry den,

dnes jsem v nove aplikaci narazil na zaznamy s ISBN 80-7196-035-7:
   https://sdnnt-test.nkp.cz/sdnnt/search?q=80-7196-035-7&fullCatalog=true 

(prihlaseny uzivatel, zobrazit i dokumenty mimo seznam)

Zaznam zarazeny do seznamu byl v SKC smazan – odkaz do katalogu nezobrazi nic. Zrejme tedy nedochazi k prubezne aktualizaci
dat prebiranych ze SKC. Co se stane, když aktualizace probehne? Bude zaznam zarazeny do seznamu smazan a z aplikace (ze seznamu) zmizi?
Nebo bude stav a licence prenesen na zaznam, který v SKC zustava?

To to je nutne otestovat, protože takove zmeny (deduplikace) jsou v SKC normalni  a velmi caste.

R. Zahorik

**Comment by CIZKOVAL** [comment]
Přikládám screenshoty:

**SDNNT:**

![duplik_skc](https://user-images.githubusercontent.com/92719629/165728984-33d813df-9b6f-4858-973d-ef0b71987167.png)

**Odkaz na záznam z katalogu u díla, které je na seznamu** - oai:aleph-nkp.cz:SKC01-007294430

![SKC-SDNNT](https://user-images.githubusercontent.com/92719629/165729020-33261c9f-115d-433f-8793-dc980a1387b7.png)


**Odkaz na záznam z katalogu u díla, které NENÍ na seznamu** - oai:aleph-nkp.cz:SKC01-000956197

![SKC-mimo](https://user-images.githubusercontent.com/92719629/165729044-da1bab06-9c78-4de1-a52a-682d5581b08f.png)

**Comment by CIZKOVAL** [comment]
@pavel-stastny, já jsem na to odpovídala emailem takto, můžete potvrdit správnost mého tvrzení?

Ze SKC by měl probíhat:
1. pravidelný inkrementální update ze SKC – pokud to dobře chápu, tak by měl pouze aktualizovat část záznamů ze SKC a měly by zůstat zachované sdnnt stavy a historie (mělo by to probíhat 1x týdně – nyní nastaveno na každé pondělí ve 2:00)

Nastavit pravidelny inkrementalni update z SKC · Issue #307 · NLCR/SeznamDNNT (github.com)

2. reimport dat ze SKC (tj. full proces) – tato operace importuje vše znovu a je nutná pokud se něco zásadního změní

Některá díla se dostaly zpět mimo seznam a smazala se historie · Issue #374 · NLCR/SeznamDNNT (github.com)

Podle toho se domnívám, že pokud proběhne full reindex ze SKC, tak záznam ze seznamu zmizí. Pokud proběhne update ze SKC, tak by měl zůstat stav v SDNNT a historie.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova  @Lichtenbergova Souvisí se změnami v SKC a je nutné se domluvit s panem Záhoříkem.

**Comment by pavel-stastny** [comment]
> pravidelný inkrementální update ze SKC – pokud to dobře chápu, tak by měl pouze aktualizovat část záznamů ze SKC a měly by zůstat zachované sdnnt stavy a historie (mělo by to probíhat 1x týdně – nyní nastaveno na každé pondělí ve 2:00)

Má za úkol zaindexovat přírustky

> reimport dat ze SKC (tj. full proces) – tato operace importuje vše znovu a je nutná pokud se něco zásadního změní

Reimport je všechno znovu.   Probral bych to na schůzce....

**Comment by CIZKOVAL** [comment]
@pavel-stastny záznam, který je v SDNNT (ISBN 80-7196-035-7, oai:aleph-nkp.cz:SKC01-007294430) byl v SKC smazán 1.12. 2021, přesto v SDNNT zůstává. Od té doby běžel už určitě několikrát reimport dat ze SKC (full).

**Comment by smallcubes** [comment]
@pavel-stastny můžu to spustit ještě jednou, ale výsledek tohoto příkazu jsem už někde tady dával, myslím.

**Comment by pavel-stastny** [comment]
@smallcubes Ne, ne... ten záznam má ten identifikátor přiřazený... díval jsem se.

**Comment by smallcubes** [comment]
@pavel-stastny omlouvám se, moc tomu nerozumím. Je tedy něco nutné provést ještě z mojí strany?

**Comment by smallcubes** [comment]
Možná jsem to spustil na špatném jádru

**Comment by pavel-stastny** [comment]
@smallcubes @CIZKOVAL Probemere ma schuzce.

**Comment by CIZKOVAL** [comment]
Rozdělím issue do několika bodů:

**1. problém s konkrétním záznamem** 
Záznam, který zůstal v SDNNT (ISBN 80-7196-035-7, oai:aleph-nkp.cz:SKC01-007294430) byl zařazen na seznam 21.4. 2022 jak je patrné z historie záznamu. Ve stejný den se spustil full import ze SKC, tím pádem daný záznam měl už svůj SDNNT identifikátor a v SDNNT zůstal (smazané nebo zrušené záznamy v SKC tento identifikátor nemají).

Zjistili jsme, že byl full import 21.4. 2022 přerušen a nově byl spuštěn následující den, tj. 22.4. 2022 - zde bych očekávala, že se vezme informace ze SKC - tzn. smazaný záznam bez identifikátoru a že se dílo tedy ocitne mimo seznam (bez historie). Záznam zůstal v SDNNT v původním stavu (A online) a odkaz do SKC ukáže smazaný záznam.

![smazany_sdnnt](https://user-images.githubusercontent.com/92719629/165927877-5ece1ec8-62bf-44e7-b6ae-ea0dd4e0776f.png)

**2. návrh na řešení smazaného záznamu v SKC (důvodem JE deduplikace)**
Na schůzce 29.4. 2022 jsme probíraly s paní @lichtenberova, @Cypzirschova a panem @pavel-stastny, že pokud je v SKC záznam smazán (z důvodu duplicity), pak by měl v SDNNT

a) zmizet a druhý záznam (ten, který v SKC zůstává) by měl převzít stav a licenci původního 
nebo 
b) zůstat a získat nový stav (např. D jako deduplikace) a měla by být zachována historie, která by končila posledním stavem D s odůvodněním. Druhý záznam (ten, který v SKC zůstává) by měl převzít stav a licenci původního 

**3. smazání záznamu v SKC (důvodem NENÍ deduplikace)**
- může dojít ke smazání záznamu v SKC, co se poté má stát? Má úplně zmizet ze SDNNT a i z filtru děl mimo seznam?

**4. update záznamu ze SKC na pravidelné denní bázi**
- dle vyjádření @pavel-stastny mají být zohledněny pouze přírůstky. Předpokládám, že přírůstky jsou nové záznamy v SKC, nikoliv změny (např. změna linku do Krameria, nebo jiná změna na záznamu) a smazané záznamy.

Jakým způsobem se tedy změny a smazané záznamy přenesou do SDNNT, když na produkci dle @pavel-stastny nepoběží full import ze SKC.

**Comment by CIZKOVAL** [comment]
FYI @smallcubes @JanMeritus @Cypzirschova @lichtenbergova

Dobrý den, snažila jsem se sesumírovat informace z dnešní schůzky ohledně SKC importů. Prosím případně mne opravte, pokud jsem něco pochopila špatně. Předem děkuji!

**Comment by CIZKOVAL** [comment]
Vyřešeno v rámci issue #387
