### ISSUE TITLE
DATA: místo výdání Československo

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#386]
Dojde k prověření, co se má stát, pokud je v SKC uvedeno Československo jako místo vydání.

@Lichtenbergova

**Comment by Cypzirschova** [comment]
Asi by se nemělo stát, řídí se podle současnosti (Česko 008 xr a Slovensko 008 xo).

**Comment by Cypzirschova** [comment]
@smallcubes Ještě si to ověřím u kolegyně.

**Comment by Cypzirschova** [comment]
Československo by tam být už nemělo. Vždy Česko (xr) nebo Slovensko (xo). Musí to odpovídat dnešnímu území. Mám to potvrzené od kolegyně ze jmenného zpracování. Můžeš asi uzavřít @smallcubes.

**Comment by smallcubes** [comment]
@Cypzirschova moc děkuji, issue uzavírám.
