### ISSUE TITLE
Stav a licence u smazaného záznamu v SKC

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#387]
Dobrý den,
přidávám scénáře, které popsal p. Zahořík a které mohou nastat pokud bude záznam v SKC smazán (deduplikován, připojen k seriálu nebo vícesvazkové monografii.

Pokud při aktualizaci zaznamu SKC prijde do aplikace informace o smazani zaznamu, je potreba dohledat zaznam, na který mají byt stav a licence preneseny. K dohledani zaznamu je mozne pouzit cislo CNB (i zrusene), pokud ve smazanem zaznamu je, pripadne pole 910 $ax. Nastat mohou pripady, ze

-	odpovidajici zaznam je nalezen a nemá prideleny stav a licenci – v tom pripade je mozne stav a licenci zkopirovat
-	odpovidajici zaznam je nalezen a ma prideleny stav a licenci – pokud jsou shodne, není potreba nic delat, pokud jsou ruzne, je nutne predat kuratorovi
-	odpovidajicich zaznamu je nalezeno několik – je nutne predat kuratorovi
-	odpovidajici zaznam nalezen není – je nutne predat kuratorovi

Problem je zejména v poslednim pripade. Napr. v situaci, kdy v NKC dochazi ke slouceni zaznamu na soubor / seriál. Zaznamy svazku jsou v NKC smazany, resp. oznaceny BAS 90, ale souborny zaznam se do SKC muze dostat az se zpozdenim, takze stav a licenci v aplikaci není kam prenest. Je nutne pockat, az se souborny zaznam do SKC a nasledne do aplikace dostane. Problem se dále komplikuje tim, ze v takove situaci ne vždy dochazi v SKC ke smazani zaznamu svazku. Obvykle dojde jen ke smazani pole 910 pro ABA001.

Tak, jak jsem popsal, to funguje ve stavajicim reseni.

S pozdravem ,
R. Zahorik

**Comment by CIZKOVAL** [comment]
Souvisí s issue #383

**Comment by CIZKOVAL** [comment]
FYI @smallcubes, @Cypzirschova, @lichtenbergova

**Comment by smallcubes** [comment]
Ještě propojuji s #384

**Comment by CIZKOVAL** [comment]
Vzhledem k tomu, že scénáře popsané p. Zahoříkem často končí stavem "předat kurátorovi", tak je nutné, aby se v takovém případě 

- [ ] buď vygeneroval požadavek na ověření kurátorem formou žádosti (tak jak je tomu např. u PXN žádostí) nebo
- [ ] aby taková díla dostala kurátorský stav (tak jako je tomu např. u PX stavů)

Jak jsme se domluvili na schůzce 3.5. 2022 poprosím paní @Cypzirschova ve spolupráci s paní @lichtenbergova, aby popsala workflow, které se budou týkat smazání/změny/nového záznamu v SKC s propagováním do SDNNT.

Já poté vytvořím diagramy, které budou podkladem pro implementaci řešení.

**Comment by Cypzirschova** [comment]
@CIZKOVAL pracuje se na tom až to bude hotové, tak to rozešlu.

**Comment by CIZKOVAL** [comment]
Vyřešeno, zavírám
