### ISSUE TITLE
Vytvoření uživatele: povolené bíle znaky v username

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#39]
Dobrý den,

při registraci mohu vytvořit uživatele, který má jako přihlašovací jméno pouze bílé znaky např. _"      "_, Možná to ještě není dořešené, pouze upozorňuji. 

příbuzné issue: #38 

Děkuji za reakci.

**Comment by smallcubes** [comment]
@albertoh pokud zadám uživatele s přihlašovacím jménem: "       bileznaky", tak sice vyskočí error (viz obrázek níže), ale uživatel se i tak vytvoří -> tedy není dána správna zpětná vazba, že uživatel byl vytvořen namísto erroru.

![znaky](https://user-images.githubusercontent.com/78028909/127286416-27a45157-ac80-4a3f-a0fd-5260c67869a3.png)

**Comment by smallcubes** [comment]
@albertoh @JanMeritus ještě bych se chtěl zeptat, nebylo by dobré zakázat bílé znaky uprostřed _přihlašovacího jména_ např. "bile znaky"?

**Comment by smallcubes** [comment]
> 
> 
> @albertoh pokud zadám uživatele s přihlašovacím jménem: " bileznaky", tak sice vyskočí error (viz obrázek níže), ale uživatel se i tak vytvoří -> tedy není dána správna zpětná vazba, že uživatel byl vytvořen namísto erroru.
> 
> ![znaky](https://user-images.githubusercontent.com/78028909/127286416-27a45157-ac80-4a3f-a0fd-5260c67869a3.png)

**Comment by smallcubes** [comment]
> 
> 
> @smallcubes Ta hlaska vypada, jakoby nemel pripraveny text pro mail. Zkousite to na adrese https://10.5.1.80/sdnnt/home ?

tento problém je staršího data a byl už odstraněn.


> @albertoh @JanMeritus ještě bych se chtěl zeptat, nebylo by dobré zakázat bílé znaky i uprostřed _přihlašovacího jména_ např. "bile znaky"?

@pavel-stastny spíše už jen čekám na reakci k tomuto

**Comment by JanMeritus** [comment]
@smallcubes ano souhlas

PS @smallcubes @pavel-stastny prosim nepouzivat interni adresy (!). Pouzivat denominaci DEV (puvodni), TEST (klon). dekuji

**Comment by smallcubes** [comment]
@albertoh @pavel-stastny 
doplňuji ještě:
- [ ] zakázat bílé znaky i uprostřed přihlašovacího jména např. "bile znaky"

**Comment by smallcubes** [comment]
@pavel-stastny @JanMeritus ještě bych poprosil, aby bylo někde napsané, co všechno může uživatelské jméno mít/nemít.

**Comment by JanMeritus** [comment]
- @pavel-stastny presne zapsat pak do docs (prip maileme)
- obecne pravidlo @smallcubes :
- min 8 znaku
  -  min 3 z:  Male, Velke znaky, Cislo, Specialni znak (bez whitespacu)

**Comment by pavel-stastny** [comment]
> pavel-stastny presne zapsat pak do docs (prip maileme)

Tady bych pozadal @albertoh  o doplneni. Nicmene, @JanMeritus  nebylo by lepsi neresit prihlasovaci jmeno a pouzit pouze email ?  Kdyz uz tam stejne musi byt.

**Comment by JanMeritus** [comment]
@pavel-stastny muze byt

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Myslim, ze muzeme uzavrit.  Pripadnou zmenu z uzivatelskeho jmena jenom na email muzeme resit separatne.

**Comment by smallcubes** [comment]
@pavel-stastny  děkuji za reakci a uzavírám. (Ještě by bylo dobré odstranit speciální znaky, pokud budeme využívat uži. jméno - můžeme to vyřešit v samostatném issue)
