### ISSUE TITLE
Historie stavu v některých případech neodpovídá stavu v SDNNT

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#393]
Dobrý den,
kontrolovala jsem namátkou díla v nových PXN žádostech.

V PXN žádosti z 22.5. 2022 jsou 2 díla, která mají stav A online, ale v historii stavu mají další změnu stavu, která neodpovídá konečnému zobrazení v SDNNT.

Např. Květy zla:

![kvety_zla_stav_nyni](https://user-images.githubusercontent.com/92719629/170961400-f38ca3b0-eaed-4563-b26f-7fc338981554.png)

![kvety_zla_stav](https://user-images.githubusercontent.com/92719629/170961431-40dbf0f0-3ebf-4b44-bb70-71ba98c44c4e.png)

**Comment by CIZKOVAL** [comment]
Vypadá to, že ten stav PN vzniknul importem, když je autorem změny Kosmas (žádný takový uživatel neexistuje). V xml importu Kosmas z 16.4. jsem dílo Květy zla našla.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova To vypada, jakoby probehl import a stav PX dostal az importem z DNT setu.   
@Cypzirschova  My mame definovany stav PN ?

**Comment by Cypzirschova** [comment]
Dobrý den,

dívala jsem se na to a je to zřejmě stav, který se generuje jako pravděpodobně N (vyřazeno). Z Alephu to vypadá, že se to děje, když se vygeneruje asi import od distributorů (zde Kosmas), viz níže.

![PN](https://user-images.githubusercontent.com/86351100/171097690-560bc95f-4392-4cd0-a752-945603759c50.png)
C.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Musíme synchronizovat stavy s panem Záhoříkem ale řešil bych to až příští týden, po té co bude hotová ta synchronizace s SKC.

**Comment by Cypzirschova** [comment]
V Alephu se vyskytlo 1 dílo s **veřejným** stavem PN. V současné době je to opravené na správný veřejný stav. PN se už nebude objevovat jako veřejný stav, který bude ve fasetách v aplikaci - zřejmě by musel proběhnout zase reindex, aby to zmizelo?

![PN](https://user-images.githubusercontent.com/86351100/173318707-6afd2442-4234-492e-ae72-e4f818d6cd59.png)

**Comment by CIZKOVAL** [comment]
Issue zavírám, u konkrétního díla se spároval DNT záznam se záznamem ze SKC a je tam již nyní správný stav X, který byl vidět i v Aleph [zde](https://github.com/NLCR/SeznamDNNT/issues/393#issuecomment-1141676683)
