### ISSUE TITLE
Automatické vyřazování - probíhá znovu u záznamů, které už mají PX

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#399]
Dobrý den,
procedura pro automatické vyřazování probíhá znovu u záznamů, které mají už kurátorský stav "PX". Je to tím, že mají stále i stav "A", takže dokud je kurátor **nevyřadí do "X"** nebo neprovede změnu stavu na **jiné než** "PA", "A", "NL", tak se automaticky každé úterý opět dají do stavu "A" a kurátorského stavu "PX". 

**Chtělo by to tedy upravit podmínku, aby byly vynechány záznamy, které už mají stav "PX".** 

_Poznámka: dělá to problém i v notifikacích, protože uživatel dostává každý týden změnu stavu na "A", přitom se stav nezměnil._

![historie_kur_stavu_automat](https://user-images.githubusercontent.com/92719629/172586863-55b956cb-d41e-4295-acba-7e7a49ab9091.png)

![historie_stavu_automat](https://user-images.githubusercontent.com/92719629/172586903-501fa532-8c86-475f-a1aa-a4f9deccd249.png)

**Comment by CIZKOVAL** [comment]
FYI @lichtenbergova, @Cypzirschova, @smallcubes

**Comment by Cypzirschova** [comment]
V testované verzi 1.0.9.4 se tento problém neobjevuje. 
Testováno na devu 8.1.2024: 
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/07595baf-4481-40c2-aab7-7ff8a6bb896a)
@CIZKOVAL
