### ISSUE TITLE
Role ma notifikace

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#40]
Role ma moznost si zvolit soournne notiifkace o zmene stavu del za: den, tyden, mesic a dle del konkretniho vydavatelstvi / nebo       mximalne 100 jednotkovych zaznamu

**Comment by pavel-stastny** [comment]
@JanMeritus Pod domluve @albertoh.  Bude nejdriv realizovano na UI, kdy uzivatel ve vysledku vyhledavani bude moct tlacitkem `sledovat` pridat titul do kolekce `svych` titulu.  Tittuly budou ukladany do samostatneho indexu a cronjob bude tahat primo z indexu a vytvart emailove zpravy.

**Comment by pavel-stastny** [comment]
Chybi zformatovat mail a odeslat.  Asociuji issue na sebe.

**Comment by JanMeritus** [comment]
@pavel-stastny je mozne zapnout sledovani hromadne nad dilami napr z celeho nakladatelstvi?

**Comment by pavel-stastny** [comment]
@JanMeritus Ne, hromadne notifikace jsou svazane s uzivatelem.

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Notifikace je mozno zapnout/vypnout/nastavit v profilu uplne dole.  
Moznosti:

- Nenastaveno
- Denni notifikace
- Tydenni notifikace
- Mesicini notifikace

**Comment by JanMeritus** [comment]
@smallcubes prosim o otestovani a pripadne uzavreni

**Comment by smallcubes** [comment]
@pavel-stastny děkujeme Vám za implementaci. Ještě by bylo dobré:
- někde mít přehled všech aktivních notifikacích pro uživatele (V současné době musím vyhledat dílo a až následně mohu zrušit notifikaci)

**Comment by smallcubes** [comment]
V současné době, lze zobrazit notifikace ve vyhledávání. Lepší by bylo možná samostatné rozhraní @CIZKOVAL @pavel-stastny @JanMeritus? Jinak uzavírám, děkuji.
