### ISSUE TITLE
Stav D - nahrazení záznamu v žádosti

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#401]
Dobrý den,

otestovala jsem nahrazení záznamu v žádosti (zatím u jedné žádosti). Do žádosti jsem dala dílo, které mělo kurátorský stav DX, který nakladatel nevidí. Dílo jsem zpracovala v žádosti DXN jako duplicitní a bylo nahrazeno následníkem, ale v žádosti u nakladatele zůstalo dílo se stavem D a nenahradilo se následníkem. Když si jako nakladatel vyhledám dílo podle čČNB, tak mi najde správné dílo, které je následníkem předchozího duplicitního díla.

Další problém, co jsem objevila, tak u díla nakladatel vidí v historii stav D a v té samotné žádosti také vidí stav D. Tento stav nemá být veřejný a níže posílám i screen, že ve fasetách nakladatel tento stav normálně nevidí.

![Stav D_žádost](https://user-images.githubusercontent.com/86351100/174541181-10eae130-e155-4a07-805d-62bddc8fdb6b.png)
![Stav D_žádost1](https://user-images.githubusercontent.com/86351100/174541192-daf1a36d-c4ea-41da-aa34-3c0edbe4a550.png)
![stav D_žádost2](https://user-images.githubusercontent.com/86351100/174541206-20cca6a8-3dc8-4a65-885a-44c6e925b9cb.png)
![Stav D_žádost3](https://user-images.githubusercontent.com/86351100/174541668-11a95343-539c-4b3a-81f2-c820c4f23a36.png)
@pavel-stastny @CIZKOVAL @Lichtenbergova

**Comment by CIZKOVAL** [comment]
Zkusila jsem nasimulovat stejnou situaci a trochu mi trvalo než jsem se zorientovala, tak se pokusím popsat bodově, co se nyní děje:

1. vytipuji si dílo, které je v žádosti **DXN**  
_7 statečných bojovníků proti interrupcím v USA_ 
**žádost DXN:** 2c6b3f74-253e-4fdc-95e3-cb34aa147a09
**cČNB:** cnb000088677
**záznam z DNT:** oai:aleph-nkp.cz:DNT01-000599474
**následník ze SKC:** oai:aleph-nkp.cz:SKC01-002366088

2. jako nakladatel udělám žádost **VN** (1a24c44d-8ef9-4370-abd9-cceaf822d9f2) na vytipované dílo a odešlu ji kurátorovi
3. Kurátor otevře **žádost DXN**, kde jsou u díla stavy PA online a kurátorský DXN. Vybere u žádosti DXN následnický záznam a potvrdí duplicitu (_Zobrazit následnické záznamy --> Akceptovat_).  Stav v **žádosti DXN** se změní na **D** a je zde příznak **Schváleno**.
4. Kurátor otevře žádost **VN**, kde vidí u záznamu (původního z DNT) stav **D**. **Není zde následnický záznam, ale ten původní. Žádost VN tedy nelze schválit.**

V historii v žádosti VN je u původního záznamu konečný stav D a toto je vidět pouze v žádosti. Nakladatel jinak nemá šanci si tento původní záznam zobrazit, protože už byl nahrazen následníkem. V té žádosti bych řekla, že to nevadí, naopak je dobře, že to tam je. Pokud se vyřeší bod 4 a bude záznam **v žádosti VN** nahrazen následníkem, pak tam nakladatel uvidí pouze nový záznam a u něj stav PA online a bude mít možnost schválit/odmítnout žádost VN a dále toto dílo získá stav N nebo zůstane v původním stavu.

**Comment by Cypzirschova** [comment]
Mě to přijde zmatečné, aby nakladatel viděl dílo, u kterého má stav D a když si najede kurzorem uvidí "smazané dílo". Já bych si pak řekla, že nemusím vyřazovat, když jde přece o smazané dílo. Mohlo by pak dojít i k mylné myšlence, že je to vlastně už vyřešené, protože je to smazané.

**Comment by CIZKOVAL** [comment]
Ještě přikládám hlášku, kterou vidí kurátor při pokusu o schválení VN žádosti.

![hlaska_schvaleni_D](https://user-images.githubusercontent.com/92719629/174568129-5613a8d2-357b-4acf-93a7-b6f7f2f2765c.png)

**Comment by CIZKOVAL** [comment]
Shrnuji, že je tedy potřeba vyřešit bod 4, kdy existuje dílo zároveň v žádosti DXN a v jiné žádosti (VN, VNZ, VNL, NZN). Nejdříve byla vyřešena žádost DXN, kdy se původní záznam vyřadil a nahradil novým.

**Co se má poté stát s dílem v žádosti VN, VNZ, VNL, NZN?**

- má se nahradit rovnou novým záznamem?
- co bude zapsané v historii?
- může kurátor v žádosti VN, VNZ, VNL, NZN rovnou vyřešit následnický záznam a až potom řešit schválení/zamítnutí aktuální žádosti (viz issue #403)?

**Comment by Cypzirschova** [comment]
> **Co se má poté stát s dílem v žádosti VN, VNZ, VNL, NZN?**
> 
> * má se nahradit rovnou novým záznamem?

Nahradila bych ho rovnou tím následníkem, který přebere stav i licenci.

> * co bude zapsané v historii?

Historii převezme z toho nového díla, jak to je v současné době, viz níže.
> * může kurátor v žádosti VN, VNZ, VNL, NZN rovnou vyřešit následnický záznam a až potom řešit schválení/zamítnutí aktuální žádosti (viz issue [Akceptace následnického záznamu z jiných typů žádostí než DXN #403](https://github.com/NLCR/SeznamDNNT/issues/403))?

Zřejmě by to šlo.

Historie díla, které převzalo a stav a licenci:
![Historie](https://user-images.githubusercontent.com/86351100/174575056-38d77ba4-37f2-4659-a998-ec0865a9ac1b.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova  Ještě bych poprosil o případ, kdy dílo nemá následníka.  Žádost automaticky zavřít ?

**Comment by Cypzirschova** [comment]
Pokud není následník, tak není moc co řešit. Jen by to chtělo nějakou informaci, proč se automaticky žádost uzavřela.

**Comment by CIZKOVAL** [comment]
Retest OK, 
bod 4 - kurátor otevře žádost VN, kde vidí následnický záznam, který má stav a licenci původního záznamu.. Žádost VN lze schválit.

**Comment by Cypzirschova** [comment]
Za mě také OK, uzavírám.

**Comment by CIZKOVAL** [comment]
Tady bychom ještě měli otestovat tu situaci, kdy záznam z DNT nemá následnický záznam - že bude po akceptování DXN žádost VN (resp. VNZ, VNL, NZN) prázdná a uzavře se.

**Comment by CIZKOVAL** [comment]
...počkáme až budeme mít data pro tento případ z update SKC (simulace 4a)

**Comment by Cypzirschova** [comment]
Máte pravdu.

**Comment by Cypzirschova** [comment]
@CIZKOVAL @pavel-stastny 
Mám v žádosti dílo - situace SKC_4a - dílo zůstalo v žádosti se stavem D. Žádost se nezachovala tak, jak by měla https://github.com/NLCR/SeznamDNNT/issues/401#issuecomment-1163142893.
Žádost: ad62db1d-09d6-49f1-9acd-24676c8f0621

**Comment by Cypzirschova** [comment]
Příklad další žádosti:
2f5a2967-3102-4068-b6e7-81a8d44e41c1

**Comment by Cypzirschova** [comment]
Retest:

- VN (1d809c92) a SKC_4b (samostatně) - žádost se uzavřela a je bez díla. U žádosti se automaticky vložila poznámka: **Zrušeno systémem - duplicita** to vidí i nakladatel u své žádosti  - **OK**
![image](https://user-images.githubusercontent.com/86351100/178691333-92e186c8-85fb-41c4-9349-cba2c22097fb.png)

- VN (d0984eb5) a SKC_4a (s více díly, které nejsou DX) - z žádosti zmizelo dílo s DX, zbytek žádosti zachováno. Původně v žádosti 3 díla. - **OK**
![image](https://user-images.githubusercontent.com/86351100/178692516-2f133c5c-1127-46c4-b80a-b50b36ff9b90.png)

- VNZ (480a6cff) a SKC_4a (samostatně) - žádost se uzavřela a je bez díla. U žádosti se automaticky vložila poznámka: **Zrušeno systémem - duplicita** to vidí i nakladatel u své žádosti  - **OK**
- VNZ (416464a7) a SKC_4a (s více díly, které nejsou DX) - z žádosti zmizelo dílo s DX, zbytek žádosti zachováno. - **OK**
- VNL (5a2da081) a SKC_4a (s více díly, které nejsou DX) - z žádosti zmizelo dílo s DX, zbytek žádosti zachováno. - **OK**
- VNL (0476b67f) a SKC_4a (samostatně) - žádost se uzavřela a je bez díla. U žádosti se automaticky vložila poznámka: **Zrušeno systémem - duplicita** to vidí i nakladatel u své žádosti  - **OK**

NZN mám připravená data a pokusím se zítra otestovat.

**Comment by CIZKOVAL** [comment]
@Cypzirschova pokusila jsem se otestovat případ NZN. Aby se mohla udělat žádost NZN na dílo, které je v DXN žádosti, tak je potřeba, aby takové dílo mělo stav N. Takový případ tam ale nemáme, tak jsem ho ručně změnila u 1ho díla (cnb000678373), které je v dosud nezpracované žádosti DXN (10c52acd-3a0d-43f3-bc60-10ac5ed2ed70) s odůvodněním SKC_4a. Provedla jsem žádost NZN (2af61b2b-1e25-48f3-9553-dde7f62aeb13) a odeslala. V takovém případě dílo v žádosti DXN ale už nelze schválit (je ve stavu N).

Toto asi nepůjde nasimulovat tedy, máme tam 1 dílo (cnb001134491), které je v žádosti z 20.7. a které by vyhovovalo, ale ta žádost už na testu není...

**Comment by Cypzirschova** [comment]
Retest 1.0.9.5, prostředí TEST:
Nasimulovaná situace s NZN - stav N a zároven kurátorský stav DX - žádost abcca4fe
V DXN nejdříve schválen stav D - na základě této inf. systém celou žádost uzavře.
