### ISSUE TITLE
Nelze schválit žádosti jako kurátor

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#402]
Dobrý den, 

jako kurátor nemůžu schválit žádost: VNZ, VNL, VN, NZN.

https://user-images.githubusercontent.com/78028909/174554218-c73278e4-7c36-4dcd-a354-6884f081daf7.mp4

Příklady (ID žádosti): 
1. f0ca8a24-1d33-4be8-9273-e87978860706
2. 75bc856c-8de2-4535-8f58-2f00b1a79430

Dále pokud schválím dílo v žádosti bez komentáře, tak se nic nestane. Dle @CIZKOVAL by měl být povinný, tzn. mělo by mi to vypsat nějakou hlášku o nutnosti komentáře.

**Comment by Cypzirschova** [comment]
Nevím, zda to souvisí s touto chybou, ale nejde mi ani hromadně odmítnout díla v žádosti.

**Comment by Cypzirschova** [comment]
Za mě už funkční. @smallcubes

**Comment by smallcubes** [comment]
@Cypzirschova děkuji za kontrolu, issue uzavírám.
