### ISSUE TITLE
Akceptace následnického záznamu z jiných typů žádostí než DXN

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#403]
Dobrý den,
pokud existuje dílo v žádosti DXN a nakladatel stejné dílo navrhne do žádosti (např. VN), tak kurátor má uvnitř žádosti kromě tlačítka Schválit/Zamítnout i tlačítko Zobrazit následnický záznam a uvnitř Akceptovat/Zavřít.

Když vyberu možnost Akceptovat následnický záznam, tak se objeví hláška "Není možné schválit stav". 

Otázka je zda by ze žádosti VN měl mít kurátor možnost rovnou potvrdit následníka --> záznam v žádosti by se změnil na následnický a až potom by mohl Schválit/Zamítnout žádost VN.

![VN_naslednik](https://user-images.githubusercontent.com/92719629/174567311-16f72548-3ecb-41a9-9309-e709dc71fdd6.png)

**Comment by CIZKOVAL** [comment]
Souvisí s issue #401

**Comment by CIZKOVAL** [comment]
Retest NOK, uživatel nemůže u díla, které je součástí DXN žádosti a ještě nějaké další (např. VNZ) akceptovat následnický záznam.

Nemůže ani VNZ žádost schválit, ale to je zřejmě dané tím, že musí být nejdříve vyřešena žádost DXN?

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova  Mohli bychom to probrat na schůzce ?

**Comment by Cypzirschova** [comment]
Můžeme, ještě bych přizvala určitě paní @Lichtenbergova. Já dneska můžu jen do 3.

**Comment by CIZKOVAL** [comment]
Ještě dodávám, že pokud je dílo součástí žádosti DXN, kde ještě není akceptováno/odmítnuto, tak v jiné žádosti (např. VNZ) ho nelze schválit. 

Ideální by bylo, kdyby mohl kurátor z jiných žádostí dávat rovnou akceptovat a poté schválit, tzn. že bez předchozí akceptace by dílo nešlo schválit. Probereme na schůzce.

**Comment by CIZKOVAL** [comment]
Domluvené řešení ze schůzky 23.6. 2022 s paní @Lichtenbergova a paní @Cypzirschova je následující:

Pokud je dílo součástí DXN žádosti a zároveň figuruje v uživatelské žádosti (VN, VNL, VNZ, NZN), pak **v uživatelské žádosti**  **nebude tlačítko "Zobrazit následnické záznamy"** 
**Uživatel uvidí pouze Schválit/Odmítnout.** 
**Schválit žádost nepůjde dokud nebude dílo schválené v DXN žádosti.** Kurátor může pouze žádost zamítnout.
**Když je dílo schválené v DXN žádosti, tak se v uživatelské žádosti (VN, VNL, VNZ, NZN) změní na následnický záznam a ten už půjde schválit.**

**Comment by CIZKOVAL** [comment]
Retest OK, všechny body fungují
