### ISSUE TITLE
Moje požadavky: chybí vyhledávací políčko (role knihovna)

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#404]
Dobrý den,

roli **knihovna** chybí vyhledávací políčko pro vyhledávání v žádostech a výzvách. 

![obrazek](https://user-images.githubusercontent.com/78028909/174568940-f168a0f7-837d-48c0-a6e0-81a1a620a2f5.png)

**Comment by pavel-stastny** [comment]
@smallcubes Dá se dodat ale je to tak schválně, původně bylo vyhledávací pole  myšleno/určeno pro kurátory. Vychází z issue #325

**Comment by smallcubes** [comment]
pokud by nikdo nebyl proti, tak by mi to přišlo fajn, aby si např. knihovna mohla vyhledávat v žádostech pomocí ččnb. 

@CIZKOVAL @Cypzirschova @Lichtenbergova

**Comment by pavel-stastny** [comment]
@smallcubes ČČNB tam právě není.  Políčko je uzpůsobeno tomu, co bylo probírano v issue #325.  Tedy aby kurátoři měli možnost se rychle dostat k žádosti pokud mají v ruce: 
1. číslo žádosti,
2. uživatele 
3. textové odůvodnění žádosti.

**Comment by CIZKOVAL** [comment]
Úplně původně jsme požadovali, aby mohl kurátor, hl. kurátor vyhledávat dle uživatele, což u ostatních rolí postrádá smysl. Až potom se k tomu přidalo vyhledávání dle id žádosti. Zatím jsem tu potřebu u knihovny nebo nakladatele neměla, nechám na posouzení paní @Cypzirschova, @lichtenbergova, jestli jim to přijde užitečné.

Spíš zjišťuji, že by se hodilo to vyhledávání podle identifikátoru záznamu - na to založím separátní issue.

**Comment by Cypzirschova** [comment]
Spíše bych zvolila, co je navrhováno tady #420.

**Comment by CIZKOVAL** [comment]
@smallcubes můžeme uzavřít? V issue #420 je požadavek na to, aby se dalo v žádostech vyhledávat i podle id konkrétního díla. Toto by bylo dobré mít i pro knihovnu, je to tam zmíněno. Zde bych uzavřela.

**Comment by Lichtenbergova** [comment]
OK
