### ISSUE TITLE
Díla se stavem DX v žádostech

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#406]
Dobrý den,

nejde mi hromadně odmítnout díla v žádosti VNZ. Všechna díla mají i kurátorský stav DX. 
Č. žádosti:17294e0b-ad23-49af-90c5-713ff00fa12c

U ostatních žádostí VNZ mi to šlo, ale díla v těchto žádostech neměla stav DX.
![hormadné odmítnutí](https://user-images.githubusercontent.com/86351100/174581955-7efe9b98-86ce-4cb6-baef-3c70dba1d675.png)
@pavel-stastny 
Možná to souvisí s chybou #402 ?
@smallcubes @CIZKOVAL @Lichtenbergova

**Comment by Cypzirschova** [comment]
Edit: 12:51 
Otestovány všechny možnosti vyřízení žádosti. Pokud jsou v žádosti díla se stavem DX, tak s žádostí se nedá nic dělat. Nelze hromadně schválit/odmítnou ani ručně schválit/odmítnout.

**Comment by Cypzirschova** [comment]
Dnes testováno:
Díla s kurátorským stavem DX lze jen zamítnout. 
Testováno na žádostech: 
- 71336f17  (VNZ)
- b3c70acd (VNZ)
- 8cf86b87 (VN)

**Comment by pavel-stastny** [comment]
souvisí s #403

**Comment by Cypzirschova** [comment]
Vyřešeno na dnešní schůzce, viz https://github.com/NLCR/SeznamDNNT/issues/403#issuecomment-1164256462
