### ISSUE TITLE
Jedno dílo předmětem více žádostí

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#408]
Dobrý den,

vyzkoušela jsem 1 dílo ve 2 žádostech (VNZ, VN). Nejprve jsem zpracovala žádost VN, kterou jsem schválila. Takže dílo má stav N - OK. Teď jsem se dostala ke zpracování té druhé žádosti (VNZ) a nejde mi dílo odmítnout ani ručně ani hromadně. Takže žádost zůstává stále nevyřízená, protože se s dílem nedá nic dělat.
Žádost: 4488b789-cdce-49e2-bd4a-6232eb944412

<img width="890" alt="odmítnutí" src="https://user-images.githubusercontent.com/86351100/174764760-1372448c-e3ff-430e-915c-a32cf1accbf3.png">
Cypzirschová

@pavel-stastny @CIZKOVAL  @Lichtenbergova @smallcubes

**Comment by CIZKOVAL** [comment]
Není to způsobené chybou #402?

**Comment by Cypzirschova** [comment]
Teď jsem to zkoušela znovu a stejný problém. Dala jsem jedno dílo do dvou žádostí a v té druhé už s tím nejde nic dělat.

**Comment by Cypzirschova** [comment]
d3150a3a - žádost, která nejde zpracovat
f235de00 - zpracovaná žádost

**Comment by Cypzirschova** [comment]
Retest - OK, uzavírám.
