### ISSUE TITLE
Přihlašování 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#41]
Dobrý den,
nemohu se přihlásit do žádného testovacího účtu (kurator, knihovna apod.). Včera mi to ještě normálně fungovalo.
Mohu dostat zpětnou vazbu, jestli se něco změnilo?
Děkuji Cypzirschová

**Comment by albertoh** [comment]
Aktivovali jsme kontrola hesla. Odpovezeno emailem

**Comment by smallcubes** [comment]
@albertoh  mohl bych také poprosit o přihlašovací údaje? Předem děkuji za odpověď.
