### ISSUE TITLE
Návrh na zařazení - zařazená díla

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#411]
Dobrý den,

dnes dorazila do aplikace žádost NZN, kterou poslali kolegové z KNAV. Žádost obsahuje i dvě díla, která už mají stav PA a licenci. Předpokládám, že žádost byla vytvoření v prostředí API. Lze tomuto nějak zabránit? Přímo v aplikaci nelze navrhovat díla, která už mají nějaký stav, ale tady to asi lze?

Žádost: f2d00ffd-57b7-4220-a5f4-efe722500213
![návrh na zařazení - stav](https://user-images.githubusercontent.com/86351100/174974686-b768a9ae-68e0-4846-b254-4cc9c928b502.png)
Cypzirschová

@pavel-stastny @CIZKOVAL @smallcubes @Lichtenbergova

**Comment by pavel-stastny** [comment]
@Cypzirschova Prověříme.

**Comment by Cypzirschova** [comment]
Další žádost od kolegů z KNAV.
![žádost NZN](https://user-images.githubusercontent.com/86351100/175017578-8fb3f725-72a9-44a7-a37a-250519dab7b0.png)

**Comment by smallcubes** [comment]
Vypadá to v pořádku.

Zkoušel jsem přes API zadat žádost NZN (`/request/batch/nzn`, *Hromadný návrh k zařazení do seznamu*):
Díla v žádosti:
- oai:aleph-nkp.cz:SKC01-001589886, (PA, DNNTO)
- oai:aleph-nkp.cz:SKC01-001004702, (PA, DNNTT)
- oai:aleph-nkp.cz:SKC01-000673565. (N)

Po zaslání žádosti dostanu odpověď, že díla `[oai:aleph-nkp.cz:SKC01-001589886, oai:aleph-nkp.cz:SKC01-001004702]` mají špatný stav.

- request
```bash
curl -X 'PUT' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/request/batch/nzn' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: token' \
  -H 'Content-Type: application/json' \
  -d '{
  "batch": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:SKC01-001589886",
        "oai:aleph-nkp.cz:SKC01-001004702",
        "oai:aleph-nkp.cz:SKC01-000673565"
      ],
      "pozadavek": "API #441",
      "poznamka": "API #441"
    }
  ]
}'
```

- response
```json
{
  "saved": [],
  "notsaved": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:SKC01-001589886",
        "oai:aleph-nkp.cz:SKC01-001004702",
        "oai:aleph-nkp.cz:SKC01-000673565"
      ],
      "pozadavek": "API #441",
      "poznamka": "API #441",
      "reason": "Invalid state of these documents: [oai:aleph-nkp.cz:SKC01-001589886, oai:aleph-nkp.cz:SKC01-001004702]"
    }
  ]
}
```

**Comment by Cypzirschova** [comment]
@smallcubes @pavel-stastny 

V žádosti jsou na první pohled vidět 4 díla, ale fakticky jich tam je méně. Vypadá to, že při zpracování to nedělá problém vyzkoušeno na žádosti (a38bad5d). Tam se ukázalo po zpracování 4 ze 4 děl, ale v žádosti je fakticky jen 1 dílo. Proč žádost na první pohled ukazuje vyšší počet děl, ale ve skutečnosti jich tam je méně?
![NZN-API](https://user-images.githubusercontent.com/86351100/176411075-6a258a04-7e3d-4359-9076-2df9d49ca728.png)
![NZN-API1](https://user-images.githubusercontent.com/86351100/176411101-2644d3ab-207c-4d32-b839-dddad4a7f180.png)

**Comment by smallcubes** [comment]
@Cypzirschova vytvořil jsem na to issue #430

**Comment by smallcubes** [comment]
@Cypzirschova Poprosil bych o uzavření, pokud je za Vás všechno v pořádku.

@CIZKOVAL

**Comment by Cypzirschova** [comment]
Problém vyřešen, zbytek se řeší v #430.
