### ISSUE TITLE
Stav PX, kdy není důvodem PXN žádost

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#416]
Dobrý den,
pokud je přidělen stav **PX kurátorem**, **nikoliv vznikem PXN** žádosti, pak se dílo v uživatelských žádostech (VN, VNZ, VNL, NZN) **může schvalovat/zamítat**.

**Nyní nelze schvalovat.**

![PX_kurator](https://user-images.githubusercontent.com/92719629/175481293-c7696ec2-dbf9-4f35-9e3c-1557fe9e9da6.png)

**Comment by Cypzirschova** [comment]
Pokud má dílo kurátorský stav PX, tak lze i tak dílo schválit v uživatelských žádostech. Řešeno na základě issue #531. Prosím @smallcubes uzavřít.
