### ISSUE TITLE
Nová záložka "Podpora" na domovské stránce

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#418]
Ahoj Jirko,
prosím o vytvoření nové záložky "Podpora", kde bude odkaz na technickou podporu dnnt-podpora@nkp.cz a na obsahovou podporu (kurátoři). Děkuju

**Comment by smallcubes** [comment]
@CIZKOVAL vytvořil jsem záložku podpora

**Comment by CIZKOVAL** [comment]
Záložka "Podpora" na produkci založena.

![podpora_prod](https://user-images.githubusercontent.com/92719629/190998251-962e4593-0591-4731-bc77-570b428444af.png)
