### ISSUE TITLE
Registrační email - přidat info pro nastavení role

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#419]
Ahoj Jirko,
prosím přidej do registračního emailu text, že uživatel má nyní práva pro roli nakladatel. 
Pokud potřebuje roli knihovna, kurátor nebo hlavní kurátor, pak si o ni musí zažádat přes technickou podporu, viz dnnt-podpora@nkp.cz

**Comment by smallcubes** [comment]
@CIZKOVAL přenastaveno, poprosil bych o kontrolu.

**Comment by CIZKOVAL** [comment]
Email nedorazil vůbec, viz #424

**Comment by CIZKOVAL** [comment]
Email byl změněn, nyní OK

![image](https://user-images.githubusercontent.com/92719629/178970464-808d34fc-839a-463f-8c4c-5fe8fde2e8c4.png)
