### ISSUE TITLE
Žádost na zařazení do SDNNT

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#42]
Dobrý den,

dnes jsem zkoušela vytvořit novou žádost na zařazení do SDNNT v profilu Knihovna. Byla tam rozpracovaná žádost, ze které jsem vymazala všechny položky (0 položek) a zařadila jiné konkrétně 2 knihy. Do té žádosti se mi zařadilo dalších cca 20 knih, které jsem vůbec nevybírala. Je možné, že si aplikace "pamatuje ", co tam bylo předtím za knihy než jsem je odstranila a automaticky je tam znovu zařazuje? Zkoušela jsem to 2x a vždy se mi tam těch cca 20 knih znovu objevilo.

Můžete se prosím na to podívat?
D. Cypzirschová

**Comment by albertoh** [comment]
Problem je zpusobeno tim, ze ted, pro testovani, jsou prihlasene vice osob (my dva, minimalne :) ) se stejnim uzivatelskym jmenem (knihovna)

**Comment by Cypzirschova** [comment]
Děkuju za zprávu. :-)
Cypzirschová
