### ISSUE TITLE
Filtr - sigla knihoven

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#421]
Dobrý den,
dostali jsme připomínky z KNAV:

_"Všimli jsme si ale několika drobností. Ve filtrech v levé části obrazovky jsou pod filtrem "Sigla" u některých institucí uvedeny jejich názvy, u jiných ale opravdu jejich sigla, což působí nekonzistentně."_

Z jakého důvodu se u některých siglách vyskytuje název knihovny a jiných zase ne?

Cypzirschová

@pavel-stastny @Lichtenbergova @CIZKOVAL  @smallcubes

**Comment by pavel-stastny** [comment]
@Cypzirschova Ne všechny sigly jsem dohledal.

**Comment by Cypzirschova** [comment]
Když sigly dohledám, dá se to opravit?

**Comment by Cypzirschova** [comment]
Sloupec Z - sigla, sloupec L - název knihovny
[Evidence knihoven-2022kveten.xlsx](https://github.com/NLCR/SeznamDNNT/files/8975607/Evidence.knihoven-2022kveten.xlsx)

**Comment by pkudela** [comment]
Dobry den @Cypzirschova , vetsinou jsem sigly nasel a do prekladu doplnil, ale stale jich nemala cast chybi, ty jsem v dokumentu nenasel. NIze posilam cast prekladu a tam kde sigla chybi jsou uvozovky prazdne, muzete mi prosim ty chybejici nejak dohledat?

"BOD001": "Ústřední knihovna Filozofické fakulty Masarykovy univerzity v Brně",
    "ABD014": "",
    "ABC013": "Knihovna Univerzity Karlovy v Praze",
    "BOD010": "Ústřední knihovna Právnické fakulty Masarykovy knihovny v Brně",
    "BOD002": "Knihovna univerzitního kampusu",
    "ABD113": "",
    "ABC023": "Knihovna České geologické služby - pobočka Brno",
    "BOD003": "Ústřední knihovna Pedagogické fakulty Masarykovy univerzity v Brně",
    "ABD010": "",
    "ABD064": "",
    "ABD006": "Ústav vědeckých informací 1. lékařské fakulty Univerzity Karlovy v Praze a Všeobecné fakultní nemocnice v Praze",
    "ABD013": "",
    "ABD063": "",
    "LID001": "Univerzitní knihovna Technické univerzity v Liberci",
    "BOD008": "Ústřední knihovna Veterinární a farmaceutické univerzity Brno",
    "ABD007": "",
    "ABE015": "",
    "ABD100": "Knihovna Výpočetního a informačního centra ČVUT",
    "ABD046": "",
    "ABC016": "Knihovna a dokumentace Ústavu mezinárodních vztahů",
    "OSD002": "",
    "ABD012": "",
    "CRE301": "Knihovna Regionálního muzea v Chrudimi",
    "OLE303": "Knihovna Muzea umění Olomouc",
    "ABD009": "",
    "ABD044": "",
    "ABB002": "Knihovna Masarykova ústavu a Archivu AV ČR, v.v.i.",
    "ABE454": "Centrální katolická knihovna",
    "ABD157": "",
    "LIE302": "Knihovna Severočeského muzea v Liberci",
    "PND001": "",
    "ABA003": "",
    "PND008": "Univerzitní knihovna Západočeské univerzity v Plzni",
    "ZLD002": "Ústřední knihovna Univerzity Tomáše Bati ve Zlíně",
    "HKD003": "",
    "BOD035": "",
    "ABD107": "",
    "JID501": "",
    "CBD007": "",
    "ABB010": "Knihovna Filosofického ústavu AV ČR, v.v.i.",
    "ABD003": "",
    "ABB071": "Knihovna Slovanského ústavu Akademie věd ČR, v.v.i.",
    "BOB001": "Knihovna Archeologického ústavu AV ČR, v.v.i.",
    "HKD001": "",
    "aba001": "",
    "ABD156": "",
    "KMG001": "Místní knihovna Bílany",
    "ABA100": "",
    "UOE802": "Muzejní knihovna Okresního muzea ve Vysokém Mýtě",
    "KMG502": "Městská knihovna Holešov",
    "PND003": "",
    "BNG501": "Městská knihovna Votice"

**Comment by pkudela** [comment]
@Cypzirschova nasel jsem tento seznam knihoven, kde jsou uvedeny sigly a nazev knihovny, vetsina chybejicich se zda, ze tam jsou, muzu nazvy brat z tohoto seznamu? -> https://www.caslin.cz/caslin/spoluprace/spolupracujici-knihovny/seznam-knihoven-zasilajicich-do-sk-cr-zaznamy-v-elektronicke-podobe

**Comment by Cypzirschova** [comment]
@pkudela  Můžete, pokud bude něco chybět, tak poprosím o zaslání.

**Comment by pkudela** [comment]
@Cypzirschova dekuji za odpoved, poslu jen seznam toho, co bude pripadne chybet,

**Comment by pkudela** [comment]
Hotovo, nakonec jsem nedohledal jen jedenu siglu ABA100, ale tu jsem nasel v alephu -> http://aleph.nkp.cz/publ/adr/00000/28/000002871.htm
Vsechny doplnene sigly jsou vcetne anglickeho prekladu, ktery mozna bude dobre v budoucnosti projit a upresnit. Jakmile bude k testovani @pavel-stastny oznaci.

**Comment by Cypzirschova** [comment]
Super, děkuji za zprávu.

**Comment by pavel-stastny** [comment]
@Cypzirschova Všechny komity by měly být již součástí stávajícího buildu.  Domluvím se s @pkudela

**Comment by Cypzirschova** [comment]
V aplikaci na Testu to zatím není.

**Comment by Cypzirschova** [comment]
Na testu je to OK, uzavírám.

**Comment by Cypzirschova** [comment]
Dobrý den,
dnes jsem narazila na problém se siglami. Pokud si vyfiltruji nějakou knihovnu přes siglu, tak se mi ve fasetě Sigla objeví sigly, které nejsou popsány názvy knihoven. 
![Sigly](https://user-images.githubusercontent.com/86351100/179450730-0896a5cc-916f-49d0-bb94-35cc730dea0c.PNG)
![Sigly1](https://user-images.githubusercontent.com/86351100/179450740-29e5d52e-6337-4333-a5ef-7ed341365b49.PNG)
D. Cypzirschová

**Comment by Cypzirschova** [comment]
Nyní jsem objevila další sigly, ale už bez nějakého filtrování.
![Sigly2](https://user-images.githubusercontent.com/86351100/179451209-a16e76d1-b47f-492f-a26b-a7ff392481cc.PNG)

**Comment by CIZKOVAL** [comment]
@Cypzirschova a nemělo by to fungovat tak, že když filtruji podle sigly knihovny, tak mám vidět ve fasetě pouze tu siglu, kterou jsem vybrala? Nyní se tam zobrazují i všechny ostatní sigly. Pokud ano, tak bych toto issue uzavřela a zadala nové.

**Comment by Cypzirschova** [comment]
Na schůzce (29.9.) bylo domluveno, že se budou zobrazovat pouze sigly nikoliv názvy knihoven. @smallcubes

**Comment by Cypzirschova** [comment]
V aktuálně vydané verzi není. 
![image](https://user-images.githubusercontent.com/86351100/222655418-e25e1dcd-34ca-40f0-9579-cefc77e4f460.png)

**Comment by Cypzirschova** [comment]
Sigly nejsou seřazené podle abecedy:
![image](https://user-images.githubusercontent.com/86351100/228823859-f69e3573-c6f5-4f27-a8fe-7cf5f591a406.png)

**Comment by Cypzirschova** [comment]
Ve vydané verzi 1.0.7.7 nejsou stále sigly seřazené podle abecedy. 
@pavel-stastny

**Comment by pavel-stastny** [comment]
@Cypzirschova Kdyz ono to nebylo predmetem teto iterace. Ani te nynejsi, ani te minule, ani te predminule.  Nyni se opravdu resila granularita  a nekonzistence SKC vs digitalizace a veci s ni spojene.

**Comment by Cypzirschova** [comment]
V testované verzi - ok
