### ISSUE TITLE
API - připomínky

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#422]
Dobrý den,
dostali jsme připomínky z KNAV:

Při testování API jsem si potom všiml, že v některých příkladech (například GET /catalog) je jako identifikátor použit "oai:aleph-nkp.cz:DNT01-000173538". Nevím jestli DNT-01 nemíří do současného SDNNT v Alephu a příklad by tedy neměl být aktualizován.

Prosím o vyjádření @smallcubes, @pavel-stastny. 

Cypzirschová

@Lichtenbergova @CIZKOVAL

**Comment by pavel-stastny** [comment]
@Cypzirschova Souvisí s párováním.  Pokud budou všechna data napárována na SKC, tak již by se DNT-01 záznamy objevovat neměly.

**Comment by Cypzirschova** [comment]
Děkuji za odpověd, issue uzavírám.
