### ISSUE TITLE
Registrace uživatele - nepřichází emaily

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#424]
Dobrý den,
zaregistrovala jsem se na sdnnt-test.nkp.cz/sdnnt/ a **nedorazil mi registrační email**. Minulý týden v pátek dopoledne 24.6. 2022 (verze 1.0.4.6) jsem založila uživatele Nick Cave a fungovalo to. Včera 27.6. 2022 (verze 1.0.4.7) jsem založila uživatele Jim Morrison a nešlo to. Dnes 28.6. 2022 (verze 1.0.4.8) jsem zkusila uživatele John Lennon a email nepřišel.

![registrace_jim](https://user-images.githubusercontent.com/92719629/176132556-fef50987-81fe-42c5-9b74-9e0b09f19900.png)

![registrace_john](https://user-images.githubusercontent.com/92719629/176132584-86942f2b-bab9-4322-8b24-b9b45773ffac.png)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Můžete vyzkoušet ?

**Comment by CIZKOVAL** [comment]
Retest OK, registační email chodí - a je tam i změněný text 

![image](https://user-images.githubusercontent.com/92719629/178731906-e1d7b76a-9f67-40f2-9d4a-f9f9415755a1.png)
