### ISSUE TITLE
API: nesedí počet záznamů u knihoven, nefunguje filtrování nebo jsou špatné popisky

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#425]
Dobrý den,

nevím, jestli není chyba na mé straně, ale nesedí mi počty záznamů pro jednotlivé knihovny.

**Veřejná API: `/lists/added/dnntt`**
- počet záznamů pro `ABA001` (NK ČR): 30 702
- request: 
```bash
curl -X 'GET' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/added/dnntt?institution=ABA001&from=2019-07-27T16%3A31%3A05.169Z&rows=5' \
  -H 'accept: application/json'
```
- response:
```json
{
  "numFound": 30702,
  "items": [
    {
      "pid": "uuid:e3022660-85c4-11e3-a606-005056827e51",
      "license": "dnnto",
      "territoriality": "CZ",
      "digital_libraries": [
        "NKP"
      ]}]
}
```

**[ve webovém rozhraní](https://sdnnt-test.nkp.cz/sdnnt/search?sigla=ABA001&dntstav=A)**:
- počet záznamů pro `ABA001` (NK ČR):
  - celkem: 514 623
  - dnnto: 477 562
  - dnntt: 37 061

Dále nesedí popisky pro request `/lists/added/dnntt` (*Umožňuje itervat přes seznam děl zařazených na seznam DNNT, Licence DNNTT*) nebo nefunguje filtrování, v requestu se objevují díla s licencí DNNTO.

- [x] počet záznamů = nesedí počet, jelikož jsou špatně popisky
- [x] filtrování nebo špatné popisky = špatně popisky
@CIZKOVAL

**Comment by smallcubes** [comment]
@pavel-stastny dobrý den, poprosil bych pouze o reakci

**Comment by pavel-stastny** [comment]
@smallcubes Prověřím.

**Comment by pavel-stastny** [comment]
@smallcubes Tam asi nesedí ten popisek k endpointům.  Ono to nejde moc srovnávat počty z UI. V endpointu se zobrazují pouze zdigitalizovaná díla a ještě se u periodik vyhodnocuje, zda má licenci alespoň jedna položka v granlaritě.  Takový filtr v UI není. Lze udělat částečně pro knihy a pro konkrétní digitální knihovnu: 

Pro NKP:  

Licence dnnto - formát BK : 

UI 
https://sdnnt-test.nkp.cz/sdnnt/search?fmt=BK&digital_libraries=ABA000&license=dnnto  počet: 81981

API
curl -X 'GET'   'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/added/dnnto?digital_library=NKP&format=BK&rows=10&resumptionToken=%2A'   -H 'accept: application/json'   - Počet 81981


Licence dnntt - format BK: 

https://sdnnt-test.nkp.cz/sdnnt/search?fmt=SE&digital_libraries=ABA000&license=dnnto počet: 23051

curl -X 'GET'   'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/added/dnntt?digital_library=NKP&format=BK&rows=10&resumptionToken=%2A'   -H 'accept: application/json'   - Počet 23051

Popisky jednotlivých endpointů změníme.

**Comment by smallcubes** [comment]
@pavel-stastny moc děkuji
