### ISSUE TITLE
API: nezobrazují se provedené změny

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#427]
Dobrý den,

ve [veřejné API: `/lists/changes`](https://sdnnt-test.nkp.cz/sdnnt/apidoc/public-api.html#/Umo%C5%BE%C5%88uje%20z%C3%ADskat%20seznam%20v%C5%A1ech%20zm%C4%9Bn/changes) se mi neobjeví provedené změny pro danou SIGLU/knihovnu. 

Příklad díla: ["Dendrologie s ekologií lesních dřevin. 2. část, Hospodářsky významné listnáče / Jindřich Chmelař"](https://sdnnt-test.nkp.cz/sdnnt/search?q=4a73935b1f65140daec5325a44f449f7&page=0)
- id SKC: oai:aleph-nkp.cz:SKC01-000891966
- id sdnnt: 4a73935b1f65140daec5325a44f449f7
- ccnb: cnb000056219
- dílo je ve fondu: Národní knihovna České republiky (ABA001)
- původní stavy: A, DNNTT
- stav po změně: N (id žádosti: f1b08fde-ab3e-4e53-944a-934a16a86c77)

**[veřejné API: `/lists/changes`](https://sdnnt-test.nkp.cz/sdnnt/apidoc/public-api.html#/Umo%C5%BE%C5%88uje%20z%C3%ADskat%20seznam%20v%C5%A1ech%20zm%C4%9Bn/changes)**
- request:
```bash
curl -X 'GET' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/changes?institution=ABA001&from=2021-07-27T16%3A31%3A05.169Z&rows=10' \
  -H 'accept: application/json'
```
- response:
```json
{
  "numFound": 0,
  "items": [],
  "resumptiontoken": "*"
}
```

Změna se neprojeví i v: `/lists/removed/dnnto` a `/lists/removed/dnnto/csvexport` (např. oai:aleph-nkp.cz:SKC01-000633179 (ABA001))

**Comment by pavel-stastny** [comment]
@smallcubes To jsou synchronizační endpointy.  Měly by se sledovat pouze změny stavu nebo licence

**Comment by CIZKOVAL** [comment]
@smallcubes je to tedy irelevantní issue? Možno uzavřít?

**Comment by smallcubes** [comment]
vyzkoušeno na: `oai:aleph-nkp.cz:SKC01-009531993`, ruční změna
```bash
curl -X 'GET' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/added/dnnto?digital_library=nkp&institution=ABA001&from=2024-02-08T00%3A31%3A05.169Z&rows=10&resumptionToken=%2A' \
  -H 'accept: application/json'
```


```json
{
  "items": [
    {
      "pid": "uuid:c93a7770-1227-11ed-b440-005056827e51",
      "state": "A",
      "license": "dnnto",
      "territoriality": "CZ",
      "sigla": [
        "ABA001",
        "ABB036",
        "ABE311",
        "BOA001"
      ],
      "title": "100 let městské hromadné dopravy v Brně / Dopravní podnik města Brna",
      "type": "BK",
      "catalog_identifier": "oai:aleph-nkp.cz:SKC01-000525593",
      "sdnnt_identifier": "dd166551721d4abc5e06713f2c056f2d",
      "skc": {
        "controlfield_001": "015940000212119",
        "controlfield_003": "CZ PrSKC",
        "controlfield_005": "20191114115618.0",
        "controlfield_008": "111024s1970    xr |||||||||||||| ||cze d"
      }
    },
    {
      "pid": "uuid:d0287260-8719-11e2-b238-005056827e52",
      "state": "A",
      "license": "dnnto",
      "territoriality": "CZ",
      "sigla": [
        "ABA001",
        "LIA001",
        "PVG001"
      ],
      "title": "Haná Josefa Mánesa / Mario Buzzi, Karel Hošek, Dušan Konečný",
      "type": "BK",
      "catalog_identifier": "oai:aleph-nkp.cz:SKC01-009531993",
      "sdnnt_identifier": "912faeeffa2cc9f2d6832bc72d0d227b",
      "skc": {
        "controlfield_001": "bk198203393",
        "controlfield_003": "CZ PrSKC",
        "controlfield_005": "20210602094543.0",
        "controlfield_008": "961208s1980    xr ac  e      000 0dcze  "
      }
    }
  ],
  "resumptiontoken": "AoE/AW9haTphbGVwaC1ua3AuY3o6U0tDMDEtMDA5NTMxOTkz"
}
```
