### ISSUE TITLE
Návrhy na zařazení do Seznamu děl nedostupných na trhu (SDNNT)

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#43]
Dobrý den,

dnes jsem zkoušela zase jeden z dalších návrhů na zařazení do seznamu, který jsem si vytvořila z profilu Knihovna. Pokud se návrh schválí automaticky se mu přidělí stav zařazeno. 

Proces zařazování do SDNNT, probíhá trochu jinak. Knihovna pošle návrh na zařazení a po kontrolách se jednotlivým titulům přiřadí stav návrh na zařazení (PA). Tyto návrhy knihovny posílají 2x do roka. (Nyní budou od 1.8. vystaveny nové návrhy na zařazení do SDNNT.) Následně je vystaven "Seznam návrhů na zařazení do DNNT" viz [https://aleph.nkp.cz/F/MKQB78959G5JTRC6467M359T7NHTUCS772EE6PYYFP9CQMNMKT-10719?func=file&file_name=find-b&local_base=DNTP](url)
Ten seznam návrhů je vystaven 6 měsíců a čeká se, zda se neozvou nositelé práv. Pokud se neozvou, tak se po 6 měsících mění stav z návrhu ... (PA) na zařazeno, což by mělo být A.

Pokud by tedy měla knihovna využívat profil v aplikaci a vytvářet návrhy na zařazení, měl by kurátor schválit žádost, ale titulu by měl být přidělen stav PA.

Nevím, jestli je to v aplikaci takto zamýšleno. Jen píšu poznatky. 
D. Cypzirschová

**Comment by albertoh** [comment]
Dobry den.
Opravim to

**Comment by albertoh** [comment]
Mam otazku. V pripade ze kurator odmitne, tj workflow:
O nebo N - > (uživatel/korporace) -> NZN -> (kurátor) -> PA -> (běží lhůta, vstoupi do toho uživatel/korporace ) -> VVN -> (kurátor, opačné rozhodnutí) -> PA -> (6 měsíců)-> A

lhuta 6 mesicu bezi od zacatku, nebo od okamziku odmitnuti?

**Comment by Cypzirschova** [comment]
Jestli dobře chápu otázku, tak pokud běží lhůta 6 měsíců a vstoupí do toho nakladatel a kurátor rozhodne v neprospěch tj. zamítne žádost, tak dále pokračuje rozběhlá lhůta 6 měsíců (nikoliv znova od začátku 6 měsíců). Ještě se raději zeptám paní Lichtenbergové. Ty návrhy se pak zatím vždy k datu 1.2. a 1.8. přesouvají do stavu zařazeno, pokud se v průběhu těch 6 měsíců nevyřadí.

**Comment by Cypzirschova** [comment]
Tak píšu jen doplnění. Po ověření u paní Lichtenbergové, je to tak, jak jsem již psala.  Ta lhůta pokračuje dál.

**Comment by JanMeritus** [comment]
@albertoh @pavel-stastny  prosim zde o status

**Comment by pavel-stastny** [comment]
@JanMeritus Zarazeni do stavu PA je jiz nynejsim buildu.   Shedulovane joby ma @albertoh obecne pripravene.

**Comment by JanMeritus** [comment]
@Cypzirschova mozno zde uzavrit? prosim pripadne @smallcubes o podporu

**Comment by Cypzirschova** [comment]
Dobrý den,
chtěla jsem se zeptat, zda jsou v aplikaci ošetřené ty 2 datumy, aby běželo těch 6 měsíců od 1. 2. nebo 1. 8.? Jinak v žádosti se stav mění na PA. Bude se v aplikaci implementovat tyto procesy, co jsme dělaly s paní Lichtenbergovou?
https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-919140167
DC

**Comment by pavel-stastny** [comment]
@Cypzirschova Ano, proces zmeny z PA na A je pripraveny. Otazka datumu je jenom v nastaveni scheduleru.

**Comment by Cypzirschova** [comment]
Uzavírám. Podrobně se řeší v #66
