### ISSUE TITLE
Importy - Palmknihy

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#432]
Dobrý den,
během včerejšího dne byly stránky Palmknihy mimo provoz, kontrola nenašla žádnou shodu. Dnes stránky fungují a importy zase nenašly žádnou shodu, což je špatně. V předchozí kontrole ze dne 28.6. jsem si tam nechala 20 děl, která jsem záměrně nekontrolovala. Tato díla by se měla dostat do další kontroly a to se nestalo. Teď jsem se dívala na odkazy do Palmknih a díla jsou dostupná na jejich webu.
![image](https://user-images.githubusercontent.com/86351100/176624477-46a5a2fd-0fed-48d0-ad7c-f1b9fe548523.png)
![image](https://user-images.githubusercontent.com/86351100/176624603-4ea559e5-2728-4e87-86fb-86f744bfc46e.png)
![image](https://user-images.githubusercontent.com/86351100/176624922-5669b62e-859d-494a-ac9d-6cd5d945ea5f.png)

@albertoh @pavel-stastny @smallcubes @CIZKOVAL @Lichtenbergova

**Comment by smallcubes** [comment]
@pavel-stastny  @Cypzirschova URL pro stáhnutí palmknih je nefunkční, hlásí 404 (https://www.palmknihy.cz/heureka.xml)

**Comment by Cypzirschova** [comment]
@smallcubes a u Distri je vše OK?

**Comment by smallcubes** [comment]
@Cypzirschova u distri se také vyskytuje problém, založil jsem issue #423

**Comment by albertoh** [comment]
URL pro stáhnutí palmknih je stale nefunkční, hlásí 404 (https://www.palmknihy.cz/heureka.xml)

**Comment by Cypzirschova** [comment]
@albertoh Předělávali stránky nesouvisí to s tím?

**Comment by albertoh** [comment]
Je to mozne. Nemam ale jinou adresu odkud stahovat katalog. Tim padem nemuzu se divat na ten problem.

**Comment by smallcubes** [comment]
@pavel-stastny @CIZKOVAL @albertoh @Cypzirschova volal jsem na podporu Palmknih.cz. Přístup k datům se pokusí obnovit do konce tohoto týdne tj. do 15/6.  Pokud by se změnil odkaz, dají nám vědět.

**Comment by Cypzirschova** [comment]
@smallcubes @albertoh @pavel-stastny Dnes (18.7.) jsou stránky stále nefunkční.

**Comment by Cypzirschova** [comment]
Odkaz stále nefunkční. @smallcubes @albertoh

**Comment by Cypzirschova** [comment]
@albertoh Prosím o opravu odkazu.

**Comment by smallcubes** [comment]
@Cypzirschova odkaz jsem vyměnil a spustil import palmknih na testu

**Comment by Cypzirschova** [comment]
Po změně adresy je OK, zavírám.
