### ISSUE TITLE
Notifikace pro stav D

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#433]
Dobrý den,
na jedné ze schůzek jsme si vyjasňovaly s p. Lichtenbergovou notifikace u záznamů, které získají stav D. Dávám do issue, abychom na to nezapomněli.

Bylo ujednáno, že v případě změny stavu na **D nebudou chodit** žádné roli **notifikace** o změně stavu.

**Comment by Cypzirschova** [comment]
S konečným stavem D se to musí ještě ujasnit. Poprosila bych o chvilku strpení.

**Comment by Cypzirschova** [comment]
@pavel-stastny Bylo rozhodnuto, že původní stanovisko zůstává stejné. **V případě změny stavu na D nebudou chodit žádné roli notifikace o změně stavu.**

**Comment by Cypzirschova** [comment]
Retest ve verzi 1.0.9.7 - označená díla dostala konečný stav D a notifikace nepřišla, @CIZKOVAL prosím uzavřít.
