### ISSUE TITLE
Notifikace pro stav DX

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#435]
Dobrý den,
záznamy, které se dostanou do kurátorského stavu DX (typicky je důvodem smazání v SKC a následný update), tak chodí v notifikacích s posledním stavem, který mají, a který se nezměnil, protože došlo k update a tím pádem ke změně kurátorského stavu.

![mapy_stav](https://user-images.githubusercontent.com/92719629/176860958-83dc0364-aca4-4192-8d46-3b3ae4cb31ae.png)

![historie_stavu_mapy](https://user-images.githubusercontent.com/92719629/176860770-cc17ef70-0d9f-49c4-aef6-e00f141f92cc.png)

![historie_mapy_kuratorsky_stav](https://user-images.githubusercontent.com/92719629/176860793-6f831a31-447d-40dd-bbe9-8ccbaefc925b.png)

![NOT_mail](https://user-images.githubusercontent.com/92719629/176860827-5b67b62d-46e7-4458-8c38-1dffff3b23c3.png)

**Comment by CIZKOVAL** [comment]
Nabízí se řešení, že by při změně stavu na DX nechodily nikomu notifikace, stejně jako u stavu D, viz issue #433 .

Nechám na zvážení p. @lichtenbergova, @Cypzirschova

**Comment by Cypzirschova** [comment]
Souhlasím s paní @CIZKOVAL - při změně na DX by neměla chodit notifikace, protože se v notifikacích vlastně opakuje stejný veřejný stav (A, PA, NL).

**Comment by Cypzirschova** [comment]
Doplňuji, že notifikace chodí i u kurátorského stavu PX. Je potřeba, aby jakákoliv změna/doplnění **kurátorského stavu** nebyla důvod k tomu, aby **chodily** notifikace, když se veřejný stav NEZMĚNIL. Kurátorské stavy jsou pro kurátory a jejich práci s díly.

**Comment by Cypzirschova** [comment]
U stavu DX situace stále stejná ve verzi 1.0.9.4.

**Comment by CIZKOVAL** [comment]
Retest dopadl následovně:
DX - při změně na kurátorský stav DX **NEPŘIJDE** notifikace = **OK**
D - při změně na kurátorský stav D **NEPŘIJDE** notifikace = **OK**
NPA - ještě **čekáme** na výsledky, předpokládáme, že bude OK, když se nemění běžný stav (pouze kurátorský)
PX - při změně na kurátorský stav PX **PŘIJDE** notifikace = **NOK**

![historie_PX](https://github.com/NLCR/SeznamDNNT/assets/92719629/87e9b46d-bd8f-4e3d-97e0-0337eeca9697)
![notifikace_PX](https://github.com/NLCR/SeznamDNNT/assets/92719629/e1ac663a-4608-410c-9a7e-94bcea4f90df)

**Comment by Cypzirschova** [comment]
NPA je **OK** - notifikace nepřišla

**Bug je tedy jen u PX.**

**Comment by Cypzirschova** [comment]
Retest - 1.0.9.8 - DEV:
**PX:
Stále chodí notifikace pro PX (oai:aleph-nkp.cz:SKC01-000832229):**
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/0fe79b1c-71dd-434a-889c-85296f0c4489)
E-mail:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/cde48c64-3dae-4c56-8dfa-94e09bbc5c2a)
Nesouvisí to s propsáním do klasického stavu - historie stavu?

**Comment by Cypzirschova** [comment]
Retest verze 1.0.0. - prostředí test:
**PX - notifikace již nechodí - OK**

@CIZKOVAL prosím uzavřít.
