### ISSUE TITLE
DXN - dílo se stavem X

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#437]
Dobrý den,
do žádosti DXN se dostalo dílo, které má stav X. Tento stav má dílo už skoro rok. Díla s X by to nemělo procházet.
![DXN_x](https://user-images.githubusercontent.com/86351100/177740387-e0aacedd-15be-400b-aaa3-be4e7abbc536.png)
![DXN_x1](https://user-images.githubusercontent.com/86351100/177740403-37d3fd72-36bd-4aae-8cda-4f502d2e271d.png)

Cypzirschová
@pavel-stastny @CIZKOVAL @smallcubes @Lichtenbergova

**Comment by pavel-stastny** [comment]
@Cypzirschova Opravdu? To by znamenalo, že by v SDNNT mohla být díla, která jsou v SKC smazána.

**Comment by pavel-stastny** [comment]
@Cypzirschova No, jde o to že ten identifikátor odiciálně zmizne z SKC. Měl by se normálně dohledat následník a tomu přiřadit X stav.

**Comment by Cypzirschova** [comment]
@pavel-stastny původní záměr tohoto issue je mylný (moje chyba). Mám založit nové issue na tu chybu, že to nenašlo následníka? Nebo počkáme až vyplní @smallcubes tabulku s díly a toto issue uzavřu?
