### ISSUE TITLE
Neúplná čeština v rozhraní

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#44]
Dobrý den,

v rozhraní pro zobrazení výsledků vyhledávání není přeložen popisek: _Items per page_ a výpis počtu záznamů např. _1 of 20_ viz obrázek. Jestě se také nepřekládají tooltips.

**výsledky vyhledávání**

<img width="960" alt="cestina" src="https://user-images.githubusercontent.com/78028909/128162429-1b2dae77-1745-458b-9b31-7c83b2d497c9.png">

**tooltips**

<img width="936" alt="tooltip" src="https://user-images.githubusercontent.com/78028909/131099648-bd5a3462-b45f-4652-9e9c-7ae3f8eadfb9.png">

**Comment by pkudela** [comment]
Paginace je material componenta, tam se preklad musi udelat jinym zpusobem, nicmene prelozime. Co se tyce ostatniho, tak postupne pri designovani novych prvku prochazim a budu doplnovat.

**Comment by JanMeritus** [comment]
@pkudela prosim o informaci o stavu

**Comment by pavel-stastny** [comment]
Hotovo. Nasazeno na devu.

**Comment by CIZKOVAL** [comment]
Retest OK

![nahore_100](https://user-images.githubusercontent.com/92719629/156736796-2cf21512-f7c5-424e-b6f2-7453f89f5c1f.png)
