### ISSUE TITLE
https protokol u aplikace SDNNT

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#440]
Ahoj Jirko,
odkaz **sdnnt.nkp.cz** odkazuje na stránky aplikace SDNNT s **nezabezpečeným protokolem** **http**://sdnnt.nkp.cz/sdnnt/home

Když se zadá přímo odkaz **https**://sdnnt.nkp.cz/sdnnt/home, tak je aplikace nedostupná.

![sdnnt nkp cz](https://user-images.githubusercontent.com/92719629/179477915-268142dd-b91b-4302-b5e2-94599ef04f2b.png)

![https](https://user-images.githubusercontent.com/92719629/179477931-cb62342d-1e31-4c10-bb8b-fef689ec4301.png)

**Comment by smallcubes** [comment]
@CIZKOVAL problém s HTTPS je vřešení

**Comment by smallcubes** [comment]
@CIZKOVAL hotovo
