### ISSUE TITLE
Registrace - úprava textu

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#441]
Ahoj Jirko,
prosím o úpravu registračního emailu: 

Dobrý den pane/paní Lucie Čížková,

Vaše vygenerované heslo je : abCDef_gh. **(odstranit _tečku za heslem_)**

Pokud potřebujete roli knihovna, kurátor nebo hlavní kurátor, pak si o ni **můžete** **(_musíte_ odstranit)** zažádat přes technickou podporu, viz [dnnt-podpora@nkp.cz](mailto:dnnt-podpora@nkp.cz). 

S pozdravem SDNNT

**Comment by smallcubes** [comment]
Hotovo
