### ISSUE TITLE
logo: formát svg

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#442]
Dobrý den,

pokoušel jsem se nastavit logo ve formátu `svg`, ale po upravení konfigurace se logo vůbec nezobrazí. 

```json
{
  "logo": "/sdnnt/assets/img/dnnt_logo.svg"
}
```

![obrazek](https://user-images.githubusercontent.com/78028909/179933821-198521f8-4fc8-4d55-a767-a6a677efeff7.png)

**Comment by pkudela** [comment]
Dobry den @smallcubes , muzete mi to logo sem nahrat, abych to mohl otestovat?

**Comment by smallcubes** [comment]
@pkudela přikládám logo: ![dnnt_logo_30x82px](https://user-images.githubusercontent.com/78028909/180951644-d894471e-892c-4d8f-8087-238768aff826.svg)

**Comment by pkudela** [comment]
@smallcubes vlozeni svg loga je jiz funkcni viz. screenshoty nize. Jakmile bude nasaszeno na dev serveru, tam vedet. Nicmene pred tim bych se rad zeptal kdo je autorem loga? To logo je nesymetricke, spatne citelne a spatne pouzitelne na webu, pokud chcete, mohu ho malinko doladit a pak znovu vyexportovat do svg. Pokud nechcete nechame to byt, je to jen muj nestranny nazor weboveho grafika a vyvojare designu teto aplikace.

![image](https://user-images.githubusercontent.com/16591052/181063437-c6634d1a-a8d1-4965-ba7b-2af273e5659a.png)
<img width="904" alt="image" src="https://user-images.githubusercontent.com/16591052/181063522-b25d9c0d-1df9-45af-bf0e-65348aae53fe.png">

**Comment by smallcubes** [comment]
@pkudela o úpravu loga budu jenom rád

**Comment by pkudela** [comment]
@smallcubes ok, mohu se zeptat co je to za font? Pripadne jesteli mohu pouzit podobny font?

**Comment by pkudela** [comment]
@smallcubes font jsem uz identifikoval, jedna se o Roboto, standardni font material frameworku. Udelal jsem 4 varianty - 1. varianta, kde jsou odladene mezery mezi DN a NT + dalsi 3, ktere se mi pro webove pouziti zdaji vice pouzitelne predevsim verze 3 a 4. Dam vedet, az bude nasazene, muzete pak vyzkouset am vsechny 4 verze zmenou v konfiguraci (cisla na konci 1-4). Pokud byste si vybral verzi 4, tak mi dejte vedet, tam bych kvuli proporcim upravil nepatrne vysku loga v css u vsech ostatnich to neni nutne.

![image](https://user-images.githubusercontent.com/16591052/181220110-b0510f00-f221-4d31-b8ca-85474b417a98.png)

**Comment by Cypzirschova** [comment]
@pkudela 
Font jsem dohledala [zde](https://dnnt.cz/uploads/dnnt_logomanual.pdf) - Helvetica Neue a Graphik

@pkudela @smallcubes Logo by mělo odpovídat původní podobě.

**Comment by pkudela** [comment]
@smallcubes  v tom pripade neni co resit, nasadte si tam co chcete, je tam i to puvodni s nazvem logo-sdnnt.svg, ktere jste mi poslal. Az bude novy build na serveru dam vedet.

**Comment by luckajirku** [comment]
Škoda:-(. Ta trojka (popř. čtyřka) vypadá podstatně líp...

**Comment by Cypzirschova** [comment]
@smallcubes @pkudela Ještě zjistím, zda to tak je.

**Comment by Lichtenbergova** [comment]
Bohužel to musí být podle logomanuálu, [odkaz](https://dnnt.cz/uploads/dnnt_logomanual.pdf)
Dala by se použít zkrácená varianta (jen zkratka), možná by to vypadalo lépe

**Comment by pkudela** [comment]
S tim uz si muzete delat co chcete, konfigurace pro logo v svg formatu je jiz funkcni, takze je to na vas, prosim o zavreni tohoto issue pokud je otestovano.

**Comment by smallcubes** [comment]
@pkudela děkuji Vám moc za navrhnuté logo

**Comment by smallcubes** [comment]
svg funguje a ještě jednou Vám děkujeme za loga
