### ISSUE TITLE
Importy - kosmas - audioknihy

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#443]
Dobrý den,
Kosmas prochází i audioknihy, což by se dít nemělo. Myslím, že už jsme to jednou řešili u Palmknih.
![image](https://user-images.githubusercontent.com/86351100/180167303-3a9407df-e4cd-4176-8fe3-6ca5378e4495.png)

![image](https://user-images.githubusercontent.com/86351100/180167423-faeb916f-7da9-41fb-9924-129b0247f983.png)
@pavel-stastny @albertoh @smallcubes @Lichtenbergova

**Comment by albertoh** [comment]
V xml od kosmas:

```
<ARTICLE>
  <NAME>Antonín Přidal</NAME>
  <EAN>8594178720140</EAN>
  <AVAILABILITY>0</AVAILABILITY>
  <DATEEXP>2018</DATEEXP>
  <AUTHOR>Antonín Přidal</AUTHOR>
  <PUBLISHING>Triáda</PUBLISHING>
  <LANGUAGE>česky</LANGUAGE>
</ARTICLE>
```

Jak poznat audioknihu?

**Comment by Cypzirschova** [comment]
Asi bych se zaměřila na ten EAN. EAN knih začíná 978 nebo 979 u periodik ted z hlavy nevím.

**Comment by albertoh** [comment]
Takze, nechat jen zaznamy zacinajici s 978 a 979?

**Comment by luckajirku** [comment]
a 977 pro periodika

**Comment by Cypzirschova** [comment]
Děkuji @luckajirku. Ještě se poradím s paní @Lichtenbergova.

**Comment by Cypzirschova** [comment]
@albertoh Mám to potvrzené.
977, 978, 979

**Comment by Cypzirschova** [comment]
Na testu bylo otestováno. Na produkci ještě není hotová aktuální kontrola Kosmasu.

**Comment by Cypzirschova** [comment]
Vypadá OK, zavírám.
