### ISSUE TITLE
odkazy do digitálních knihoven

### ISSUE THREAD

**Issue by zabak** [NLCR/SeznamDNNT#444]
Navazuji na https://github.com/NLCR/SeznamDNNT/issues/222#issuecomment-1186494826

Je potřeba opravit linkování do digitálních knihoven - linky by se ze záznamů v souborném katalogu měly přebírat jen z polí 911, nikoli 856. Mělo by se ale linkovat na správná místa - v datech SK jsou staré odkazy, z těch je nutno vyextrahovat uuid a vytvořit linky na správné URL - v případě MZK je to https://digitalniknihovna.cz/mzk/uuid/... a v případě NK https://ndk.cz/uuid/...

**Comment by luckajirku** [comment]
Že by tam měly být jen odkazy z 911 to je jasné, už třeba jen proto, že u těch živých periodik je pak dost nepřehledné, když je tam x odkazů na zdigitalizované ročníky, na web periodika, online verzi atd. 
Ale co se týká té druhé věci, Petře, nebylo by lepší, kdybyste si ty odkazy hromadně opravili už v SKC, než to opravovat pro SDNNT a v SKC to nechat špatně?

**Comment by zabak** [comment]
@luckajirku  Vzhledem k tomu, že i linky do NK jsou v datech SK jiné tak to je na rozhodnutí správce SK, předpokládám....

**Comment by zabak** [comment]
@luckajirku  Vzhledem k tomu, že i linky do NK jsou v datech SK jiné tak to je na rozhodnutí správce SK, předpokládám....

**Comment by black23** [comment]
Mám dotaz k odkazům do DK. Pro nasazení v produkčním prostředí potřebujeme vědět, odkud máme přebírat odkazy do DK. Někde jsou v 856, někde (i) v 956, jinde jen v 856. Potřebovali bychom to mít konzistentně a spolehlivě ve všech záznamech v setu DNNTO.

**Comment by CIZKOVAL** [comment]
Po konzultaci s p. Zahoříkem si nejsem jistá, zda je správné přebírat data pouze z MARC pole 911. 
Názor p. Zahoříka je takový, že by se mělo přebírat i pole 856x, protože odkazy do digitalních knihoven mohou byt **v poli 856 i v poli 911 současně.**

**Např. záznamy:**

**oai:aleph-nkp.cz:SKC01-003380333**
85641: |u http://krameriusndk.nkp.cz/search/handle/uuid:d5b411d0-5373-11e4-8b11-005056827e51 \|y Digitalizovaný dokument
911: |a ABA007 \|d digitalizuje se \|r 1952- \|u https://kramerius.lib.cas.cz/uuid/uuid:444fef62-e2d2-4055-97f8-1cde67538fd4

**oai:aleph-nkp.cz:SKC01-004225136**
85641: |u http://krameriusndk.nkp.cz/search/handle/uuid:ed1809a0-1e62-11e2-bec6-005056827e51 |y Digitalizovaný dokument
911: |a HKA001 |d zdigitalizováno |r 1991-2006 |u https://kramerius.svkhk.cz/search/handle/uuid:659629be-6d62-4991-8808-a062def1b2e4

**Pokud by se vypustilo pole 856x, tak přijdeme v tomto případě o odkazy do NKP.**

**Comment by luckajirku** [comment]
No a tak má NK v záznamech u těch odkazů do DK v 856 vždy vyplněné i podpole y? Pak by se dala ta podmínka nastavit tak, že 856 přebírat pouze v případě, že má 856y s hodnotou Digitalizovaný dokument, ne? 
Jako aby se tam házely úplně všechny 856, to je špatně.

**Comment by luckajirku** [comment]
Odkazy se sice přímo neukazují, ale faseta Digitální knihovna pracuje zřejmě dál i s odkazy z 856 bez ohledu na to, jestli odkaz vede skutečně do DK. Takže když si dám filtr Digitální knihovna SVK HK, vyhodí mi to např. i občasník X (cnb001785599). který v DK nemáme (ale v záznamu v SKC je v 856 odkaz na stránky vydavatele).
