### ISSUE TITLE
Odkaz na digitální dokument - chyba parsování

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#446]
U dokumentu "Obrábění I : návody pro cvičení / Josef Brychta" (cnb001409678) je chyba v odkazech na digitálních dokument - za URL adresou se vkládá text " - Část 1" / " - Část 2" 

Pravděpodobně bude tato chyba i u jiných dokumentů.

![Snímek obrazovky z 2022-07-26 10-36-49](https://user-images.githubusercontent.com/33415849/180962976-c17a6bc3-2aa5-4d56-9289-088b959a2202.png)

**Comment by jahhoo** [comment]
Stejný problém #445

**Comment by smallcubes** [comment]
@jahhoo na sdnnt-test by měla být oprava [cnb001409678](https://sdnnt-test.nkp.cz/sdnnt/search?q=cnb001409678&page=0)

@pavel-stastny

**Comment by smallcubes** [comment]
případně bych poprosil @CIZKOVAL ještě o kontrolu

**Comment by jahhoo** [comment]
U dokumentu cnb001409678 je to OK.
