### ISSUE TITLE
Chybné slučování záznamů

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#447]
V SDNNT došlo k chybnému sloučení děl:

Evropský týden kvality ( [uuid:228f1510-88d9-11e3-bd09-005056827e51](https://kramerius5.nkp.cz/uuid/uuid:228f1510-88d9-11e3-bd09-005056827e51) ) - není DNNT
a
Evropský týden kvality v České republice: kvalita - iniciativa pro změny : mezinárodní konference, Praha-Nymburk 12.-14. listopadu 2002 ( [uuid:53c6eea0-6a33-11e4-b202-005056827e52](https://kramerius5.nkp.cz/uuid/uuid:53c6eea0-6a33-11e4-b202-005056827e52) ) - ožnačeno jako DNNTO

![Snímek obrazovky z 2022-07-26 10-51-02](https://user-images.githubusercontent.com/33415849/180965438-8146803f-649b-41f2-ab22-a4c0d396ea2d.png)

**Comment by pavel-stastny** [comment]
@smallcubes Ten konkrétní [záznam](https://aleph.nkp.cz/F/?func=direct&doc_number=003237011&local_base=SKC)  byl již takto přebrán z DNT setu a důvod proč odkazuje na [uuid:228f1510-88d9-11e3-bd09-005056827e51](https://kramerius5.nkp.cz/uuid/uuid:228f1510-88d9-11e3-bd09-005056827e51) je, že to má v datech. 


![image](https://user-images.githubusercontent.com/675753/181174266-fb9a182b-7e0d-45d4-819c-2365ed11f2cb.png)

**Comment by smallcubes** [comment]
@jahhoo jedná se o stejné dílo, jsou to pouze variantní názvy.

Záznam v Alpehu od @Cypzirschova: 
![obrazek](https://user-images.githubusercontent.com/78028909/183648174-68ac3ed7-e863-4ef6-862c-ee8f7f6db550.png)

**Comment by smallcubes** [comment]
případně bych poprosil ještě @CIZKOVAL o kontrolu
