### ISSUE TITLE
Importy

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#451]
Dobrý den,
nelze schvalovat zpracované importy. Aplikace mi píše, že není vše zkontrolované, ale v nekontrolovaných záznamech je počet 0.
<img width="910" alt="importy-schválení" src="https://user-images.githubusercontent.com/86351100/181769244-e80ce77e-7c7e-4cbe-a5fa-9002d1035343.png">
<img width="839" alt="importy-schválení1" src="https://user-images.githubusercontent.com/86351100/181769369-e6a65db2-e636-468d-a9da-e5f65d2fcf1d.png">
Cypzirschová
@pavel-stastny @CIZKOVAL @smallcubes @Lichtenbergova

**Comment by smallcubes** [comment]
@Cypzirschova děje se to i na sdnnt-test?

**Comment by Cypzirschova** [comment]
@smallcubes ano, teď jsem to vyzkoušela.

**Comment by albertoh** [comment]
Opraveno. Bude v dalsim buildu
