### ISSUE TITLE
Nelze vyhledávat dle ročníků granularity

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#452]
V aplikaci SDNNT a jeho API nelze vyhledávat dle PIDů, které jsou vedeny v granularitě. 

Např. u Lidových novin (root PID: bdc405b0-e5f9-11dc-bfb2-000d606f5dc6) se nemohu dotázat na ročník 24 - PID: 2607f3e0-61e6-11dc-9c6f-000d606f5dc6

U kořenového PID je informace o granularitě obsažená, ale bylo by potřeba ještě dodělat vyhledávání PID ročníků.

**Comment by smallcubes** [comment]
Lze se dotazovat na ročníky. např. mzk, `uuid:2113d9e0-e7c7-11ec-930f-5ef3fc9bb22f`, ročník 1923 `uuid:dbae5e50-0771-11ed-9ac3-005056827e52`
