### ISSUE TITLE
Nefunguje generování CSV

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#453]
Generování CSV vrátí prázdný soubor. 

Např:

https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/added/dnntt/csvexport?from=2022-07-27T16%3A31%3A05.169Z&removeduplicatesuuid=false

nebo 

https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/added/dnntt/csvexport?digital_library=ABA001&format=BK&institution=ABA001&from=2021-07-27T16%3A31%3A05.169Z&removeduplicatesuuid=false

**Comment by smallcubes** [comment]
@jahhoo nejspíše je nutné použít kombinaci: `sigla=ABA001&digital_libraries=ABA000`

nicméně nevím proč tomu tak je @pavel-stastny

**Comment by pavel-stastny** [comment]
@smallcubes @jahhoo Sigly případně zkratky jsou brány z registru [kramériů](https://registr.digitalniknihovna.cz/library/nkp
), to byl ten důvod.  Je možné použít zkratku NKP nebo ABA000

**Comment by smallcubes** [comment]
@pavel-stastny děkuji moc za reakci

@jahhoo issue bych uzavřel a ohledně dotazu bez položky digitální knihovna bych vytvořil nové issue.

**Comment by pavel-stastny** [comment]
@smallcubes Souvisí s překlopením děl  PA - A
