### ISSUE TITLE
Registrační formulář - nelze se registrovat jako jiná knihovna než NK, MZK a KNAV

### ISSUE THREAD

**Issue by annie-cz** [NLCR/SeznamDNNT#454]
Dobrý den,

je prosím nějaký důvod, proč se dá na SDNNT registrovat pouze takto? Chybí mi tam možnosti pro další knihovny (nejlépe blank pole, kde bude pouze knihovna a člověk si vypíše sám, do které patří).

![image](https://user-images.githubusercontent.com/43028501/182144391-407a05b9-6ee5-4de6-a6b9-8428c224388c.png)

Tohle osobně považuji za chybu a bylo by prima, kdyby se opravila co nejdříve, protože jinak nelze hlásit díla za jiné knihovny - s ohledem na to, že deadline na nahlášení je ani ne do konce srpna.

**Comment by Cypzirschova** [comment]
@pavel-stastny prosím o úpravu instituce, aby se dalo případně ručně doplnit jiná knihovna.

**Comment by CIZKOVAL** [comment]
Nechat možnost vyplnit, nikoli výběr.

**Comment by Cypzirschova** [comment]
Mělo by to být řešeno aktuálně v další etapě rozvoje.

**Comment by pkudela** [comment]
Autocomplete pro instituce s moznosti vlozit novou instituci pokud neni v seznamu je pripren k implentaci pro. @pavel-stastny

**Comment by smallcubes** [comment]
děkujeme za úpravu

**Comment by Cypzirschova** [comment]
Aktuálně nasazené už i na produkci, viz obr. Proprosím @smallcubes o uzavření issue.
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/afc75aa6-1311-4429-af67-6679bca75dff)
