### ISSUE TITLE
Granuralita: stav N

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#457]
Dobrý den, 

**pokud dostane dílo s granularitou stav N (vyřazeno), tak by stav N měly získat i všechny jeho díly (části)**.

Nyní u jednotlivých částí zůstává původní stav a licence.

Toto se týká jak seriálů, tak vícesvazkových monografií.

Příklad:
- žádost: f8c9360e-561b-4c4b-b084-18305c847e9d
- dílo: oai:aleph-nkp.cz:SKC01-009389328, cnb003370539, 03dc60dbce535d7e48ae0d362c29c308

Granuralita po změně z A, DNNTO na stav N:
![obrazek](https://user-images.githubusercontent.com/78028909/183666904-0d45bc7c-7352-45a4-a1df-41ccc145ca8c.png)

- [X] **K PŘIPOMÍNKOVÁNÍ** od 09/08/2022
- [ ] **K SCHVÁLENÍ NK ČR**
- [ ] **K SCHVÁLENÍ DODAVATEL**

**Comment by CIZKOVAL** [comment]
Retest na TEST [v1.0.7.1 pre-release]

1. Pokud uživatel navrhne dílo (SE) na vyřazení (VN žádost) a kurátor to schválí, tak dílo jako celek získá stav N. **Zároveň se stav N přidělí i všem jeho dílům (granularita)** = OK

2. Pokud kurátor změní ručně stav u díla (SE) z A na N, tak dílo jako celek získá stav N. **Zároveň se stav N přidělí i všem jeho dílům (granularita)** = OK

1a) pokud dílo navrhnu zpět na zařazení (žádost NZN) a kurátor to schválí, tak dílo jako celek získá stav NPA--PA--A. **U jednotlivých dílů zůstává stále stav N** (od stavu PA by měly mít všechny části PA, posléze A). Předpokládám ale, že toto bude vyřešeno, pokud proběhne automatická procedura na granularitu, kde se stav a licence řídí rokem vydání (pokud není N) je to tak?

2a) pokud kurátor změní u vyřazeného díla stav N na PA (A), tak **musí vybrat i stav a licenci u jednotlivých dílů**, jinak zůstane prázdné. Nebo by se to mělo doplnit po spuštění procedury, viz 1a) Je to tak?

![granuralita_A](https://user-images.githubusercontent.com/92719629/208398462-1cb269f5-c529-4ce6-a9fd-89301986534a.png)

![granuralita_N](https://user-images.githubusercontent.com/92719629/208398491-60873ee6-0c45-4035-8bfc-fd0f55701b4b.png)

**Comment by Cypzirschova** [comment]
Doplnění issue: 
na stejném principu by měl fungovat i stav X a bohužel je tu stejná chyba jako u stavu N.
![x - granularita](https://user-images.githubusercontent.com/86351100/214541145-7a4de3eb-77ef-4ca1-97e5-f4e5402b708f.png)
![x - granularita1](https://user-images.githubusercontent.com/86351100/214541163-38f3c2d9-4dc0-4cc6-a403-ee739847e829.png)

**Comment by Cypzirschova** [comment]
Můj výše uvedený komentář souvisí spíše s granularitou obecně a jejím zobrazování. 

Prosím @pavel-stastny  o odpovědi na otázky od paní Čížkové v tomto komentáři:https://github.com/NLCR/SeznamDNNT/issues/457#issuecomment-1357384912, aby se toto issue mohlo uzavřít.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova Po našem telefonátu: 

1a) Ano, procedura bude automaticky přepisovat všechna díla.  
2a) Zařídí automatická procedura.

**Comment by Cypzirschova** [comment]
Ve verzi 1.0.7.7 OK, za mě se může issue uzavřít.
