### ISSUE TITLE
API info - vrací špatné výsledky licence

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#458]
V návaznosti na #447 upřesňuji problém. 

Aplikace správně vrací granualitu - všechny 3 zdigitalizované díla jsou správně označené jako **dnntt**. Viz:
![image_2022_08_09T13_26_23_610Z](https://user-images.githubusercontent.com/33415849/183669631-1aa147cc-86d9-4f15-b46f-e1a75fd65a22.png)

API na dotaz uuid [228f1510-88d9-11e3-bd09-005056827e51](https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/info/228f1510-88d9-11e3-bd09-005056827e51) nevrátí správnou licenci. Pro požadované UUID je licence prázdná.

![Snímek obrazovky z 2022-08-09 15-58-53](https://user-images.githubusercontent.com/33415849/183670023-e24a0461-e786-4a13-b432-ffd0f672b845.png)

Dále špatně vrací navíc i: "uuid:53c6eea0-6a33-11e4-b202-005056827e52". Nejedná se o kořenové UUID - nemělo by ho to vůbec vrátit. Chybně u něj vrací licenci **dnnto**!

**Comment by jahhoo** [comment]
Ještě přidávám screen z testovací verze API - zde to již konečně umí granualitu. Problém ale nastavá v duplikovaném zobrazení záznamu. 

- uuid:53c6eea0-6a33-11e4-b202-005056827e52 nelze považovat za rootovské UUID
- V druhé položce vrací uuid:228f1510-88d9-11e3-bd09-005056827e51 opět bez licence. Podle čeho by se pak aplikace měla rozhodovat, když v granualitě má licenci a v samostatném zobrazení se licence nenačte...


![Snímek obrazovky z 2022-08-09 16-12-41](https://user-images.githubusercontent.com/33415849/183671764-40dd7f9e-d39c-4ee6-ba3b-f99d79f08f62.png)

**Comment by pavel-stastny** [comment]
@smallcubes @jahhoo 

Ohledně licence vs nelicence.  Ve výpisu jsou dvě různá díla: 

První dílo je na seznamu: 

https://aleph.nkp.cz/F/?func=direct&doc_number=003237011&local_base=SKC  
Je to seriál, celý je pod licencí dnnto a jednotlivé ročníky jsou pod licencí dnntt. 

Pod pidem jednoho z ročníků pak figuruje i kniha, která není na seznamu: 
https://aleph.nkp.cz/F/?func=direct&doc_number=003815077&local_base=SKC. 

To je ta druhá položka výpisu a nemá stav ani licenci. 

U generování CSV nebo u synchronizace s krameriem se bere v potaz pouze díla která jsou na seznamu a mají licenci.  Pokud má položky granularity, přiděluje licence  pouze položkám granularity. Horní úroveň by se měla propisovat pomocí contains-dnnt-labels případne contains_licenses.  Viz issue [853](https://github.com/ceskaexpedice/kramerius/issues/853)

Ad root_pid.  Tam vidím chybu.  Obvykle bývá v SKC odkaz vrchní dokument a  ročníky se dotahují samostatně, tady jsou ročníky přímo v poli 856  a odkaz na vrchní úroveň chybí.

**Comment by jahhoo** [comment]
@pavel-stastny pokud ale dílo získá v granularitě licenci uuid:228f1510-88d9-11e3-bd09-005056827e51 - mělo by ji mít i při samostatném výpisu.

Pokud budu potřebovat odstranit z minulosti špatně označené dokumenty v Krameriovi - v seznamu bude i uuid:228f1510-88d9-11e3-bd09-005056827e51, že? Což by bylo špatně.

**Comment by jahhoo** [comment]
Každopádně pro https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/info/53c6eea0-6a33-11e4-b202-005056827e52 vrací API špatně licenci. Je to potřeba prioritně vyřešit. Pravděpodobně to vzniká tím, že si SDNNT myslí, že to je kořenové UUID, ale není.

![Snímek obrazovky z 2022-08-16 12-15-38](https://user-images.githubusercontent.com/33415849/184856101-25b9bbb5-86bc-4a06-b48c-62800d926ca6.png)

**Comment by smallcubes** [comment]
@pavel-stastny poprosil bych případně o reakci, abychom issue uzavřeli, vyřešii

**Comment by CIZKOVAL** [comment]
Retest na TEST [v1.0.7.1 pre-release]

Dokumenty z tohoto issues vypadají OK, zatím ale nechám otevřené v rámci testování kmplexního řešení v rámci issue #493.

**Comment by smallcubes** [comment]
Dobrý den, ten původní požadavek asi není splnění, nesedí licence: 
- https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/53c6eea0-6a33-11e4-b202-005056827e52

**Comment by pavel-stastny** [comment]
@smallcubes Opet granularita.   Neni pritomna a duvodem je, ze dilo je vedeno jako serial, jednotlive linky vedou na samostatne monografie.  Teoreticky lze rozlisit dle pole 856z ale na tom by musela existovat shoda.

**Comment by smallcubes** [comment]
retest: ca3998e

zůstalo stejné

**Comment by pavel-stastny** [comment]
@smallcubes ?? Kde nesedi licence ?

**Comment by smallcubes** [comment]
- uvedené dílo je správně [53c6eea0-6a33-11e4-b202-005056827e52](https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/53c6eea0-6a33-11e4-b202-005056827e52) (ještě proběhne dotestování) @CIZKOVAL

**Comment by smallcubes** [comment]
Nefunguje dotaz na uuid svazku, který je pod titulovým uuid.
Samostatný dotaz na uuid svazku, který není pod titulovým uuid funguje.

Příklad: oai:aleph-nkp.cz:SKC01-003137078

Granularita:
- nefugnuje: https://www.digitalniknihovna.cz/mzk/uuid/uuid:e1877a30-3cbb-11e3-ad71-005056827e52
- funguje: 	https://www.digitalniknihovna.cz/mzk/uuid/uuid:6ec32690-1702-11ed-a9ae-5ef3fc9bb22f

**Comment by pavel-stastny** [comment]
@smallcubes Nerozumim

**Comment by smallcubes** [comment]
Pro dílo v granularitě nefunguje API dotaz na uuid:6ec32690-1702-11ed-a9ae-5ef3fc9bb22f (záznam oai:aleph-nkp.cz:SKC01-003137078 ), nic mi to nevrátí:

request (uuid:6ec32690-1702-11ed-a9ae-5ef3fc9bb22f)
```bash
curl -X 'GET' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3A6ec32690-1702-11ed-a9ae-5ef3fc9bb22f?digital_library=mzk' \
  -H 'accept: application/json'
``` 

response
```json
{
  "numFound": 0,
  "items": []
}
```

naopak pro uuid:e1877a30-3cbb-11e3-ad71-005056827e52 odpověď dostanu: 
```json
{
  "numFound": 1,
  "items": [
    {
      "pid": "uuid:45d9d8e0-a20e-11ed-9ac7-5ef3fc9bb22f",
      "state": "A",
      "license": "dnnto",
      "territoriality": "CZ",
      "sigla": [
        "ABA001",
        "ABA004",
        "ABB002",
        "BOB007"
      ],
      "title": "X. mezinárodní sjezd slavistů : Sofija 14. - 22. 9. 1988 : bibliografie / zpracovala Eva Velinská",
      "type": "BK",
      "catalog_identifier": "oai:aleph-nkp.cz:SKC01-003137078",
      "sdnnt_identifier": "b0880d9312d58f445865b5069af09ff1",
      "granularity": [
        {
          "states": [
            "A"
          ],
          "license": "dnnto",
          "territoriality": "CZ",
          "pid": "uuid:e1877a30-3cbb-11e3-ad71-005056827e52",
          "number": "1994"
        },
        {
          "states": [
            "A"
          ],
          "license": "dnnto",
          "territoriality": "CZ",
          "pid": "uuid:6ec32690-1702-11ed-a9ae-5ef3fc9bb22f",
          "number": "1993"
        }
      ],
      "skc": {
        "controlfield_001": "cpk20152663976",
        "controlfield_003": "CZ PrSKC",
        "controlfield_005": "20230315105841.0",
        "controlfield_008": "150209m19931994xr            ||| | cze  "
      }
    }
  ]
}
```

**Comment by pavel-stastny** [comment]
@smallcubes To je uz ale strasne daleko od puvodni issue. Doporucil bych to resit separatne

**Comment by smallcubes** [comment]
k problému založit nové issue
