### ISSUE TITLE
API - doplnění kontroly

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#461]
Dobrý den,

@pavel-stastny na základě dnešní e-mailové komunikace zakládám toto issue. 
Je potřeba v prostředí API doplnit kontrolu oproti formátu a místa vydání.

@smallcubes @CIZKOVAL @Lichtenbergova
DC

**Comment by CIZKOVAL** [comment]
@pavel-stastny Pan Zahořík opakovaně doporučuje používat OAI set SKC-DNNT, kde jsou pouze záznamy **knih a seriálů vydaných na území ČR**.
Pokud se bude používat tento set, pak není třeba doplňovat výše popisovanou kontrolu.

**Comment by smallcubes** [comment]
Kontrola na (feb00f3, sdnnt-test)

**země vydání Německo: [oai:aleph-nkp.cz:SKC01-009584309 ](https://aleph.nkp.cz/F/94P727IPX6RPA9KSC127BUJF6L6BPRU3M2QFG7LB3GA5T81J8K-57208?func=full-set-set&set_number=126914&set_entry=000008&format=999)**
- request
```bash
curl -X 'PUT' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/request/batch/nzn' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: token' \
  -H 'Content-Type: application/json' \
  -d '{
  "batch": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:SKC01-009584309"
      ],
      "pozadavek": "Německo",
      "poznamka": "Německo"
    }
  ]
}'
```
- response
```json
{
  "saved": [],
  "notsaved": [
    {
      "identifiers": [
        "oai:aleph-nkp.cz:SKC01-009584309"
      ],
      "pozadavek": "Německo",
      "poznamka": "Německo",
      "reason": "Failed validation / document state or place of publication or format. Identifiers: [oai:aleph-nkp.cz:SKC01-009584309]"
    }
  ]
}
```

**Comment by smallcubes** [comment]
poprosil bych o kontrolu @CIZKOVAL, @Cypzirschova, nebo @Lichtenbergova (staré tisky, MX, ER atd.)

@pavel-stastny

**Comment by Cypzirschova** [comment]
Problém by se měl nejspíše vyřešit, pokud by se vyřešilo issue #482.

**Comment by Cypzirschova** [comment]
Otestováno v 1.0.7.7 - OK
