### ISSUE TITLE
Zobrazit jako samostatný seznam nezařazená díla na SDNNT

### ISSUE THREAD

**Issue by annie-cz** [NLCR/SeznamDNNT#464]
Chybí mi mezi seznamy samostatný seznam toho, co ještě není na SDNNT nahlášeno. Aktuální možnosti nahlášení, kde jsem nucená se probírat hromadami výsledků vyhledávání, které mám namíchané s již nahlášenými díly, mi připadá dost nešťastné.

**Comment by smallcubes** [comment]
v současné době lze díla mimo seznam prohlížet následovně:

1. v katalogu zaškrtnout políčko: "Zobrazit i dokumenty, které nejsou zařazeny na seznamu"
![obrazek](https://user-images.githubusercontent.com/78028909/184903552-84b829b1-ada4-4875-beeb-b56802f4e72b.png)
2. vybrat si pouze díla, která mají stav N (Vyřazeno)

**Comment by annie-cz** [comment]
No ... ano. Já vím. Proto sem píšu, že mi toto nepřijde vůbec šťastné, protože se mi pak tímto způsobem míchají výsledky vyhledávání s již nahlášenými díly a je to nepřehledné. Kdyby tam to tlačítko bylo ve verzi "zobrazit POUZE dokumenty, které nejsou zařazeny na seznamu", pak by to bylo ok.

Tak či tak pro lepší představu si myslím, že by bylo lepší to dát jako jasně viditelný a vizuálně odlišený seznam, stejně jako to mají další seznamy. Viz:

![image](https://user-images.githubusercontent.com/43028501/185068736-d9cc837c-4ffa-4993-8b6b-b423ab0528d5.png)

**Comment by CIZKOVAL** [comment]
@annie-cz souhlasím s Vámi, upozorňovala jsem na to už v issue a komentáři níže, také mě to mátlo. Paní Lichtenbergová rozhodla, že se to zatím takto ponechá a upraví kdyby to nevyhovovalo.
https://github.com/NLCR/SeznamDNNT/issues/141#issuecomment-984422221

@smallcubes to co popisuješ se týká vyřazených děl se stavem N (ty jsou ale na seznamu v SDNNT). Annie šlo o díla, která na seznamu nejsou a nikdy nebyla, ty se filtrovat nedají a také mi to vadí.

**Comment by Cypzirschova** [comment]
Bylo by možné skrýt filtr pro vyhledávání v různých seznamech (mimo/SDNNT) pro Exporty a Importy? V těchto dvou případech se tento filtr nepoužívá. @pavel-stastny @smallcubes 
![Bez názvu](https://github.com/NLCR/SeznamDNNT/assets/86351100/7e48566d-9ecb-4198-9191-70f21f267baf)
![Bez názvu1](https://github.com/NLCR/SeznamDNNT/assets/86351100/5ffb9f5a-d524-49ea-b246-0d5464bddf8c)

**Comment by Cypzirschova** [comment]
Vydáno a nasazeno ve verzi 1.0.9.6
@smallcubes prosím uzavřít issue.
