### ISSUE TITLE
Vytvoření seznamů

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#47]
Dobrý den,

pokud aktuálně pracuju na seznamu na zařazení/vyřazení a přidávám jednotlivé tituly, tak nevyskočí žádná informace, že titul byl přidán na seznam, který aktuálně vytvářím. Nebylo by možné tam takovou "vyskakovací" informaci přidat? Dneska jsem zkoušela nějaký seznam na zařazení vytvořit a nic se mi tam nepřidalo. Předpokládám, že je to tím, že je přihlášeno více uživatelů na profilu Knihovna.

Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Vyzkoušejte, prosím, na nynější verzi (Build: 4a5186e )

**Comment by Cypzirschova** [comment]
Super, moc děkuju za úpravu.
Cypzirschová
