### ISSUE TITLE
Chybějící odkaz do Krameria u kořenového uuid

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#470]
Při vyhledání UUID [a91cf900-0ee5-11eb-aeed-5ef3fc9bb22f](https://sdnnt.nkp.cz/sdnnt/search?q=uuid:a91cf900-0ee5-11eb-aeed-5ef3fc9bb22f&page=0) se zobrazí správně dílo: "Genetika a šlechtění", ale chybí zde odkaz do Krameria (https://kramerius5.nkp.cz/periodical/uuid:7dca6730-1ce4-11eb-9210-5ef3fc9ae867 ) - což je zvláštní, když to zná jeho UUID...

![Snímek obrazovky z 2022-08-23 17-02-43](https://user-images.githubusercontent.com/33415849/186193533-5ce272b3-4ef0-4de4-93b0-4022a6457960.png)

**Comment by CIZKOVAL** [comment]
To bude nejspíš tím, že vlivem opravy "chyby" #444 nám odkaz do Krameria zmizel. Nyní to v SDNNT funguje tak, že pokud není přítomno MARC pole 911, tak se MARC 856 ignoruje, což je špatně a další diskuze je ve zmiňovaném issue.

v SKC je toto:

**85641** | \|u http://krameriusndk.nkp.cz/search/handle/uuid:a91cf900-0ee5-11eb-aeed-5ef3fc9bb22f \|y Digitalizovaný dokument
**8564** | \|u http://www.cazv.cz \|4 N

**911 - není přítomno**

**Comment by smallcubes** [comment]
@Cypzirschova děkuji za kontrolu, uzavírám
