### ISSUE TITLE
Hromadné schvalování žádostí

### ISSUE THREAD

**Issue by Lichtenbergova** [NLCR/SeznamDNNT#472]
Při hromadném schvalování  záznamů ze stavu NZN (trvalo cca 2 min.)  do NPA byla schválena jen část  záznamů (Schváleno NPA). U zbytku záznamů se objevil stav NPA, chybí Schváleno, nabízí se možnost editace, ale není možné změnit stav (Chyba při Schválení návrhu. Není možné změnit stav). Pokud se skryjí zpracované záznamy, objevuje se např. v rozmezí 601-700 záznamů jeden nezpracovaný, 801-900 je 0, 1001-1100 jeden, 1901-2000 patnáct…). 
Informace v přehledu uvádí chybný počet záznamů, v přehledu žádosti je počet nalezených záznamů 2526, v přehledu pro kurátora 2619 (48), odmítnuty byly ve skutečnosti 4 záznamy.

**Comment by Cypzirschova** [comment]
Také se mi ted stalo a týkalo se to 15 záznamů v 1 žádosti. Hromadné schválení zafungovalo až po třetím pokusu a ještě se to neschválilo u všech děl. @smallcubes @CIZKOVAL @pavel-stastny

**Comment by Cypzirschova** [comment]
![image](https://user-images.githubusercontent.com/86351100/186673803-114c29b8-c51e-4fa0-bdc8-98237dec9233.png)

**Comment by Cypzirschova** [comment]
Výše jsou popsány dva různé problém. Toto issue se bude zabývat problémem **schvalování děl uvnitř žádosti a přidělování stavu NPA**. Druhý problém s celkovým označením celé žádosti jako zpracovanou se řeší v issue #473. 

U popsané žádosti NZN bca7dd59-447b-4918-86c1-f9d8fb086be4 se hromadně označila díla jako schválená https://github.com/NLCR/SeznamDNNT/issues/472#issue-1350786532.
Ve výše uvedené žádosti bylo chování aplikace následující:

- U první skupiny děl se díla správně označila Schváleno a stavem NPA - **OK**, 
- u druhé skupiny děl se díla označila pouze stavem NPA (bez schváleno), ale tato díla se tváří jako nezpracovaná - tzn. jako by je kurátor neschválil, do historie se zapsal stav NPA. Tato díla lze jen odmítnou, protože už mají stav NPA - **NOK**

 **Správné chování aplikace: všechna díla dostanou stav NPA a vidíme i stav schváleno. U všech děl se rozhodlo a žádné dílo se nedá dál zpracovávat.** 

![NZN - NPA - schvalování](https://user-images.githubusercontent.com/86351100/187147876-9d9a90c9-4385-43e6-9fe7-bdbc4daad89f.png)
![NZN - NPA - schvalování1](https://user-images.githubusercontent.com/86351100/187147883-1c4f0094-b371-4d42-b447-97f5dbe81491.png)

**Comment by Cypzirschova** [comment]
Bylo vyřešeno novou verzí, která už je nasazená - OK.

**Comment by CIZKOVAL** [comment]
@Lichtenbergova je možno uzavřít?

**Comment by Lichtenbergova** [comment]
Ano, jak komentuje výše DC, bylo vyřešeno novou verzí.
