### ISSUE TITLE
NZN žádosti - při změně licence se díla nedostanou do cílového stavu

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#475]
Dobrý den,
1. byla vytvořena NZN zadost č. _e557fe1d-2084-452e-aec0-a928206f4db8_ - obsahuje díla, která nebyla na seznamu (nemají stav a licenci)
2. kurátor ji schválil -- díla dostala kurátorský stav NPA (bez licence)
3. běží lhůta 0 
4. doběhne lhůta 0 - díla dostanou stav PA, licence DNNTO (na toto je issue #200, že se automaticky **všem dílům** přidá licence **DNNTO** bez ohledu na rok vydání)
5. běží lhůta 1 (na produkci 6 měsíců, na testu 2 hodiny)
6. kurátor **změní** u vybraných děl **licenci na DNNTT** (oai:aleph-nkp.cz:SKC01-002564375, oai:aleph-nkp.cz:SKC01-002564396)
7. v žádosti se změna projeví změnou licence
8. doběhne lhůta 1 - všechna díla z žádosti se mají překlopit do stavu A s relevantními licencemi

**Díla, u kterých došlo v kroku 6 ke změně licence na DNNTT se nepřeklopí v kroku 8 do stavu A, ale zůstávají PA.**

_To může za půl roku na produkci způsobit velké problémy, nyní paní Cypzirschová měnila licenci prozatím cca u 4000 záznamů z nových návrhů._

![PA_zmena_licence](https://user-images.githubusercontent.com/92719629/188173422-98c362f6-1956-4d9c-a79c-8aa041590a1c.png)

![NEPŘEKLOPILY_SE](https://user-images.githubusercontent.com/92719629/188173452-7a1e5a2a-c12d-4210-86c4-f693577b0d67.png)

![historie_knihovna](https://user-images.githubusercontent.com/92719629/188174254-a8f774f6-c089-408a-94da-1b5c219ce4a0.png)

![historie_kurator_PA](https://user-images.githubusercontent.com/92719629/188174228-71310b3a-6191-49bb-b16d-94fb257b9c29.png)
)

**Comment by Cypzirschova** [comment]
Retest ve verzi 1.0.7.4:
OK
V žádosti NZN se díla překlopila do správného konečného stavu A. 
Před překlopením do stavu A, jsem změnila licence u dvou děl na terminál (DNNTT). Po uplynutí lhůty 1 se díla správně převedla do stavu A i s licencí na terminál (DNNTT).
![image](https://user-images.githubusercontent.com/86351100/224637509-ee59beaf-82fd-4b81-b08e-92b9282ff510.png)

**Comment by Cypzirschova** [comment]
Ještě doplnění: 
č. žádosti: 85fb741a-c811-4b8e-bbaf-598a910c207f
a ještě screen historie, kde je vše jasně viditelné:
![image](https://user-images.githubusercontent.com/86351100/224653205-baed2ee3-f9d0-478f-89cc-e35d98498d35.png)

**Comment by Cypzirschova** [comment]
Cizokrajní ptáci chovaní v klecích. Díl 2. / Napsal a novými českými názvy ptáků opatřil Jaroslav Karásek a F. Markowski
oai:aleph-nkp.cz:SKC01-002245887

Daňové přiznání / sestavil Martin Juráček
oai:aleph-nkp.cz:SKC01-002245954
