### ISSUE TITLE
Rok vydání - seriály nebo vícesvazkové monografie

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#477]
Dobrý den,
Jak funguje prosím faseta roku vydání u seriálů? Mám např. seriál oai:aleph-nkp.cz:SKC01-002938420, který byl vydávaný mezi léty 1922-1930.

Pokud si ho najdu v SDNNT, tak **faseta obsahuje údaje 1915-2008**, kterou když aplikuji, tak to žádný záznam nenajde. 

Když dám rok vydání 1922 nebo 1930 tak také ne. Když zadám rozmezí 1922-1930, tak také ne. Co mám tedy zadat, aby byl tento seriál nalezen?

![serial](https://user-images.githubusercontent.com/92719629/188202285-55b37035-584d-4ca7-8c5c-d7b15811055e.png)

![rozmezi_SKC](https://user-images.githubusercontent.com/92719629/188202312-506a7aa5-2072-4270-a387-3b8215005620.png)

![rozmezi](https://user-images.githubusercontent.com/92719629/188202327-a9499c4c-57cd-43ac-874d-dbcc738a5a26.png)

**Comment by Cypzirschova** [comment]
Primární problém je, že si filtr pro rok vydání bere data z pole 260/264. Rozhodně by bylo lepší kdyby se to bralo z pole 008. Seriály obecně ten filtr hledá hrozně blbě.

**Comment by Cypzirschova** [comment]
Dnes jsme s @smallcubes řešili jedno dílo, které nešlo dohledat v SDNNT i když mělo kurátorský stav NPA. Zřejmě to souvisí s rokem vyd.

Dílo [oai:aleph-nkp.cz:SKC01-001000731](https://aleph.nkp.cz/F/?func=direct&doc_number=001000731&local_base=SKC) formát BK, země vydání xr v poli 008, rozmezí let 20019999 v poli 008

Dílo nešlo dohledat podle žádného identifikátoru ani podle filtru stavu NPA. Jirka zkusil změnit druhé datum vyd. (9999) v metadatech na datum 2002. Po této změně šlo dílo dohledat podle identifikátoru. 

Dílo jsme zkusili vyřadit (stav N) a znovu zařadit přes žádost NZN, aby dílo dostalo cílový stav PA. Jakmile dílo dostalo požadovaný stav PA, tak Jirka změnil druhé datum vydání zpátky na 9999. I po této změně šlo dílo stále najít podle identifikátoru. 

Závěr je takový, že díla s rozmezím dat v poli 008 a obsahující druhé datum vyd. 9999 nelze nalézt v aplikaci, pokud nemají veřejný stav (PA,A,N,NL).

Prosím o případné doplnění @smallcubes.

**Comment by CIZKOVAL** [comment]
V SDNNT nelze dohledat dílo dle roku vydání v těchto případech:
pokud je v poli MARC 260 (respektive MARC 008): 

**1. rozmezí let**
cnb002616077 Supplent : román / Karel Klostermann

008 	140901m**19131914**xr------------|||-|-cze--
260	|a V Praze : |b Jos. R. Vilímek, |c [**1913-1914**] |f (Unie)

**2. zástupné znaky**
oai:aleph-nkp.cz:SKC01-001622660 Supplent : román. IV / Karel Klostermann

008	990118s**19uu**----xr-----e------000-f-cze-d
260	|a V Praze : |b Jos. R. Vilímek, |c [**19--**]

oai:aleph-nkp.cz:SKC01-004717228 Supplent : román. II. / Karel Klostermann

008	110223s1913----xr-----e------000-f-cze-d
260	|a V Praze : |b Jos. R. Vilímek, |c [**1913?**]

**Comment by CIZKOVAL** [comment]
Ještě jsem narazila na problém u této monografie:
**3. chybí pole MARC 260 a údaje se berou z pole MARC 264**

cnb000132382 Lady Hamiltonová : historický a životopisný román / Alexandre Dumas ; přeložil Josef Špičák

264 1 | \|a Praha : \|b Melantrich, \|c [1970]
264 4 | \|c ©1970

**Comment by Cypzirschova** [comment]
Je nutné, aby se data pro FILTR Rok vydání brala z pole 008 nikoliv z pole 260 nebo 264.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @Cypzirschova  Faseta změněna na pole 008 spodní hranice.  Pro zahrnutí horní hranice je potřeba udělat změny na o kterých jsme se bavili na schůzce.

**Comment by Cypzirschova** [comment]
> Dobrý den, Jak funguje prosím faseta roku vydání u seriálů? Mám např. seriál oai:aleph-nkp.cz:SKC01-002938420, který byl vydávaný mezi léty 1922-1930.
> 
> Pokud si ho najdu v SDNNT, tak **faseta obsahuje údaje 1915-2008**, kterou když aplikuji, tak to žádný záznam nenajde.
> 
> Když dám rok vydání 1922 nebo 1930 tak také ne. Když zadám rozmezí 1922-1930, tak také ne. Co mám tedy zadat, aby byl tento seriál nalezen?
> 
> ![serial](https://user-images.githubusercontent.com/92719629/188202285-55b37035-584d-4ca7-8c5c-d7b15811055e.png)
> 
> ![rozmezi_SKC](https://user-images.githubusercontent.com/92719629/188202312-506a7aa5-2072-4270-a387-3b8215005620.png)
> 
> ![rozmezi](https://user-images.githubusercontent.com/92719629/188202327-a9499c4c-57cd-43ac-874d-dbcc738a5a26.png)

1. Pokud zadám rozmezí let 1922-1930, omezím filtr na SE, stav A - dílo je nalezeno.
2. Pokud zadám rozmezí let 1922-1922, omezím filtr na SE, stav A - dílo je nalezeno.
3. Pokud zadám rozmezí let 1930-1930, omezím filtr na SE, stav A - **dílo je nenalezeno**.
4. Pokud zadám rozmezí let 1925-1929, omezím filtr na SE, stav A - **dílo je nenalezeno.**

**Comment by pavel-stastny** [comment]
@CIZKOVAL O tom jsme se bavili na poslední schůzce, nevím, zda jste tam byla.  Momentálně není zohledněna horní mez vydání ale pouze spodní.  Tedy začátek vydání díla musí spadat do zadaného intervalu. Vyhledává se nyní dle pole 008.

**Comment by CIZKOVAL** [comment]
RETEST - všechna díla z tohoto issue se při zadání různých hodnot dohledají správně = OK.

Zůstávají ale méně závažné chyby:

1. když zadám rozmezí filtru ROK OD - ROK DO a kliknu na "Použít", tak se hodnoty ve filtru změní 
2. lze zadat hodnotu ROK DO < ROK OD a pak se nic nedohledá, přestože hodnota OD je v pořádku. Takhle by to nemělo jít vůbec zadat, měla by tam být nějaká hláška, že ROK DO je nižší. Uživatel se může nevědomky ukliknout a nic mu to nenajde.

<img width="949" alt="rok_vydání" src="https://github.com/NLCR/SeznamDNNT/assets/92719629/0341fedb-d3f7-41f5-b5b2-44cc86c2e5f9">

**Comment by CIZKOVAL** [comment]
Retest ve verzi 1.1.0.3 je OK. 

Rok vydáni ve filtru zůstává a nelze zadat nižší rok DO.

Vše ostatní také OK.
