### ISSUE TITLE
API nevrací UUID požadovaného díla

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#478]
Při dotazu API na UUID [uuid:b77f55a0-1e62-11e2-bec6-005056827e51](https://sdnnt.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3Ab77f55a0-1e62-11e2-bec6-005056827e51) chybí ve výpisu požadované UUID.

**Comment by jahhoo** [comment]
Podobný problém je u díla: [uuid:b8cd0990-1256-11e4-8f64-005056827e52](https://kramerius5.nkp.cz/uuid/uuid:b8cd0990-1256-11e4-8f64-005056827e52), kde se bere jako primární UUID z Medviku

**Comment by jahhoo** [comment]
Je potřeba, aby API vždy odpovídalo primárně jen UUID jedné knihovny. 
Není možné, aby při dotazu UUID z NK vrátilo UUID jiných knihoven a nepotvrdilo informaci, že se jedná o stejné dílo.

**Comment by CIZKOVAL** [comment]
Pravděpodobně souvisí s issue #444, kde došlo **chybně** k úpravě, že se ignoruje pole 856 v SKC. Zkontrolovat po vyřešení 444.

**Comment by CIZKOVAL** [comment]
Přikládám komentář od @jahhoo z 21.12. 2022
Opraveno zvláštním způsobem - např. u díla: https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3Ab77f55a0-1e62-11e2-bec6-005056827e51
vrátí původní špatný výpis + záznam vypíše znovu správně jako další položku. V tom pak může být dost chaos.

**Comment by smallcubes** [comment]
Zkoušel jsem dotaz na uuid monografie, ale nic mi to nevráti. Vyzkoušeno: s "uuid:" i bez.

- vyzkoušeno na: `uuid:79b5b2e0-0427-11ed-8460-005056827e52`, `nkp`

```bash
curl -X 'GET' \
  'https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3A79b5b2e0-0427-11ed-8460-005056827e52?digital_library=nkp' \
  -H 'accept: application/json'
```

odpověď:
```json
{
  "numFound": 0,
  "items": []
}
```

**Comment by pavel-stastny** [comment]
@smallcubes Zalezi zda je u daneho titulu naindexovana knihovna: 

Zkousim na testu: 

- `uuid:79b5b2e0-0427-11ed-8460-005056827e52` `nkp`

https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3A79b5b2e0-0427-11ed-8460-005056827e52?digital_library=mzk

- `uuid:79b5b2e0-0427-11ed-8460-005056827e52` `mzk`

https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3A79b5b2e0-0427-11ed-8460-005056827e52?digital_library=mzk

`oai:aleph-nkp.cz:SKC01-000994834`

- [https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/oai%3Aaleph-nkp.cz%3ASKC01-000994834?digital_library=mzk](https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/oai%3Aaleph-nkp.cz%3ASKC01-000994834?digital_library=mzk)

**Comment by smallcubes** [comment]
retest: 5c70ced

Zadám-li [uuid:b77f55a0-1e62-11e2-bec6-005056827e51, digital_library=nkp](https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3Ab77f55a0-1e62-11e2-bec6-005056827e51?digital_library=nkp), tak mi to vrátí i uuid, které patří jiné digitální knihovně. Konkrétně [uuid:597addcc-816a-4672-b4bc-c79454db691c](https://kramerius.svkhk.cz/periodical/uuid:597addcc-816a-4672-b4bc-c79454db691c) patří SVHK.

**Comment by smallcubes** [comment]
retest: ca3998e

přijde mi to beze změny

**Comment by smallcubes** [comment]
retest: 2d5a7d8

dotaz na [uuid:b77f55a0-1e62-11e2-bec6-005056827e51, digital_library=nkp](https://sdnnt-test.nkp.cz/sdnnt/api/v1.0/lists/info/uuid%3Ab77f55a0-1e62-11e2-bec6-005056827e51?digital_library=nkp) už vypisuje pouze NKP
