### ISSUE TITLE
Odkazy do digitální knihoven: odkazy v 856 i 911 svázat se správným Krameriem

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#484]
**NESCHVÁLENO**
---

Dobrý den,

požádali bychom Vás o následující změnu při práci s odkazy do digitálních knihoven. 

**Požadovaná změna:**
Odkazy do digitálních knihoven se berou ze všech polí 856 a 911. Následně budou z polí vybrány pouze odkazy do ZAPOJENÝCH digitálních knihoven (nikoliv pouze partnerských). Nevyskytují se zde duplicitní odkazy a nerelevantní odkazy např. na jiné weby nežli na digitální knihovny. Navrhované řešení: filtrovat odkazy přes [registr Krameriu](https://registr.digitalniknihovna.cz/). Zobrazeny jsou správně i odkazy v granularitě tj. na jednotlivé ročníky a svazky. 

- [ ] 1. Odkazy do DK se berou ze všech MARC polí 856 i 911 filtrované přes registr Krameriů
- [ ] 2. Je možné konfigurovat seznam zapojených knihoven, které se v odkazech zobrazí

1. [X] **K PŘIPOMÍNKOVÁNÍ** od 30/9/2022
2. [ ] **K SCHVÁLENÍ NK ČR**
3. [ ] **K SCHVÁLENÍ DODAVATEL**

**Comment by CIZKOVAL** [comment]
Otázka:
1. odkazy do digitálních knihoven mají být zobrazeny pro všechny knihovny?
2. granularita pouze pro partnerské knihovny?

**Comment by CIZKOVAL** [comment]
Odkazy v polích 856 filtrovat přes seznam uvedeny v registru Krameriů. Odkazy v SKC se v některých případech liší, aktuálně jsou v SKC odkazy:

kramerius.nkp.cz/kramerius - ABA001
kramerius5.nkp.cz - ABA001
krameriusndk.nkp.cz - ABA001

krameriusndk.mzk.cz - BOA001
[www.digitalniknihovna.cz/mzk - BOA001](http://www.digitalniknihovna.cz/mzk%20-%20BOA001)

kramerius.vse.cz - ABA006
kramerius.lib.cas.cz - ABA007
kramerius.medvik.cz - ABA008
kramerius.uzei.cz - ABA009
kramerius.techlib.cz/kramerius-web-client - ABA013
kramerius.nfa.cz/kramerius - ABC135
kramerius.lf1.cuni.cz - ABD006
kramerius.vsup.cz - ABD024
[www.digitalniknihovna.cz/vsup](http://www.digitalniknihovna.cz/vsup) - ABD024
kramerius.army.cz - ABE045
kramerius.divadlo.cz/kramerius - ABE304
kramerius.upm.cz - ABE310
kramerius4.jewishmuseum.cz - ABE323
digitalniknihovna.mlp.cz - ABG001
digi.law.muni.cz - BOD010
kramerius.cbvk.cz - CBA001
kramerius.kkvysociny.cz - HBG001
kramerius.svkhk.cz - HKA001
kramerius.svkkl.cz - KLG001
k4.kr-karlovarsky.cz - KVG001
kramerius.kvkli.cz - LIA001
kramerius.kr-olomoucky.cz - OLA001
kramerius.svkos.cz - OSA001
kramerius.knihovna-pardubice.cz - PAG001
k4.svkpl.cz - PNA001
[www.digitalniknihovna.cz/svkpk](http://www.digitalniknihovna.cz/svkpk) - PNA001
kramerius.svkul.cz - ULG001
kramerius.kfbz.cz - ZLG001

a

kramerius.cuni.cz - UK Praha

**Comment by CIZKOVAL** [comment]
Toto je již vyřešeno.
