### ISSUE TITLE
Granularita: vícesvazky, které dříve byly zdigitalizované samostatně

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#487]
**NESCHVÁLENO**

---

**Obecná pravidla pro granularitu:**
procedura na granularitu VŽDY prochazí VŠECHNY seriály a vícesvazkové monografie s odkazem do digitalní knihovny (pouze partnerske DK) a VŽDY PŘEPISUJE původní granularitu. Zdrojem dat jsou odkazy v SKC v MARC polích **856 i 911** - měl by zde být algoritmus, kdy se ke každému odkazu doptá na související "potomky" (**"monographunit"** resp. "periodicalvolume") a každému svazku přiřadí vlastní stav a licenci dle těchto [pravidel](https://github.com/NLCR/SeznamDNNT/issues/487#issuecomment-1270729936). 

_Poznámka: nově je také požadováno, aby se u seriálů šlo až na úroveň **"periodicalIem"**, viz issue #491 ._

**Granularita se musí VŽDY dostat na odpovídající úroveň a to i v případě, kdy je dokument zdigitalizovaný v několika částech** – některé svazky samostatně, některé svazky pod titulovým UUID, případně je titul rozdělen pod několik titulových UUID.

POZOR, můžou se vyskytnout např. tyto případy:
* vícesvazková BK nebo SE, který má titulové UUID (rodič) a podřazené UUID (děti) navázané na titulové UUID 
* vícesvazková BK nebo SE, u kterého byla zdigitalizovaná část(i) jako samostatná monografie 
* vícesvazková BK nebo SE, u kterého byla zdigitalizovaná část(i) jako samostatná monografie a další části jako vícesvazková monografie

- [X] **K PŘIPOMÍNKOVÁNÍ** od 3/10/2022
- [ ] **K SCHVÁLENÍ NK ČR**
- [ ] **K SCHVÁLENÍ DODAVATEL**

**Comment by CIZKOVAL** [comment]
[granularita_pravidla.docx](https://github.com/NLCR/SeznamDNNT/files/9728832/granularita_pravidla.docx)

**Comment by CIZKOVAL** [comment]
Procházení všech záznamů a přepisování granularity je nutné z důvodu, že může dojít ke změně metadat v DK (např. rok vydání) nebo změna statustu public x private.

**Comment by pavel-stastny** [comment]
@CIZKOVAL @smallcubes Musi existovat jednoznacne rozliseni, kdy je uuid "chapano" jako soucasti granularity a kdy se jedna o korenove uuid.

**Comment by CIZKOVAL** [comment]
Všechny typy nekonzistencí byly otestovány a ve finální verzi je to OK.

[SKC_nekonzistence_oficial.docx](https://github.com/NLCR/SeznamDNNT/files/11686477/SKC_nekonzistence_oficial.docx)
