### ISSUE TITLE
Licence - průběžná kontrola

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#488]
**NESCHVÁLENO**
---

- [ ] 1. v případě, že se změní rok vydání u některého díla, tak by se měla ověřit odpovídající licence. Pokud **změna roku má za následek jinou licenci, pak by mělo dojít k automatické opravě na relevantní licenci.** K ověřování roku vydání by mělo docházet na pravidelné bázi.
- [ ] 2. možnost **konfigurace pro klouzavé roky** - pevný je pouze rok 2007. (monografie)
- [ ] 3. provést **výjimku u žádostí VNZ**, které podal nakladatel (nositel práv), viz komentář níže.

_Poznámka 1 - podle jakého pole se vyhodnocuje licence? MARC 260 nebo MARC 008? Pokud podle MARC 008 a je tam rozmezí let, pak by se měla brát v úvahu dolní hranice?_

_Poznámka 2 - mělo by se totéž týkat i jednotlivých ročníků, dílů v granularitě?_

Nyní (pro rok 2022) jsou licence vázány na tyto roky:

**DNNTO:**
BK - **do r. 2001** včetně
SE - **do r. 2001** včetně

**DNNTT:**
BK - **od r. 2002** včetně **do r. 2007** včetně
SE - **od r. 2002** včetně -  **do r. 2011** včetně

**N:**
BK - **od r. 2008** včetně
SE - **od r. 2012** včetně

- [X] **K PŘIPOMÍNKOVÁNÍ** od 3/10/2022
- [ ] **K SCHVÁLENÍ NK ČR**
- [ ] **K SCHVÁLENÍ DODAVATEL**

**Comment by Cypzirschova** [comment]
Vyřešením tohoto issue se zároveň vyřeší starší issue #200.

Poznámka 1: Mělo by se brát z pole 008, dolní hranice.
Poznámka 2: Ano, je potřeba ještě myslet na granularitu - příklad:

Dílo Tři mušketýři - záznam je ve formátu **BK** - vícesvazková monografie (3 díly). 1. díl vyjde v r. 2001, 2. a 3. díl v roce 2005 

- Celek bude **DNNTO**, protože v poli 008 bude rozpětí let **2001**-2005. 
- V granularitě se budou řešit jednotlivé díly - 1. díl (**2001**) = **DNNTO**, 2.-.3. díl (**2005**) = **DNNTT**

**Comment by Cypzirschova** [comment]
Doplnění:
Je nutné, aby se neprocházela díla, kterým byla změněná licence na základě požadavku nositelé práv. Pokud v aplikaci k takové situaci dojde, tak se změna propisuje i s číslem žádosti, kterou nositel práv vytvořil, viz níže.
![změna historie](https://user-images.githubusercontent.com/86351100/194319282-93c37e82-ae1a-4210-bcfa-2f88741527d5.png)

**Comment by Cypzirschova** [comment]
K roku 2023 dochází ke změně:
**DNNTO:**
BK - do r. **2002** včetně
SE - do r. **2002** včetně

**DNNTT:**
BK - od r. **2003** včetně do r. 2007 včetně
SE - od r. **2003** včetně - do r. **2012** včetně

**N:**
BK - od r. 2008 včetně
SE - od r. **2013** včetně

Připomínám, že toto platí pouze u **všech** monografií (BK) a nepravých periodik - vycházejících **méně** než 2x ročně.

**Comment by Cypzirschova** [comment]
Ještě jsem chtěla upozornit na fakt, že předchozí požadavky od nakladatelů (omezení na terminál) nejsou nijak rozeznávány v aplikaci, protože aplikace nepřevzala poznámky z báze DNT.

**Comment by CIZKOVAL** [comment]
Pro nadcházející rok 2024 je potřeba upravit proceduru na přidělování licencí a to jak na úrovni CELKU, tak na úrovni GRANULARITY.
 
**Je potřeba proceduru upravit tak, aby byla konfigurovatelná kurátory NK!**

Změna pravidel pro r. 2024 viz přílohy.
[granularita_pravidla_r_2024_v2.docx](https://github.com/NLCR/SeznamDNNT/files/12917278/granularita_pravidla_r_2024_v2.docx)

[GRAN_pravidla_r.2024_v2.xlsx](https://github.com/NLCR/SeznamDNNT/files/12917258/GRAN_pravidla_r.2024_v2.xlsx)

**Comment by Cypzirschova** [comment]
Ještě doplním, že je potřeba, aby to bylo **konfigurovatelné** ze strany administrátora.

**Comment by smallcubes** [comment]
konfigurace je z releasu přenesena na wiki + doplněna o informace z e-malu: [wiki](https://github.com/NLCR/SeznamDNNT/wiki/Soupis-konfigura%C4%8Dn%C3%ADch-parametr%C5%AF)

**Comment by Cypzirschova** [comment]
Hromadný posun licencí je nasazen na produkci. Každoroční posun licencí si musí pohlídat kurátoři aplikace.
Prosím uzavřít issue.
