### ISSUE TITLE
Licence a stavy

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#49]
Je nutne obohatit index o licence na základě stavu. 
Přičemž platí:
 
- `A` = `dnnto`
- `A`,`NZ` = `dnntt`

Licence se vytváří až při překlopení do finálního stavu, tedy 

-  `PA  => A`  = Přiřadí licenci `dntto` 
-  `A  => A NZ` (Po omezení dostupnosti díla)  = odebere licenci `dntto`  a přidá licenci dnntt `dntto` 

Každá odebraná licence se bude zapisovat do historie záznamu, aby šlo vytvořit exporty odebraných licencí.

Licence se bude odovozovat při sklízení z OAI

Pokud se bude sklízet nový záznam, historie licencí bude prázdná

**Comment by JanMeritus** [comment]
@pavel-stastny 
 
1. ano,
2. Ano najprv musi mit stav, pak ma aj licenci - zde bud dnnto nebo dnntt
3. Ano je nutno evidovat historii licenci na zaznamu dila
4. a 5. Do prepnuti ano. Po prepnuti licence administruje SDNNT.
