### ISSUE TITLE
API - úprava hromadného návrhu

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#494]
**NESCHVÁLENO**
---
Aktuálně je hromadný návrh tvořen jako seznam systémových čísel SKC, která ovšem nemají knihovny běžně k dispozici a musí seznam vytvářet pracně ručně mimo SDNNT.

Hromadný návrh na zařazení https://sdnnt.nkp.cz/sdnnt/api/v1.0/request/batch/nzn musí být možné vytvořit na základě lokálních údajů – **sigla + ID záznamu** (pole 001), tj. např.. ABA001-nkc20071748063 (v SKC jde o údaje uvedené v poli 910 $ax)

- [X] **K PŘIPOMÍNKOVÁNÍ** od 3/10/2022
- [ ] **K SCHVÁLENÍ NK ČR**
- [ ] **K SCHVÁLENÍ DODAVATEL**

**Comment by smallcubes** [comment]
6.3.2023 - zatím neřešeno

**Comment by pavel-stastny** [comment]
@smallcubes Nyní záznam se dohledá dle uvedených kriterií (pole 910ax)  a v žádosti figuruje už jako standardní skc identifikátor. V případě odmítnutí problematických  záznamů je ve výsledku vidět pole 910. (tak jak bylo požadováno zde #495)

**Comment by smallcubes** [comment]
vyzkoušeno:

odpověď (NZN):
```json
{
  "batch": [
    {
      "identifiers": [
        "OLA001-vkol000672927",
        "oai:aleph-nkp.cz:SKC01-002246178"
      ],
      "pozadavek": "494",
      "poznamka": "494"
    } ]
}
```

odpověď (VN):
```json
{
  "batch": [
    {
      "identifiers": [
        "ABB036-000426175"

      ],
      "pozadavek": "494",
      "poznamka": "494"
    }]
}
```
