### ISSUE TITLE
Faseta Digitální knihovny - bug

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#499]
Dobrý den,

**faseta Digitální knihovny** nepracuje správně. V níže uvedené situaci neobsahuje všechna díla, která jsou zdigitalizovaná. 

1. Nastavím si filtry následovně - Licence: terminál, rok vydání: 2002 a filtr potvrdím
2. Faseta Digitální knihovna vidím pro Národní knihovna České republiky 74 děl - po prokliku zjistím, že jsou všechna  díla ve stavu **PA** s licencí DNNTT, rok vydání 2002.
3. Mezi zdigitalizovanými díly pro NK úplně chybí např. dílo Zprávy z nadsmyslového světa / Ernst Meckelburg **80-86218-83-X**. Dílo je ve stavu **A** s licencí DNNTT (v SKC jsou odkazy v poli [911](https://aleph.nkp.cz/F/?func=direct&doc_number=001012427&local_base=SKC)). 

_Poznámka: pokud dílo vyhledám samostatně dle ISBN, tj. bez předchozích filtrů, tak se ve fasete Digitální knihovna pro NK vyskytuje - jde ale o dílo ve stavu **D**. **Následník ve stavu A DNNTT se ve fasetě neprojeví**._

![DK - chyba1](https://user-images.githubusercontent.com/86351100/211764621-298c151b-d77c-4218-80b8-9b5f1833a160.png)
![DK - chyba3](https://user-images.githubusercontent.com/86351100/211765559-06983c56-5dfe-4f46-9969-044e396f391c.png)

![DK - chyba4](https://user-images.githubusercontent.com/86351100/211765935-8615248a-2b8c-4664-9d3d-be40b4251ff0.png)

**Comment by CIZKOVAL** [comment]
V jiných případech se následník ve fasetě projeví (např. cnb000024193) - dílo je ve stavu D a následník ve stavu A online. Faseta pro digitální knihovnu je provázána jak s původním záznamem z DNT01 (NK), tak následníkem (NK, MZK).

Podle jakého klíče je faseta pro digitální knihovnu naindexovaná? Dílo  80-86218-83-X (cnb001196292) i cnb000024193 mají v SKC vyplněná pole 911, která obsahují UUID pro NK i MZK. Následnický záznam pro dílo  80-86218-83-X (cnb001196292) **není** ve fasetě pro DK zahrnut, následník pro dílo cnb000024193 ve fasetě zahrnutý je.

**Comment by pavel-stastny** [comment]
@CIZKOVAL Myslim, že se jednalo o nekonzistenci v datech. Vyzkoušejte nyní.

**Comment by Cypzirschova** [comment]
V nasazené verzi 1.0.9.9 se tento problém již nevyskytuje.
