### ISSUE TITLE
Vyhledávání: diakritika

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#50]
Dobrý den,

zadám-li do vyhledávání dotaz (bez uvozovek): _Lidove noviny_, tak to nenajde žádné záznamy. Je-li zadáno (bez uvozovek): _Lidové noviny_ s diakritikou, tak to již díla najde. Nejedná se o chybu? Tedy nemělo by vyhledávání automaticky brát v potaz i záznamy s diakritikoku? 

Předem děkuji za reakci @albertoh @pavel-stastny

**Comment by pavel-stastny** [comment]
@smallcubes  Provedeme změnu ve schématu indexu a reindexaci. Pak už by se to najít mělo.

**Comment by pavel-stastny** [comment]
@smallcubes Můžete vyzkoušet?

**Comment by smallcubes** [comment]
@pavel-stastny vypadá to v pořádádku, děkuji za opravu
