### ISSUE TITLE
Stejná notifikace chodí 2 dny za sebou

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#507]
Dobrý den,
stejná notifikace chodí 2 dny za sebou, přestože nedošlo ke změně stavu ani licence.

[23.5.docx](https://github.com/NLCR/SeznamDNNT/files/11552984/23.5.docx)

[24.5.docx](https://github.com/NLCR/SeznamDNNT/files/11552985/24.5.docx)

**Comment by CIZKOVAL** [comment]
Následující den (25.5. 2023) přišla notifikace znovu, kde už byla pouze 2 díla z původních notifikací, přesto, že u nich nedošlo k žádné aktualizaci.

[25.5.docx](https://github.com/NLCR/SeznamDNNT/files/11562288/25.5.docx)

**Comment by CIZKOVAL** [comment]
Projevilo se pouze na produkci.

**Comment by smallcubes** [comment]
chyba v nastavení: 
```json
"notifikace_den": {
	"type": "notifications",
	"interval": "den",
	"cron": "0 0 0 * * ?"
}
```

nastaveno na: 0 0 3 * * ?
