### ISSUE TITLE
Notifikace - změna licence nepřijde

### ISSUE THREAD

**Issue by CIZKOVAL** [NLCR/SeznamDNNT#508]
Dobrý den,
mám nastavenou hromadnou notifikaci "zdigitalizované polské seriály" následovně:
formát dokumentu: SE
jazyk: PL
digitální knihovna: ABA001
stav: A

1. záznam oai:aleph-nkp.cz:SKC01-003462141 jsem dala do žádosti VNZ - po schválení kurátorem došlo ke změně z 
A **dnnto** --> A **dnntt**
2. záznam oai:aleph-nkp.cz:SKC01-004310928 jsem ručně změnila z A **dnntt** --> A **dnnto**
V obou případech se změnila licence, ale notifikace nedorazila.

_Poznámka: oba záznamy mají při vyhledání přes id nebo přes hromadnou notifikaci **neaktivní zvonečky** (to znamená, že už jsou součástí hromadné notifikace). Dílo 1, které je v žádosti VNZ má ale zvonek **aktivní, když se dívám přes žádost**, viz obrázky._

![hr_not](https://github.com/NLCR/SeznamDNNT/assets/92719629/c7a0384e-3dad-4196-bd06-107d9baa1cb7)

![akt_zv](https://github.com/NLCR/SeznamDNNT/assets/92719629/11a5dc5c-57b9-443f-ad1d-37b7c340b8b5)

Dnes ještě zkusím stejný případ aplikovat u jednoltivé notifikace a zítra to sem dopíšu.

**Comment by Cypzirschova** [comment]
Otestováno v 1.0.9.7 - TEST:
Nasimulován podobný scénář:

**Jednotlivé notifikace:**

- oai:aleph-nkp.cz:SKC01-004225272: ruční změna z A dnntt --> A dnnto - **OK - notifikace přišla**

- oai:aleph-nkp.cz:SKC01-000086462: pomocí žádosti VNZ - po schválení kurátorem došlo ke změně z A dnnto --> A dnntt - **OK - notifikace přišla**

**Hromadné notifikace:**

- oai:aleph-nkp.cz:SKC01-003462141: ruční změna z A dnntt --> A dnnto - **OK - notifikace přišla**

- oai:aleph-nkp.cz:SKC01-004310928: pomocí žádosti VNZ - po schválení kurátorem došlo ke změně z A dnnto --> A dnntt - **NOK - notifikace nepřišla**

- oai:aleph-nkp.cz:SKC01-002814923: pomocí žádosti VNZ - po schválení kurátorem došlo ke změně z A dnnto --> A dnntt - **NOK - notifikace nepřišla**

**Bug je jen u hromadných notifikací, když se u díla změní licence pomocí žádosti VNZ.**

**Comment by Cypzirschova** [comment]
Retest - verze 1.1.0.0 - prostředí TEST:

Otestovány hromadné notifikace - změna pomocí VNZ žádosti -- **OK, notifikace přišla.**
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/e055fd31-f9eb-44d4-9430-a57720a44bbd)

![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/c7203e11-1c6e-4f77-b491-93689e397fcb)
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/df669d6f-12e5-4f17-8573-4f7614f6d520)

**Prosím uzavřít.**
