### ISSUE TITLE
Změna textu - NZN žádosti

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#509]
Dobrý den,
potřebovali bychom změnit text, které se týkají NZN žádostí. Prosím aby bylo vše konfigurovatelné, tento požadavek byl už v přechozím issue #456. 

- Ve sloupci lhůta by nově měl být text 1.1. nebo 1.7.
- U kurátorského stavu NPA by měly být také termíny 1.1. nebo 1.7., viz níže.

![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/d1973a5b-4361-4739-ab9f-46db0b910a91)
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/99210b9f-64c7-4680-967d-c72a11e8fbe6)
DC
@Lichtenbergova

**Comment by smallcubes** [comment]
Popisek jsem změnil.
Soubory: cs.json / en.json

**Comment by Cypzirschova** [comment]
Díky, uzavírám
