### ISSUE TITLE
Díla mimo seznam - nelze najít některá díla

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#510]
Dobrý den,

v aplikaci se nezobrazují všechna díla mimo seznam. V aplikaci nelze najít např. tato díla:

cnb001194565 
cnb001931814
cnb001194565

Díla splňují podmínky pro zařazení do SDNNT, ale nelze je v aplikaci najít a tudíž ani navrhnout.

DC
@Lichtenbergova @CIZKOVAL @smallcubes @pavel-stastny

**Comment by CIZKOVAL** [comment]
MARC pole 008 vypadá takto:
cnb001194565 
021125m2002**9999**xr-abc-e-e----000-0-cze—

cnb001931814
090611q2001**2009**xr-ach-g-f----000-0-cze—

cnb001194565
021125m2002**9999**xr-abc-e-e----000-0-cze--

Nemůže to být tím, že se ve filtru pro díla mimo seznam počítá se horní hranicí MARC 008?

**Comment by smallcubes** [comment]
pro úplnost, dojde ke změně viz e-mail

> Pro monografie: 
>
>1. Vypočítá se rozpětí: 1911 až aktuální rok - 15, tedy  1911 - 2008
>2. Filtr bere: 
>   2a. Monografie, které mají spodní hranici v rozmezí a nemají definovou horní hranici (tedy mohou zde být zástupné znaky ----/uuuu/9999 apod)  NEBO 
>   2b. Monografie, které mají definované obě hranice a spodní musí spadat do vypočítaného rozmezí 
>
>Pro seriály: 
>
>1. Vypočítá se rozpětí: 1911 až aktuální rok - 10, tedy  1911 - 2013
>2. Filtr bere: 
>   2a. Všechna periodika, které mají spodní hranici v rozmezí a nemají definovou horní (tedy mohou zde být zástupné znaky ----/uuuu/9999 apod)  NEBO 
>   2b.  Všechna periodika, které mají definované obě hranice a spodní musí spadat do vypočítaného rozmezí

**Comment by Cypzirschova** [comment]
Narazila jsem na záznam, kdy je v poli 008 uveden rok 19uu-9999 [SKC](https://aleph.nkp.cz/F/?func=direct&doc_number=002814883&local_base=SKC). Jak umí pracovat filtr se znaky **u** **-**? U těchto záznamů nedokážeme určit rok přesného vydání.

**Comment by pavel-stastny** [comment]
@Cypzirschova Filtr pracuje jenom s přesnými roky, záznam nebude dohledán.

**Comment by Cypzirschova** [comment]
Jde to v aplikaci nějak zohlednit? Takové záznamy máme v SDNNT ještě z předchozí báze DNT a třeba pro tento záznam by nebyl důvod, proč ho nezařadit do SDNNT.

**Comment by pavel-stastny** [comment]
Jde to zohlednit pouze tak, že se povolí pouze konkrétní podoby takto definovaných datumů. (19uu, 199u, 198u, 197u, atd..)

**Comment by Cypzirschova** [comment]
V dodané verzi 1.0.8.4 - OK
