### ISSUE TITLE
DXN - u záznamů zmizely stavy, licence a EUIPO ID

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#514]
Dobrý den,

u několika žádostí DXN (vždy odůvodnění SKC_4a) po zpracování zmizel stav a EUIPO ID. Záznamy nelze vůbec dohledat ani pomocí OAI. Zpětně si nevzpomínám, jak jsem tyto žádosti zpracovávala, ale ta poslední žádost ze srpna je určitě zpracována ručně.

ID žádostí: 

- 65d9d83b-4b80-4024-8307-50c4f3dd5184
- de37586d-ddec-45a1-bdc8-59c7044b039c
- 38c497d6-8753-4cad-842f-1fd01a911d93
- fee393b8-4833-4ae1-842e-f62342ab62cd

![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/33c8c068-764f-4083-9df0-6cf3957d75d1)

DC
@pavel-stastny @smallcubes @Lichtenbergova

**Comment by Cypzirschova** [comment]
Chyba se promítá do dalších DXN žádostí (SKC_4a) na produkci.

**Comment by pavel-stastny** [comment]
Opraveno až ve verzi [https://github.com/NLCR/SeznamDNNT/releases/tag/1.0.8.5](1.0.8.5).  Na produkci je starší.

**Comment by Cypzirschova** [comment]
Retest verze 1.0.8.7 - prostředí test:

Stále chybí EUIPO ID a dílo nelze dohledat podle žádného ID, nemá stav D a nelze ho najít ani mimo seznam.
Např. žádost DXN: be6f94b8-03c1-468b-a3ca-077ccf2609f8:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/4be2857c-8715-49e7-bb31-17544a9aae16)

**Comment by Cypzirschova** [comment]
Dobrý den,

u jedné žádosti se po spuštění procedury DXN ztratí stav D, label EUIPO i ID. Otestováno v prostředí DEV.

ID žádosti: fee393b8-4833-4ae1-842e-f62342ab62cd
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/d4b0a053-8c0e-477b-b009-12363e11b7ee)
DC

**Comment by Cypzirschova** [comment]
@pavel-stastny Jak je řešeno ve verzi 1.0.8.9?

**Comment by pavel-stastny** [comment]
@Cypzirschova Opet update ze souboru, ktere jsem poslal a pak update z SKC.

**Comment by pavel-stastny** [comment]
@smallcubes Ja to v tom 4.xml vidim.  (soubor updates.zip mail odchazel 9.11)

**Comment by Cypzirschova** [comment]
Retest - verze 1.0.8.9 (prostředí DEV):

OK, dílům byl přiřazen stav D, label EUIPO i EUIPO ID. Díla lze dohledat pomocí identifikátorů v SDNNT.
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/de5d2b1e-bc52-4fcf-b6f3-c7f5a7565c8f)
