### ISSUE TITLE
Exporty - název 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#517]
Dobrý den,

v exportech chybí celý název jednotlivých exportů, jak byl v zadání. 
Navrhovala bych, aby se celý název zobrazoval po najetí kurzorem myši na zkratku exportu.

- Importní soubor do EUIPO OoC (zkratka IOCP)

- Seznam změn pro EUIPO OoC (zkratka UOCP)
![Bez názvu](https://github.com/NLCR/SeznamDNNT/assets/86351100/e2fdc920-4d6b-4741-a43c-6fd01ef9866c)
DC

**Comment by pkudela** [comment]
hotovo, tooltip implementovan a dosazena lokalizace

**Comment by Cypzirschova** [comment]
Ve verzi 1.0.8.6 - OK
