### ISSUE TITLE
DXN - ruční změna stavu 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#518]
Dobrý den,

při testování (prostředí test) verze 1.0.8.5 jsme zkoušeli nasimulovat situaci, kdy v DXN žádosti budeme mít smazaný záznam ve stavu PA a následnický záznam A. Takový případ jsme nenašli, a proto jsme u jednoho smazaného záznamu ručně změnili stav z A na PA (oai:aleph-nkp.cz:SKC01-001055853). 

Smazaný záznam je v žádosti DXN **1acdd123-7ea6-4734-814e-352f4ed759c0**. Smazaný záznam nelze v DXN schválit, jak ručně tak i hromadně. Vždy to vyhodí chybu. 

<img width="858" alt="EUIPO - bug" src="https://github.com/NLCR/SeznamDNNT/assets/86351100/20767746-4564-4218-93ac-dee85317f261">

**Zároveň s ruční změnou stavu zmizel kurátorský stav DX a proklik na následnický záznam.**

![EUIPO - bug1](https://github.com/NLCR/SeznamDNNT/assets/86351100/5ec97736-87c2-49e7-acb9-cc9d5a373e20)

Tato situace by mohla být problematická např. při scénáři SKC_4b, kdy smazaný záznam čeká na následnický záznam a z nějakého důvodu, by se musel ručně změnit stav smazaného záznamu. 

Záměr změny stavu na PA bylo testování přesunu EUIPO ID.

DC

**Comment by pavel-stastny** [comment]
@Cypzirschova Musí mít kurátorský stav DX aby mohl přejít do stavu D. 

Ruční změnou z UI toho docílit nelze, jedině si "natvrdo" v solru připravit data.   Veřejný stav PA, kurátorský stav DX a nastaveného následníka.

**Comment by Cypzirschova** [comment]
@pavel-stastny Takže pokud změním jakýkoliv stav u záznamu, který čeká v DXN třeba na toho následníka (SKC_4b), tak se automaticky ztratí DX a už se následník nedohledá?

**Comment by pavel-stastny** [comment]
> Takže pokud změním jakýkoliv stav u záznamu, který čeká v DXN třeba na toho následníka (SKC_4b), tak se automaticky ztratí DX a už se následník nedohledá?

Ano, ruční změna vždycky přepisuje veřejný i kurátorský stav a má vliv na všechny wofkflow.  Změna z PA na N, znamená, že se záznam nepřepne do stavu A, změna z PX u žádosti PXN na cokoliv co není PX znamená, že v žádosti nejde schválít do stavu X atd..

**Comment by Cypzirschova** [comment]
@pavel-stastny Děkuji za vysvětlení. V běžném provozu se s tím nesetkáváme. Uzavírám.
