### ISSUE TITLE
Label EUIPO 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#519]
Dobrý den,

label EUIPO se odebírá všem záznamům, pokud jsou v seznamu změn. Správně by se měl label odebírat až ve chvíli, kdy kurátor hromadně označí celý soubor změn, tzn. celý soubor je zpracovaný a v EUIPO OoC kurátor všechny záznamy smazal.

"Label OoC (Out-Of-Commerce Works Porta) je přidělen záznamům, pokud byl hromadně schválen soubor záznamů vygenerovaných procesem Importní soubor do EUIPO OoC. **Label je odebrán v případě, že byl hromadně schválen soubor záznamu vygenerovaných procesem Seznam změn pro EUIPO OoC.** Pomocí labelu OoC lze filtrovat záznamy ve vyhledávání."

DC

**Comment by pavel-stastny** [comment]
> Správně by se měl label odebírat až ve chvíli, kdy kurátor hromadně označí celý soubor změn, tzn. celý soubor je zpracovaný a v EUIPO OoC kurátor všechny záznamy smazal.

Toho nepůjde úplně dobře docílit, pokud těch záznamů v exportu bude hodně.   Jde docílít toho, že místo jednoho vyřazovacího procesu budou dva.  Jeden bude měnit platné euipo identifikátory na neplatné a zařazovat do exportů, druhý bude hromadně odebírat faset ze všech děl které jsou ve schválených exportech.  Ale to mi přislo poněkud přes ruku. 

PŠ

**Comment by smallcubes** [comment]
@pavel-stastny nevím, zdali Vám rozumím správně. Napíšu, jak to bylo zamýšleno. 

ID EUIPO (v zadání ID OCP) není to stejné jako label OoC. 

ID EUIPO se přiděluje, jak je uvedeno v mapování, to je správně. A lze podle něj vyhledávat. Samostatná faseta může zůstat. 
Label OoC je ale samostatná faseta a přiděluje se dle pravidel uvedených výše.

**Comment by pavel-stastny** [comment]
@smallcubes Máme na mysli tohle 
![image](https://github.com/NLCR/SeznamDNNT/assets/675753/98573950-3007-4b4b-800d-69b845f77909)

u každého dokumentu v exportu?   Pokud ano, pak to lze z UI odebírat ale pouze v případě, že bude v exportu **vždy** nějaký rozumný počet položek (řádově maximálně pár tisíc).  Pokud budeme mít expoty, které jsou neomezené(jako je to teď), pak by se to muselo dělat přes proces. (V rámci requestu z browseru se to nestihne.)  Nic víc v tom není.

**Comment by smallcubes** [comment]
Já nevím, jakým způsobem to máte řešené. Pokud by bylo potřeba vytvořit nový proces pro přidělovaní/oddělování labelu, tak bych poprosil o jeho vytvoření.

**Comment by Cypzirschova** [comment]
Retest 1.0.8.7: OK

Label se odebírá dílům které jsou: 

1. jednotlivě zpracované v UOCP
2. hromadně zpracované v UOCP
