### ISSUE TITLE
Certifikát

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#52]
Dobrý den,

pokud chci navštívit stránku aplikace, vyskočí na mě okno ohledně certifikátu (viz níže). Pokud pokračuju můžu jen stránku používat jen dočasně max. 30 min.

Navštěvování domény s nedůvěryhodným certifikátem
Vaše připojení není zabezpečené. Zločinci se mohou pokusit zachytit vaše soukromá data. Doporučujeme přestat s webovou stránkou pracovat.

10.5.1.80

Důvod:

Certifikát podepsaný svým držitelem

Zobrazit certifikát

Uvědomuji si riziko, ale chci pokračovat.

Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Taková byla domluva s @JanMeritus.  Před překlopením na test dát na standardní službu `https` a použít "selfsigned" certifikát.  (Certifikát podepsaný certifikační autoritou se musí řešit uvnitř NK )

**Comment by Cypzirschova** [comment]
Myslela jsem si to, ale raději jsem se zeptala.
Cypzirschová

**Comment by JanMeritus** [comment]
@smallcubes prosim o poslani zadosti na infra - jmeno sdnntdev.nkp.cz a sdnntest.nkp.cz

**Comment by smallcubes** [comment]
@JanMeritus ještě jsem poslal upřesňující dotaz na e-mail

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o donasazeni certifikatu, NK ho pripravila k prevzeti

**Comment by pavel-stastny** [comment]
@JanMeritus viz email

**Comment by pavel-stastny** [comment]
@JanMeritus dev ma jiz certifikat.  Pri pristupu pouzivat jmeno ne adresu.   U testu nevim jakou ma adresu.

**Comment by pavel-stastny** [comment]
@JanMeritus Dal jsem certifikat na test.  Port 443 je pro me zavreny.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o potvrzeni ze port je nadale zavreny

**Comment by pavel-stastny** [comment]
@JanMeritus Je. Ping taky neprochazi.

**Comment by JanMeritus** [comment]
@smallcubes prosim o vyrizeni s infra

**Comment by smallcubes** [comment]
@pavel-stastny přetrvává stále problém?

**Comment by pavel-stastny** [comment]
@smallcubes ano

**Comment by smallcubes** [comment]
@pavel-stastny kolega problém odstranil, mohl byste to prosím vyzkoušet?

**Comment by pavel-stastny** [comment]
@smallcubes ssh <test_addr>  mi nefunguje a GET https://<interni_adresa>  taky ne.   Pokud se prihlasim na dev a pak z devu na test, tak to jde.

**Comment by smallcubes** [comment]
@pavel-stastny dle e-mailu už vše funguje, uzavírám
