### ISSUE TITLE
OAI - pole 956

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#524]
Přidat do pole 956 všechny liky do krameria.

**Comment by smallcubes** [comment]
SDNNT-A sklizeno záznamů s granularitou granularitou: 7 641 
SDNNT-TEST (SOLR):  fq=dntstav:A&q=granularity:[*TO*] 7 641 

děkuji za přidaní

**Comment by smallcubes** [comment]
wiki: https://github.com/NLCR/SeznamDNNT/wiki/OAI%E2%80%90PMH-SDNNT

**Comment by smallcubes** [comment]
Popis pole na [wiki](https://github.com/NLCR/SeznamDNNT/wiki/OAI%E2%80%90PMH-SDNNT)
