### ISSUE TITLE
NPA v NZN žádostech

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#528]
Dobrý den,

v NZN žádostech se přiřazuje NPA už při zpracování. Kurátorský stav NPA se má přiřadit až ve chvíli, kdy kurátor označí celou žádost za zpracovanou.

![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/a0f07f83-bd36-4a4c-a608-17d8a85ab4c2)

DC
@Lichtenbergova

**Comment by pavel-stastny** [comment]
@Cypzirschova Tomu nerozumím.  Do NPA stavu přejde při schvalování (buď jednotlivě nebo hromadně) a je tomu tak od začátku.

**Comment by Cypzirschova** [comment]
Omlouvám se, došlo k chybě, uzavírám.
