### ISSUE TITLE
EUIPO ID + label EUIPO

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#529]
Dobrý den,

přidělování EUIPO ID i label EUIPO je zřejmě omezen hranicí pro monografie. Tomu tak mělo být pouze při prvotním přiřazení v SDNNT, takto je to zmíněné i v zadání. Chtěla jsem poprosit, zda by bylo možné tuto hranici měnit? Kdyby šlo třeba upravovat ten rok jako máme pro vyhledávání mimo seznam? Pro další roky se bude vždy hranice posouvat kvůli novele AZ, kde musí platit pro monografie hranice 20 let od vydání.

Bylo by možné, prosím toto v SDNNT změnit?
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/418f655b-0bc4-4ac7-948a-049468d9137a)

DC
@Lichtenbergova

**Comment by pavel-stastny** [comment]
Mělo by fungovat nastavení: 

```javascript
"euipo_iocp": {
       "type": "euipo_iocp",
       "cron": "cronpattern",
       "iteration":{
           "maxbkyear":2023,  // maximalni rok pokud se ho podarilo naparsovat - jedna se o cislo 
           "nonparsabledates":[ "1.*", "200.*"] // regularni vyrazy pokud datum neni definovany cislem
       }
}
```

**Comment by smallcubes** [comment]
@pavel-stastny 
děkujeme, vyzkoušíme to
přidám to do poznámky k realesu a wiki

**Comment by Cypzirschova** [comment]
@pavel-stastny Moc Vám děkujeme za pomoc.
