### ISSUE TITLE
Kurátor - seznamy

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#53]
Dobrý den,
v profilu kurátora jsou stále seznamy, které jsou zpracované, ale nejdou označit jako zpracované (např. viz seznam ze dne 13.07.2021 10:47 - VVS). Vyskočí chyba, že není vše zpracované, ale všechny tituly jsou zpracované.
Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Můžete vyzkoušet nyní? (V žádosti byla díla, která nejsou v katalogu. Patrně stav, který vznikl při reindexaci)

**Comment by Cypzirschova** [comment]
Děkuju, už to funguje.
