### ISSUE TITLE
DX a PX v DXN žádosti

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#531]
Dobrý den,

narazila jsem na problematickou situaci, kdy je dílo v DXN žádosti a mělo by mít kurátorský stav DX, ale později dílo dostalo kurátorský stav PX. Podle historie to vypadá, že kurátorský stav PX přemazal kurátorský stav DX. Při zpracování DXN žádosti jsem zpočátku předpokládala, že je problém v PX. Tento stav jsem ručně upravila, aby dílo mělo jen stav A, online. Žádost DXN stále nešla zpracovat, protože chyběl kurátorský stav DX. Na tento problém jsem narazila jak na produkci, tak i na testu.

Bylo by dobré, kdyby se např. kurátorské stavy nepřemazávaly nebo kdyby šlo zpracovat žádosti i s kurátorským stavem PX. 
Kurátorský stav PX má sloužit jen jako informace navíc. Nejvhodnější způsob by mi přišlo, kdyby se dala jakákoliv žádost zpracovat i přes kurátorský stav PX. 

Níže příklad z testovacího prostředí: 
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/fe9802c7-3ff2-4fc6-9b0c-b75e65fcd3a0)

Historie díla:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/a92f22e9-0584-4522-97d7-21fdc4583125)

DXN žádost ff93cff8-a262-4eed-be2f-1a64218319ca: 
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/d11fd9cb-95d1-4c47-916f-d844255c5c33)

Smazaný kurátorský stav PX - ruční úprava:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/e615970c-2df3-4e0b-a789-b3af65cecac3)

Žádost po odstranění PX:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/f0b62032-fc2f-47ab-9507-1d4a2aa9573e)

Zároveň tento problém souvisí s issue #416.

@Lichtenbergova
@smallcubes 
@CIZKOVAL 
DC

**Comment by Cypzirschova** [comment]
Našla jsem další problematickou situaci související s PX stavem v DXN žádosti. 

V DXN žádosti čeká smazaný záznam na následnický záznam, ale v průběhu čekání dostal záznam stav PX a tím smazal stav DX. Nyní je v SKC následnický záznam, ale smazaný záznam se s tímto záznamem nespojil a zřejmě už asi nespojí (předpokládám kvůli chybějícímu stavu DX). Tato situace je velmi problematická a je potřeba ji vyřešit, aby k podobné situaci nechodázelo.

[Smazaný záznam:](https://aleph.nkp.cz/F/?func=direct&doc_number=009069721&local_base=SKC)
[Následnický záznam:](https://aleph.nkp.cz/F/?func=direct&doc_number=009997979&local_base=SKC)

**Žádost DXN:**
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/679bbbc7-ed69-43bd-9136-369e313ad53d)

**ID smazaného záznamu:**
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/f49beb8b-1bcf-41a6-87be-18e349ca2687)

**Nenalezen následnický záznam:**
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/322ab311-ccbf-4ab6-b337-bdff95b67dff)

**Vyhledaný záznam podle čČNB v SKC:**
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/ff8e3249-1ade-4ee2-9b36-7d3bbacd168e)

DC

**Comment by Cypzirschova** [comment]
Ještě posílám historii smazaného záznamu:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/b6b98412-49c8-48b4-a0b0-6b7bd33b0484)

**Comment by pavel-stastny** [comment]
@Cypzirschova Nyní (poslední DEV verze) jsou při kontrole volných děl vynechávvány záznamy se stavem DX.  K problému by již nemělo docházet.

**Comment by Cypzirschova** [comment]
Jak je to řešeno v procesu, kde se přiřazuje kurátorský stav PX na základě roku vydání (viz poslední screen scheduler/yearscheck)? Přemaže se stav DX, pokud se dílu přiřadí PX?

**Comment by pavel-stastny** [comment]
Záznamy s kurlátorským stavem DX se nekontrolují/vynechají. Kontrola proběhne až na následníkovi. (Po schválení).

**Comment by Cypzirschova** [comment]
Otestováno v prostředí DEV - OK:
Díla s kurátorským stavem DX se vynechávají.
