### ISSUE TITLE
Exporty - UOCP - SKC_4b

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#532]
Dobrý den,

v exportech je drobná chyba. Do UOCP se dostala díla, která měla v historii SKC_4b a po určitém časem se k těmto dílům našel následnický záznam (např. SKC_1). Takové záznamy v EUIPO zůstávají, protože v současné době se záznamy podle nových následnických záznamů neupravují. V UOCP by měla být jen díla, která nemají následnický záznam. Oprava bude stačit až po Vánocích.

Např.:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/2eef0e66-2a0c-485d-99d1-954486d66373)
@smallcubes @Lichtenbergova @pavel-stastny 
DC

**Comment by Cypzirschova** [comment]
Ještě přidávám příklad, kdy by dílo mělo být v UOCP - SKC_4b 
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/b2a3e5d0-7cd3-4d36-b889-e98dd555506c)

**Comment by Cypzirschova** [comment]
Retest verze 1.0.9.4, prostředí DEV:

Chyba se stále vyskytuje:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/1a03c95b-b143-40cf-b045-926148dfecb5)

**Comment by smallcubes** [comment]
otestováno na [verzi 1.0.9.5](https://github.com/NLCR/SeznamDNNT/labels/Verze%201.0.9.5), děkujeme za opravu
