### ISSUE TITLE
Granularita - NPA 

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#536]
Granularita se stahuje i pro díla, která mají pouze kurátorský NPA stav.  Nelze pak přiřadit stav a licenci jednotlivým ročníkům

**Comment by pavel-stastny** [comment]
řešeno komitem e9f0152040e0650648d5ea1691534c2e3479577b

**Comment by Cypzirschova** [comment]
Testováno ve verzi 1.0.9.4 na testu:
Granularita se stahuje pouze pro díla s veřejným stavem. Pro díla s kurátorským stavem NPA se granularita nestahuje. - **OK** 
@smallcubes
