### ISSUE TITLE
Notifikace, když se (ne)mění stav/licence

### ISSUE THREAD

**Issue by luckajirku** [NLCR/SeznamDNNT#539]
Je možné nějak nastavit u notifikací, aby chodily pouze v případě, že dojde ke změně stavu/licence? Teď mi chodí, když proběhne jakákoli akce, i když ta jen potvrdí tu licenci/stav, kterou už tam máme. Ta možnost tam není, nebo jsem ji jen přehlédla?
![licence_notifikace](https://github.com/NLCR/SeznamDNNT/assets/6359479/565197be-b540-4047-ad90-4ea2ece7a302)

**Comment by pavel-stastny** [comment]
@luckajirku Nyní tam tato možnost není. Změníme fukncionalitu tak, aby při těchto akcích (SKC_1 až .. SKC_4) notifikace nechodily.
(souvisí s #435 a #433)

**Comment by pavel-stastny** [comment]
@luckajirku V nové verzi by notifikace při kurátorských akcích (SKC1 ... SKC4) chodit neměly.  V případě potřeby znovu otevřete.

**Comment by luckajirku** [comment]
Nějakou dobu to vypadalo OK, ale teď o víkendu zas přišla notifikace k dílu, kde se stav nezměnil:

_Seznam změněných dokumentů:

Název: Majalesový list studentstva královéhradeckého
Identifikator: oai:aleph-nkp.cz:SKC01-010138846
Stav: A
Licence: dnnto
Odkaz: https://sdnnt.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-010138846

S pozdravem SDNNT_

![sdnnt_matoucinotifikace](https://github.com/NLCR/SeznamDNNT/assets/6359479/7b8f6182-a145-40d0-ac01-4d785bf25c62)

**Comment by luckajirku** [comment]
> @luckajirku V nové verzi by notifikace při kurátorských akcích (SKC1 ... SKC4) chodit neměly. V případě potřeby znovu otevřete.

@pavel-stastny issue znovu otevřít nemůžu, nejsem oprávněna:-). Jinak dnes se to stalo zase.

**Comment by pavel-stastny** [comment]
@luckajirku A ten druhý případ je taky SKC_1

**Comment by luckajirku** [comment]
@pavel-stastny jj, taky SKC_1, dnes ve 3:00, tenhle: https://sdnnt.nkp.cz/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-010142290

**Comment by luckajirku** [comment]
a dnes opět, tentokrát SKC_2a

**Comment by Cypzirschova** [comment]
REtest ve verzi 1.1.0.3 - prostředí TEST: **OK**

Notifikace dorazily jen pro změnu veřejného stavu/licence. 
Pro SKC_1-4 notifikace nedorazily.

**Comment by luckajirku** [comment]
Nevím, jestli to souvisí s touhle úpravou, nebo je to něco jiného. Ale 24. 6. v 15:10 mi přišel zvláštní mail s notifikacemi, kde:

1. jsou nefunkční odkazy
2. je uveden stav A, ale v SDNNT je PA (a je to tak v pořádku, ještě neuplynulo 6 měsíců od 1. 1.)

Např.: 

Nazev: Lánov : 1355 - 2000 / [Martin Bartoš ... et al.]
Identifikator: oai:aleph-nkp.cz:SKC01-009903657
Stav: A
Odkaz: https://server/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-009903657


Nazev: Výsledky voleb do obecních zastupitelstev v obcích okresu Trutnov 18. a 19. listopadu 1994
Identifikator: oai:aleph-nkp.cz:SKC01-009900782
Stav: A
Odkaz: https://server/sdnnt/search?page=0&q=oai:aleph-nkp.cz:SKC01-009900782

**Comment by Cypzirschova** [comment]
Děkujeme za upozornění, podíváme se na to s kolegou. Úprava ještě není nasazená na produkci, protože není ještě dotestovaná celá verze. @smallcubes

**Comment by smallcubes** [comment]
@luckajirku mělo by to být už v pořádku, Vyskytne-li se chyba znova, dejte nám prosím vědět.
