### ISSUE TITLE
Importy - Distri

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#54]
Dobrý den,
v importech konkrétně v Distri nefungují odkazy na jednotlivé tituly (distri.cz). Respektive odkazy jako takové funkční jsou, ale neodkazují na konkrétní tituly. Vždy vyskočí přihlašovací okno.
Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Tady požádám @albertoh o upřesnění ale toto bude záležitostí dat.  S tím lze těžko něco udělat.

**Comment by albertoh** [comment]
To neni problem dat, ale web stranky distri.cz, ktere vyzaduji prihlaseni. Staci jednou se prihlasit, a dokud relace je platna, odkazy budou fungovat.

**Comment by Cypzirschova** [comment]
Takže se musím do stránek distri zaregistrovat a pak stačí se 1x přihlásit?

**Comment by albertoh** [comment]
Pro NKP jiz existuji prihlasovaci udaje (pro xml feedy).

**Comment by JanMeritus** [comment]
@Cypzirschova @CIZKOVAL  je zde vyreseno?

**Comment by Cypzirschova** [comment]
Budu potřebovat přihlašovací údaje pro NK, protože se mi nezobrazují knihy, ale pouze přihlašovací okno. @JanMeritus

**Comment by CIZKOVAL** [comment]
Dobrý den, přihlašovací údaje předány. Pokud funguje poprosím p. @Cypzirschova o uzavreni.

**Comment by Cypzirschova** [comment]
Děkuji, byla jste rychlejší. Uzavírám.
