### ISSUE TITLE
Přidání sigel

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#542]
Poprosili bychom o přidání sigel: 

Sigla.LMDA - Lesnický a myslivecký digitální archiv
Sigla.D - DiFMOE 
Sigla.VUGTK - Výzkumný ústav geodetický, topografický a kartografický
Sigla.DSMO - Digitální studovna Ministerstva obrany ČR

**Comment by Cypzirschova** [comment]
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/0c68e11c-3b8a-4407-a4a8-8a116fe7557c)

**Comment by smallcubes** [comment]
ještě bych poprosil o změnu popisku pro `period_vn_0_28d` v níže uvedených souborech. (Abych to nemusel pořád přepisovat)

soubory cs.json a en.json: 
https://github.com/NLCR/SeznamDNNT/blob/82e1c879d99e65fa604249521715da425f416a81/sdnnt/src/main/ui/src/assets/i18n/cs.json#L4 
https://github.com/NLCR/SeznamDNNT/blob/82e1c879d99e65fa604249521715da425f416a81/sdnnt/src/main/ui/src/assets/i18n/en.json

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za přidání popisků.

Ještě bych poprosil změnu na 15 dnů i u `debug_vn_0_28d` (zapomněl jsem ji tu napsat).

**Comment by Cypzirschova** [comment]
Verze 1.1.0.5 - TEST:

Popis lhůty upraven:
![image](https://github.com/user-attachments/assets/881531f9-8b2a-4a1b-a2ea-5b100b13e33d)
