### ISSUE TITLE
Díla mající PX: nepřijdou v PXN žádosti 

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#543]
Pokud má dílo PX nedostane se do PXN. 
Ověřeno na (sdnnt-test): oai:aleph-nkp.cz:SKC01-001085564

**Comment by Cypzirschova** [comment]
Dříve mělo dílo kurátorský stav PX a nedostalo se do PXN. 
Změněn stav jen na A, DNNTO - dílo se dostalo do PXN.
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/8b9ff75b-068e-4c7c-9cee-55b61d0ee1a2)
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/cc39d628-b8f1-4dbb-b75e-0523072fbef1)

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova pomohla změna nastavení
