### ISSUE TITLE
UI Faseta: chybí nakladatel

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#545]
Ve fasetě nakladatel se nezobrazí každý nakladatel, který tam patří. Samostatně jsou ale záznamy vyhledatelné.

Příklad filtr: 
  - licence:dnntt 
  - fmt:BK

Ve fasetě **nakladatel** poté nejsou zobrazena díla: 
- Vysoká škola ekonomická, Fakulta managementu Jindřichův Hradec - oai:aleph-nkp.cz:SKC01-000984980
- Vysoká škola ekonomická, Katedra světové ekonomiky - oai:aleph-nkp.cz:SKC01-000977152
- Vysoká škola ekonomická, Katedra veřejných financí
- Vysoká škola ekonomická, Fakulta výrobně ekonomická
- Vysoká škola ekonomická, Fakulta národohospodářská

Faseta:
![obrazek](https://github.com/NLCR/SeznamDNNT/assets/78028909/802728ea-c9a3-4206-a74a-dddf70b7cacd)

Srovnání:
![obrazek](https://github.com/NLCR/SeznamDNNT/assets/78028909/8fcd4758-70bf-4ebf-8557-df0cff16a365)

@Cypzirschova

**Comment by pavel-stastny** [comment]
@smallcubes Solr standardně vrací ve fasetech prních 100 položek. Dělá to tak hlavně z výkonostních důvodů.

**Comment by Cypzirschova** [comment]
Pokud jako kurátor potřebuju pracovat s nějakými daty, tak je potřeba, aby ta data seděla jak v UI SDNNT, tak i po vytažení dat adminem z metadat.

**Comment by pkudela** [comment]
dialog pripraveny, @pavel-stastny je to Tvoje

**Comment by Cypzirschova** [comment]
**Retest verze 1.1.0.2: NOK**

Situace je stále podobná té předchozí. Stále nejsou vidět všichni nakladatelé, viz příklad níže.

Ve fasetě nakladatel se nezobrazí každý nakladatel, který tam patří. Nakladatelé končí písmenem S a dál už nepokračují. Samostatně jsou ale záznamy vyhledatelné.

Na poslední schůzce byl navrhován návrh nového vyhledávání ve fasetě nakladatel. Tento návrh nebyl zapracován do aktuální verze. 

Příklad filtr:

licence:dnntt
fmt:BK
Ve fasetě nakladatel poté nejsou zobrazena díla:

Vysoká škola ekonomická, Fakulta managementu Jindřichův Hradec - oai:aleph-nkp.cz:SKC01-000984980
Vysoká škola ekonomická, Katedra světové ekonomiky - oai:aleph-nkp.cz:SKC01-000977152
Vysoká škola ekonomická, Katedra veřejných financí
Vysoká škola ekonomická, Fakulta výrobně ekonomická
Vysoká škola ekonomická, Fakulta národohospodářská
Faseta:
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/0c99521c-59f0-47ac-ad76-274f6e5b50d7)

**Comment by Cypzirschova** [comment]
@pavel-stastny na testu a nebyla jsem přihlášená. Teď když jsem se přihlásila jako kurátor už to vidím. Takže je to viditelné jen pro všechny přihlášené uživatele nebo je to viditelné pro konkrétní roli v app?

**Comment by pavel-stastny** [comment]
@Cypzirschova Dal jsem to jenom pro kurátory.

**Comment by Cypzirschova** [comment]
chybí diakritika 
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/1e58bb6b-1a39-4270-b80f-45771125105b)

**Comment by Cypzirschova** [comment]
@pavel-stastny Bylo by možné tuto funkci zpřístupnit všem přihlášeným uživatelům bez ohledu na roli v aplikaci?

**Comment by pavel-stastny** [comment]
@Cypzirschova Ano, změním to.

**Comment by Cypzirschova** [comment]
Prosím ještě o úpravu té diakritiky, viz výše.

**Comment by Cypzirschova** [comment]
Retest - verze 1.1.0.3:  **OK**

1) upraven popis 
2) funkce je viditelná pro všechny přihlášené uživatele (běžný uživatel, knihovna, kurátor, hlavní kurátor)

**Comment by smallcubes** [comment]
děkujeme za vyřešení
