### ISSUE TITLE
Hromadné notifikace 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#546]
Dobrý den,

nelze vytvořit hromadné notifikace. Aplikace uvádí, že není vybrán žádný filter i když vybrán je.

![Hromadné notifikace](https://github.com/NLCR/SeznamDNNT/assets/86351100/5af4d0cf-0e14-4777-855e-37888790b8a6)
DC
@pavel-stastny

**Comment by pavel-stastny** [comment]
@Cypzirschova @smallcubes Myslím, že tady se jedná o špatný tooltip.  Počet záznamů v hromadné notifikaci je řízen konfigurací, konkrétně klíčem `numberOfItemsInRulenotification` viz [konfigurační parametry](https://github.com/NLCR/SeznamDNNT/wiki/Soupis-konfigura%C4%8Dn%C3%ADch-parametr%C5%AF#klientsk%C3%A1-%C4%8D%C3%A1st).  Když tak zkuste překonfigurovat, mělo by to pomoct.

**Comment by Cypzirschova** [comment]
@pavel-stastny Děkujeme za pomoc, povedlo se.
