### ISSUE TITLE
NZN žádosti - změna zveřejnění nových návrhů

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#549]
Dobrý den,

potřebovali bychom upravit lhůtu, kdy jsou zveřejňovány nové návrhy v SDNNT, **včetně popisků.** Nyní by se nové návrhy měly zveřejňovat vždy k **1. dni následujícího měsíce**. Lhůta překlopení ze stavu PA na A - zůstává stejná. 

Např.:
15.6. - schválení nové NZN žádosti - kurátorský stav NPA
1.7. - zveřejnění nových návrhů (stav PA)

29.8. . schválení nové NZN žádosti - kurátorský stav NPA
1.9. - zveřejnění nových návrhů (stav PA)

Děkujeme 
D. Cypzirschová

**Comment by smallcubes** [comment]
*lhůta `period_nzn_1_12_18` v konfiguračním souboru už není potřeba

**Comment by Cypzirschova** [comment]
Verze 1.1.0.5 - TEST:
**OK** - všechny popisky jsou upraveny

Přehled žádostí:
![image](https://github.com/user-attachments/assets/b758347e-44fd-418c-98f4-1d5169fb890e)

Kurátorský stav NPA:
![image](https://github.com/user-attachments/assets/77ae5a6d-bd04-4b57-aabb-d3de4ce549ca)
