### ISSUE TITLE
Několik dalších poznatků 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#55]
Dobrý den,
píšu několik dalších poznatků, něco z toho posílala paní Lichtenbergová v připomínkách:

1. Formáty dokumentů: Stále v aplikaci vidím MU, MV atd. Mělo by být pouze BK a SE.
2. Rok vydání: V rozmezí let jsou roky např. 2016 a tituly mají status zařazeno. Kontrolovala jsem to v prozatímní databázi SDNNT a nic z toho uvedeného není zařazeno v seznamu. Roky musí omezeny do roku vydání 2007. 
3. Stav dokumentu: field.X - Chtěla jsem se zeptat, co je to za stav dokumentu? Zda je myšleno X jako možné volné dílo?
4.  Schvalování návrhů na zařazení (Kurátor): Vyskakuje "chyba při schváleném návrhu" + stále tituly, které schválíme mají status A a mělo by být PA.

Jestli mě ještě něco napadne, tak napíšu.
Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Ad bod 4 . Uz by mel byt stav PA

**Comment by JanMeritus** [comment]
@albertoh ako probehlo (3.) ?

1. FMT - je omezeno jenom na BK a SE?
2. Je nejaky plan to resit? (FYI @smallcubes )

**Comment by albertoh** [comment]
ad 1. Zaznamy s formatem MX, MU, atd, jsou videt, protoze jsou v DNT setu v Alephu. Dohoda byla, ze to co je v soucasnem setu zobrazujeme.

ad 2. Rychlou kontrolou vidim v Alephu. Napriklad https://aleph.nkp.cz/F/?func=direct&doc_number=000518711&local_base=DNT

ad 3. jsou zaznamy ze setu DNT. Maji pole 990a s hodnotou X. Napr: https://aleph.nkp.cz/F/?func=direct&doc_number=000065499&local_base=DNT

ad 4. Melo by to byt vyresene

**Comment by Cypzirschova** [comment]
1) Ještě proberu s paní Lichtenbergovou. (Dnes tu není.)

2) Zde, dochází k problematice duplicit. Ověřovala jsem: https://aleph.nkp.cz/F/?func=direct&doc_number=006967070&local_base=SKC  (rok vyd. 2016 - samostatný záznam ISBN 978-80-7369-675-7) +  https://aleph.nkp.cz/F/?func=direct&doc_number=002663213&local_base=SKC (souborný záznam i s vydáním 2016, ISBN 978-80-7369-675-7). Takže v bázi máme 2x stejný záznam. Nicméně v souborném záznamu 2005-[?] budou zpřístupněny roky 2005-2007 a dále ne. Takhle to může v aplikaci působit, že budeme uživatelům zpřístupňovat i publikace, které jsou novější než rok vyd. 2007. (V současné době určitě nebudeme a ani nemůžeme.) Přikládám obr. z hledání v bázi DNT01 - jen pod názvem. Zde vyběhne jen ten souborný záznam. (Ještě proberu s paní Lichtenbergovou.)

![Bez názvu0](https://user-images.githubusercontent.com/86351100/130203983-4c9ce96d-0b64-411a-a472-d0f5d989ac21.png)

3) Ověřeno v bázi DNT - X (volné dílo). Příznak X dáváme dílům, které jsou nejspíše volná díla (dále se ověřuje s kolegy - kurátor kram.).

4) Vyřešeno. Doplňující dotaz: Je nějak vyřešeno v aplikaci ty lhůty, které jsem psala již  #43

**Comment by JanMeritus** [comment]
3. jde o kontextove stotozneni s Krameriem. Tam kde jsou volna dila, je priznak X - nevystupuji ako DNNT a nemuzu mit ani licenci

**Comment by Lichtenbergova** [comment]
Do SDNNT může být  zařazeno jen to, co prošlo Návrhem na zařazení do SDNNT. Vzhledem k duplicitám a chybám v Souborném katalogu nemůžou být k již schváleným záznamům připojovány další záznamy, protože pak vznikají chyby. Ilustrací tam je již hodně - záznamy připojené kvůli chybě v ISBN, chybně popsané jednotlivé svazky souboru, záznamy popsané jinak - třeba jako hudebniny. Pokud je nyní v SDNNT v Alephu například 300 000 záznamů, musí jich tam být stejně po překlopení do aplikace. 
Propojování dalších záznamů za účelem jejich zařazení do SDNNT jako schválených nelze svěřit stroji (vzhledem k povaze obsahu SK ČR), musí to prověřovat kurátor.

**Comment by JanMeritus** [comment]
@albertoh @Cypzirschova prosim o kontrolu

**Comment by Cypzirschova** [comment]
1. V aplikaci se zobrazují ještě mapy a hudebniny, ale to se může jednat o špatně zpracované záznamy. _Nejdou mi katalogy, tak dokontroluji snad během dneška._
2. Omezení let v aplikaci vidím do r. 2010, což by mělo sedět na seriály - namátkou jsem něco prošla a 2010 jsem zatím narazila jen na seriály - tak by to bylo být OK
3. X - volné - OK
4. Opraveno - při schválení už není rovnou stav A, ale PA

**Comment by Cypzirschova** [comment]
Ad. 1. - V aplikaci vidím jen knihy a seriály, ale nějak mi nesedí celkový počet se současnou bází DNT.

**Comment by pavel-stastny** [comment]
@Cypzirschova Museli jsme spustit reindex dat.  Bude to nějakou dobu trvat. (cca 2-3 hodiny)

**Comment by Cypzirschova** [comment]
Všechny požadavky z toho issue jsou vyřízené, zavírám.
