### ISSUE TITLE
API - Hromadný návrh (NZN)

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#551]
Dobrý den,

při odpovědi na hromadný návrh se ukládají odmítnuté záznamy do pole: **saved**. Podle popisu v API by se tyto záznamy měly ukládat do pole: **notsaved**.

![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/95442181-ddb7-498c-91b1-175dde27917d)
![image](https://github.com/NLCR/SeznamDNNT/assets/86351100/867bd49c-54cd-425a-8718-3423b317b982)
@CIZKOVAL @smallcubes @Lichtenbergova

DC

**Comment by Cypzirschova** [comment]
Buď se musí upravit proces nebo upravit popis v API.

**Comment by pavel-stastny** [comment]
@Cypzirschova  Souvisi s timto issue #495, kde byl požadavek neodmítat celé dávky ale jenom vypsat problematické záznamy ale přesto dávku uložit.

**Comment by Cypzirschova** [comment]
@pavel-stastny To je v pořádku, ale podle toho popisu jsem pochopila, že se do notsaved mají vypisovat záznamy, které byly zamítnuty.

**Comment by smallcubes** [comment]
@pavel-stastny myslím, že by stačilo upravit popisek - API pracuje na úrovni žádostí, ne jednotlivých záznamů

**Comment by Cypzirschova** [comment]
Verze 1.1.0.4. - TEST:
Prosím o úpravu překlepu:
..., pokud **obsahuje** alespoň jednu validní položku.
![image](https://github.com/user-attachments/assets/3b892aac-ea03-4982-856e-3225cb3007df)

Mohli bychom Vás ještě poprosit o úpravu textu v úvodu?

V posledním bodu by mělo být uvedeno:
**Dílo musí mít stav N nebo mimo seznam.**
![image](https://github.com/user-attachments/assets/80d20cea-1cfb-4259-b283-9377307f9696)

**Comment by Cypzirschova** [comment]
Není součástí vydané verze 1.1.0.5

**Comment by Cypzirschova** [comment]
Verze 1.1.0.6 - OK
Děkujeme za upravení.
