### ISSUE TITLE
Label Volné dílo v DK  a PX

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#553]
Dobrý den,

narazila jsem na dílo (cnb000203254, oai:aleph-nkp.cz:SKC01-000908227), které má přidělený label Volné dílo v DK, ale v DK je dílo pod licencí DNNT. Toto dílo má přiřazený kurátorský stav PX. Podle již řešeného issue #525 by se měl label ukazovat podle aktuální situace v DK. V tomto případě by měl label zmizet. Je možné, že je překážkou kurátorský stav PX? 

Zobrazení v SDNNT:
![image](https://github.com/user-attachments/assets/9cda8ffb-d2ed-46f3-bec5-c4ba835cc4fb)

Situace v DK:
![image](https://github.com/user-attachments/assets/46a4cad6-8fb9-492e-9b0e-d226011dd33b)  ![image](https://github.com/user-attachments/assets/049e900e-73b2-49bd-b93f-05f68dae004f)

Předem děkuji za vysvětlení a případné vyřešení tohoto problému.
DC

**Comment by Cypzirschova** [comment]
Příklad dalšího díla: 
oai:aleph-nkp.cz:SKC01-001081368, cnb000635915

**Comment by pavel-stastny** [comment]
@Cypzirschova Standardně se vynechávají stavy X,PX, D, DX.  Pokud je potřeba je zařadit, je nutno stav vyjmenovat v konfiguraci procesu.  Například:  

```json
			"kram_kontextova_informace": {
                                "type":"kramerius_px_check",
                                "logger": "krameriove_kontext_px_check",
                                "cron": "0 25 13 ? * MON,TUE,WED,THU,FRI *",
                                "iteration": {
                                        "data":"granularity",
                                        "states":["A","PA","NL", "PX"]
                                },
                                "results":{
                                        "ctx": true
                                }
                        }

```
Můžete vyzkoušet ?

**Comment by Cypzirschova** [comment]
Děkujeme za doporučení, funguje.

**Comment by Cypzirschova** [comment]
Dobrý den,

dnes jsme zjistili, že nefunguje přiřazování labelu Volné dílo v DK u děl mimo seznam, viz https://github.com/NLCR/SeznamDNNT/issues/269#issuecomment-1084390960. Testováno dnes na DEVu - dílo cnb002700797:
![image](https://github.com/user-attachments/assets/eb916e96-8d49-49ce-9a2c-76ea531c3401)
DC

**Comment by pavel-stastny** [comment]
A to chcete? Těch děl a hlavně dotazů do krameriů bude hodně.

**Comment by pavel-stastny** [comment]
Resp. ještě se opravím, pokud to omezíme na ty, které mohou být na seznamu, tak to půjde.

**Comment by Cypzirschova** [comment]
Retest_ dev: NOK
@pavel-stastny Nemáme mít něco jinak nastavené?

**Dílo mimo seznam (mělo by mít kontextovou inf. volné dílo v DK):**
![image](https://github.com/user-attachments/assets/ec92e111-636c-4746-a5f1-32fc195c0357)

**Dílo v seznamu + stav PX (nemělo by mít kontextovou inf. volné dílo v DK):**
![image](https://github.com/user-attachments/assets/e483fbe4-4322-4aa0-bd3e-9a91bfcba327)

**Comment by pavel-stastny** [comment]
Musel jsem proces rozdělit na dva samostatné procesy. První vyřeší příznak pouze pro díla, která mají dntstav a mohou brát data z předchozího běhu pro granularitu. Zde je konfigurace: 

```

				"krameriove_kontrola_zaznamu_states":{
						"type":"kramerius_px_check",
						"logger":"krameriove_kontrola_px_check",
						"cron":<pattern>,
						"iteration":{
								"states":["A","PA","NL", "PX"],
								"data":"granularity"
						},
						"results":{
							"ctx": true
						}
				},

```

Druhý bude procházet díla bez stavu a pro konkrétní rozsah roku vydání. Tam konfigurace by měla být následující: 

```

"krameriove_kontrola_zaznamu_dates":{
						"type":"kramerius_px_check",
						"logger":"krameriove_kontrola_px_check",
						"cron":<pattern>,
						"iteration":{
								"date_range":"[1800 TO 1945]",
								"disabled_states":true,
								"fqoperator":"AND",
								"data":"live"
						},
						"results":{
							"ctx": true
						}
				}


```
Kde jednotlivé parametry procesu znamenaní následující:
 - `"date_range"`:  Filtr pro rozsah let 
 - `"disabled_states"`:  Zkoumananá data  nemají žádný dntstav
 - `"fqoperator"`: Operátor mezi jednotlivými filtry 
 - `"data"`:"live" - Nebere data z granularity, připojuje se na živé instance.

**Comment by Cypzirschova** [comment]
Retest: **OK** 

1. Kontextová inf. se aktualizuje dílům mimo seznam podle licence v DK
2. Kontextová inf. se aktualizuje dílům v SDNNT podle licence v DK
