### ISSUE TITLE
Vyhledávací pole ve fasetě Nakladatel

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#554]
Dobrý den,

uvítali bychom, kdyby se ve fasetě Nakladatele nacházelo vyhledávací pole, kde by se dalo vyhledávat, viz níže.

![Nakladatel - vyhledávací pole](https://github.com/user-attachments/assets/0021b4b9-1857-4068-8d11-ae498df0bd95)
Děkujeme
DC

**Comment by pavel-stastny** [comment]
@Cypzirschova Plnohodnotné vyhledávání udělat nejde.  Facety umožňují filtrovat dle prefixu -> naimplementoval jsem prefixsearch. Funguje to podobně jako vyhledávání v žádostech.  

![image](https://github.com/user-attachments/assets/6a1a813d-b64e-4b99-878b-452a9eabbf85)

**Comment by Cypzirschova** [comment]
Děkujeme za úpravu, ale narazila jsem na menší problém v zobrazení. Pokud si vyfiltruju nějakého nakladatele a chci si vybrat více nakladatelů, tak se nemůžu dostat na konec okna a potvrdit výběr. V níže uvedeném příkladu jsem chtěla označit všechna nakladatelství, kde figuruje VŠE:
![image](https://github.com/user-attachments/assets/17be403a-26c6-476f-9943-22369b4bafbc)

**Comment by pavel-stastny** [comment]
Výpis aktuálního výběru jsem zkrátil.  Pokud je ve výběru více položek, je doplněna výpustka `...`   Celý výběr je pak vidět v tooltipu.  Viz screenshot: 
![image](https://github.com/user-attachments/assets/f0b490bb-55af-4d12-a15a-a4945be616f2)

**Comment by pkudela** [comment]
Jeste doplnim kolegu, je tu jeste jedna moznost, dat vypisu vybranych polozek maximalni vysku a jakmile dojde k presahnuti teto vysky, objevi se scroll bar stejne jako u tabulky viz. screenshot nize:

![image](https://github.com/user-attachments/assets/e5a001ab-f5c8-40e8-898b-c86d9e578287)

Dejte prosim vedet, ktera varianta Vam vyhovuje, jestli ta na jeden radek s tooltipem, nebo ta se scrolovanim.

**Comment by pkudela** [comment]
Jeste jsem objevil problem se zobrazovani instituce na 2 radky v tabulce, pokud je nazav prilis dlouhy, toto jsem opravil.
