### ISSUE TITLE
Pravidla pro zařazování ročníků do granularity - pole 911r

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#556]
Pokud je uvedeno dílo 911r, pak se do granularity zařazují pouze ty ročníky, které jsou definované v tomto poli.  Pole umožňuje i zkrácené zápisy. Popis zápisu a interpretace pole je [zde](https://www.caslin.cz/caslin/spoluprace/jak-prispivat-do-sk-cr/standardy/spravny-zapis-udaju-v-poli-910-a-v-poli-911)

**Comment by Cypzirschova** [comment]
@pavel-stastny je zachovaný původní postup odkazů do DK i z pole 856?

**Comment by CIZKOVAL** [comment]
Dobrý den,
po spuštění granularity dopadl retest následovně:
1. pro problematické dílo ze SVKHK cnb001690428, které má v podpoli **911r** vyplněny tyto roky **1999,2001,06-10,17-18** je to OK. V granularitě jsou zobrazeny všechny ročníky, tedy 1999-2018.
![SVKHK_gran_cast1](https://github.com/user-attachments/assets/614a1fc4-6031-479b-8872-3f41c180fe5a)
![SVKHK_gran_cast2](https://github.com/user-attachments/assets/455f0dc6-229a-49bf-b85f-49720f45926e)

2. pro dílo, které jsme tam měli z minulosti je to ale špatně.
V tomto případě jde o to, že v Krameriovi dílo vystupuje jako 1 celek (je na to již historicky zadaný požadavek na opravu), ve skutečnosti se ale v roce 1990 dílo začalo vydávat pod jiným názvem a v SKC tedy existují 2 různá díla a každé má v poli 911r uvedené jiné roky:
a) cnb002901904 - **911r 1968-89**
b) cnb000360244 - **911r 1990-2017**

V granularitě se u **obou děl** objevují **všechny ročníky**, tedy od r. 1968 do roku 2017 a to je chyba.

Před nasazením nové verze tento 2. případ fungoval správně, tedy takto:

- pro a) se zobrazovaly pouze ročníky 1968-1989 
- pro b) se zobrazovaly pouze ročníky 1990-2017

**Comment by pavel-stastny** [comment]
Musel jsem upravit konfiguraci. Doplňte, prosím, do seznamu kramériů parameter additional_sigla následovně: 

```

				"https?://ndk.cz/.*":{
					"description":"...",
					"api":"https://...",
					"client":"https://ndk.cz/uuid/{0}",
					"acronym":"nkp",
					"sigla":"ABA000",
					"additional_sigla":["ABA001","ABA004"],
					"skip": false
				},"https?://kramerius.*.nkp.cz.*":{
					"description":"...",
					"api":"https://...",
					"client":"https://ndk.cz/uuid/{0}",
					"acronym":"nkp",
					"sigla":"ABA000",
					"additional_sigla":["ABA001","ABA004"],
					"skip": false
				},
				

```

**Comment by CIZKOVAL** [comment]
Retest OK pro případy 1 i 2.

Další dílo, které vynechává některé ročníky v granularitě (protože jsou vynechány i v SKC) a přitom jsou v Krameriovi: oai:aleph-nkp.cz:SKC01-004660681. V SDNNT je to OK - ročníky 1925, 1926, 1927, 1928 nejsou zobrazeny.
