### ISSUE TITLE
Následníci záznamu v případě, že záznam obsahuje více případů SKC_X

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#557]
V případě, že záznam obsahuje v historii stavů více případů SKC_X, například `SKC_1 -> A -> SKC_4b`, pak je problém s dohledáním následníků

**Comment by Cypzirschova** [comment]
OK, následník např. u záznamu: 
oai:aleph-nkp.cz:SKC01-009888965
dohledán, děkujeme za úpravu.

@smallcubes prosím můžeš zavřít.
