### ISSUE TITLE
API: prázdné odpovědi (/request)

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#56]
Dobrý den,

pokud zašlu _API dotaz_ z účtu _knihovna_, tak se mi občas zobrazí prázdná odpověď, ačkoliv by nejspíše neměla být.
příklad: 
```bash
curl -X 'GET' \
  'https://sdnntdev/sdnnt/api/v1.0/request?status=rejected&navrh=VVS' \
  -H 'accept: application/json' 
```

**Problémové hlavičky (`/request`)**:
- status: rejected (VVS, NZN, VVN), approved (VVS, NZN, VVN)

**Comment by pavel-stastny** [comment]
@smallcubes Tady doslo k zmateni (na me strane).  Filtrovani se deje na urovni celych davek a pro ne plati pouze stavy `open`, `waiting` a `processed`.  Stavy `approved` a `rejected` jsou stavy u jednotlivych titulu.   Zatim jsem ponechal pouze stavy pro jednotlive davky.

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes  Toto navrhuji zavřít.  Nad stavy approved a rejected bych se domluvil na některé s našich schůzek.

**Comment by smallcubes** [comment]
@pavel-stastny nechal bych to otevřené, následně po schůzce bych tu napsal, jak jsme se domluvili a issue bych uzavřel.

**Comment by pavel-stastny** [comment]
@smallcubes Do odpovedi pridany detaily, aby slo videt ktere polozky jsou `approved` a ktere `rejected `.  Po vyzkouseni se muze zavrit.

**Comment by smallcubes** [comment]
@pavel-stastny možná je to tak správně, akorát mi dotazy fungují pouze pokud jsou vyplněny všechny atributy (status, itemstatus, navrh) - tedy nemohu zadat dotaz např. `status: processed, itemstatus: approved`

**Comment by smallcubes** [comment]
@pavel-stastny také nemohu ověřit, zdali odpověď z API odpovídá webovému prostředí, jelikož na sdnnt-dev.nkp.cz  nefunguje účet _knihovna_ (nemohu vytvářet výzvy/návrhy) a sdnnt-test.nkp.cz nemá nejnovější verzi API

**Comment by pavel-stastny** [comment]
@smallcubes Ucet knihovna by uz mel fungovat.  Zkuste ty filtry v API jeste jednou. Diky.

**Comment by smallcubes** [comment]
@pavel-stastny pořád se mi nedaří přiřadit položky na seznam (VVS - Navrženo na vyřazení), prostředí: sdnnt-dev.nkp.cz

**Comment by pavel-stastny** [comment]
@smallcubes  Myslite vytvorit vyzvu k vyrazeni ?  Endpoint `/request/batch/vvs` ?

**Comment by JanMeritus** [comment]
@pavel-stastny prosim popis

**Comment by pavel-stastny** [comment]
Stavy cele davky:

1. `Open `
2. `Waiting`
3. `Processed`

Umoznujeme filtrovani podle stavu cele davky. 

Davka muze mit polozky a kazda muze byt stav `approved`, `rejected`.  

Filtr `itemstatus `umoznuje filtrovat ty davky, ktere maji alespon jeden zaznam v daném filtru. Details obsahuje položky odpovídající filtru.  

@smallcubes Muzete vyzkouset.  Build e578af5.   Pokud se shodneme, ze ted ta odpoved dava smysl, provedu rebuild indexu aby se provevili zmeny, co udelal @albertoh.  Rebuild bude trvat nekolik hodin.

**Comment by smallcubes** [comment]
@pavel-stastny při dotazu na záznamy, které čekají na zpracování se mi v odpovědi objeví pouze 4 (v rozhraní jich vidím 9)
Jinak je to nejsípše v pořádku.

(prostředí: SDNNT-DEV, uživatel: knihovna)

dotaz
```bash
curl -X 'GET' \
  'https://sdnnt-dev.nkp.cz/sdnnt/api/v1.0/request?status=waiting&navrh=NZN' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: token'
```

**Comment by pavel-stastny** [comment]
@smallcubes Nepodarilo se mi to nasimulovat, v pripade potreby prosim vytvorit nove issue.
