### ISSUE TITLE
Vyhledávání: obrázek

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#58]
Dobrý den,

jedná se o drobnost. Ve vyhledání je u díla "_Tramp [Praha : Quido Langhans, 1929-1931]_" ikonka obrázku, ale žádný nemá. V SK ČR také nemá obrázek (obalkyknih.cz).

![bezobrazku](https://user-images.githubusercontent.com/78028909/129187286-aeaab089-4cb2-4baa-87ff-bc641399a446.png)

**Comment by albertoh** [comment]
Zaznam ma odkaz na DK,
 https://ndk.cz/kramerius/handle/ABA001/21164601
Odtud se bere nahled:
http://kramerius.nkp.cz/kramerius/api/v5.0/item/ABA001/21164601/thumb

Problem je na strane NDK

**Comment by JanMeritus** [comment]
@jahhoo prosim koukni se na to. 

@albertoh myslim ze je to trochu problem. Ne vsechny nahledy pro vsechny dila su v NK. Nebylo by lepsi vyuzit obalky knih?

**Comment by jahhoo** [comment]
@albertoh z kramerius.nkp.cz to nemůze brát náhledy - tam běží K3. Mělo by se to brát z kramerius5.nkp.cz

**Comment by pavel-stastny** [comment]
@JanMeritus @albertoh to url pochází ještě s K3. Tedy nejde z toho vytvořit náhled.

**Comment by pavel-stastny** [comment]
@JanMeritus Ještě doplním. Ta stará adresa do K3 digitalizace může mít i větší problém.  Psal jsem tobě a paní Lichtenbergové v mailu z 26.7.   Díla, která mají starý odkaz do K3 nemají uuid identifikátor, neprojdou tedy do csv seznamů pro import labelů do K5 přičemž se mi zdá, že některé v K5 jsou. (Alespoň jsem viděl někde logo, které zobrazovalo, že dokument byl konvertován z K3 do K5)

**Comment by JanMeritus** [comment]
momentalne resi @jahhoo kdyztak, mame data u kterych objektu tak je. Bohuzel mnohe jsou v tranzici (nejsou uplne).

**Comment by smallcubes** [comment]
děkuji za reakci @albertoh, náhledy byly tedy u záznamů s odkazy na K3 odstraněny? Ptám se proto, aby bylo z issue jasné, jak se to vyřešilo.

**Comment by albertoh** [comment]
Ano, presne tak. Ted pokus o zobrazeni obrazku je kdyz odkaz ma uuid. Uzaviram

**Comment by smallcubes** [comment]
děkuji za reakci @albertoh a uzavírám
