### ISSUE TITLE
Chybějící funkce: předávání požadavků

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#59]
Dobrý den,

doplňuji funkci, kterou jsem nenalezl v aktuální verzi. Dle zadávacího dokumentu by měla být aplikace schopna: **"Předávání požadavků k vyřízení na další osobu nebo skupinu osob, dle aktuální konfigurace workflow; převzetí a vyřešení požadavku v rámci kompetencí role"** (sekce: Správa záznamů o dílech pro knihovny ČR a nositele práv nebo příslušného kolektivního správce prostřednictvím editace stavů)

Možná se na tuto funkcionalitu ještě nedostalo, ale raději na ni upozorňuji. 
@JanMeritus, @Cypzirschova

**Comment by pavel-stastny** [comment]
@JanMeritus  Neni to duplicita s #15 ?

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Stejné jako u issue #15.   Je nutno specifikovat usecase. Nejlepší bude mít separátní call.

**Comment by JanMeritus** [comment]
@pavel-stastny neni duplicita, jde o funkci kde administrator nebo hlavni kurator muze predavat pozadavky k vyrizeni medzi kuratory. Standardne si je ti proaktivne berou, ale muzu je dostat prideleny.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o komentar k stavu

**Comment by pavel-stastny** [comment]
@JanMeritus Neni zatim implementovano. Prvni probehne konzultace s @pkudela jakym zpusobem to reprezentovat v UI.

**Comment by pavel-stastny** [comment]
@JanMeritus Přidána nová role "mainCurator", která má možnost měnit prioritu u žádostí a zároveň asociovat každou žádost s některým kurátorem.  Kurátoři mají teď navíc fasety pro filtrování dle priority a kurátora.

**Comment by JanMeritus** [comment]
@smallcubes prosim o nasledny test a potvrzeni funkcnosti

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Dám vědět až to bude na Devu.  Ještě je potřeba udělat nějaké změny v UI.

**Comment by JanMeritus** [comment]
@pavel-stastny jj, pripravuji na Po / Ut

**Comment by pavel-stastny** [comment]
Build 79893b4

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za implementaci. 

Narazil jsem na tyto problémy:
- delegace požadavku na kurátora (uživatel *kurator*) od hlavního kurátora (uživatel *bileZnakyzkouska2*) funguje - tedy je mu přidělen. Vyřizení přiděleného požadavku skrze daného uživatele *kurator 2*, ale nefunguje.
(ID požadavku:  knihovna8a1e86ae-689e-461c-8e33-0a1f2047278e)
- v rozhraní pro zpracování požadavků se ztrácí možnost zrušit filtr




https://user-images.githubusercontent.com/78028909/136209656-359d14a2-7da8-4a0f-9c34-2d5f165b81a5.mp4

**Comment by JanMeritus** [comment]
je to chyba,

vrchni kurator rozdeluje pozadavky
pokud uz nejaky kurator pozadavek dostal / nebo si vzal, nemuze resit jine pozadavky (pokud je vrchni kurator nepredeli)

**Comment by Cypzirschova** [comment]
Dobrý den, 
na testu už nelze ani přidělit jinému kurátorovi požadavek k řešení, viz níže.
![přidělení kurátor](https://user-images.githubusercontent.com/86351100/142833752-676667cc-a3c1-48c2-9791-9d9204551ecc.jpg)
Cypzirschová

**Comment by pavel-stastny** [comment]
Prazdne menu by se jiz objevovat nemelo.  Kurator lze nyni menit pouze pokud je zadost ve stavu `waiting`.

**Comment by CIZKOVAL** [comment]
Nyní se aplikace chová následovně, podle mě NOK

1. uživatel (CIZKOVAL) podá žádosti a odešle je
2. nové žádosti vidí všichni kurátoři, resp. všichni kurátoři vidí všechny žádosti (nové i minulé) a mohou kteroukoliv zpracovávat
3. **hlavní kurátor** (Kazimír Kazisvět) udělí vybraným žádostem (_ve stavu waiting_) prioritu a přidělí je **kurátorovi** (Lucie Verderon)
4. **kurátor** Lucie Verderon se to dozví tak, že si jemu přidělené žádosti vyfiltruje dle pole **"Delegovaný kurátor"** - tam vidí pouze jemu přidělené žádosti 
5. **jiný kurátor**, např. Kurátor null všechny žádosti i nadále vidí (i ty, které mu nejsou přidělené) a může je zpracovat

![main_kurator_delegace](https://user-images.githubusercontent.com/92719629/144603538-8ef4d2d8-8fe6-4b32-a1c7-735e5c9c7e2b.png)

![kurator_delegace](https://user-images.githubusercontent.com/92719629/144603561-22be228f-53d0-41cf-8fa4-2705f76815be.png)

**Comment by Cypzirschova** [comment]
Dnes jsem to testovala s paní Lichtenbergovou a přišlo mi to OK. Má to i své výhody. V případě, že delegovaný kurátor bude v pracovní neschopnosti/dovolená atd... Může jiný kurátor tyto žádosti zpracovat. 

Jediné nad čím jsem trochu tápala. Je to podbarvení. Nikde pro kurátory není žádná informace, jestli to mělo být zpracované před x dny nebo kolik dní je po termínu. Případně u těch ostatních, že se blíží (např. 1 den) termín zpracování. Nebo tam nechat barevné podbarvení, ale mít někde nějakou malou legendu? Světle žlutá - blíží se čas do vypršení data 1-2 dny? Sv. červená - žádosti vypršela lhůta? Píšu jen návrhy a nevím, jak by to vypadalo, aby to zase nebylo nepřehledné. Spíš by mě zajímal Váš názor @pavel-stastny @CIZKOVAL @Lichtenbergova
No snad si už nevymýšlím zbytečné hlouposti. :-)

Samozřejmě budeme zpracovávat žádosti podle data, ale asi by bylo vhodné tam mít nějakou informaci a nemuset dopočítávat u každé žádosti jednotlivé dny, do kdy máme ještě čas, v případě náhlého zavalení žádostí.

**Comment by JanMeritus** [comment]
Videt muze, zprqcovovat jenom po prideleni sefkuratorem/prevzeti issue (dle
komentare vyse asi i toto je optimalnejsi

Dňa po 6. 12. 2021, 14:57 Cypzirschova ***@***.***>
napísal(a):

**Comment by pavel-stastny** [comment]
> Dnes jsem to testovala s paní Lichtenbergovou a přišlo mi to OK. Má to i své výhody. V případě, že delegovaný kurátor bude v pracovní neschopnosti/dovolená atd... Může jiný kurátor tyto žádosti zpracovat.

Ok. Myslím, že by to bylo dobré to zatím nechat a řešit případné změny až na základě toho, jak to bude v praxi vypadat. 

> Jediné nad čím jsem trochu tápala. Je to podbarvení. Nikde pro kurátory není žádná informace, jestli to mělo být zpracované před x dny nebo kolik dní je po termínu. Případně u těch ostatních, že se blíží (např. 1 den) termín zpracování. Nebo tam nechat barevné podbarvení, ale mít někde nějakou malou legendu? Světle žlutá - blíží se čas do vypršení data 1-2 dny? Sv. červená - žádosti vypršela lhůta? Píšu jen návrhy a nevím, jak by to vypadalo, aby to zase nebylo nepřehledné. Spíš by mě zajímal Váš názor

Teď se tam podbarvují pouze dvě možnosti.  Ta více křiklavější je, že žádost je po termínu a ta méně křiklavá je, že se termín blíží. To jak Jak moc dopředu se má upozorňovat je definováno v konf. souboru v sekci  `eslacation`

> Samozřejmě budeme zpracovávat žádosti podle data, ale asi by bylo vhodné tam mít nějakou informaci a nemuset dopočítávat u každé žádosti jednotlivé dny, do kdy máme ještě čas, v případě náhlého zavalení žádostí.

V tabulce je políčko "Čas uzávěrky/přepnutí"  To je ten čas do kdy by to mělo být zpracované ( v případě, že se čeká na kurátora) nebo kdy se očekává přepnutí stavů v žádosti (v případě, že se čeká na automatické přepnutí )

**Comment by Cypzirschova** [comment]
> Ok. Myslím, že by to bylo dobré to zatím nechat a řešit případné změny až na základě toho, jak to bude v praxi vypadat.

Souhlasím.


> Teď se tam podbarvují pouze dvě možnosti. Ta více křiklavější je, že žádost je po termínu a ta méně křiklavá je, že se termín blíží.

Přijde mi, že vidím zatím 1 barvu. Jaké jsou nastavené lhůty pro testování? Dostala jsem e-mail, že by to mělo být v řádu minut, ale stále mi tam čeká žádost ze včerejška a není nijak podbarvená.


> V tabulce je políčko "Čas uzávěrky/přepnutí"

Děkuji za informaci, toho jsem si nevšimla.

**Comment by CIZKOVAL** [comment]
@Cypzirschova Dobrý den, lhůty se dají upravovat pomocí API. Chceme otestovat zítra, dáme Vám vědět než to přenastavíme.

**Comment by CIZKOVAL** [comment]
Dobry den p. @Cypzirschova, za mě je to OK. Mohu uzavřít? Děkuji

**Comment by CIZKOVAL** [comment]
Kopiruji z emailu odpoved p @Cypzirschova k tomuto [bodu](https://github.com/NLCR/SeznamDNNT/issues/59#issuecomment-985484770): 
já bych uzavřela. O tomto jsme se bavily s paní Lichtenbergovou a zatím nám tohle nevadí. Má to i své výhody – kurátor1 onemocní, tak kurátor2 zpracuje za kurátora1 žádosti. V historii je to pak vidět, kdo to zpracoval. Kdyby praxe ukázala něco jiného, tak bychom se ozvaly.
D. Cypzirschová
