### ISSUE TITLE
Relativni linkovani problem

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#60]
Prosim opravit linkovani na relativni (informacni cast popis zde vede vzdy na pevne interni IP cislo)

**Comment by pavel-stastny** [comment]
@JanMeritus Zmeneno

**Comment by pavel-stastny** [comment]
@JanMeritus Zmeneno, myslim, ze muzeme zavrit.

**Comment by smallcubes** [comment]
poprosil bych @JanMeritus o schválení a případné uzavření

**Comment by JanMeritus** [comment]
@smallcubes prosim otestovat a uzavrit (schvaleno)

**Comment by smallcubes** [comment]
@JanMeritus vypadá v pořádku. Děkuji Vám za opravu a uzavírám.
