### ISSUE TITLE
API: Swagger UI config

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#61]
Dobrý den,

nejsem si jistý, zdali to je chyba, ale úplně dole ve Swagger UI se zobrazí upozornění: `invalid` (viz obrázek).

<img width="954" alt="invalid" src="https://user-images.githubusercontent.com/78028909/129867765-eff31003-1fc8-410a-bd66-f52406f02e9a.png">

**Comment by pavel-stastny** [comment]
@smallcubes Jedná se jenom o zapnutou validaci openapi specifikace.  Server `validator.swagger.io` se  nemůže dostat na yaml definici api, protože je v privatní síti.  Pokud bude server vystrčený ven, hláška zmizí.  Případně se dá validace zakázat.

**Comment by pavel-stastny** [comment]
@smallcubes Zrušil jsem validaci. Build a3be574

**Comment by smallcubes** [comment]
Dobrý den @pavel-stastny, děkuji Vám za vysvětlení uzavírám.
