### ISSUE TITLE
Kurator - žádosti 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#62]
Dobrý den, 
nezobrazují se všechny žádosti v profilu kurátora (hned po otevření Moje konto). Zobrazí se jen prvních 20 čekajících na posouzení, které končí datem 17.8. Nelze ani jít na další stránku. Pokud si nastavím více položek na stránce např. 50, tak se ukáže zbytek (i to co jsem dělala dnes ráno). Nemělo by se na tom profilu dát postupovat na další stránky (dalších 20 položek)? Ještě doplním, že jsem neměla nastavený žádný filtr.
C.
![Bez názvu](https://user-images.githubusercontent.com/86351100/130011689-8650ed64-192b-46f3-a8c3-dd57c7c08974.png)

**Comment by pavel-stastny** [comment]
@Cypzirschova Dal jsem nový build.  Vyzkoušejte nyní.

**Comment by Cypzirschova** [comment]
Super, funguje.
