### ISSUE TITLE
Filtr Rok vydání zmizí při ručním zadání roku

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#63]
Dobrý den, u filtru Rok vydání jsem se pokusila první rok přepsat ručně a po umazání roku mi zmizel celý filtr, viz záznam obrazovky. Vyzkoušeno na Chrome a Firefox. Druhý rok lze bez problému přepsat. 
prostředí: DEV  
číslo buildu: 3f029e2

https://user-images.githubusercontent.com/43740512/130077860-601c5145-6ee2-4b0c-a363-8a360b289820.mp4

**Comment by smallcubes** [comment]
Dobrý den @marketakrutska,

poprosil bych Vás o kontrolu a případné uzavření.

**Comment by marketakrutska** [comment]
Dobrý den, přepsání roku mi už funguje, děkuji za opravu. Issue uzavírám.
