### ISSUE TITLE
Návrh řazení

### ISSUE THREAD

**Issue by pavel-stastny** [NLCR/SeznamDNNT#64]

**Comment by pavel-stastny** [comment]
3. ještě by mi přišlo dobré, aby se moje požadavky (rozhraní Moje konto) u běžného uživatele (knihovna) řadily: 1. nezaslané, 2. zaslané (v procesu schválení kurátorem) a 3. vyřízené. (Aktuálně to je: 1. nezaslané, 2. vyřízené a 3. zaslané (v procesu schválení kurátorem)

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim o posunuti stavu issue

**Comment by CIZKOVAL** [comment]
@pavel-stastny Toto issue bych uzavřela, defaultní řazení je řešené takto:

user - dle Data zadání vzestupně - neodeslané žádosti (bez data) jsou tedy defaultně na 1. místě.
kurátor - dle Uzávěrky vzestupně
