### ISSUE TITLE
Návrh na přejmenování možností v řazení výsledků

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#65]
Dobrý den,
u řazení výsledků mě zarazila možnost dle "Titulku". Nebylo by lepší to pojmenovat dle "Názvu"?
Poté tam je možnost řazení dle "Data" a přiznám se, že nemůžu přijít na to, dle jakého data se to má řadit. Nešlo by to nějak blíže specifikovat? 
prostředí: DEV
číslo buildu: 3f029e2
![image](https://user-images.githubusercontent.com/43740512/130185025-341c5a77-ae8e-4395-8b62-fbfc155ce249.png)

**Comment by CIZKOVAL** [comment]
@marketakrutska můžeš prosím toot issue zavřít? Na relevanci jsem založila issue #297, kde je více problémů. Děkuju

**Comment by marketakrutska** [comment]
Jasně, issue uzavírám.
