### ISSUE TITLE
Stav dokumentu: N

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#66]
Dobrý den,

chtěla jsem se zeptat, jak je to v aplikaci s příznakem N (stav dokumentu)? Nyní se dává N dílům, které jsou vyřazené a byly zařazené v SDNNT. V aplikaci koukám, že je u N: nezařazeno. Nezařazeno je myšleno, to co nebylo vůbec v SDNNT?

Ještě jsem se chtěla zeptat, zda aplikaci testuje i pak Zahořík z NK? 

Cypzirschová

**Comment by albertoh** [comment]
N je presne jak pisete, vyřazené a byly zařazené. Muzu menit popis, misto Nezařazeno -> Vyřazené 
@Cypzirschova  Souhlas?

**Comment by Cypzirschova** [comment]
To by bylo ideální, ale pak tam ještě máme stav dokumentu VS: vyřazeno - dílo bylo na seznamu (A). Do tohoto stavu se asi nově přidávají díla, která schválím k vyřazení (VVS)?? Jedná se zřejmě o totožný stav, ale jinak pojmenovaný.

![Bez názvu01](https://user-images.githubusercontent.com/86351100/130207268-94f4cdbd-8ba0-4a29-9c41-61a6ac22d1cc.png)

**Comment by JanMeritus** [comment]
@albertoh prosim o odpoved

**Comment by albertoh** [comment]
Pokud tomu spravne rozumim, stav VVS je "Výzva k vyřazení ze Seznamu" a je to prechodni interni stav. Pokud konci na VS, ten stav VVS se nema reflektovat, tj, VS bude "Vyřazeno - dílo bylo na Seznamu (A)
Je to tak?

**Comment by Cypzirschova** [comment]
Jestli jsem to správně pochopila, tak VS = N. My žádný status VS v současné době nepoužíváme. Používáme N = vyřazeno ze seznamu (tzn. už to na seznamu bylo, takže to mělo status A). Pokud by se měly zavádět nějaké další statusy, tak se to musí konzultovat s paní Lichtenbergovou. 

Ponechala bych, jak je to v současné době:

A - zařazeno 
N - vyřazeno
NZ - by měl být označován titul, který je dostupný pouze na terminálu knihovny (Nevím, zda je v současné době funkční.)
PA - návrh na zařazení

nově označujeme PX - pravděpodobná volná díla - Dále prochází kontroly p. Zahořík s ndk a posílá kurátorovi Krameria. Pokud kurátor Krameria rozhodne o tom, že se jedná o volné dílo, tak přechází do statusu X. Toto se, ale nezveřejnuje v seznamu. Nevím, jak to má p. Zahořík ošetřené, ale volná díla v tom seznamu být nesmí a při kontrolách je vyřazujeme ze seznamu. Je to jen zanesené interně v systému Aleph, ale ve veřejném OPACu DNT nikoliv.

**Comment by albertoh** [comment]
My jsme to implementovali podle dokumentaci:

Proces zařazování a lhůty:
O nebo N - > (uživatel/korporace) -> NZN -> (kurátor) -> PA -> (6 měsíců) -> A
O nebo N - > (uživatel/korporace) -> NZN -> (kurátor) -> PA -> (běží lhůta, vstoupi do toho uživatel/korporace ) -> VVN -> (kurátor) -> N
O nebo N - > (uživatel/korporace) -> NZN -> (kurátor) -> PA -> (běží lhůta, vstoupi do toho uživatel/korporace ) -> VVN -> (kurátor, opačné rozhodnutí) -> PA -> (6 měsíců)-> A

Proces vyřazování
A -> (uživatel/korporace) -> VVS ->(kurátor) -> VS
nebo
A -> (uživatel/korporace) -> VVS ->(kurátor) -> NZ (nedojde k vyřazení, jenom limitaci na terminál, na žádost vydavatelů)

Muzeme to jeste zmenit, nebo nechat tak. Je to na vas

**Comment by JanMeritus** [comment]
@albertoh @Cypzirschova je to interni prechodni stav. Navenek, do rozhodnuti kuratora sa nic nemeni

priznak volneho dila by v tomto seznamu mel  byt, nicmene muze byt dostupny jenom interne ako informace pro kuratora

**Comment by Cypzirschova** [comment]
Já bych se asi přikláněla k tomu, aby byl stav dokumentu PX a X skryt a bylo to viditelné jen pro kurátory a administrátory. Pro nakladatele a čtenáře bude asi nejdůležitější, co je v seznamu, co bylo vyřazeno a jaké jsou návrhy. Primárně se počítá, že aplikaci budou hlavně používat nakladatelé/autoři a knihovny. Takto jsem to z jednání pochopila. K tomu procesu vyřazovaní se musím domluvit s paní Lichtenbergovou, zda to upravíme a dám Vám vědět.

**Comment by Cypzirschova** [comment]
Dobrý den,
jen jsem Vám chtěla dát vědět, že na procesu zařazování a vyřazování s paní Lichtenbergovou intenzivně pracujeme. Jakmile to bude hotové, tak to hned pošlu.
Cypzirschová

**Comment by Cypzirschova** [comment]
Dobrý den,
tak níže posílám jednotlivé procesy i s lhůtami. Jednotlivé příznaky jsou na konci vysvětleny. Je potřeba, aby kurátor i administrátor mohl tyto příznaky (stavy) měnit. Pokud něco nebude jasné, tak to mohu případně více rozepsat.

**Sběr návrhů**
*Knihovna, nositel NPA (lhůta 0) – přidělí se automaticky PA (lhůta 1) – nositel práv může reagovat: 
VN – lhůta 2 – kurátor přidělí N nebo zanechá výchozí stav
VNZ – lhůta 3 – kurátor přidělí N nebo zanechá výchozí stav
VNL – lhůta 4  – kurátor přidělí NL se lhůtou 4 (na 18 měs., pak naběhne hláška kurátorovi) - kurátor prověří a buď N nebo A
Po uplynutí lhůty 1 se zbylá PA mění na A
 
Lhůta 0 – čekání na termín 1. 2. nebo 1. 8. 
Lhůta 1 – 6 měsíců - AZ §97 f
Lhůta 2 - nejpozději do posledního dne následujícího měsíce od doručení výzvy - (28 dní) - AZ §97 f  
Lhůta 3 – Vyřazení ze vzdáleného přístupu (do 5 pracovních dnů – lze požádat nakladatele o prodloužení do 10 pracovních dnů) - Memorandum odst. 11 
Lhůta 4 - lhůta 18 měsíců - pokud nakladatel vydá dílo - N, pokud nevydá rovnou - A (bez odkladné lhůty 6 měsíců - tzn. bez PA) - Memorandum odst. 11 b)
 
**Vyřazení ze seznamu**
A – nositel VN/VNZ/jiný nakladatel VNL - VN, VNL lhůta 2/VNZ lhůta 3 - kurátor N/NZ/PX/A/NL - lhůta 4
Lhůta 2 - nejpozději do posledního dne následujícího měsíce od doručení výzvy - (28 dní) - AZ §97 f
Lhůta 3 - odst. 11 Vyřazení ze vzdáleného přístupu (do 5 pracovních dnů – lze požádat nakladatele o prodloužení do 10 pracovních dnů) - Memorandum odst. 11 
 
**Opětovné zařazení**
N-* (postup opětovné zařazení vyřazeného)
         Opakuje se postup jako u sběru návrhů včetně lhůt*
 
**Zpět na vzdálený přístup**
NZ-*
       Opakuje se postup jako u sběru návrhů včetně lhůt*
 
**Ověřování volných děl**
Kurátor přidělí PX = dílo bude stále na seznamu (A + PX) – admin automatizovaná kontrola oproti NDK – shoda volné dílo =  X 
Kurátor přidělí PX = dílo bude stále na seznamu (A + PX) – admin automatizovaná kontrola oproti NDK – není shoda – kurátor Kram. – shoda volné dílo = X
Kurátor přidělí PX = dílo bude stále na seznamu (A + PX) – admin automatizovaná kontrola oproti NDK – není shoda – kurátor Kram. – není shoda = vrací se původní stav bez PX (A nebo PA)
 
**Zatím nepopsáno – automatizované kontroly**
Kontrola oproti NDK – vše proti X
Kontrola oproti distributorům 
 
**Vysvětlivky**
NPA - Návrh na zařazení (čekání na termín 1. 2. nebo 1. 8. - lhůta 0)
PA - Návrh na zařazení (běží lhůta 6 měsíců - lhůta 1)
VN – Výzva k vyřazení (lhůta 2)
VNL – Výzva k vyřazení díla jiného nakladatele při získání licence na dílo 
VNZ – Výzva k licenci pro terminál na místě samém (lhůta 3)
A – zařazeno 
N – Vyřazeno ze seznamu (bylo na seznamu A)
NZ – Licence pro terminál na místě samém
NL – Vyřazeno – plánované vydání po získání licence – na 18 měs. (bez odkladné lhůty 6 měsíců tzn. pak N nebo A)  
PX – Pravděpodobně volné dílo
X – Volné dílo 
 
**Stavy:**
Veřejně viditelné stavy: PA, A, N, NZ, NL
Interní stavy (kurátor + admin): PX, X, NPA
Pracovní stavy (kurátora + admin + po přihlášení knihovna/nakladatel/autor): VN, VNZ, VNL 

Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Porad je tu jeste ta otazka na kterou apeluje @JanMeritus  a to je granularita.  Tedy kdyz je na seznamu del jenom cast titulu. Napriklad u https://dnnt.mzk.cz/periodical/uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6. Tedy  rocniky 1911 a vys maji licenci dnnt  ale samotny titul Lidove noviny dnnt licenci nema.   Ma to byt reflektovano ve workflow ? 

@JanMeritus @pavelkocourek Vidim to hodne spatne terminove.  Toto je velka zmena oproti puvodnimu.

**Comment by Cypzirschova** [comment]
Dobrý den,
 
my máme periodika zařazená v seznamu jako celek (tzn. jsou tam celé záznamy na všechny svazky periodik). V NDK se to omezuje licencí DNNT - do roku vyd. 2010. Díla, která vyšla v r. 1910 a níž jsou už volná díla (do SDNNT nepatří). Jak je to přesně řešeno, nevím. S tímto problémem se budete muset obrátit na pana Zahoříka a další kolegy, co mají na starost NDK. 
 
Po zvážení tohoto problému, by bylo dobré do aplikace nadefinovat oznamovací hlášku, že zpřístupnění v rámci DNNT se týká pouze periodik vydaných do r. 2010. Rok vydání by se pak musel každý rok posouvat, tak aby to administrátor mohl pak upravit.  
 
Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova A u periodik se nebude stavat, ze by se nejaky rocnik nebo vytisk musel omezit pouze na terminal?  A pokud ano, bude omezovat cele periodikum ?

**Comment by Cypzirschova** [comment]
Ze zákona je to možné. Dle mého mínění záleží na nositeli práv, zda bude chtít omezit celé periodikum nebo jen jednotlivé ročníky. Takže jsou nejspíše možné obě varianty.

**Comment by pavel-stastny** [comment]
@Cypzirschova V tom případě to moc nechápu.  Pokud platí to, že se v aplikaci řeší periodika jako celek  (Tedy zobrazí se pouze celé periodikum) tak jakým způsobem dojde k omezení pouze jednoho ročníku a jak se to projeví na tom periodiku? 
(Protože nyní má celé periodikum stav A nebo NZ a to bez ohledu na jeho podcasti)

**Comment by Cypzirschova** [comment]
Jde pouze o mou domněnku. Dotaz jsem už přeposlala paní Lichtenbergové.

**Comment by Lichtenbergova** [comment]
Periodika se popisují jako celek, licence povoluje možnost zveřejnit do -10 let zpět, pokud se neozve nakladatel, že starší ročníky komerčně využívá (placené archivy). Před digitalizací se záznamy kontrolují, takže by v nich nemuselo být moc chyb a propojení záznam/digitalizát by mělo fungovat. Zatím nikdo nepožadoval znepřístupnění části ročníků, je to jen teoretická možnost, nevím, zda to teď řešit. Pro všechna periodika s A tedy platí, že se zpřístupňují nyní do 2010. Granularita se nedá řešit v bibliografickém záznamu, svazky jsou rozepsány v tzv.  jednotkách (něco jako samostatný formát), tedy nikoli v podpoli $p.
Řešení určitě konzultujte s R. Zahoříkem.

**Comment by pavel-stastny** [comment]
@JanMeritus Jak jsme se domlouvali na telefonu ve středu. Na změně workflow se musíme domluvit/ujasnit v separátním callu.  Nejbližší verze bude mít wf stejné jako je specifikováno v zadávací dokumentaci.

**Comment by JanMeritus** [comment]
@Cypzirschova zde si myslim ze by to melo do budoucna pak vest k rozsireni celeho flow i na roli kuratorKrameria - na ktere se pripadne da preposlat pozadavek k posouzeni/vyrizeni/uvolneni dila, pokud na Vasi strane zistite ze jde o dilo jiste verejne, nebo bude taky nutny nejaky druh dobrozdani z jejich strany.

**Comment by Cypzirschova** [comment]
Souhlasím, zde je potřeba součinnost obou stran kurátorů.

**Comment by pavel-stastny** [comment]
Dobrý den paní @Cypzirschova @Lichtenbergova , 

otázka ohledně výzev. Vzhledem k tomu, že u jednotlivých výzev jsou ruzné lhůty musí být výzvy v aplikaci realizovány samostatně. Nyní je tam jenom jeden typ a to VVN. V novém workflow je následující: 

> 
> VN – Výzva k vyřazení (lhůta 2)
> VNL – Výzva k vyřazení díla jiného nakladatele při získání licence na dílo
> VNZ – Výzva k licenci pro terminál na místě samém (lhůta 3)
> 


Předpokládám, že VN odpovídá standardnímu vyřazení ze seznamu. NZ je omezení na terminál, tedy realizováno licencí ale co je VNL a kdo (jaký typ uživatele) bude mít práva provádět tento typ vyřazení?   

A druhá otázka:   

Pro vyřazení ze seznamu nebo omezení na terminál máme samostatné tlačítko (v novém layoutu). Ta výzva VNL je ještě jiný typ akce (tedy je potřeba další tlačítko)?

**Comment by Cypzirschova** [comment]
VNL - mohou podle Memoranda využít jiní nakladatelé než je původní dílo vydáno. Mohou získat licenci na vydání konkrétního díla, které předtím vydal jiný nakladatel. Pak je tam ta lhůta 4 - 18 měsíců

**Comment by pavel-stastny** [comment]
@Cypzirschova Zde vidím problém s identifikací takového nakladatele.  Nyní jsou v aplikaci následující role: 

- uživatel
- knihovna
- kurátor
- hlavní kurátor
- admin

Přičemž nakladatel je jako každý jiný uživatel, může vytvářet žádosti o zařazení, vyřazení případně omezení pouze na terminál).  Tady ten nový typ žádostí může být u jakéhokoliv uživatele?  Tedy jedná se opravdu o přidání tlačítka pro všechny nebo je to svázáno pouze s nakladateli ?

**Comment by Cypzirschova** [comment]
NL se týká pouze nakladatelů.

Když se přidá další tlačítko, tak už mi to přijde, že by tam toho v 1 záznamu bylo moc. Nebylo by to už tak přehledné. Vymyslely jsme zaškrtávací okénko pro stav **NL** - kde jsem to neuvedla přesně, jak to je podle Memoranda:

NL je omezení na terminálu, ale podle Memoranda má NK možnost zkontrolovat (po 18 měs.), zda nakladatel vydal dílo, na které měl licenci nebo díla, která jsou podobná tematicky. O toto mohou žádat nakladatelé, kteří na díla mají buď novou licenční smlouvu, nebo budou vydávat nové dílo, které je tematicky obdobné s jinými díly v seznamu.

NZ je stav, kde mohou žádat nakladatelé pouze u své produkce. Např. Albatros může omezit na terminál pouze svá díla, nikoliv např. od Orbisu. U tohoto stavu nejsou žádné čekací lhůty, pouze lhůta do kdy to musí kurátor zpracovat (lhůta 3 - do 5 pracovních dní).

Nevím, zda je to technicky možné, ale přidalo by se do žádosti o omezení na terminál toto pole (viz níže). Pokud by to nakladatel oškrtnul, tak by se tím celá žádost odeslala jako žádost VNL. Po rozhodnutí kurátora by se díla, která schválí, označila stavem NL, kde běží lhůta 18 měsíců. Tato lhůta po 18 měsících upozorní kurátora, že je potřeba zkontrolovat, zda nakladatel dílo vydal (to na které má licenční smlouvu nebo tematicky obdobné). Zde se vlastně mění i ta licence na dnntt.
![18 měsíců odkl](https://user-images.githubusercontent.com/86351100/140725374-99d90739-69ab-49e5-8eeb-18eff3c4ec57.jpg)

**Comment by pavel-stastny** [comment]
@Cypzirschova Takže výzva k omezení na terminál by měla dvě podoby, první je je NZ a druhá je NL a řídílo by se to zaškrtávacím polem ve výzvě, je to tak?  Dostupné by to bylo roli uživatel.

**Comment by Cypzirschova** [comment]
Ano, je to tak. Dostupné by to bylo pouze v roli nakladatele. Ještě kurátor by mohl měnit stav na NL, jak je to již v současné době v aplikaci, že může kurátor měnit stavy u jednotlivých děl.

**Comment by pavel-stastny** [comment]
@Cypzirschova no, právě že role nakladatel nyní není.  Asi nebude problém ji tam dodat jenom by asi ta role nakladatel byla nastavována v admin rozhraní.  (Uživatel by při registraci dostal roli uživatel) ?

**Comment by Cypzirschova** [comment]
![nakladatel](https://user-images.githubusercontent.com/86351100/140730194-58dc7d5a-b064-4c9f-a302-53f6b03a33f6.jpg)

**Comment by pavel-stastny** [comment]
@Cypzirschova myslim, ze toto je ukládáno jenom jako informace u uživatele.  @albertoh mě když tak doplní.

**Comment by pavel-stastny** [comment]
@Cypzirschova ještě NPA vs PA.  Já stav NPA chápu jako návrh na zařazení, je to tak?  Tedy každé dílo které je v návhru mu běží lhůta 0, kurátorem schválené dílo je ve stavu PA a běží mu lhůta 1.

**Comment by Cypzirschova** [comment]
NPA je stav, který vidí pouze kurátor, admin, knihovna. Tento stav je takový "představ" před PA, kdy pak běží lhůta 6 měsíců.

**Comment by Cypzirschova** [comment]
Chceme tím stavem (NPA) říct, že díla budou zařazená do návrhů na zařazení, ale čekají na datum 1.2. a 1.8. a až po tomto datu běží lhůta 6 měsíců (PA). V současné době jsou návrhy vystavovány pouze 1.2. a 1.8. 

Knihovna vytvoří žádost s návrhy na zařazení do SDNNT. Kurátor to schválí a dílům se přidělí stav NPA - čekají na datum 1.2. nebo 1.8. (podle toho co je blíž - lhůta 0). 1.2 nebo 1.8. se dílům automaticky změní stav na PA (veřejný stav, který vidí kdokoliv) - běží lhůta 6 měsíců.

- VN - zde má kurátor lhůtu 28 dní, do kdy musí žádost vyřídit

- VNZ - lhůta 5 pracovních dní, do kdy musí kurátor žádost vyřídit

- VNL - zde by zřejmě měla být lhůta těch 5 prac. dní - ještě si ověřím

U NPA se lhůta bude lišit. Např. pokud knihovna vytvoří návrh 1.11., tak běží lhůta do 1.2. (3 měsíce).

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim o rychle doplneni diagramu stavu a lhut, plus vyznaceni, co vyplyva z AZ, co vyplyva se Smlouvy s DILIA  a co z Memoranda v spolupraci s @Cypzirschova. Pro lhuty prosim spracovat tabulku tak aby bolo jasne, pri prechodu z jakeho stavu do jakeho v ramci "mezistavu V[x] a N[x]" jsou jake lhuty a jake role tyto stavy vidi 

@pavel-stastny pro NL - za mne zase jede o stav, pokud to chapu spravne @Cypzirschova, jeho vyznam je ze:
- kdyz nakladatel poda zadost na jine dilo, kurator vi ze je opravnen udelat tak z memoranda 
- kuratory pak muzu po 18 mesicich skontrolovat opravnenost pozadavku a prsi na nem timing
- vaze se s nim licence DNNTT

**Comment by pavel-stastny** [comment]
@JanMeritus VNL a VNZ je o licenci DNNTT.  Můsí být realizovány jiným typem žádosti  - váže se k nim jiné lhůty a platí pro celou žádost.

**Comment by JanMeritus** [comment]
@pavel-stastny to nikdo nerozporuje

**Comment by CIZKOVAL** [comment]
@JanMeritus pracuji na diagramech, behem zitrka je dam k pripominkam.

**Comment by CIZKOVAL** [comment]
Dobrý den, dle výše popsaných stavů jsem vypracovala diagramy a tabulku stavů a lhůt.
Prosím @Cypzirschova @Lichtenbergova @JanMeritus o kontrolu. Děkuji

[STAVY.xlsx](https://github.com/NLCR/SeznamDNNT/files/7527523/STAVY.xlsx)
[Sběr_návrhů.pdf](https://github.com/NLCR/SeznamDNNT/files/7527524/Sber_navrhu.pdf)
[Návrhy.pdf](https://github.com/NLCR/SeznamDNNT/files/7527525/Navrhy.pdf)
[Vyřazení ze seznamu.pdf](https://github.com/NLCR/SeznamDNNT/files/7527528/Vyrazeni.ze.seznamu.pdf)
[Opětovné_zařazení.pdf](https://github.com/NLCR/SeznamDNNT/files/7527529/Opetovne_zarazeni.pdf)
[Volná díla.pdf](https://github.com/NLCR/SeznamDNNT/files/7527531/Volna.dila.pdf)
[Dostupnost_změny.pdf](https://github.com/NLCR/SeznamDNNT/files/7527532/Dostupnost_zmeny.pdf)
[UC.pdf](https://github.com/NLCR/SeznamDNNT/files/7527537/UC.pdf)

**Comment by pavel-stastny** [comment]
@CIZKOVAL Nepujde úplně udělat jedním typem návrhu dvě akce,  Návrh na zařazení a zároveň návrh na zvýšení dostupnosti.  Musí se udělat jiným typem žádosti. (Stějně jako u VN a VNZ) 

@Lichtenbergova @Cypzirschova Co je zde nové je to zvýšení dostupnosti . Zatím se to nikde neobjevovalo.  Je to změna oproti tomu co bylo napsáno v tomto [komentáři ](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-919140167) ?

**Comment by JanMeritus** [comment]
@CIZKOVAL Dekuji, dobra prace. Prosim jeste upravit tabulku v zmyslu kde
sloupec stav obsahuje stavy zelene plus npa, hned vedle toho je sloupec
pracovni stavy, pak sloupec licence (tj A bude mit dva radky - dnnto a
dnntt), pak interni licence

- Barvy oznacuji viditelnosti pro jednotlive skupiny uzivatelu


>

**Comment by CIZKOVAL** [comment]
Dobrý den
@pavel-stastny co se týče zvýšení  dostupnosti, tak to je zmíněno v tomto [komentáři](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-953734156)

@JanMeritus Upravila jsem tabulku se stavy, přidala jsem nový list, kde jsou stavy versus akce (pracovní stavy), lhůty a licence. Pokud tomu dobře rozumím, tak licence jsou interní do okamžiku, kdy je dílo zařazeno na seznam (A). S tím souvisí i moje první otázka + přidávám další otázky, které mě napadly:

1. má smysl žádat o snížení dostupnosti (VNZ) u dokumentů které jsou ve stavu PA? Nyní to možné je...při schválení žádosti bude dílo ve stavu N a bude mít licenci dnntt, která bude interní? Nemá smysl VNZ pouze u dokumentů které jsou na seznamu (A)?
2. totéž u zvýšení dostupnosti? (toto je novinka)
3. jak se bude nazývat pracovní stav pro zvýšení dostupnosti a jakou bude mít kurátor lhůtu na vyřízení?
4. jaká je lhůta u pracovního stavu NZN? Nikde jsem ji nenašla
5. jaká je lhůta u pracovního stavu VNL? Někde jsem našla lhůta 2 a někde lhůta 3... (nemyslím lhůtu 4 u stavu NL)

Ještě přidávám nový obrázek s UC, který jsem upravila.

[STAVY_v2.xlsx](https://github.com/NLCR/SeznamDNNT/files/7538415/STAVY_v2.xlsx)
[UC_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7538417/UC_v2.pdf)

Jinak platí diagramy [zde](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-967075998)

**Comment by Lichtenbergova** [comment]
ad 1. Pokud je vystaven návrh na zařazení (PA), nakladatelé mohou o  omezení dostupnosti žádat a běžně tak činí již v této fázi.  Byl by to asi ojedinělý případ, ale i VNZ a VN se může sejít, v případě více nositelů práv, kteří by měli odlišné požadavky. V tomto případě by asi zvítězil přísnější režim, musel by to posoudit kurátor.  

ad 2. rozšíření dostupnosti jsme řešili jen pro situaci v souladu s memorandem (8, věta 2) - po uplynutí 18ti měsíců...  Zatím jsme se nesetkali s tím, že by autor požadoval rozšířit dostupnost tam, kde ji nakladatel omezil (11a). Zřejmě tedy není nezbytné to řešit teď prostřednictvím aplikace ?

ad 3. u NL po 18ti měsících provede kurátor kontrolu dostupnosti na trhu, lhůta na prověření určena není, jen je tam, že se může uplatnit přímo, nemusí se dávat návrh.  NL se může  změnit, NLX? Můžeme si tam nastavit  kontrolu, např. použít do pěti pracovních dnů - lhůta 5 (interní, s možností změny nastavení)

ad 4. NZN - můžeme si tam nastavit  kontrolu, např. použít do pěti pracovních dnů - lhůta 5 (interní, s možností změny nastavení)

ad 5. U VNL je výzva podle memoranda odst. 11 - tedy lhůta 3

**Comment by Cypzirschova** [comment]
@CIZKOVAL v UC_v2 ještě chybí u kurátora ověření dostupnosti oproti knižnímu trhu. Zatím teda v aplikaci dle mého není úplně vyřešeno. Zda jsem to dobře pochopila.

**Comment by Cypzirschova** [comment]
@CIZKOVAL Sběr návrhů - vidím zde X - Jak je to zda myšleno - sta X (volné dílo)?

**Comment by Cypzirschova** [comment]
@CIZKOVAL Ještě bych do návrhů doplnila tuto informaci. Mohlo by to vypadat, že dílům běží lhůta 1 od začátku. 
![Návrhy  ](https://user-images.githubusercontent.com/86351100/142425207-ee3d4a4b-1156-493b-a318-87397708efaf.jpg)

**Comment by Cypzirschova** [comment]
https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-963936611
@JanMeritus Je to tak, jak píšete.

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim stav NL a stavy N[x], V[x] oznacovat zlutou, narozdil od stavu PA, A, N, X

**Comment by CIZKOVAL** [comment]
Dobrý den,
upravila jsem tabulku STAVY_v3.xls, diagram Návrhy a Vyřazení.

Zapracovala jsem následující:

- [návrh, bod 3](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-969028464) paní Lichtenbergové, zohledněno zde:
[Vyřazení ze seznamu_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7570179/Vyrazeni.ze.seznamu_v2.pdf)
[Návrhy_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7570178/Navrhy_v2.pdf)
[STAVY_v3.xlsx](https://github.com/NLCR/SeznamDNNT/files/7570181/STAVY_v3.xlsx)

- UC - přidání akce u kurátora (ověření dostupnosti oproti knižnímu trhu), zohledněno zde:
[UC_v3.pdf](https://github.com/NLCR/SeznamDNNT/files/7570183/UC_v3.pdf)

- přidání u PA, že běží dále Lhůta 1, viz [poznámka](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-972872294), viz Návrhy_v2.pdf

Ano, u sběru návrhů vycházím ze stavu X - je to špatně? (návrhy NZN mohou být pouze u N nebo N a PX)? Děkuji

**Comment by Cypzirschova** [comment]
@CIZKOVAL Stav X = volné dílo = dílo, které už není svázáno autorským zákonem (uplynulo 70 let od smrti všech autorů). Volná díla jsou něco jiného než díla, která budou nejvíce knihovny zařazovat. Volná díla (stav X) jsou vyřazena ze seznamu a už by neměla být znovu zařazována do seznamu, protože v seznamu být nesmí. 

Asi bych zvolila jinou zkratku než X, protože to může trochu mást s tím stavem X.
Knihovny navrhují díla, která nemají žádný stav + díla, která mají N (vyřazená).

Stav PX - pravděpodobně volné dílo je stále na seznamu. Dílo má stav např. A + bude mít ještě PX - interní stav tzn., že dílo je pořád na seznamu a knihovny ho nemohou znovu zařadit, když tam stále figuruje.

**Comment by Cypzirschova** [comment]
@CIZKOVAL Ještě jsem si všimla, že u volných děl je jen A + PX. Ještě by mohla být varianta PA + PX.

**Comment by CIZKOVAL** [comment]
Dobrý den,
přikládám finální podobu diagramů a workflow, jsou tam pouze drobné úpravy na základě posledních 2 komentářů od @Cypzirschova a také tam byly drobné chybky, které jsem opravila:

[STAVY_v4.xlsx](https://github.com/NLCR/SeznamDNNT/files/7608022/STAVY_v4.xlsx)
- úpravy jsou vyznačeny formou revizí

[Sběr_návrhů_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7608026/Sber_navrhu_v2.pdf)
- úprava z X --> nezarazena dila

[Návrhy_v3.pdf](https://github.com/NLCR/SeznamDNNT/files/7608027/Navrhy_v3.pdf)
- stav NLX zmenen na interni (sedy)

[Vyřazení ze seznamu_v3.pdf](https://github.com/NLCR/SeznamDNNT/files/7608030/Vyrazeni.ze.seznamu_v3.pdf)
- stav NLX zmenen na interni (sedy)

[Opětovné_zařazení_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7608033/Opetovne_zarazeni_v2.pdf)
- pridana Lhuta 5

[Volná díla_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7608035/Volna.dila_v2.pdf)
- pridan i vychozi stav PA+PX

[Dostupnost_změny_v2.pdf](https://github.com/NLCR/SeznamDNNT/files/7608037/Dostupnost_zmeny_v2.pdf)
- pridana Lhuta 3, zvyseni dostupnosti zatim nebude pozadovana

**Comment by CIZKOVAL** [comment]
Ještě jsem zapracovala připomínky, které mám od @JanMeritus

- u NPA jsem napsala poznámku, že se jedná o Odložený start 
- v souboru se STAVY jsem upravila licence (u PA i A na DNNTT/DNNTO)

Ještě otázky od @JanMeritus:
1. ke stavu NPA - když bude požadavek zadávat knihovna, tak je mezistav NPA s odloženým startem. Pokud bude ale žádat o zařazení vlastník práv, tj. autor nebo nakladatel, tak tam bude také běžet lhůta 0 a bude stav NPA?
2. ke zvýšení dostupnosti - tuto funkcionalitu by bylo potřeba doplnit. Např. situace kdy nakladatel omezí dílu dostupnost na terminál (A dnntt) a poté bude chtít např. autor zvýšit dostupnost (A dnnto)

**Comment by CIZKOVAL** [comment]
Dobrý den, testuji nové workflow a narazila jsem na následující a potřebovala bych ověřit, zda je to OK.

Jedná se o opětovné zařazení na seznam nebo Sběr návrhů:

N nebo díla bez stavu --> NZN --> NPA --> běží lhůta 0, stav NPA vidí pouze kurátor, ale ostatní vidí N a můžou podávat další žádosti NZN než dojde k 1.2. nebo 1.8. Podle workflow je to OK, ale takové žádosti se tam můžou hromadit, přitom už tam budou....je to tak v pořádku?

Prosím o posouzení @Cypzirschova, @JanMeritus 

Ještě prosím o posouzení [techto bodu](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-980012812)

**Comment by Cypzirschova** [comment]
Posílám odpovědi po konzultaci s paní Lichtenbergovou.
> * ke stavu NPA - když bude požadavek zadávat knihovna, tak je mezistav NPA s odloženým startem. Pokud bude ale žádat o zařazení vlastník práv, tj. autor nebo nakladatel, tak tam bude také běžet lhůta 0 a bude stav NPA?
> * ke zvýšení dostupnosti - tuto funkcionalitu by bylo potřeba doplnit. Např. situace kdy nakladatel omezí dílu dostupnost na terminál (A dnntt) a poté bude chtít např. autor zvýšit dostupnost (A dnnto)

NPA - zatím zůstane stejný proces u všech žadatelů.

Zvýšení dostupnosti - toto téma je docela problematické. Zatím tu žádný takový případ nebyl. Autor většinou prodá práva na dílo/díla a ty jsou vázané smlouvou. Podle Memoranda nám nakladatel nemusí ukazovat nic, takže se takové případy budou řešit individuálně s komunikací, jak nakladatelem, tak autorem.

> Sběr návrhů:
> 
> N nebo díla bez stavu --> NZN --> NPA --> běží lhůta 0, stav NPA vidí pouze kurátor, ale ostatní vidí N a můžou podávat další žádosti NZN než dojde k 1.2. nebo 1.8. Podle workflow je to OK, ale takové žádosti se tam můžou hromadit, přitom už tam budou....je to tak v pořádku?

Mě to OK nepřijde. Stav N je pro díla, která byla na seznamu nebo v návrhu a jsou vyřazená. Nemůžou mít díla stav N, když ještě ani nebyly v seznamu/návrhu.

**Comment by pavel-stastny** [comment]
> Mě to OK nepřijde. Stav N je pro díla, která byla na seznamu nebo v návrhu a jsou vyřazená. Nemůžou mít díla stav N, když ještě ani nebyly v seznamu/návrhu.

Ok. Pokusím se vysvětlit.  Ono to mělo implementační konotace. Ve workflow jsem se snažil mít vždy stav veřejný pouze jako subset stavu pro kurátory.  Kurátorský stav je ten, podle kterého se řídí workflow, veřejný pak pouze pro zobrazení. Proto se při přepnutí přiřadil i veřejný stav.   Nicméně, pokud je to koncepčně NOK, tak bych tu diskusi přenesl do jiného issue.   TAdy to velké bych uzavřel.

**Comment by pavel-stastny** [comment]
Ještě poznámka.  Ten můj komentář se týkal děl nezařazených (bez stavu)

**Comment by CIZKOVAL** [comment]
Děkuji za odpovědi. Pomotala se nám issues, proto bych je nadále řešila zvášť:

Pro díla mimo seznam (**bez stavu**) --> NZN --> veřejný stav N řeší se v #158 
Pro díla nezařazená (**stav N**) --> NZN --> veřejný stav N založila jsem nové issue-otázku #166

**Comment by Cypzirschova** [comment]
> TAdy to velké bych uzavřel.

Chci nejdříve projít celé issue a po kontrole ho následně uzavřu. @pavel-stastny
