### ISSUE TITLE
Zobrazování záznamů v aplikaci

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#67]
Dobrý den,

chtěla jsem se zeptat na zobrazování záznamů? Některé záznamy vidím s nakladatelskými údaji (260, 264) a jiné zase ne (viz níže). Šlo by toto nějak opravit?
![Bez názvuvvvvvvv](https://user-images.githubusercontent.com/86351100/130212973-24149ef6-b333-48b9-9be6-8b82b3c1153b.png)

![Bez názvuvvv](https://user-images.githubusercontent.com/86351100/130212993-f4b02b10-0ede-4a32-9919-4642d784d913.png)

https://aleph.nkp.cz/F/?func=direct&doc_number=000384861&local_base=SKC
https://aleph.nkp.cz/F/?func=direct&doc_number=000384867&local_base=SKC 

Cypzirschová

**Comment by smallcubes** [comment]
Dobrý den @Cypzirschova ,

poprosil bych Vás o kontrolu a případné uzavření.

**Comment by Cypzirschova** [comment]
Dobrý den,
zkontrolováno a uzavírám.
Cypzirschová
