### ISSUE TITLE
Vyhledávání: příliš dlouhý text

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#69]
Dobrý den,

pokud vyhledám dílo např. _"Toulavá kamera / Iveta Toušlová, Marek Podhorský, Josef Maršál (cnb001657638)"_, tak se vyhledávácí rozhraní velmi protáhne směrem doprava, jelikož se řádky nezalamují. Bylo by možné je zalamovat, případně to jinak vyřešit? (Seznam problematických záznamů lze najít i přes dotaz _"80-"_.)

**Ukázka**

https://user-images.githubusercontent.com/78028909/130425523-3e70c91b-b540-4e82-a97a-607b543a5abe.mp4

**Comment by pkudela** [comment]
Dobry den @JanMeritus, testoval jsem to v chrome a v Safari a zalamuje se mi to spravne, poprosil jsem Pavla o otestovani edge, ale take bez problemu az u Firefoxu jsem narazil na problem. Pokud to byl Firefox, tak jsem to fixnul viz. screenshot

![image](https://user-images.githubusercontent.com/16591052/134678510-8d391214-1bcd-4fce-be73-ae5e4de04bee.png)

Jakmile bude nasazena nova verze, pravdepodobne v pondeli, tak predam k otestovani.

**Comment by JanMeritus** [comment]
@pkudela pak na @smallcubes

**Comment by pkudela** [comment]
nasazeno, ready to test

**Comment by smallcubes** [comment]
@pkudela děkuji Vám za reakci a opravu. Issue uzavírám. Pouze mám ještě dotaz na @JanMeritus. Nebylo by lepší upravit formátování výpisu ISBN pro větší přehlednost? např. alespoň přidání mezer mezi jednotlivými ISBN
