### ISSUE TITLE
Definovat, která pole se sledují pro verzování záznamu

### ISSUE THREAD

**Issue by pavelkocourek** [NLCR/SeznamDNNT#7]
UC - změní se bibliografický záznam 
Logujeme údaje, které mohou mít autorsko právní dopad.
Uložen je Aktuální (poslední záznam) + historie změn z Alephu. 

Logovaná pole (dokud je stejné SYSNO)
- Autor
- Nakladatel
- Rok vydání
- Název (používán pro vyhledání záznamu v nakladatelských datech)

**Comment by pavel-stastny** [comment]
implementovano
