### ISSUE TITLE
Schvalovací rozhraní: nefunguje "Označit jako zpracované"

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#71]
Dobrý den,

pod uživatelem _kurátor_ nefunguje v rozhraní pro _zpracování žádostí/výzev_ tlačítko: _Označit jako zpracované_, ačkoliv byly již všechny záznamy zpracovány.

**ukázka**

https://user-images.githubusercontent.com/78028909/130588741-b4609a5e-1750-447f-a0eb-b688fa9e3db1.mp4

**Comment by smallcubes** [comment]
Možná je problém jen u tohoto požadavku: datum zadání 19.07.2021 09:52, jelikož u ostatních mi tlačítko funguje.

**Comment by JanMeritus** [comment]
@smallcubes prosim o overeni na soucasne verzi (novy pozadavek) a pripadne uzavreti

**Comment by smallcubes** [comment]
@pavel-stastny děkuji Vám za opravu, uzavírám.
