### ISSUE TITLE
Consent se zpracovanim dat

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#72]
- po prichodu na stranku
- pri prihlaseni

**Comment by pkudela** [comment]
Dobry den, prosim, muzete vice spefifikovat jak by se hlaska mela chovat, jaky text by mela obsahovat? Jedna se o klasickou "cookie" hlasku viz. screenshot, nebo neco jineho? Podle textu, ktery poslete jsou de facto 2 moznosti zobrazeni:
-----

- klasicky v dolni casti browseru
- vyskakovaci dialogove okno
-----
![image](https://user-images.githubusercontent.com/16591052/133055164-aee7d772-1db9-482f-89db-d8e610a61fe6.png)

**Comment by JanMeritus** [comment]
@pkudela 
- dolni cast browseru
- "Tento web používá k poskytování služeb, personalizaci reklam a analýze návštěvnosti soubory cookie. Používáním tohoto webu s tím souhlasíte."

**Comment by JanMeritus** [comment]
@pkudela v jakom je to stavu?

**Comment by pkudela** [comment]
Hotovo, jakmile nasadime na vyvojovy server, dam k testovani.

![image](https://user-images.githubusercontent.com/16591052/134687997-256c89dc-d693-412a-aac7-9a0a3c923645.png)

**Comment by pkudela** [comment]
nasazeno, ready to test

**Comment by pavel-stastny** [comment]
Build: fc1c7e8

**Comment by smallcubes** [comment]
@JanMeritus @pavel-stastny @pkudela proužek s upozorněním se zobrazí. Děkuji Vám za vyrízení a issue uzavírám.
