### ISSUE TITLE
Úprava názvu tlačítka "Odkaz do dk"

### ISSUE THREAD

**Issue by marketakrutska** [NLCR/SeznamDNNT#75]
Dobrý den, 
u tlačítka "Odkaz/y do dk" bych to "dk" rozepsala. Případně bych zvážila, zda by nebylo lepší "Odkaz na digitální dokument" nebo něco podobného.
DEV, 4be5b16
![image](https://user-images.githubusercontent.com/43740512/130603887-885cc304-adac-4b90-9cd0-20d7f85248d8.png)

**Comment by smallcubes** [comment]
Dobrý den @marketakrutska,

vypadá to v pořádku. Poprosil bych Vás o kontrolu a případné uzavření.

**Comment by marketakrutska** [comment]
Dobrý den, děkuji za úpravu! Je to v pořádku.
