### ISSUE TITLE
Chybné ISBN 

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#77]
Dobrý den, 

narazila jsem na chybu v aplikaci. Týká se to pole 020 (ISBN - podpole a + z).
Aplikace zřejmě bere i chybné ISBN - **MARC 21 (020 podpole z****)**. 

Jedná se o titul :  Let's sing in English |h [hudebnina] = |b Zpívejme anglicky : české, moravské a slovenské lidové písničky / |c překlad [z češ.] a výběr Mark Landry ; jazyková úprava Jaromír Stuchlík 
Tento titul ani není aktuálně zařazen v SDNNT. Tento titul má uvedené chybné ISBN v podpoli **z**, které je totožné s jiným titulem, který je zařazen v SDNNT. Níže přikládám odkazy.
 
https://aleph.nkp.cz/F/?func=direct&doc_number=002365995&local_base=SKC
https://aleph.nkp.cz/F/?func=direct&doc_number=001403796&local_base=SKC
https://aleph.nkp.cz/F/?func=direct&doc_number=000153664&local_base=DNT

![ISBN - app](https://user-images.githubusercontent.com/86351100/130762032-dc063879-a164-4f03-851d-3a56bdb98895.png)

![ISBN](https://user-images.githubusercontent.com/86351100/130762062-4fae4ea0-c5c3-485b-ac01-dd5fecc3905b.png)

C.

**Comment by JanMeritus** [comment]
@Cypzirschova prosim o retest

**Comment by Cypzirschova** [comment]
Nyní to vypadá v pořádku. Uzavírám.
