### ISSUE TITLE
Chybějící funkce: přehledové statistiky

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#78]
Dobrý den, 

doplňuji funkci, kterou jsem nenalezl v aktuální verzi. Dle zadávacího dokumentu by měla být aplikace schopna zobrazit přehledovou statistiku: _"část B) Pro všechny uživatele i neregistrované je vždy dostupný: Přehledové statistiky přístupnosti a stavů."_. Tedy stručný přehled, podobně jako tomu je i u [Registru digitalizace](http://registrdigitalizace.cz/rdcz/home).

Možná se na tuto funkcionalitu ještě nedostalo, ale raději na ni upozorňuji.
@JanMeritus, @Cypzirschova

**Comment by JanMeritus** [comment]
@albertoh @pavel-stastny zakladni prehledove statistiky by meli byt dostupne

**Comment by JanMeritus** [comment]
preraduji na dalsi milestone, zatim jeste neimplementovano

**Comment by pkudela** [comment]
Dobry den, @JanMeritus, @Cypzirschova, @CIZKOVAL jak jsem se zminil v issue #130 tak jsem na titulni stranku udelal 5 karet, ktere zobrazuji 3 stavy, ktere chceme zobrazovat uzivatelum a 2 licence sdnnto a sdnntt. V kazde karte je zobrazen identifikator stavu / licence tak jak je to ve facetech a vysledcich vcetne barevnosti, dale titulek karty, jestli se jedna o stav, nebo licenci, popisek o ktery stav/licenci se jedna a pocet zaznamu daneho stavu/licence. Vse je vytazeno do konfigurace, takze pokud bychom se rozhodli v budoucnu doplnit nejakou dalsi kartu, nebo zmenit napr. popis, barvu atd., tak se to provede na jednom miste. Kazda karta slouzi zaroven jako filtr, takze prokliknutim se dostaneme na vysledky s omezenim na zvoleny filtr viz. screenshoty. Co bych za sebe navrhoval je, home stranku designove jeste vylepsit a zjednodusit. Komponentu se zalozkama bych presunul na stranku "Napoveda", nebo vytvoril novou stranku "About" a pod ty karty bych dal pouze jednoduchy box, ktery by obsahoval strucny popis aplikace o 3 - 4 odstavcich. Dle meho uzivatel nepotrebuje na home page videt takovou spoustu textu, k tomu by mela slouzit dedikovana stranka. Prosim o vyjadreni, jinak nize posilam screenshoty. Pravdepodobne behem pondeli bychom nasadili novou verzi, kde jiz bude tato titulni stranka a veksere upravy layoutu.

Home page:
![image](https://user-images.githubusercontent.com/16591052/140538055-0a2d74c0-0400-46ba-bc4d-6cd62549ff91.png)

Proklik napr. z karty licence:
![image](https://user-images.githubusercontent.com/16591052/140538209-6b08797b-bf00-44a5-8d10-d920c4a8fac3.png)

Proklik ze stavu:
![image](https://user-images.githubusercontent.com/16591052/140539015-dae3ebed-ceb1-48b5-b6b6-3349c59e51da.png)

**Comment by Cypzirschova** [comment]
Dobrý den,
mě se úprava líbí a texty se budou měnit, hlavně zkracovat.
Cypzirschová

**Comment by pkudela** [comment]
@Cypzirschova dekuji za reakci. Pokud tam zalozky s texty zustanou, tak se musi udelat revize a formatovani sjednotit. Nyni jsou tam velke mezery mezi odstavci, ruzne velikosti pisma a celkove to nepusobi dobre, s tim bych pripadne pomohl, mozna by bylo idealni dodat texty pro kazdou zalozku ve wordu a ja uz bych je nalezite v html zformatoval. Pokud tam zalozky nezustanou, tak bych byl pro zanechani 2 boxy - O sdnnt a Aktuality, ostatni bych pak presunul pod stranku about, help ... ale to uz je na Vasem rozhodnuti.

**Comment by Cypzirschova** [comment]
Záložky s texty zůstanou, ale chceme je trochu změnit. Chceme přejmenovat ze záložky O DNNT na O SDNNT. Zůstanou záložky Aktuality, Knihovnám. Čtenářům se úplně vypustí. Autorům a Nakladatelům se sjednotí pod 1 název Nositelům práv. @Lichtenbergova

**Comment by pkudela** [comment]
@Cypzirschova rozumim, cili jestli to pujde, tak mi prosim dodejte texty k jednotlivym zalozkam ve wordu zformatovane tak jak chcete a ja to pak prevedu do html.

**Comment by Cypzirschova** [comment]
Texty ještě nemáme všechny hotové.

**Comment by JanMeritus** [comment]
@Cypzirschova texty mozete postupne posielat a opravovat via @CIZKOVAL , az budete kvazi hotova, prosim o predanie na @pkudela 

Popis API (jako zalozka) se vypustit nesmi

**Comment by smallcubes** [comment]
bylo by možné přidat k statistikám i intervaly (tedy zobrazení časového rozpětí)?

**Comment by pavel-stastny** [comment]
@smallcubes Časové rozpětí čeho ?

**Comment by smallcubes** [comment]
Pokud si dobře vzpomínám, tak dle @JanMeritus, by mělo jít navolit např. časové období pro stav zařazeno (třeba od 2020 do 2021)

Poprosil bych jenom @JanMeritus, jak hluboko by časové rozpětí mělo jít např. mělo by jít nastavit i měsíce?

**Comment by JanMeritus** [comment]
dny, mesice, roky

**Comment by pkudela** [comment]
Hotovo, grafy se statistikama jsou na titulni strance po zalozkou "Statistiky". A bude naszeno, oznacime.

**Comment by pkudela** [comment]
Prosim o uzavreni tohoto issue.

**Comment by smallcubes** [comment]
@pkudela uzavřít toto issue mohu až bude změny nasazeny na testu

**Comment by pkudela** [comment]
@smallcubes aha, cili prosim alespon o reakci, jestli je to na dev serveru v poradku.

**Comment by pkudela** [comment]
Prosim, nyni je to na testu, otestujte a pripadne zavrete, dekuji.

**Comment by JanMeritus** [comment]
@CIZKOVAL @smallcubes v jakem je to stavu, prosim o posunuti issues, rsp uzavreni duplicity

**Comment by CIZKOVAL** [comment]
@JanMeritus @smallcubes ja bych toto uzavrela. Statistiky se řeší v issue #257

**Comment by smallcubes** [comment]
@CIZKOVAL issue uzavírám a další chyby či připomínky budou v nových issue. Děkuji za implementaci @pkudela.
