### ISSUE TITLE
Jaké jsou termíny na vyřízení žádostí o změnu stavu

### ISSUE THREAD

**Issue by pavelkocourek** [NLCR/SeznamDNNT#8]
Prosíme upřesnit termíny, které by znamenaly upozornění pro admin kurátora v rozhraní aplikace.

**Comment by JanMeritus** [comment]
lhuty specifikovane v #66 , obecne by vsechny lhuty meli byt rekonfigurovatelne z konfiguraku

**Comment by pavel-stastny** [comment]
Reseno s issue #66
