### ISSUE TITLE
Chybějící funkce: oblíbené hledání

### ISSUE THREAD

**Issue by smallcubes** [NLCR/SeznamDNNT#80]
Dobrý den, 

doplňuji funkci, kterou jsem nenalezl v aktuální verzi. Dle zadávacího dokumentu by měla být aplikace schopna: _"sekce B) Pro všechny uživatele i neregistrované je vždy dostupné: Oblíbené a nejčastější hledání"_. Zase pouze raději upozorňuji, možná se ještě na funkci nedostalo.

@JanMeritus @Cypzirschova

**Comment by JanMeritus** [comment]
@Cypzirschova @CIZKOVAL  @Lichtenbergova dle vseho tato funkcionalita je bezpredmetna pro SDNNT, mozno uzavrit?

**Comment by Cypzirschova** [comment]
V SDNNT je toto asi zbytečné, pokud to mají využívat hlavně knihovny a nakladatelé. Ještě poprosím ostatní o názor. @CIZKOVAL @Lichtenbergova

**Comment by CIZKOVAL** [comment]
Myslím si, že se bez toho obejdeme.

**Comment by Lichtenbergova** [comment]
OK, souhlas, obejdeme se.

**Comment by smallcubes** [comment]
dle komenářů od @Lichtenbergova @JanMeritus @Cypzirschova @CIZKOVAL uzavírám. 

Funkcionalita nebude implementovaná.
