### ISSUE TITLE
Stav dokumentu - změny

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#81]
Dobrý den,

kdo a jak bude moci změnit stav dokumentu v SDNNT? Např. pokud kurátor zjistí chybu zařazení díla, které je ve stavu A (zařazeno) a dílo by mělo být např. zařazeno v X (volná díla). Zatím jsem nezjistila, jak lze změnit stav bez nějaké žádosti od nakladatele nebo knihovny.

Cypzirschová

**Comment by albertoh** [comment]
Jake moznosti bude mit kurator pro zmenu? Omezeno z jakeho stavu na konkretni, nebo volne zmenit na cokoli? Musi pridat poznamku/duvod?

**Comment by Cypzirschova** [comment]
Po domluvě s paní Lichtenbergovou bude moct kurátor měnit všechny stavy, ale musí k tomu napsat důvod/poznámku. Je potřeba, aby tam byla viditelná historie (kdo to změnil, co změnil a kdy to změnil).

**Comment by JanMeritus** [comment]
@albertoh v jakom je to stavu?

**Comment by albertoh** [comment]
V  podstate je to implementovano. 
Pridal jsem tam funkcionalitu pro pridavani/editaci granularity.
Chybi dodelat disajn @pkudela

**Comment by pavel-stastny** [comment]
@Cypzirschova Funkcionalita dostupná v buildu fc1c7e8.  (Dostupné pouze pro kurátora)

**Comment by Cypzirschova** [comment]
Dobrý den,
chybí mi tam několik stavů např. PX, X viz níže:
https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-919140167
Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova Nové workflow se musí nejdřív prodiskutovat, viz můj [komentář](https://github.com/NLCR/SeznamDNNT/issues/66#issuecomment-931311338). Stav X přidáme

**Comment by Cypzirschova** [comment]
Uzavírám. Lze měnit stavy u jednotlivých děl i na X. PX se řeší v #66
