### ISSUE TITLE
Zapomenuté heslo - mail obsahuje nefunkční URL

### ISSUE THREAD

**Issue by zabak** [NLCR/SeznamDNNT#82]
Když si nechám poslat mail se zapomenutým heslem, obsahuje URL začínající na https://sdnnt-dev.nkp.cz/... ale já jsem na server přistupoval přes IP adresu a dané doménové jméno neexistuje - po přepsání adresy serveru vše fungovalo. Bylo by dobré, aby v posílaném mailu byla vždy skutečná adresa serveru.

**Comment by zabak** [comment]
DEV, build e578af5

**Comment by pavel-stastny** [comment]
@JanMeritus To se tyka spis spravneho nastaveni DNS jmena.  Aplikace nijak neusuzuje adresu aplikace, vezme preddefinovany text  ktery lezi na serveru, doplni potrebne udaje a posle mailem.

**Comment by JanMeritus** [comment]
@smallcubes prosim o zadokumentovani a nastaveni @pavel-stastny kde to lezi?

**Comment by pavel-stastny** [comment]
@JanMeritus @smallcubes Všechny texty leží v domovském adresáři uživatele pro `tomcat `v podadresáři `~/.sdnnt/texts`

**Comment by JanMeritus** [comment]
@smallcubes prosim o potvrzeni uprav a uzavreni

**Comment by smallcubes** [comment]
@pavel-stastny vypadá v pořádku, děkuji Vám za vyřešení a uzavírám.
