### ISSUE TITLE
Změna hesla - podpora browserem navrhovaných hesel

### ISSUE THREAD

**Issue by zabak** [NLCR/SeznamDNNT#83]
Pokud na většině webů měním heslo, browser mi dokáže nabídnout bezpečné heslo. V případě SDNNT Firefox je schopen heslo nabídnout, ale Chrome ne - pravděpodobně nerozezná že jde o pole pro vložení hesla.

**Comment by zabak** [comment]
DEV, build e578af5

**Comment by pkudela** [comment]
Dobry den, jestli mate na mysli nabidku ulozneho hesla, viz. screenshot, tak me to v Chrome funguje. Jestli se jedna o neco jineho, prosim vice specifikujte problem.

![image](https://user-images.githubusercontent.com/16591052/135224243-a45175f9-26fc-464f-a583-66d7de1a4dd5.png)

**Comment by zabak** [comment]
Aha, tak mě to nefunguje ani v anonymním režimu ale v Safari a Firefoxu je to v pořádku. Zatím zavírám, tohle asi není moc jak vyřešit a možná je to jen v é instalaci Chrome.
