### ISSUE TITLE
Zapomněli jste heslo

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#84]
Pokud v přihlašovacím okně kliknu na "Zapomněli jste heslo" a nemám vyplněné přihlašovací jméno - rovnou vyskočí hláška "Nejde vyresetovat heslo, nemůžu najít účet." 
Bývá zvykem, že se aplikace dotáže uživatele na uživatelské jméno. V případě, že není uživatelské jméno vyplněné - musí se zobrazit hláška, že je nutné zadat uživatelské jméno. Nikoliv aby se okno zavřelo a napsalo, že nemůže najít účet..

**Comment by smallcubes** [comment]
@pavel-stastny testováno `sdnnt-dev.nkp.cz`, Pokud kliknu na _Zapomněli jste heslo_ bez vyplněných přihlašovacích údajů, tak se nabídka schová a nic se nestane.

**Comment by pavel-stastny** [comment]
@smallcubes Na server byl špatný build.  Vyzkoušejte nyní.  Build 41e0dd2

**Comment by smallcubes** [comment]
@pavel-stastny děkuji za odpověď, nabídka se už zobrazí. Děkuji za vyřešení a uzavírám.
