### ISSUE TITLE
Záznamy z katalogu - neplatný odkaz

### ISSUE THREAD

**Issue by jahhoo** [NLCR/SeznamDNNT#85]
Pokud kliknu např. u Lidových novin (https://sdnnt-dev.nkp.cz/sdnnt/search?q=lidov%C3%A9%20noviny&page=0) na odkaz záznamy z katalogu - odkáže mě to na stránku: https://sdnnt-dev.nkp.cz/sdnnt/DNT01-000526019 - která vyhodí error 404

**Comment by smallcubes** [comment]
@pavel-stastny v pořádku a děkuji Vám za opravu. Uzavírám.
