### ISSUE TITLE
Neuplný response /catalog

### ISSUE THREAD

**Issue by Romx98** [NLCR/SeznamDNNT#86]
Zdravím, 

dnes som sa snažil získať a  analyzovať dáta, ktoré sa nachádzaju v novom SDNNT, avšak narazil som na neuplný obsah dokumentov. 
Vo veľa dokumentoch chýba field value author, publisher, licence,  ... 
Bude sa to ešte doplnovať, alebo je to finálna forma?

**Comment by pavel-stastny** [comment]
@Romx98 To je otázka dat.  Uděláme reindex katalogu.

**Comment by zabak** [comment]
@pavel-stastny prosím o info až bude reindexované

**Comment by pavel-stastny** [comment]
@Romx98 @zabak Reindexace hlavního DNT setu doběhla,  zároveň byly doplněny některé údaje do API  (aby bylo konzistentní s tím, co je vidět v UI). Jedná se především: 

- identifikátory objektu, pokud jsou přítomny (ISSN, ISBN a ČČNB) 
- u periodik seznam ročníků - pokud je v katalogu přítomný, položka `granularity`
- pole `institutions` přejmenováno na `sigla` (stejně jako faceta v UI) 
- pokud v datech pole není, ve výstupu se teď neobjeví (platí u prázdných klíčů `licence`, `pids`, atd...) 

Build: fc1c7e8

**Comment by Romx98** [comment]
@pavel-stastny Bude sa reindexovať/dopĺnať aj obsah položiek seznamu ročníkov u periodík?  Momentálne je to v takom štádiu, že nie je možné určiť či daný ročník je dnntt/dnnto. (obsahuje polia "states", link, + u niektorých number), Za mňa osobne by bolo dobré, keby sa tam prida aj pole license.

**Comment by pavel-stastny** [comment]
@Romx98 Zrovna tu licenci u přítomných ročníků doplnit můžeme. (Odvozuje se ze stavu.)  Ostatní věci jsou záležitostí přítomnosti / neprřítomnosti dat v katalogu.

**Comment by Romx98** [comment]
@pavel-stastny To by bolo super, keby sa to tam prida. Momentalne je v stave nastavené súčastne A a NZ. Nemalo by tam byť len jedno z toho? (A alebo NZ)

**Comment by pavel-stastny** [comment]
@Romx98 Takto je to přebíráno z katalogu.  Znamená to je, že to je na seznamu ale s omezením na terminál - licence `dnntt`.

**Comment by Romx98** [comment]
@pavel-stastny Toto chápem. Ale moc nechapem toto, že keď pre daný ročník je  "states" : ["A", "NZ"]. A-dnnto, NZ-dnntt. Či je možné aby bol daný dokument dnntt a zároveň dnnto?

**Comment by zabak** [comment]
Já to chápu tak, že cokoli co je dnnt-o je zároveň dnnt-t, což je správně.

**Comment by Romx98** [comment]
Okej, ale to isté značenie je aj pre dnntt. Skúsil som vyfiltrovať dnntt dokument, a má presne také isté značenie ako dnnto. Čiže dnntt ročník má  "states" : ["A", "NZ"] a dnnto ročník ma to isté.

**Comment by pavel-stastny** [comment]
@Romx98 Ne,  licence dnnto - stav [A],  licence dnntt - stavy [A,NZ].

**Comment by pavel-stastny** [comment]
@Romx98 @zabak @JanMeritus Licence do granularity doplněna. Nicméně možnosti filtrování doznají ještě změn.  (Nyní se filtruje pouze podle vrchního titulu, ne podle ročníků)

**Comment by smallcubes** [comment]
@pavel-stastny, chtěl bych se zeptat, zdali byly už všechny změny provedeny tzn. finálnější verze.

**Comment by pavel-stastny** [comment]
@smallcubes Uz nepředpekládáme žádné změny na endpointu katalogu.

**Comment by smallcubes** [comment]
poprosil bych @Romx98 o kontrolu a případné uzavření

**Comment by smallcubes** [comment]
@Romx98 připomínám se s kontrolou a případným uzavřením

**Comment by Romx98** [comment]
@smallcubes ospravdelňujem sa, že takto neskoro, ale malo by to byť všetko OK. MMôže sa zatvoriť.
