### ISSUE TITLE
Stylovani metadat

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#87]
Poprosim @pkudela @pavel-stastny o formalnejsi stylovani zobrazovanych metadat ze zaznamu, toto pusobi bez ladu a skladu:

<img width="704" alt="Screenshot 2021-09-30 at 15 47 10" src="https://user-images.githubusercontent.com/25201690/135468086-c3a627ec-ba6b-4f25-a020-9975fbe00711.png">

**Comment by pkudela** [comment]
@JanMeritus ano, upravim, to byle jedna z mala veci, ktere jsem mel v planu

**Comment by pkudela** [comment]
@JanMeritus vyhovuje takto?

![image](https://user-images.githubusercontent.com/16591052/135478166-7f72fc69-f350-4b85-a495-cd6fba442bcb.png)

**Comment by JanMeritus** [comment]
@pkudela dekuji, muzu poprosit este bud mensi font, alebo zmenu jeho farebnosti u hodnot? mam pocit ze ty hodnoty su vetsi nez nadpisy, ale mozna je to jenom uzitym pismem.  Snazim se trochu navodit taky ten pocit jaky je u zobrazovani metadat v knihovnickych katalozich, zde napr knihovni cz, ale vetsinou to maji vsichni tak nejak obdobne


<img width="926" alt="Screenshot 2021-09-30 at 16 59 31" src="https://user-images.githubusercontent.com/25201690/135480770-65b50692-aab1-4408-863a-1818d71725c7.png">
<img width="563" alt="Screenshot 2021-09-30 at 16 59 47" src="https://user-images.githubusercontent.com/25201690/135480790-988102a4-614d-487b-95ed-f3ac57816a07.png">

**Comment by pkudela** [comment]
@JanMeritus v aplikaci se snazim resit design jednotlivych prvku co nejvice globalne tak, aby v pripade potreby zmeny konkretni komponenty se sahalo na jedno misto a aby design jednotlivych komponent byl co nejvice srozumitelny a citelny uzivateli. To se snazim vysvetlit z toho duvodu, ze tuto konkretni tabulku na zobrazeni dat pouzivame na vice mistech v ruznych formach viz. priklady nize. Cili pokud udelam zmenu zde, promitne se to vsude. Samozrejme si muzu pohrat s velikosti a barevnosti pisma u labelu tabulky (th element) apod., ale musime pocitat, ze tato zmena bude globalniho charakteru. Nize priklady stejne tabulky v ruznych formach:

![image](https://user-images.githubusercontent.com/16591052/135487587-2641c3e0-c5cf-4f37-8942-ff2d958406a8.png)

![image](https://user-images.githubusercontent.com/16591052/135487659-adbeec3c-5088-41b7-a464-dd03bbebf59c.png)

![image](https://user-images.githubusercontent.com/16591052/135487760-ddac5599-ae4a-40ad-ad20-e74ae6f3b8a0.png)

**Comment by JanMeritus** [comment]
@pkudela za mne takto asi v poradku, prosim este o nazor @Cypzirschova @Lichtenbergova a @smallcubes

**Comment by Cypzirschova** [comment]
Dobrý den,
po úpravě to za mě je OK, ale v aplikaci změnu zatím nevidím.
![123](https://user-images.githubusercontent.com/86351100/135567830-21232eca-2cd8-4fb8-b776-a980f7342c4d.png)
Cypzirschová

**Comment by pkudela** [comment]
@Cypzirschova jeste to neni nasazene na serveru, jakmile bude, napisi sem, jeste tam delam par designovych zmen, novou verzi nasadim behem dneska

**Comment by JanMeritus** [comment]
@smallcubes prosim o print screen jak to ve finale vypada, dekuji

**Comment by smallcubes** [comment]
@JanMeritus v současné době se mění vyhledávací rozhraní viz #130, takže možná ještě dojde ke změnám @pkudela. Aktuálně to vypadá takto: 

**zobrazení granurality (nepřihlášený uživatel, kurátor, knihovna):**
![obrazek](https://user-images.githubusercontent.com/78028909/140033077-b089e9bb-a947-4e9f-80b3-bb432d43051d.png)

**rozhraní pro správu granurality (kurátor):**
![obrazek](https://user-images.githubusercontent.com/78028909/140039401-4ff0a5a3-7d61-4596-b84f-d1f6410a3592.png)

**Comment by pkudela** [comment]
@JanMeritus je po me prosim jeste neco vyzadovano? Toto issue povazuji za uzavrene.

**Comment by JanMeritus** [comment]
@pkudela souhlas, zatvaram
