### ISSUE TITLE
Ako cez API overit dokument ....

### ISSUE THREAD

**Issue by Romx98** [NLCR/SeznamDNNT#88]
Zdravim,

chcel by som sa spytat, ako je mozne cez API overit dokument ked poznam len uuid korenu a systemove cislo v katalogu MZK? 
napr.  uuid:fd704aa5-9645-4965-8b80-acf0d2656a7b

Dakujem
R. K.

**Comment by pavel-stastny** [comment]
@Romx98 Mělo by fungovat vyhledávání přes všechny typy zaindexovaných identifikátorů (pid, isbn, issn, ccnb) U pidu může být problém, že není v katalogu přítomný.

**Comment by JanMeritus** [comment]
@Romx98 @zabak  z produkcniho API tyto informace dostavate?

**Comment by Romx98** [comment]
@JanMeritus Zatial pracujeme len na testovacom API. 
@pavel-stastny Okej, tak skusim hladat s danymi identifikatormi. Plus este sa chcem spytat, ze ak pre dany dokument je len uuid korenu a len sysno, a nenajdem dany dokument v katalogu. Mam to povazovat, ze dany dokument sa nenachadza v katalogu a ked bude mat DNNT label, tak dany label bude treba odstranit?

**Comment by pavel-stastny** [comment]
@Romx98 Správně by to mělo být tak, že dokument který najdete a má stav N by měl být bez lincence.  Jak je to s dokumentem, který nelze ztotožnit s ničím co je v katalogu, to nevím.  Domluvíme se s @JanMeritus @Cypzirschova.

**Comment by Romx98** [comment]
@pavel-stastny Ako to vyzera? Uz sa prislo nato, co s tymi dokumentami?

**Comment by annie-cz** [comment]
@pavel-stastny Tak jaká? U nás potřebují lidi taky pracovat a je potřeba tady vědět už nějaký odpovědi. ;)

Btw, s jakými kurátory jste měli schůzku? S kurátory čeho? Krameria? SDNNT?

**Comment by pavel-stastny** [comment]
> Btw, s jakými kurátory jste měli schůzku? S kurátory čeho? Krameria? SDNNT?

Myslel jsem paní @Cypzirschova a paní @Lichtenbergova.  

> Tak jaká? U nás potřebují lidi taky pracovat a je potřeba tady vědět už nějaký odpovědi. ;)

Sypu si popel na hlavu. Ta poslední schůzka co jsme spolu měli se týkala granularity děl a na toto bohužel nedošla řada. 

Nicméně ona je to obecná otázka: 

Paní @Cypzirschova a @JanMeritus, pokud se nenajde dílo v seznamu a pro hledání se použijí zaindexované identifikátory uuid, issn, isbn a ccnb a dílo je přitom v Krameriovi označené licencí, dá se z toho usoudit, že se mu licence má odebrat ?

**Comment by Cypzirschova** [comment]
@pavel-stastny @JanMeritus  Já jsem si myslela, že to funguje tak, že SDNNT určuje licence Krameriovi. Pak by se nemělo stát, že bude v Krameriovi dílo s licencí DNNT a nebude v SDNNT. Tohle nám řeší p. Zahořík, tak případně se obrátit na něj.

**Comment by JanMeritus** [comment]
@Romx98 @annie-cz @pavel-stastny dle porady:

- hodne zalezi na Vasi aktualni praxy - obecne co na seznamu neni v nijaky forme - by nemelo vystupovat v DK
- je nekolik stupnu stotozneni - UUID - dle stupne (ROOT/Casti)
- dalsi technicke identifikatory issn, isbn a ccnb
- vlastni evidence znaceni odeslana do seznamu potvrzena a v seznamu vystupujici, ktera ale nejde vyse popsanym spusobem stotoznit ale je vedena lokalne

pokud bude treba neco upresnit prosim volejte

**Comment by smallcubes** [comment]
@Romx98 @annie-cz @pavel-stastny @JanMeritus jak se nakonec problém vyřešil? Ptám se, aby bylo možné uzavřít issue.

**Comment by Romx98** [comment]
Riešenie je popísane v predošlom komentári. 
Čiže ak chcem overiť dokument či je dnnt, tak si to overujem pomocou root UUID, a iných identifikátorov,
Ak dokument neobsahuje identifikátory, kontrola je pomocou UUID z granularity, poprípade som zistil, ze sa dajú niektoré dokumenty nájsť podla Title. 
Ak ani toto nepomôže pri určení či je dnnt, predpokladám, že dokument nemá obsahovať dnnt-label (čiže mu bude odstránení).

**Comment by smallcubes** [comment]
Pokud tedy už nic nechybí, poprosil bych Vás o uzavření.

**Comment by JanMeritus** [comment]
Zde jenom vyjadreni:

Pro DNNT je autoritativni SDNNT, pokud se dle technickych identifikatoru
(zejmena UUID), pripadne jinych (ale viz k tomu RFC na automatizaci
oznacovani do Krameria - zejmena granularita rootu) nepodari dilo
ztotoznit,nemuze byt oznaceno.

Je nutne prvne upravit zaznam v SKC.

Dňa ut 25. 1. 2022, 13:41 smallcubes ***@***.***> napísal(a):
