### ISSUE TITLE
Pole 245, podpole p (název části/dílu)

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#89]
Dobrý den,
dnes jsem narazila náhodou na záznamy, kde v katalogizačním záznamu je obsazeno v poli 245 i podpole p (název části/dílu). V aplikaci se název části/dílu vůbec nezobrazuje, viz obr. Bylo by možné toto opravit? Zrovna jsem na to narazila u těch map, které nyní kontroluji, ale toto podpole je významné i např. v monografiích, kde může být název konkrétního dílu.
https://aleph.nkp.cz/F/?func=direct&doc_number=000395039&local_base=DNT

![podpole p](https://user-images.githubusercontent.com/86351100/135807021-e777c009-e846-499c-8c0c-340cea653f93.jpg)
Cypzirschová

**Comment by Cypzirschova** [comment]
Nezobrazuje se ani podpole n (číslo části/dílu). - 245 n
https://aleph.nkp.cz/F/?func=direct&doc_number=000387251&local_base=DNT

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o vyjadreni k tomuto problemu

**Comment by pavel-stastny** [comment]
@JanMeritus @Cypzirschova Podpole do názvu přidáme.

**Comment by JanMeritus** [comment]
@CIZKOVAL prosim o screen zde

**Comment by Cypzirschova** [comment]
Na devu funguje, ale všimla jsem si, že se záznamy špatně zobrazují (posloupnost dat). 
Níže posílám, jak by to mělo vypadat. Interpunkce je správně, jen je to špatně poskládané.

245a (název)**:** 245b (podnázev)**.** 245n (číslo dílu/části)**,** 245p (název části/dílu) **/** 245c (autoři, překlad, ilustrátoři apod.)
 
![špatné řazení - záznam](https://user-images.githubusercontent.com/86351100/139627616-9ee0985b-013c-4a03-887d-207d506e53c8.jpg)
![špatné řazení - záznam1](https://user-images.githubusercontent.com/86351100/139627626-45f3ab61-b7e1-4bdb-abb7-ed52128e0b0f.jpg)

**Comment by Cypzirschova** [comment]
Zatím stále stejné. Autor má být za lomítkem na konci.
![autor - chyba](https://user-images.githubusercontent.com/86351100/145020283-1761a61a-4e92-42f2-a18d-5e3e648af008.png)

**Comment by Cypzirschova** [comment]
Bude se řešit ta posloupnost dat?

**Comment by CIZKOVAL** [comment]
Retest NOK

**Nyní je zobrazeno:**
Zmizelá Praha. Kateřina Bečková Dodatky II., Historická předměstí a okraje města - pravý břeh Vltavy /

**Mělo by být zobrazeno:**
Zmizelá Praha. Dodatky II., Historická předměstí a okraje města - pravý břeh Vltavy / Kateřina Bečková

**Posloupnost polí tedy takto:**
245a (název): 245b (podnázev). 245n (číslo dílu/části), 245p (název části/dílu) / 245c (autoři, překlad, ilustrátoři apod.)

Poprosím p. @Cypzirschova o potvrzení.

**Comment by Cypzirschova** [comment]
@CIZKOVAL Souhlasím, žádné změny neproběhly.
Posloupnost polí je taky v pořádku.

**Comment by pavel-stastny** [comment]
Změněno:

![image](https://user-images.githubusercontent.com/675753/152068530-c5cc9841-59cb-4c71-9212-56b23eb779b5.png)

**Comment by Cypzirschova** [comment]
Za mě OK, uzavírám.
