### ISSUE TITLE
Vyhledavani

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#90]
Je mozne vyhledavat dle wildcard, alebo aspon case insensitive?

**Comment by pavel-stastny** [comment]
@JanMeritus Wildcard vyhodnocuje samotny solr a pole jsou pripravena jako case insensitive.

**Comment by CIZKOVAL** [comment]
Vyhledávání je case insensitive a funguje správně - vyhledává se bez ohledu na malá/velká písmena. Zároveň lze vyhledávat bez ohledu na diakritiku. Další issue na vyhledávání bych ponechala v issue #128
