### ISSUE TITLE
Odlíšit stav a licenci díla

### ISSUE THREAD

**Issue by JanMeritus** [NLCR/SeznamDNNT#91]
- stav a licence díla mají vystupovat samostatně (v samostatných bublinách, rsp graficky odlišných prvcích)
- návrh na změnu licence eg. z DNNTO na DNNT (pokuď ji má) a vyřazení ze seznamu (eg z A na X) by mělo jít podat prostřednictvím dvoch tlačitek / API endpointu

**Comment by pkudela** [comment]
@pavel-stastny upravy jsem tam uz udelal viz. screenshots, pokud tu neni jeste neco jineho, tak prosim dat k testovani

![image](https://user-images.githubusercontent.com/16591052/144408507-735678ec-2e3f-4447-930e-3f3fa4048447.png)

**Comment by CIZKOVAL** [comment]
@JanMeritus lze zavřít? Za mě je to OK. Stavy a licence jsou oddělené.
