### ISSUE TITLE
Poskytování biblio záznamů ze seznamu DNNT skrze OAI-PMH

### ISSUE THREAD

**Issue by black23** [NLCR/SeznamDNNT#92]
Pro snadnou integraci seznamů DNNT do katalogů knihoven, by bylo skvělé vystavovat bibliografické záznamy titulů skrze standardní OAI set. K použitelnosti by stačilo převzít odpovídající biblio z dat NK. Za předpokladu, že bude obsahovat odpovídající odkaz do NDK. Aktualizace ideálne denní. V případě, že titul vypadne ze se seznamu DNNT, měl by se odpovídající záznam v setu označit jako "deleted". Takové bychom z katalogů snadno odstranili. Použitím standardního komunikačního kanálu by se výrazně zjednodušila integrace do všech knihovních katalogů v ČR. Bez ohledu na to, zda jsou proprietární nebo s otevřeným kódem. Pokud se záznamy začnou zobrazovat plošně v katalozích knihoven, mělo by to přinést nové uživatele, protože cesta k dokumentu se výrazně zjednoduší.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o status? FYI @CIZKOVAL

**Comment by smallcubes** [comment]
@pavel-stastny poprosil bych o reakci

**Comment by smallcubes** [comment]
@pavel-stastny @albertoh poprosil bych o reakci, aby se mohlo issue uzavřít

**Comment by black23** [comment]
Souvisí s #190

**Comment by black23** [comment]
Souvisí s #344

**Comment by JanMeritus** [comment]
@black23 mozno zde uzavrit v prospech zminenych issues ? zejmena #344, dle popisu zde modifikuju mirne zadani na dva sety
