### ISSUE TITLE
Vytváření seznamů (návrhů) a jejich problém

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#96]
Dobrý den,

při testování s paní Lichtenbergovou jsme narazily na jeden zásadní problém. Nevím, zda to dokážu dobře popsat, tak to popíši, tak jak jsme postupovaly.

Já jsem byla přihlášená jako kurátor a paní Lichtenbergová jako nakladatel, pod kterým se zaregistrovala. Nakladatel vytvářel návrh na vyřazení a odeslal ho kurátorovi. To fungovalo, jak má. Jakmile nakladatel odeslal návrh, hned jsem ho viděla v mém kontu. Já jsem zatím tento návrh nezačala zpracovávat a paní Lichtenbergová v domnění, že bude vytvářet další nový návrh zařazovala další záznamy z aplikace. To se však nestalo. V době kdy začala přidávat další záznamy (i když první návrh byl ve stavu odeslán a čekal na posouzení), mi tento první návrh zmizel z mého konta a paní Lichtenbergová si ty další záznamy vkládala do prvního návrhu - tzn. vlastně jsem to pochopila, že se ten první návrh editoval i přesto, že byl ve stavu odeslán. (Myslím, že by se to nemělo dít, když se návrh odešle, měl by být už pro nakladatele/knihovnu/autora uzavřený a nemělo by se s ním dál manipulovat.) Toto jsme vyzkoušely asi 7x. Vždy mi návrh přišel, ale jakmile paní Lichtenbergová začala přidávat další záznamy, znovu se začal stále ten první návrh editovat a mě z kurátorského profilu zmizel. Ještě jsem vyzkoušely variantu, že ten návrh začnu zpracovávat - procházet jednotlivé záznamy a schvalovat/zamítat jednotlivé požadavky. Zároven paní Lichtenbergová začala přidávat další záznamy, v domnění, že se bude vytvářet už nový druhý návrh - nestalo se. Mě po odeslání celý návrh zmizel a u paní Lichtenbergové se objevil s 16 záznamy a ani tam nebyly ty, které jsem už zpracovala.

Je možné se na tento problém podívat a vyřešit, aby návrhy po odeslání byly "uzavřené" a mohl kurátor s návrhy pracovat? 
DC

**Comment by pavel-stastny** [comment]
@Cypzirschova No to jo, ale díla by ze setu neměla mizet, ne ? (Má se změnit jejich stav, licence možná metadata ale dílo by mizet němělo )

**Comment by Cypzirschova** [comment]
To máte pravdu, nevím odkud jsou záznamy přetažené (v současné době), ale teoreticky se může stát, že se záznamy slučují. V NKC to takto děláme (odd. retrokonverze), že se původní záznam smaže, ale pole 001, 920, 035, 015 se přetahují do toho nového (souborného) záznamu, takže by to mělo být normálně dohledatelné i podle ččnb (015) pokud tam je i podle jiných dat. Nevím, jak je to technicky ošetřeno v DNT01. Píši jen, jak to z pohledu knihovníka, který záznamy slučuje vypadá.

**Comment by Cypzirschova** [comment]
Vše zřejmě běží, jak má - prozatím uzavírám.
