### ISSUE TITLE
Testovací verze - duplicita + zobrazení záznamů

### ISSUE THREAD

**Issue by Cypzirschova** [NLCR/SeznamDNNT#98]
Dobrý den,

narazila jsem na problém, který se týká ISBN. V aplikaci jsem pod ISBN našla více záznamů a z toho jeden (mapa) je v aplikaci zařazen do SDNNT. V současném SDNNT, ale tato mapa není zařazena. Jedná se totiž o duplicitní ISBN, které je ve 2 různých záznamech, z toho 1 záznam je aktuálně zařazen v SDNNT, ale v aplikaci jsou zařazené oba záznamy, což je špatně. 

Tento záznam v SDNNT není zařazen:
https://aleph.nkp.cz/F/?func=direct&doc_number=002457872&local_base=SKC

Tento záznam je aktuálně zařazen v SDNNT:
https://aleph.nkp.cz/F/?func=direct&doc_number=002433071&local_base=SKC
https://aleph.nkp.cz/F/?func=direct&doc_number=000505058&local_base=DNT

Další věc, která mě trochu překvapila, je že v aplikaci vidím 2 totožné záznamy, ale v jednom je odkaz do SKC a druhý do DNT. To by mohlo být problematické např. při vyřazování, který záznam má pak nakladatel označit? Nebylo by možné to sloučit do 1 záznamu?

![ISBN - problematické záznamy](https://user-images.githubusercontent.com/86351100/137268375-da0b50b1-c064-419c-a18a-68be50bb3d5f.jpg)

Cypzirschová

**Comment by pavel-stastny** [comment]
@Cypzirschova @Lichtenbergova Souvisí s následujícím issue, resp. komentářem: 

https://github.com/NLCR/SeznamDNNT/issues/55#issuecomment-905314150 

Máme dva sety  DNT a SKC, v původní verzi  se provádělo dohledávání a ztotožnění záznamů z DNT do SKC (@albertoh prosím Tě oprav mě, pokud to neříkám přesně) , potom jsme se domluvili, že DNT má být tak jak je a vedle toho bude ležet SKC katalog no ale to vede k následujícímu. Jsou duplicity.  

@Cypzirschova Jaké má být řešení.  Mají se dohledávat a mergovat záznamy z DNT a SKC ?

**Comment by Cypzirschova** [comment]
No tak hlavně báze DNT by měla být smazána, jakmile poběží tato aplikace veřejně. Takhle jsem to pochopila ze schůzek k DNNT. Tak se budou data (předpokládám) potom tahat jenom ze SKC. Problém je v samotném SKC, jsou tam i blbě zpracované záznamy např. 1 záznam BK, 2. záznam MU - záznamy jsou stejné, akorát někdo záznam zpracoval jako BK a někdo jako MU, tím pádem máme v aplikaci obojí. Něco je blbě zpracované z retrokonverze. Nevím, jak to z pohledu IT ošetřit, zda by se toto dalo nějak vyřešit automatizovaně? Případně něco napůl automatizovaně + zbytek dořešit ručně? My opravdu s paní Lichtenbergovou nevidíme do toho, jak to je v současné době vyřešené. Já si myslím, že to bude ošetřené asi skripty, ale to se budu nyní opakovat, je potřeba najít řešení s panem Zahoříkem, případně někoho od nás z IT. 

Bylo by dobré prozatím sjednotit duplicitní záznamy, které se objevují 2x ty samé záznamy (viz obr.). Pokud se to bude dávat k testování nakladatelům, tak je potřeba toto nějak vyřešit, protože nakladatelé se budou ptát, proč tam máme zařazené mapy a hudebniny. Ty jsem procházela a to, co hudebnina a mapa byla, to jsme ze současného SDNNT vyřazovali - v současné době je to stále v aplikaci zařazené. To co tam nyní je, jsou většinou natažené chybné záznamy, nebo jak jsem psala výše, špatně zpracované záznamy v SKC, které se opakují.

**Comment by smallcubes** [comment]
@pavel-stastny @Cypzirschova data jsem na sdnnt-test reindexoval

**Comment by Cypzirschova** [comment]
@pavel-stastny Na testu zatím stále stejné.

**Comment by Cypzirschova** [comment]
Vyřešeno, zavírám.
